- docs/source/manual/configuration.rst
* Add the default logging format to the docs.
* Spelling correction for threshold
> Add the default logging format to the docs.

- docs/source/manual/configuration.rst
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
- dropwizard-jetty/src/test/resources/yaml/http-connector.yml
> Add possibility to configure Jetty's minRequestDataRate

- dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java
This will allow to monitor the usage of the thread pool which is used to handle the requests landing at admin endpoint.
Closes #2179.
> Use InstrumentedQueuedThreadPool for admin endpoint

- dropwizard-util/src/main/java/io/dropwizard/util/Generics.java
- dropwizard-util/src/test/java/io/dropwizard/util/GenericsTest.java
Jackson is able to deserialize parametrized configuration classes, so we should support configured commands with them. To figure out the type, we need to check the raw type one of the type arguments and check if it's can be cast to the `Configuration` class.
Simply put, for the class
`RunDbVacuum extends ConfiguredCommand<ReplicaConfig<Replica>>`, `Generics` should be able to figure out that we need to deserialize the config as `ReplicaConfig`.
Resolves #2187
> Add support for parametrized commands with parametrized configurations

- dropwizard-benchmarks/pom.xml
- dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/SelfValidatingBenchmark.java
- dropwizard-validation/pom.xml
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidating.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidator.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidation.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ValidationCaller.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ViolationCollector.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
This pull request solves my feature request issue #2140 .
It adds the two Annoations @SelfValidation and @SelfValidating. An example of how to use it:
```java
@SelfValidating
public class Example {
private int a = 3;
private int b = 6;
@SelfValidation
public void validOnlyIfEven(ViolationCollector col) {
if(a+b % 2 != 0)
col.addViolation("a+b must be an even value. At the moment it is "+a+"+"+b+"="+(a+b));
}
}
```
What do you think of it? If this solution is okay with you (especially the names of annotations) I would write a paragraph for the documentation.
> SelfValidation annotation as an alternative to ValidationMethod

- dropwizard-util/src/test/java/io/dropwizard/util/EnumsTest.java
The class Enums is used in Jackson (FuzzyEnumModule) and in Jersey (FuzzyEnumParamConverter). Both of these classes have unit tests and they work around the the Enums class (Jersey requires support of
deserialization from a `fromString` method, Jackson support of `@JsonCreator` methods and the `@JsonProperty` annotation). It would be to have a unit test which states what kind of deseralizations
it supports.
See #2161 and #1909.
> Add tests for fuzzy deserialized enums

- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidator.java
Instead of synchronizing on "methodMap", we could use a `ConcurrentMap` and the `putIfAbsent` method, because a cashable value depends only from the key.
References: #2150
> Simplify concurrency handling in SelfValidatingValidator

- dropwizard-bom/pom.xml
- dropwizard-configuration/pom.xml
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationParsingException.java
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableLookup.java
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableSubstitutor.java
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/SubstitutingSourceProvider.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/SubstitutingSourceProviderTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java
Several classes and methods from the `commons-lang` package like `StrSubstitutor` and `StringUtils.getLevenshteinDistance` have been moved to a separate library `commons-text`. We should follow this deprecation warning and move our dependencies to the new library.
Unfortunately, it's not possible to make this change for the 1.2.1 version, because it changes the public API.
References #2171
> Migrate deprecated classes from commons-lang to commons-text

- dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java
- dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java
- dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
Some users want to have more fine-grained Jersey-Apache HTTP client integration. For example, more elaborate behavior during retrying of with the chunked encoding enabled. 
Make the `getEntity` method of `DropwizardApacheConnector` protected and provide a new method for creating an own implementation of `DropwizardApacheConnector` in `JerseyClientBuilder`.
Powerful users are more happy with Dropwizard and don't need to copy-past classes to customize them.
> Add possibility to possibility to extend `DropwizardApacheConnector`

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/BiDiGzipHandler.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/ZipExceptionHandlingInputStream.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/BiDiGzipHandlerTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/ZipExceptionHandlingInputStreamTest.java
Currently, making a request with `content-encoding` set to `gzip` (or `deflate`) with content that's either not gziped, corrupt, or truncated results in a 500 because the exception from `GZipInputStream` is never handled.
Gzip request decompression is handled by `BiDiGzipHandler`. This change decorates the GZipInputStream it creates so that `ZipException` and `EORException` are handled, and the exception is propagated as a Jersey BadMessageException. Similar changes were made to handle
deflate.
Making a request like
```
echo plaintext | curl -X POST -d @- http://localhost:8080/endpoint
```
will return a 400 rather than a 500. Additionally, `ZipExceptions` won't be logged as unhandled exceptions.
> Return a 400 when a request body can't be decompressed

- dropwizard-bom/pom.xml
- dropwizard-http2/pom.xml
- dropwizard-http2/src/test/resources/test-http2-with-custom-cipher.yml
- dropwizard-http2/src/test/resources/test-http2.yml
The jetty version is outdated
Upgrade to the latest one.
Dropwizard use can take advantage of new features like support of native SSL via [Conscrypt](https://github.com/google/conscrypt/): 
https://webtide.com/conscrypting-native-ssl-for-jetty/
> deps: Upgrade jetty to 9.4.8.v20171121

- docs/source/manual/core.rst
- dropwizard-bom/pom.xml
- dropwizard-http2/pom.xml
- dropwizard-http2/src/test/java/io/dropwizard/http2/AbstractHttp2Test.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2IntegrationTest.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithConscrypt.java
- dropwizard-http2/src/test/resources/test-http2-with-conscrypt.yml
Jetty 9.4.8 supports native SSL via [Conscrypt](https://github.com/google/conscrypt), but it's not clear how to use it in Dropwizard.
Add an integration test and upgrade the SSL documentation.
Dropwizard users can see how they can take advantage of native SSL.
> Add an example of using Dropwizard with Conscrypt

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/caching/CacheControl.java
`@CacheControl` can be applied at the resource level, but actually handled only at the method level,
Remove the type target from the `@CacheControl` annotation.  It doesn't seem useful to specify it at the resource level, because resources typically contain methods with different caching behavior.
Less confusion for Dropwizard users who use `@CacheControl`
Fixes #2226
> Remove the type target from the `@CacheControl` annotation

- docs/source/manual/auth.rst
Any custom `AuthFilter` needs to have the `@Priority` annotation set
otherwise authorization will run before the auth filters and will
use the default security context set by Jersey.
I was having issues with authorization always allowing my `@RolesAllowed` annotated methods to be called and my auth filter not running (was basing my code on #1632, which has a test case that worked perfectly fine).
Not sure if this is specific to polymorphic auth as I've never used `@RolesAllowed` with custom `AuthFilter`s before. Should we also add documentation about adding the annotation to all custom `AuthFilter`s (there doesn't seem to be anything about this at the moment)?
Added documentation.
Clearer documentation.
> Add documentation for `@Priority` for polymorphic auth

- dropwizard-bom/pom.xml
- dropwizard-core/pom.xml
- dropwizard-core/src/main/java/io/dropwizard/setup/Bootstrap.java
Metrics 3.2.* is now not actively developed, only bugfixes are ported. It would be nice to depend on an actively developed version of Metrics.
Upgrade Metrics to 4.0.2
Dropwizard users can use a Metrics version which targets JDK8 and 9, polished internally and actively developed. A potential upgrade to Metrics 5.x will be easier.
> Upgrade to Metrics 4.0.2

- docs/source/manual/core.rst
> Fix typo in core.rst

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
Previously, once a validation constraint was evaluated the entire string
was cached. The impetus for a cache is that reflection is used to
determine if we need to prefix an error message with additional context
(eg. "query parameter x ..."). Repeatedly calculating this prefix is
wasteful -- thus the cache was born.
The biggest issue with this cache is that while it worked with all
Hibernate Validation default message templates, it failed for message
templates that contained the invalid value (eg. "query parameter x
({validatedValue}) is greater than {value}"), as the same error would be
returned regardless of validatedValue. It would also fail for custom
constraint validators that didn't return the same message everytime.
The fix is to switch the cache from caching the entire error …
> Constraint validation caches error prefixes

- dropwizard-bom/pom.xml
Oops >_>
I dun goofed and forgot to add `dropwizard-jdbi3` to the project's bom
Added it to the bom
It's now in the bom
> Add `dropwizard-jdbi3` to bom

- .travis_after_success.sh
- dropwizard-example/pom.xml
- pom.xml
We currently use Cobertura for code coverage, which is not actively developed and doesn't support JDK9.
Switch to JaCoCo which supports JDK9 and is currently actively maintained.
In the future we can our primary build with test coverage on JDK9.
> Switch to JaCoCo for Code coverage

- dropwizard-views-freemarker/src/main/java/io/dropwizard/views/freemarker/FreemarkerViewRenderer.java
- dropwizard-views-freemarker/src/test/java/io/dropwizard/views/freemarker/AutoEscapingView.java
- dropwizard-views-freemarker/src/test/java/io/dropwizard/views/freemarker/FreemarkerViewRendererTest.java
- dropwizard-views-freemarker/src/test/resources/auto-escaping.ftl
Output was not being auto escaped by Freemarker
Freemarker output format was not set [as HTML] which meant that auto escaping was not enabled. With this change it is enabled by default.  
This might affect users who are using formats other than HTML, but 
there should be enough benefit of making this a default.  The current method for getting the output format setting through to the underlying freemarker library is not very pleasant.
Users relying on the existing behaviour may need to set individual
freemarker values as `?unsafe`
I couldn't find security contact information - is that something you are planning on adding?
> Enable auto escaping of strings in Freemarker templates

- dropwizard-http2/pom.xml
Currently the HTTP2 tests fail on Travis CI, because they use jdk-8u161.
Add a new profile which links to the corresponding Jetty ALPN library.
The HTTP2 test correctly run on Travis CI.
> Add a new Maven profile to support Jetty ALPN on jdk8u161

- docs/source/manual/core.rst
Docs needs a little fixin' up when mentioning HTTP2 support and conscrypt.
Updated docs. Don't need to specify jetty version as it in brought in with our bom. Also one doesn't want it as only a test dependency 😉
> Doc fix: h2 conscrypt pom update

- dropwizard-bom/pom.xml
Guava 24.0-jre was recently released, and Dropwizard's 1.3.0 release candidates are using 23.5-jre still. There is no specific issue driving this, just a general keeping up to date sort of thing.
I updated the Guava version in the dropwizard-bom
Guava will be up to date in the next minor version release of Dropwizard
> Upgrade to Guava 24.0-jre

- docs/source/manual/configuration.rst
Incorrect default value for port was used, "transport" was missing when comparing with the actual [configuration class](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteReporterFactory.java).
Changed default value for port, added "transport"
Doc now displays the correct configuration options for the Graphite reporter.
> Fix Graphite reporter documentation

- dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
Endpoints logged out take into consideration jersey's URL pattern, but not the context path.
```
GET /endpointA
POST /endpointA
```
Copy pasting this URL gives 404s if you have context-path
Append context path if present to the end points along with jersey URL pattern
```
GET /context-path/endpointA
POST /context-path/endpointA
```
> Add context path to logged endpoints

- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/BootstrapLogging.java
Dropwizard users have the ability to configure their application to use JSON as the logging format. Unfortunately, the default logging bootstrap mechanism which kicks off before Dropwizard logging
configuration, uses the default logging layout. As a result, some internal logging messages (Jetty, Hibernate initialization) are produced in a not recognized format.
This change add possibility to specify a layout factory during the bootstrap process. Users can override the bootstrap method of `Application` and provide an own layout format. For example,
```java
BootstrapLogging.bootstrap(Level.INFO, new EventJsonLayoutBaseFactory());
```
As a result, the all applications logs will produced in the JSON format.
Resolves #2250
> Add support for providing a custom layout during logging bootstrap

- dropwizard-jackson/src/main/java/io/dropwizard/jackson/FuzzyEnumModule.java
- dropwizard-jackson/src/test/java/io/dropwizard/jackson/FuzzyEnumModuleTest.java
Since Jackson 2.9, the `mappingException` method has been deprecated in favour of more specific methods
Use the `weirdStringException` method for our case when we can't map a string value to a an enum value.
No compilation warnings and easier migration to newer Jackson versions.
> Upgrade handling an unknown value in FuzzyEnumModule

- dropwizard-e2e/src/test/java/com/example/badlog/BadLogTest.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java
Guava's `Files` API has been deprecated in Guava 24.
Use the standard java.nio.Files API for reading the content of a file.
No compilation warnings and an easier upgrade to newer Guava versions
> Remove usage of the deprecated Guava Files API

- dropwizard-bom/pom.xml
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-17485
According to the CVE, maliciously crafted JSON input can allow a remote code execution, if it's passed directly to the `readValue` method of `ÒbjectMapper`. The blacklist of deserialized types is
ignored if the Spring libraries are available in the classpath.
Upgrade Jackson to 2.9.4 with a fix to the CVE.
Dropwizard doesn't use Spring, but some end users use Spring along with Dropwizard, so we should give them a simple way to protect their applications.
> Upgrade Jackson to 2.9.4 in 1.2.* to address a CVE

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/BiDiGzipHandler.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/BiDiGzipHandlerTest.java
`BiDiGzipHandler` decompresses HTTP requests with compressed data, so for the handlers down the stack the content looks like plain-text data and they don't need to bother with decompressing in the application level logic. Unfortunately, the handler doesn't strip the original `Content-Length` header from requests, and requests return the content length of compressed content instead of uncompressed. This can create confusing situations for applications that check the length of requests for future processing. A classic example is a reverse proxy handler which parses a request, enriches it, and sends it to an origin server for processing. In this case, the proxy handler will send plain data to the origin server, but with a misleading `Content-Length` header and the origin will reject the …
> Strip the Content-Length header after decompressing HTTP requests

- dropwizard-bom/pom.xml
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-17485
According to the CVE, maliciously crafted JSON input can allow a remote code execution, if it's passed directly to the `readValue` method of `ÒbjectMapper`. The blacklist of deserialized types is
ignored if the Spring libraries are available in the classpath.
Upgrade Jackson to 2.8.11
Dropwizard doesn't use Spring, but some end users use Spring along with Dropwizard, so we should give them a simple way to protect their applications.
> Upgrade Jackson to 2.8.11 in 1.1.* to address a CVE

- dropwizard-bom/pom.xml
- dropwizard-hibernate/pom.xml
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryFactoryTest.java
- pom.xml
We depend on a Jadira fork instead of an official release, because we want to run Dropwizard apps with Hibernate under JDK 9.
There has been a new release of Jadira which supports running under JDK 9. That means we can remove a dependency on my fork via jitpack.
This new release also now picks up the database timezone from the `hibernate.jdbc.time_zone` property, so we should specify it in our tests, otherwise Hibernates reads timestamps in the host's timezone.  Theoretically, it can break applications which run databases and application servers in different timezones, but one could argue that such systems should explicitly specify the database timezone. See:
* https://github.com/JadiraOrg/jadira/issues/58
* http://in.relation.to/2016/09/12/jdbc-time-zone-configuration-property/
No 3rd …
> Upgrade Jadira to 7.0.0-rc1

- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/AbstractDAO.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java
Hibernate has deprecated the native Criteria API and since Hibernate 5.2 it's advised to use
the JPA Criteria API. 
To deprecate the `criteria` method in `AbstractDao` and advice to use `criteriaQuery` implemented in Dropwizard 1.2
Drowizard users are encouraged to use the new API, so have fewer issues when upgrading to newer Dropwizard/Hibernate versions.
> Deprecate the native Hibernate criteria API in AbstractDAO

- dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/DropwizardTestApplication.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionTest.java
Currently the Jersey client produced by `DropwizardAppRule` uses a simple Jackson's ObjectMapper. This could be an issue when a serialized/deserialized entity requires additional modules (Java 8
`Optional`, `DateTime`, `ParamaterNames` module etc...), which are
added automatically in Dropwizard's `ÒbjectMapper` and used for the server side.
Produce a client with a Jackson binder which uses the `ObjectMapper` instance from the test environment.
Less surprises for users and discrepancies between the client and server JSON serialization.
> Make sure test Jersey test client uses Dropwizard's ObjectMapper

- .travis.yml
- pom.xml
The jacoco agent runs by default alongs with the tests which creates additional overhead. We need only on Travis CI, where we measure code coverage, we don't in another CI or during local development.
Move the jacoco agent to a separate profile which is invoked by the build script at Travis.
More fast tests during development.
> Run code coverage only if needed

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
The default context path is not an empty string, but slash. Currently, a slash is considered as a custom context path and printed out along with the endpoint with a slash. So, for a typical endpoint we output two slashes, which is not great.
A fix is to consider a slash as a default context path and don't print it out.
Logged endpoints without a double slash for applications which uses a root context (i.e. default server configuration).
This is a follow-up for #2254
> Correctly handle the default context path when logging endpoints

- dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/DropwizardTestApplication.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionTest.java
Dropwizard supports PATCH method via a custom annotation io.dropwizard.jersey.PATCH. The io.dropwizard.client.io.dropwizard.client.JerseyClientBuilder also allows to submit patch requests.
However test client from `DropwizardAppRule`, 
uses org.glassfish.jersey.client.JerseyClientBuilder which does not support `PATCH` requests by default. See issue #2287
A simple workaround however is to set JerseyClientBuilder.property(HttpUrlConnectorProvider.SET_METHOD_WORKAROUND, true)
Jersey test client can now be used to submit patch requests via `client.target(...).request(...).method("PATCH", Entity.text("Patch is working"), String.class)`
> Add support for PATCH request to Jersey test client

- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactory.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/EventJsonLayout.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/EventJsonLayoutTest.java
- dropwizard-json-logging/src/test/resources/yaml/json-log.yml
My logging needs are to have the MDC in the root JSON object, not nested under the key `mdc`. 
A configuration option (defaulting to false) that allows the user the flatten MDC into the root object.
> Add configuration option to EventJsonLayoutBaseFactory to flatten MDC

- docs/source/about/release-notes.rst
- docs/source/manual/configuration.rst
- dropwizard-logging/src/main/java/ch/qos/logback/core/recovery/ResilentSocketOutputStream.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractOutputStreamAppenderFactory.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/ConsoleAppenderFactory.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/TcpSocketAppenderFactory.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/UdpSocketAppenderFactory.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/socket/DropwizardSocketAppender.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/socket/DropwizardUdpSocketAppender.java
- dropwizard-logging/src/main/resources/META-INF/services/io.dropwizard.logging.AppenderFactory
- dropwizard-logging/src/test/java/ch/qos/logback/core/recovery/ResilentSocketOutputStreamTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/TcpSocketAppenderFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/UdpSocketAppenderFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/socket/DropwizardUdpSocketAppenderTest.java
- dropwizard-logging/src/test/resources/yaml/logging-tcp-buffered.yml
- dropwizard-logging/src/test/resources/yaml/logging-tcp-custom.yml
- dropwizard-logging/src/test/resources/yaml/logging-tcp.yml
- dropwizard-logging/src/test/resources/yaml/logging-udp.yml
Add support for sending log events to a log management server via TCP or UDP. This is useful for applications that want ship logs to a remote machine for processing/alerting. We recently have added support for formatting messages as JSON and in combination with TCP/UDP logging it can be an interesting solution for a direct log shipping from Dropwizard without 3rd-party modules. 
From the implementation side `TcpSocketAppenderFactory` and `UdpSocketAppenderFactory` are both discoverable and work with generic logging events. That means they can be configured in a YAML config file for general and request logging.
```yaml
logging:
level: INFO
appenders:
- type: tcp
host: localhost
port: 24562
```
```yaml
server:
requestLog:
appenders:
- type: tcp
host: localhost
port: 24562
```
From the …
> Add a TCP and UDP log appenders to Dropwizard

- docs/source/manual/configuration.rst
- dropwizard-client/src/main/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactory.java
- dropwizard-client/src/main/java/io/dropwizard/client/ssl/TlsConfiguration.java
Dropwizard allows to configure JCE provider for server side, passing `jceProvider` property to Jetty. This allows to use some non-standard provider, like Conscrypt. But there is no such setting on client side.
Add new field `provider` to `TlsConfiguration` and pass it to Apache HTTP client builder.
> Allow to use some custom security provider in HTTP client

- docs/source/manual/configuration.rst
- dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java
- dropwizard-db/src/test/resources/yaml/full_db_pool.yml
If Dropwizard starts when the database is down, the application will shutdown. This is caused by org.apache.tomcat.jdbc.pool.ConnectionPool where there is an explicit check on ignoreExceptionOnPreLoadon property. If this is set to "true" Dropwizard will still be able to start without a database present.
Make ignoreExceptionOnPreLoadon on PoolProperties configurable
> Make ignoreExceptionOnPreLoadon on PoolProperties configurable

- docs/source/manual/configuration.rst
The HTTP/2 section in the configuration manual only mentions adding `alpn-boot` library to the JVM bootpath for the connector to work with the ALPN protocol. The same can be achieved by using Google's Conscrypt as described in the core manual, which was modified in #2230.
Interlink the two sections.
Please let me know if things can be worded/organized better.
> Link to SSL docs in the HTTP/2 config section

- docs/source/about/javadoc.rst
- docs/source/manual/configuration.rst
- dropwizard-bom/pom.xml
metrics-ganglia was removed in #2239, but it is still referenced from BOM and documentation.
Remove metrics-ganglia completely.
> Remove metrics-ganglia completely

- .travis.yml
- dropwizard-example/pom.xml
- dropwizard-http2/pom.xml
- dropwizard-testing/pom.xml
- pom.xml
JDK 9 has been deprecated in favour of JDK 10.
Switch the build to run on JDK 10. Unfortunately, Travis doesn't support Oracle JDK 10 yet, but we can download OpenJDK 10.
Test Dropwizard on the latest JDK release.
> Switch the build to run on JDK 10 from JDK 9

- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/proxy/HttpClientConfigurationTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/BaseConfigurationFactoryTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryFactoryTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableLookupTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableSubstitutorTest.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java
- dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOTest.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalCookieParamResourceTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalHeaderParamResourceTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalQueryParamResourceTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalCookieParamResourceTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalHeaderParamResourceTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalQueryParamResourceTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/PostBodyTaskTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/FixtureHelpersTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/DurationTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/GenericsTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/SizeTest.java
Modern testing libraries seems to favour an approach with explicit testing for errors where tested code is wrapped in a lambda expression, because it provides flexibility in verifying the cause of the error. For example, JUnit5 doesn't support it anymore the `expected` attribute in the `Test` annotation and the `ExpectedException` rule.
Replace them with AssertJ's `assertThrown`. 
If we ever switch to JUnit5 for testing, migration would be easier.
> Remove expected exceptions from tests

- dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
Since Maven 3.5, maven will warn when using `<prerequisites>..</prerequisites>` for a non maven-plugin project. Since Dropwizard projects are not maven plugins, we remove it from the
archetype pom.
https://maven.apache.org/docs/3.5.0/release-notes.html
> Remove prerequisites from archetype pom

- pom.xml
- suppressed-cves.xml
Currently, the dropwizard project does not run a check for security vulnerabilities during its build process. This results in dependencies being included that contain security risks (e.g. Jackson versions below 2.9.5)
I have added the dependency-check plugin to the maven build process (https://jeremylong.github.io/DependencyCheck/) so CVEs can be identified.
> Add owasp dependency check.

- dropwizard-views/src/main/java/io/dropwizard/views/ViewBundle.java
The formatting of [ViewBundle's JavaDoc](http://www.dropwizard.io/1.3.1/dropwizard-views/apidocs/index.html) is broken.
The formatting breaks after the @see Link to the FreeMarker reference. The rest of the javadoc relating to Mustache is totally broken.
@see may not be used for inline links, but will always start a new section at the end of the javadoc ([reference](https://docs.oracle.com/javase/6/docs/technotes/tools/windows/javadoc.html#@see)). @link in turn is used to link to other classes and thus is also no good substitute ([reference](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#link)). 
Inline links should thus be created with plain HTML ([stackoverflow](https://stackoverflow.com/questions/1082050/linking-to-an-external-url-in-javadoc)).
Javadoc is …
> Fix javadoc for ViewBundle

- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java
We have some imperative collection operations in `DbDumpCommandTest`.
Move them to the Stream API.
It allows us to convert the list of attributes to a map of attributes
in a declarative way without using loops and variables
> Use Java Stream API in DbDumpCommandTest

- pom.xml
In the dev profile we want to build and install artifacts as fast as possible, and an OWASP check is quite slow.
Disable the dependency-check plugin in the dev profile.
Faster builds during development
> Skip an OWASP dependency check in the dev profile

- dropwizard-testing/src/main/java/io/dropwizard/testing/common/Resource.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithoutLoggingBootstrap.java
Currently, users who don't have Logback in the classpath can't use `ResourceTestRule`, because it automatically tries to configure logging with Logback. We should provide a configuration parameter
which allows users to disable it.
Add a configuration parameter `bootstrapLogging` to `Resource.Builder`
Fixes #2333
> Add possibility to disable logging bootstrap for ResourceTestRule

- .gitattributes
On Windows machines with git crlf auto convert turned on, `rendersViewsWithAbsoluteTemplatePaths` will fail as `example.ftlh` is committed with lf line endings but will be checked out with crlf endings. Our Windows CI (appveyor) doesn't suffer from this issue as this git feature is turned off.
Set all extensions that we use for freemarker templates to explicitly keep the line ending as lf.
Can run this test on Windows.
> Checkout all freemarker templates with lf line endings

- dropwizard-http2/pom.xml
- JDK 171 & 172 have missing alpn values, so add them to the pom
- I have a machine that contains special characters in `${user.home}`, so quotes are necessary to reference the ALPN jar correctly. @arteam I see that you reverted this behavior in 3b8c255d929e and I just want to make sure I'm not missing something.
I can run http2 tests on this machine again 😄
> Http2 ALPN and bootclasspath update

- dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java
When creating environments in parallel (like when executing tests in parallel). Two threads may try to get the default metric registry (only to see it does not exist) and both of them try to set the default. One will succeed, the other will fail. This issue was foretold by @arteam in #1938
Always try and atomically set the default registry and ignore the exception that one already exists. Keeps the same look and feel of the logic.
Behaviorally the same (set the default registry if not already set else ignore). Now race free!
> Fix shared metrics race with multiple environments

- dropwizard-bom/pom.xml
We use not the latest version of Jetty in the upstream
Bump the version
We take advantage of many small bugfixes in Jetty, especially in the HTTP/2 module. See
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.9.v20180320
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.10.v20180503
> Upgrade Jetty to 9.4.10.v20180503

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/SelfValidatingClass.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
When using the new [@SelfValidating](https://github.com/dropwizard/dropwizard/blob/v1.3.1/dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidating.java) annotation on a class that is used as a `@BeanParam`, a 500 error is raised instead of 400/422.
This is described in more detail in #2334. 
Handle [@SelfValidating](https://github.com/dropwizard/dropwizard/blob/v1.3.1/dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidating.java) violations like [@ValidationMethod](https://github.com/dropwizard/dropwizard/blob/v1.3.1/dropwizard-validation/src/main/java/io/dropwizard/validation/ValidationMethod.java).
> Fix bug when using @SelfValidating with @BeanParam (#2334)

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/filter/RequestIdFilter.java
- dropwizard-views/src/main/java/io/dropwizard/views/ViewBundle.java
Intellij found some issues with our javadocs:
- Improper escaping of annotations
- Broken `@see` reference.
Fix the issues. The javadoc annotation issue was created with #2331, so this should be a once-and-for-all fix for that 😉 
Removed those javadoc warnings and those pages are properly displayed when I generate the api docs with maven site. And intellij no longer gives the warnings.
> Fix javadoc errors

- dropwizard-e2e/src/main/java/com/example/app1/App1.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/EmptyOptionalNoContentExceptionMapper.java
https://github.com/dropwizard/dropwizard/issues/1727 points out that returning a 204 for Optional.empty() is usually a more reasonable server response, but a dangerous change to default behavior. https://github.com/dropwizard/dropwizard/pull/1784 addressed the issue by showing how to override the default behavior. However, overriding the default behavior requires implementing a new class (i.e. EmptyOptionalNoContentExceptionMapper). It would be nice if users didn't have to implement this class every time they want to override the default behavior. Although, the implementation is really small, so I understand if this is rejected.
Uses the same solution presented in https://github.com/dropwizard/dropwizard/pull/1784, but includes the implementation in dropwizard-jersey
An additional class …
> Provide class that returns a 204 for Optional.empty()

- docs/source/manual/testing.rst
Testing client implementations in JUnit 5 looks a lot different, and I had to dig through the source code to get it to work. 
This PR adds documentation for testing client implementations with JUnit 5 so that it is easier to achieve.
New documentation example.
> Add JUnit 5 Example to Testing Clients

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/GzipHandlerFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipHandlerFactoryTest.java
This commit exposes three additional configuration properties from Jetty's GzipHandler in DropWizard's GzipHandlerFactory: excludedMimeTypes, includedPaths, excludedPaths.
Jetty provides configuration properties for GzipHandler that are not currently exposed in DropWizard. This commit adds these additional properties to GzipHandlerFactory.
The three additional GzipHandler configuration properties have been exposed in GzipHandlerFactory following the pattern already adhered to by that class.
> nanreh/expose additional GzipHandler configuration properties

- dropwizard-testing/pom.xml
- pom.xml
We use an outdated version of JUnit 5 dependencies.
Upgrade the JUnit5 dependencies and `maven-surefire-plugin` to the latest versions.
It adds some new features for parametrized tests and provides better Java 9/10 comparability. Suprisingly enough, we used a very old version of `junit-vintage-engine`
> Upgrade to JUnit5 5.2.0

- dropwizard-validation/pom.xml
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidator.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidation.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidatorTest.java
- dropwizard-validation/src/test/resources/slf4jtest.properties
As stated in #2336 the SelfValidation system did not handle class hierarchies as one would expect.
This pull request:
- discoveres @SelfValidation annotated methods on superclasses
- handles overriding these methods as expected
- adds tests for these cases
- extends the testing to test the logged errors and warnings in case of incorrectly used annotations
> improved self validation #2336

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/UUIDParam.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/UUIDParamTest.java
`UUID::fromString` does not length check the input to be 32 in length, which violates UUID RFC 4122 spec. Consequently,  This can be seen in the example where one UUID has a `0` appended
```java
assertThat(UUID.fromString("067e6162-3b6f-4ae2-a171-2470b63dff000")).isEqualTo(
UUID.fromString("067e6162-3b6f-4ae2-a171-2470b63dff00")
);
```
Fails with:
```
Expected :067e6162-3b6f-4ae2-a171-2470b63dff00
Actual   :067e6162-3b6f-4ae2-a173-470b63dff000
```
While `UUID::fromString` does not care about length when validating, it's clearly an issue as it shifts the internal representation.
Some UUID implementations are lenient and allow absent dashes (thus making the total length 32), but
since fromString requires dashes we don't need to worry about supporting a range of lengths and may only check …
> UUID param to length check input

- dropwizard-bom/pom.xml
Jackson patched a [2.9.6](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.6) version with some security fixes.
Jackson 2.9.5 contains the following CVEs
- CVE-2018-12022
- CVE-2018-12023
Upgrade to jackson 2.9.6 which contains patches for both of these CVEs
CVEs are patched
> Update jackson version to 2.9.6. Fixes #2392

- .travis.yml
- pom.xml
A significant amount of time spent in `mvn test` is in checking the dependency for vulnerabilities. Running `mvn test` takes upwards of 13 mins for me when the vulnerability database needs to be updated. While extremely important to check for vulnerabilities, it is bizarre to have it as part of the `validate` stage in maven, which is the very first stage executed for "validating the project is correct and all necessary information is available". Additionally running mvn test on a submodule fails due to the vuln check (I think because it searches for the suppressed warnings, but I'm not 100% sure)
I know we have the dev profile, which will skip the dependency check, but I'm still working on some test concurrency issues brought on by the dev profile.
- Move the vulnerability check to the …
> Move dependency check to maven verify

- dropwizard-benchmarks/pom.xml
- dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/DropwizardResourceConfigBenchmark.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
Dropwizard logs resource endpoints on startup like so:
```
GET     / (io.dropwizard.jersey.dummy.DummyResource)
GET     /another (io.dropwizard.jersey.DropwizardResourceConfigTest.ImplementingResource)
```
It's very nice, but the current implementation only caters to resources registered directly through `DropwizardResourceConfig` and may fail to log endpoints that have been registered through a DI tool or some other mechanism. See #2244
Use the jersey application event hooks so that after jersey has finished initializing the application we can query jersey's (more accurate) state than our own. The result is an implementation that is more accurate and simple (imo).
This does require us to start a jersey instance so that it has a chance to collect all the information, which did cause some …
> Overhaul logging resource endpoints

- dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientIntegrationTest.java
- dropwizard-e2e/src/test/java/com/example/request_log/CustomRequestLogPatternIntegrationTest.java
- dropwizard-e2e/src/test/java/com/example/request_log/RequestLogPatternIntegrationTest.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2CIntegrationTest.java
- dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/DBIFactoryTest.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/setup/JerseyEnvironment.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/TimestampFormatter.java
- dropwizard-metrics/src/main/java/io/dropwizard/metrics/ConsoleReporterFactory.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/AbstractMigrationTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCommandTest.java
- dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/layout/SafeRequestParameterConverterTest.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/ByteRange.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/PostBodyTaskTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
- dropwizard-views-freemarker/src/test/java/io/dropwizard/views/freemarker/MultipleContentTypeTest.java
Errorprone warnings during builds are irksome.
Fix the errors:
- Most of them in tests
- The ones involving generic return types are suppressed (`TypeParameterUnusedInFormals`) as they are part of our public API and I don't think we're changing that now
- Switched ConsoleReporterFactory.ConsoleStream enum from containing a non-immutable type (`PrintStream`) to a function returning that printstream (stdout or stderr)
- [Use Guava's `Splitter` instead of `String.split`](https://github.com/google/error-prone/blob/fc16cc53b8a05cc410f1cea1fcdd98a3fcb9e614/docs/bugpattern/StringSplit.md) in the `ByteRange` and `AssetServlet` classes
- errorpone detected that the futures were unused in the `JerseyClientIntegrationTest.java` test, so I collected them as `CompletableFutures` using jersey rx client …
> Fix errorpone warnings

- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/BooleanParamTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/DateTimeParamTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/DurationParamTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/InstantParamTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/IntParamTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/LocalDateParamTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/LongParamTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/NonEmptyStringParamTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/SizeParamTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/UUIDParamTest.java
Tests in the jersey.params class are a bit verbose, contain duplicate code, and unnecessary exception modifiers
- Remove unused exception modifier
- Prefer `assertThatThrownBy` to `failBecauseExceptionWasNotThrown`
jersey.params tests are now more concise and written in a consistent style
> Clean up tests in jersey.params

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
On application startup for an https service we'll see something like:
```
INFO  [...] ....HttpsConnectorFactory: Supported protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
```
While not technically wrong, displaying the protocols that *could* be enabled is misleading as it makes one believe that Dropwizard employs extremely unsafe defaults.
In fact, the logging of configuration values for included / excluded, protocols / cipher suites also doesn't fit with the rest of Dropwizard (ie, we don't log configuration values for other classes)
Log only the protocols and cipher suites that Jetty will expose. And log the protocols and cipher suites that Jetty will reject (though it could expose them if configured to do so).
This will make a clean break from the previous https configuration …
> Overhaul https logging of supported protocols and cipher suites

- dropwizard-logging/src/test/java/io/dropwizard/logging/ThrottlingAppenderTest.java
- dropwizard-logging/src/test/resources/yaml/logging-message-rate.yml
The logging throttle tests are flaky on CI, due to a combination of sleeps, file logs (file IO can be slow in CI) , and asserting on exact lines that are logged.
- Log into `System.out` to avoid file IO
- Use a ratelimiter instead of a sleep to simulate an application logging at an average rate
- Don't assert on the contents on the log lines, but assert how approximately how many should have been logged and that there are no duplicates.
No more flakiness!
> Logging throttle tests now CI friendly

- dropwizard-logging/src/test/java/io/dropwizard/logging/ThrottlingAppenderTest.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/MaxDuration.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/MinDuration.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/DurationValidatorTest.java
Currently max/min duration will give errors like:
```
messageRate must be less than (or equal to, if in 'inclusive' mode) 1 MINUTES
```
From the user's point of view, they don't know if inclusive is true or not, so it can be a bit misleading
Hibernate allows a bit of logic in the error templates!
The new error messages one will see:
if inclusive is true
```
messageRate must be less than or equal to 1 MINUTES
```
if inclusive is false:
```
messageRate must be less than 1 MINUTES
```
> Improve validation message for min/max duration

- dropwizard-testing/src/main/java/io/dropwizard/testing/common/Resource.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ContextInjectionResource.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithGrizzlyTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ResourceExtensionWithGrizzlyTest.java
When using the client from ResourceTestRule with the Grizzly container it is not possible to use PATCH via the custom annotation io.dropwizard.jersey.PATCH. (It seems to work with  the in-memory container)
Similar to: #2287 
Since the builder takes a `Consumer<ClientConfig>`  instead of a property, like in #2287  I choose to set it in the Resource instead of manipulating the builder. This solution is up for discussion. 
```
protected Resource buildResource() {
...
Consumer<ClientConfig> extendedConfigurator = config -> {
clientConfigurator.accept(config);
config.property(HttpUrlConnectorProvider.SET_METHOD_WORKAROUND, true);
};
```
Now possible to use the client and make a PATCH reuqest
client.target(...).request(...).method("PATCH", Entity.text("Patch is working"), String.class)
> Add support for PATCH request to ResourceTestRule client when using Grizzly

- docs/source/manual/core.rst
The documentation didn't tell me that I can't annotate a method with `@Timed` and `@Meterd` at the same time.
I added an Important box that says that `@Timed` includes `@Metered` and that an `IllegalArgumentException` is thrown when both are used at the same time. 
It is easier for a user to understand that `@Timed` and `@Meterd` can't be used at the same time.
> Document that the Timed and Metered can't be used at the same time.

- docs/source/manual/configuration.rst
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
I'm feeling this out -- feel free to discuss 😄 
Thanks to https://github.com/dropwizard/dropwizard/pull/2405 we'll see the following on startup for an HTTPS connector:
```
Enabled protocols: [TLSv1, TLSv1.1, TLSv1.2]
Disabled protocols: [SSLv2Hello, SSLv3]
```
You may recall that nearly two years ago I tripped up upgrading to Dropwizard 1.0 as [only TLSv1.2 seemed supported](https://github.com/dropwizard/dropwizard/issues/1700), so why is Dropwizard logging that TLSv1 and TLSv1.1 is enabled? Jetty would serve TLSv1.1 requests when the server runtime and client could agree on a cipher suite (nothing surprising here).  But by default, openssl could not communicate via TLSv1.1 with a Dropwizard server running on the latest oracle / openjdk versions. This can be verified with …
> Disable protocols less secure than tls v1.2 by default

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java
Dropwizard drops connections during a burst of short lived connections, as the accept queue is set to (most commonly) 1 or 2 due to `Files.readAllBytes` unable to work with pseudo files like somaxconn
[Adopt Netty's implementation](https://github.com/netty/netty/blob/77ec8397927e3ceb9b9a447a74e718f625ed9976/common/src/main/java/io/netty/util/NetUtil.java#L261-L269)
Test passed and dropwizard should be more burst resistant. Closes #2429
Dropwizard users currently afflicted by this bug, can override this default behavior by specifying an `acceptQueueSize` in their configuration.
> Fix incorrect reading of somaxconn for tcp backlog on linux

- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
- dropwizard-bom/pom.xml
- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationValidationExceptionTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableLookupTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableSubstitutorTest.java
- dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/DBIHealthCheckTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/gzip/ConfiguredGZipEncoderTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProviderTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleConfigOverrideTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionTest.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/PortRangeValidatorTest.java
- pom.xml
This change set replaces the remaining use of Hamcrest matchers with the equivalent functionality of AssertJ, which is used in all other tests in Dropwizard, and therefore removes the dependency on Hamcrest completely.
Closes #2437
Closes #2443
> Replace remaining use of Hamcrest with AssertJ

- dropwizard-jackson/src/main/java/io/dropwizard/jackson/FuzzyEnumModule.java
During load tests, there is significant lock contention in Jackson when
using the FuzzyEnumModule. For each deserialized enum type, there is a
synchronized block that attempts to create a deserializer in the cache and
ultimately since the PermissiveEnumDeserializer isn't marked as
cacheable, the underlying deserializer is recreated each time. Update
the PermissiveEnumDeserializer to be cacheable (similar to
EnumDeserializer from Jackson) to remove significant overhead during
deserialization.
See https://github.com/FasterXML/jackson-databind/issues/1394 for the relevant Jackson issue.
> Change fuzzy enum deserializer to be cacheable.

- dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
- dropwizard-example/pom.xml
- pom.xml
https://blog.soebes.de/blog/2018/07/30/apache-maven-compiler-plugin-version-3-dot-8-0-released/
> Upgrade to Maven Compiler plugin 3.8.0

- dropwizard-bom/pom.xml
JDBI3 3.2.1 has a few bugs/issues that have been fixed in later versions.
Updated dependencies to depend on 3.4.0.
Dropwizard will have the latest and greatest JDBI3.
> Upgrade JDBI3 to 3.4.0

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/ContextRoutingHandler.java
> Extend from AbstractHandlerContainer instead of AbstractHandler

- docs/source/about/release-notes.rst
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableLookup.java
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableSubstitutor.java
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/SubstitutingSourceProvider.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableSubstitutorTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/SubstitutingSourceProviderTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/TcpSocketAppenderFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/ThrottlingAppenderWrapperTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/TlsSocketAppenderFactoryTest.java
The `StrSubstitutor` class is deprecated as of Apache commons-text 1.3. This will be removed in 2.0. See: https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StrSubstitutor.html
**NOTE:** This is a breaking change.
I have replaced the deprecated classes with their replacements as per the Apache documentation (with the exception of `StrLookup`; its documentation states to use `StringLookupFactory` but in our case, we needed to instead implement `StringLookup` which is the interface that replaced the abstract `StrLookup` class).
This eliminates compiler warnings related to using a deprecated class. It also will allow a smooth upgrade path for commons-text when the time comes.
> Fixed deprecated class usage (Apache StrSubstitutor)

- .travis.yml
Travis CI provides a default `~/.m2/settings.xml` which is using repository.apache.org which can become slow.
Remove default settings and use the Maven default of repo.maven.apache.org.  GRPC made a similar change in https://github.com/grpc/grpc-java/pull/4782
Builds are faster when it needs to fetch resources from Maven.
> Use default maven repo on travis

- dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java
- dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
I wanted to build two different clients with the same builder, so I had some code sort of like this:
```
final private JerseyClientConfiguration clientConfigA = new JerseyClientConfiguration();
final private JerseyClientConfiguration clientConfigB = new JerseyClientConfiguration();
...
JerseyClientBuilder jerseyClientBuilder = new JerseyClientBuilder(environment);
Client a = jerseyClientBuilder.using(clientConfigA).build("client-A"));
Client b = jerseyClientBuilder.using(clientConfigB).build("client-B"));
```
I ran into these problems:
1. Only metrics for "client-A" were being reported
2. The connection timeout I set for client-A was the same for client-B. This especially confused me because client B's config had a different timeout value.  
I realized when `connectorProvider` is not …
> ConnectorProvider Not Set Silently

- dropwizard-bom/pom.xml
While trying to work through some JDK10 building issues, JSR305 is causing a lot of issues:
- https://blog.codefx.org/java/jsr-305-java-9/
- https://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use
- https://github.com/google/guava/issues/2960
- https://github.com/ben-manes/caffeine/issues/242
- http://openjdk.java.net/jeps/320
Dropwizard is explicitly pulling in jsr305 as a dependency and using it internally.  I'm not sure if this will continue to work with JDK10+ or not.  We could do a future PR to replace our jsr305 usage with another library.
> Upgrade to latest Guava (26.0-jre) and exclude jsr305 from Guava dependencies

- dropwizard-db/src/main/java/io/dropwizard/db/ManagedPooledDataSource.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java
Current metrics in JDBI and Hibernate modules include some of the available metrics in apache connection pool, It would be useful to have all available metrics,
Add the missing metrics
The metrics, when including dropwizard-db module, will now include created, borrowed, reconnected, released, releasedIdle, returned and removeAbandoned counts.
> #2459 Include all apache ConnectionPoolMetrics

- docs/source/manual/testing.rst
Just a tiny change in a code example in the documentation: Use the diamond operator to make it more modern/readable.
> testing.rst: Make example use diamond operator

- dropwizard-core/src/main/java/io/dropwizard/validation/GetLocatorFeature.java
- dropwizard-core/src/main/java/io/dropwizard/validation/GetResourceContextFeature.java
- dropwizard-core/src/main/java/io/dropwizard/validation/InjectValidatorBundle.java
- dropwizard-core/src/test/java/io/dropwizard/validation/InjectValidatorBundleTest.java
- dropwizard-e2e/src/main/java/com/example/validation/DefaultValidatorApp.java
- dropwizard-e2e/src/main/java/com/example/validation/InjectValidatorApp.java
- dropwizard-e2e/src/main/java/com/example/validation/ValidatedResource.java
- dropwizard-e2e/src/main/java/com/example/validation/WasInjected.java
- dropwizard-e2e/src/main/java/com/example/validation/WasInjectedConstraintValidator.java
- dropwizard-e2e/src/test/java/com/example/validation/DefaultValidatorTest.java
- dropwizard-e2e/src/test/java/com/example/validation/InjectValidatorBundleTest.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/MutableValidatorFactory.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/Validators.java
Following discussion at https://github.com/dropwizard/dropwizard/pull/2427
Somewhere during update to `1.0.0` we lost ability to inject into custom `ConstraintValidator`s because validator factory was moved into Dropwizard.
PR Introduces `InjectValidatorBundle` to enable validator injections inside jersey resources. Note that validators for dropwizard configuration are not affected because `ConstraintValidatorFactory` is updated after jersey initialisation.
Under the hood: There is new `MutableValidatorFactory` registered by default in validator configuration that allows to swap factory at runtime. So after jersey initialisation is possible to change `ConstraintValidatorFactoryImpl` with `InjectingConstraintValidatorFactory`
Closes #2234, making injections available in …
> Inject validator feature

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
Register instances using an AbstractBinder instead of
registering them directly
This should fix all the warnings in https://github.com/dropwizard/dropwizard/issues/2418
Instead of registering Resource instances directly, register the .class and let jersey instantiate it.
In the case where there are constructor args, use an AbstractBinder that binds the instance to the class.
> Fix new jersey 2.27 warnings

- docs/source/manual/core.rst
Documenting how to escape periods in system property config overrides
I've always wanted an easy way to tweak logging levels of individual loggers with a low touch approach (so I can debug issues without pushing an entire deployable change),  but had difficulty because the property for it contains periods. Finally, I spent some time today going through the code that makes these system property overrides happen, and found that there is a way to escape the period, it just wasn't explicitly documented.
Document how periods are escaped in parsing system property overrides
> Documenting how to escape periods

- dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
It is not uncommon for a DropwizardResourceConfigTest.java test to fail on Appveyor with a complaint about "Address already in use: bind"
- Only teardown the jersey test after the test has finished instead of immediately after startup. This would avoid a race condition that may exist in the underlying test container
- Switch to `AbstractJerseyTest` instead of plain `JerseyTest` for conformity. Even though `DropwizardResourceConfig.forTesting` will have the port sent to the next available, so to will `AbstractJerseyTest` (which is used in other tests), so this is just another measure to ensure the next available port is used. Side benefit of this, is we get to remove `BootstrapLogging` as `AbstractJerseyTest` already incorporates that.
- Appveyor passed on the first time prepping this PR.
> Rework resource config test for resilient CI

- docs/source/manual/configuration.rst
- dropwizard-bom/pom.xml
- dropwizard-core/src/test/resources/yaml/server.yml
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
- dropwizard-jetty/src/test/resources/yaml/http-connector.yml
What this PR entails:
- Update Jetty to latest (9.4.12) from (9.4.11)
- Remove deprecated configuration knobs (blockingTimeout and soLingerTime)
- Add minResponseDataRate
As for reasoning:
- Dropwizard should start with a clean slate with deprecations
- soLingerTime was literally a noop and a warning, so it has been removed (and not replaced with an alternate method)
- blockingTimeout has been rendered unnecessary (https://github.com/eclipse/jetty.project/issues/2525), and those interested in some sort rate limit  should see minResponseDataRate and minRequestDataRate (which was already part of 1.3.0 (https://github.com/dropwizard/dropwizard/pull/2184))
- Since minResponseDataRate was not present in our configuration, I added it, in case someone was using blockingTimeout in that fashion. …
> Update to jetty 9.4.12

- docs/source/manual/configuration.rst
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactory.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/ExceptionFormat.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactoryTest.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/ExceptionFormatTest.java
- dropwizard-json-logging/src/test/resources/yaml/json-log.yml
JSON logging is missing some features that standard logging supplies due to the lack of a format override.
Support configuration of exception cause placement, depth and package filtering with JSON logging.
See also #2488 and #2489
> Support configuration of exception details with JSON logging

- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
While preparing a response for #2497, I glanced at the tests for the JSON access logs, and assumed that query parameters were part of the uri, they is not (confirmed with some of the e2e tests).
Change the test mock to exclude query params when asked for the URI to avoid misleading others.
Mock better represents true events.
> Request Uri event should not contain params in tests

- pom.xml
We use HTTP and the the build fails from time to time. Sonatype
automatically redirects traffic to HTTPS, so it may cause
problems for the client, because it has to perform 2 HTTP
requests.
Let's try to use HTTPS straight away.
Hopefully the Travis build will be more stable
> Try to fix problems with deploying snapshots to Sonatype OSS repo

- docs/source/manual/configuration.rst
Broken and outdated links in the documentation:
- The link to JavaDoc for ForwardedRequestCustomizer was broken (HTTP 404).
- The link to JavaDoc for java.net.Socket was outdated (Java 7, which is no longer supported by Dropwizard).
Updated a couple of broken and outdated links.
> Update broken and old links in configuration.rst

- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/AccessJsonLayout.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/EventJsonLayout.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/MapBuilder.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/MapBuilderTest.java
json event creation calls into the I*Event objects to get the value before it is known if the value should be included in the log message.
* Convert to lazy evaluation for json event creation
* Initialize maps to the size of the includes list.
json log message creation should be more performant by delaying method invocations until necessary.
> Convert to lazy evaluation for json event creation

- .travis.yml
Now that JDK11 is officially released, we can probably stop building on openjdk9 and 10
> Remove openjdk9 and openjdk10 from Travis

- docs/source/manual/configuration.rst
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/AccessAttribute.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/AccessJsonLayout.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/AccessJsonLayoutTest.java
- dropwizard-json-logging/src/test/resources/yaml/json-access-log.yml
Implementation from #2497 
> The standard request access logs default[1] to request URL. The JSON access logs introduced in #2232 default[3] to request URI. While it could be argued that a different output format doesn't have to remain passive to the previous layout. It did take a bit to trace down the issue as I assumed switching the format would produce logs with the same composite parts. What this change between uri/url intentional?
Been thinking about this quite a bit more trying to reason about the differences between uri/url. It isn't very clear from the [spec](https://tools.ietf.org/html/rfc3986#section-3) if there is a canonical name for the path+query part. The current dropwizard namings seem misleading according to spec, not sure if it was intended to align or if it carried over …
> Add support for pathQuery json access log attribute

- dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java
- dropwizard-jackson/src/main/java/io/dropwizard/jackson/SafeDurationDeserializer.java
- dropwizard-jackson/src/main/java/io/dropwizard/jackson/SafeInstantDeserializer.java
- dropwizard-jackson/src/main/java/io/dropwizard/jackson/SafeJavaTimeModule.java
- dropwizard-jackson/src/test/java/io/dropwizard/jackson/JacksonDeserializationOfBigNumbersToDurationTest.java
- dropwizard-jackson/src/test/java/io/dropwizard/jackson/JacksonDeserializationOfBigNumbersToInstantTest.java
Jackson uses `BigDecimal` for deserialization of `java.time` instants and durations. The problem is that if the users sets a very big number in the scientific notation (like `1e1000000000`), it takes forever to convert `BigDecimal` to `BigInteger`, and then to convert it to a long value. An example of the stack trace:
```java
@Test(timeout = 2000)
public void parseBigDecimal(){
new BigDecimal("1e1000000000").longValue();
}
org.junit.runners.model.TestTimedOutException: test timed out after 2000 milliseconds
at java.math.BigInteger.squareToomCook3(BigInteger.java:2074)
at java.math.BigInteger.square(BigInteger.java:1899)
at java.math.BigInteger.squareToomCook3(BigInteger.java:2053)
at java.math.BigInteger.square(BigInteger.java:1899)
at …
```
> Add safe Jackson deserializers to prevent a DoS attack

- docs/source/manual/client.rst
- docs/source/manual/internals.rst
Redundant the
Remove it
Signed-off-by: Benny Zlotnik <uber442@gmail.com>
> Remove redundant "the"

- docs/source/manual/configuration.rst
Picked up issue #2500 and added the default log pattern into documentation.
I did copy it directly from class LogbackAccessRequestLayoutTest, in order to avoid copy/paste errors.
Any feedback welcome.
> Fix issue #2500 Include default requestLog format string in documentation

- dropwizard-bom/pom.xml
- dropwizard-example/pom.xml
- dropwizard-http2/pom.xml
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ScheduledExecutorServiceBuilder.java
- dropwizard-testing/pom.xml
- pom.xml
Replaces #2528
Note: Errorprone/Nullaway are currently not working on JDK11.  It fails to compile.
> Upgrade dependencies

- dropwizard-bom/pom.xml
I think these three entries can be removed since we're importing the `jdbi3-bom` above them.
> Remove entries covered by the jdbi3-bom

- docs/source/getting-started.rst
- docs/source/manual/auth.rst
- docs/source/manual/core.rst
These changes should correspond to the code changes made in #2400
While #2400 removed Guava from the Dropwizard code, the documentation wasn't updated.
Update the documentation to reflect the changes made in #2400.
> Remove most mentions of Guava from documentation

- dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientIntegrationTest.java
Appveyor occasionally fails due to a timeout.
I noticed that the failing test did not adjust the timeout, so I took the liberty of setting (and increasing) it to 10 seconds 
Less flaky 🤞
> Avoid flakiness with CI by increasing timeouts

- .circleci/config.yml
Circle CI fails 100% of the time due to surefire exiting with an error (snipped)
```
[ERROR] Process Exit Code: 1
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
```
Turns out, a lot of people have this problem:
- [link 1](https://discuss.circleci.com/t/circleci-build-failure-on-openjdk-image/26104)
- [link 2](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925)
- [link 3](https://stackoverflow.com/q/53010200/433785)
- [link 4](https://github.com/apache/maven-surefire/pull/197)
The temporary solution is to pin the jdk version used to one that …
> Pin circle ci jdk version

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/NonblockingServletHolder.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/NonblockingServletHolderTest.java
This change is made to address https://github.com/dropwizard/dropwizard/issues/2482. When a client disconnects before the response is written, or the full response has already been written, an `EofException` is thrown. An exception mapper can't be used because this error arises when the response is attempting to be written. This causes a lot of `ERROR` logs which clutters logging.
The solution that has been implemented is to catch and ignore the `EofException` during the response write. The ideal solution would be to catch the `EofException` and accept configuration to log at different levels. This is a much more involved change and can be implemented if there is want for it. This implementation shouldn't preclude such an effort.
No more `EofException` errors in logs
> Fix EofException spamming of logs

- dropwizard-logging/src/test/java/io/dropwizard/logging/ThrottlingAppenderWrapperTest.java
Travis CI has been extra flaky with the `overThrottlingLimit` logging throttle appender. The test has been failing as it sees 12 lines instead (at max) 11 logged.
Calculate the total elapsed time after the sleep to "clear" the rate limiter. By delaying the calculation, it encapsulates the time for the async log to write out the last line, which in turn allows the test to pass when 12 lines are logged.
If this test passes 10 times on travis CI, I'll mark this as good to go.
> Tweak throttler test for CI

- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
The CachingAuthenticatorTest fails under load due to the way eviction works in Caffeine. Refer to the AppVeyor failure in PR #2573.
I've changed around a few things to detect cache changes and eliminated sleeps that actually weren't required. This is not a perfect solution, but should be more robust than the current implementation.
- Removed unnecessary sleeps.
- Added retry concept to extend the window for cache eviction.
Unforuntately without invoking direct cache controls, this runs the risk of being flaky on high load systems. This implementation should be more robust than the previous, however.
The unit test should not fail except under the most extremely slow (i.e. high load) invocations.
> Cleaned up flaky test in CachingAuthenticatorTest

- dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
"Y" is actually the year according to "week of year"-based calendars. This will be different from the calendar year on dates like 2018-12-30, which has a "y" of 2018 and a "Y" of 2019.
http://unicode.org/reports/tr35/tr35-10.html#Date_Format_Patterns
> Fix date formatting pattern in test

- dropwizard-bom/pom.xml
Fixes the vulnerability CVE-2018-10237 reported in #2586
Details:
https://nvd.nist.gov/vuln/detail/CVE-2018-10237
https://groups.google.com/forum/#!topic/guava-announce/xqWALw4W1vs/discussion
> Upgrade Guava to 24.1.1

- docs/source/manual/configuration.rst
Not clear from our docs that in order to use `responseContent` or `requestContent` in json logging that `TeeFilter` must be registered
Link to the official logback site for TeeFilter and show a comment of one being registered
Hopefully the docs are more clear.
> Document TeeFilter for json log format

- docs/source/manual/configuration.rst
- dropwizard-metrics/src/main/java/io/dropwizard/metrics/MetricsFactory.java
- dropwizard-metrics/src/main/java/io/dropwizard/metrics/ScheduledReporterManager.java
- dropwizard-metrics/src/test/java/io/dropwizard/metrics/MetricsFactoryTest.java
- dropwizard-metrics/src/test/java/io/dropwizard/metrics/ScheduledReporterManagerTest.java
- dropwizard-metrics/src/test/resources/yaml/metrics-report-on-stop.yml
We use dropwizard extensively and are fans of how relatively quick it starts and stops.
When testing locally, we start our application from its all-in-one jar file and shut it down again after the tests, configuring metrics as local .csv files. However, we never see them :disappointed:
This is because dropwizard starts, we run tests and dropwizard stops again without ever getting the `report()` called from `ScheduledReporterManager `.
Add a `reportOnStop` boolean setting in `MetricsFactory` that would cause one last report() by the `ScheduledReporterManager` when stopping.
This should have no other impact, as the default for this boolean is `false` to remain backwards-compatible.  
This fixes #2557
> Allow reporting Metrics on stop

- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/AccessJsonLayoutBaseFactory.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventAttribute.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactory.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/EventJsonLayout.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/JsonFormatter.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/EventJsonLayoutTest.java
- dropwizard-json-logging/src/test/resources/yaml/json-log.yml
The "callerData" event attribute in the "includes" configuration setting allows logging caller-specific details, such as:
* class name ("caller_class_name")
* method name ("caller_method_name")
* file name ("caller_file_name")
* line number ("caller_line_number")
Closes #2539
> Add support for logging caller data in dropwizard-json-logging

- docs/source/about/release-notes.rst
There was a typo in the release notes. The release v1.3.8 seems to be done in 2019 but the date is mentioned as Jan 2, 2018.
Corrected the year from 2018 to 2019.
> Fixing a documentation typo in release date

- dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
There's a NPE when asking for /admin/tasks. 
Check the `request.getPathInfo()` return value before passing it to the map. `HttpServletRequest.getPathInfo()` will return null if there's no path information.
Instead of a 500 response it will return a 404
> NPE if /admin/tasks is requested. Now it returns a 404 (#2626)

- dropwizard-bom/pom.xml
- pom.xml
* Joda-Time 2.10.1
* Apache HttpClient 4.5.7
* Apache Tomcat JDBC Pool: 9.0.14
* Hibernate ORM 5.2.18.Final
* Liquibase 3.6.3
* Freemarker 2.3.28
* Mustache 0.9.6
* Javassist 3.24.1-GA
* Classmate 1.4.0
* HSQLDB 2.4.1
* Mockito 2.24.0
> Update dependencies to latest patch-level

- docs/source/manual/testing.rst
In the testing docs in the "Test Containers" section regarding adding the grizzly test container; unnecessary reference to 
```xml
<version>${jersey.version}</version>
```
will cause users to provide their own (potentially incompatible) property (like jersey 2.28 in dropwizard 1.x). The dropwizard bom renders any need to specify the property unnecessary. 
Additionally, the dependency exclusions are unnecessary as well, as there is no difference in `mvn dependency:tree` before and after the exclusions (eg: notice that "javax.servlet-api" doesn't appear):
```
\- org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-grizzly2:jar:2.25.1:test
+- org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:2.25.1:test
|  \- …
```
> Remove unnecessary pom mods for grizzly container

- dropwizard-e2e/src/test/java/com/example/badlog/BadLogTest.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
As documented in https://github.com/dropwizard/dropwizard/issues/2523, if a `DropwizardTestSupport::before` throws an exception this cancels `DropwizardTestSupport::after` (under `DropwizardAppRule` / `DropwizardClientRule`) [as documented](https://junit.org/junit4/javadoc/4.12/org/junit/rules/ExternalResource.html). This can cause config overrides (and potentially other aspects like logging) to leak into other tests -- causing headache during debugs.
If `DropwizardTestSupport::before` throws, it will cleanup after itself before propagating the exception.
No more leakage. Closes #2523
> Test support cleanup on before exceptions

- dropwizard-forms/pom.xml
`dropwizard-forms` is the only project that defines `<packaging>jar</packaging>` in `pom.xml`. I spent 3 minutes wondering why it was the only one like this. No reason, it's just stating the default value.
Bring it inline by erasing the explicit setting and making it conform with the other modules
No difference 😄
> Remove unnecessary packaging from dropwizard-forms

- dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java
- dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/GuavaOptionalLocalDateArgumentFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/GuavaOptionalLocalDateTimeArgumentFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/GuavaOptionalOffsetTimeArgumentFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/GuavaOptionalZonedTimeArgumentFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/InstantMapper.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/JodaDateTimeMapper.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/OffsetDateTimeMapper.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/OptionalInstantArgumentFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/OptionalJodaTimeArgumentFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/OptionalLocalDateArgumentFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/OptionalLocalDateTimeArgumentFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/OptionalOffsetDateTimeArgumentFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/OptionalZonedDateTimeArgumentFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/ZonedDateTimeMapper.java
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ScheduledExecutorServiceBuilder.java
I'm running dropwizard code through some static analysis checkers to make sure we're on good ground for 2.0. In this first PR, a lot of issues surrounded superfluous warnings about unwrapping an optional. 
Implemented said fixes
Everything is behaviorally the same -- dropwizard just a little more static analysis friendly.
> Satisfy optional check before unwrap analyses

- dropwizard-testing/pom.xml
On builds, a warning pops up:
```
+-------------------------------------------------------------------------------+
| WARNING:                                                                      |
| The junit-platform-surefire-provider has been deprecated and is scheduled to  |
| be removed in JUnit Platform 1.4. Please use the built-in support in Maven    |
| Surefire >= 2.22.0 instead.                                                   |
| » https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven |
+-------------------------------------------------------------------------------+
```
Remove from the offending pom dependency
No more warning!
> Remove junit platform-surefire-provider

- docs/source/manual/core.rst
- dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
- dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java
- dropwizard-lifecycle/pom.xml
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/LifecycleEnvironment.java
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ScheduledExecutorServiceBuilder.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilderTest.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/LifecycleEnvironmentTest.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ScheduledExecutorServiceBuilderTest.java
- dropwizard-metrics/src/test/java/io/dropwizard/metrics/CsvReporterFactoryTest.java
Currently the ```Environment``` factory methods for ```ExecutorService``` and ```ScheduledExecutorService``` don't come with instrumentation out of the box.
I'm suggesting using ```InstrumentedThreadFactory``` which monitors  the number of threads created, running and terminated. I've added some documentation as well.
Please refer to https://github.com/dropwizard/dropwizard/pull/2639 as there's more context there
> Use instrumented thread factory

- dropwizard-example/pom.xml
Dropwizard-example pom is bloated with Sonatype Nexus Snapshots
Remove it
Closes #2664
> Remove sonatype snapshots from dropwizard-example

- .travis_after_success.sh
- .travis_deploy.sh
Reduce output of downstream Maven builds to reduce the overall log size of the Travis CI builds.
Otherwise, we might run into problems with the overall log output:
> The job exceeded the maximum log length, and has been terminated.
> Run downstream Maven builds in quiet mode

- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/LazyLoadingTest.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportWithMissingConfigurationTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportWithResourceConfigProviderTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportWithUrlConfigProviderTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/GzipDefaultVaryBehaviourTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceExceptionMapperTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithGrizzlyTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithoutLoggingBootstrap.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleConfigOverrideTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleReentrantTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleResetConfigOverrideTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleWithExplicitTest.java
* Allow specifying ConfigurationSourceProvider in DropwizardTestSupport, DropwizardAppRule, and DropwizardAppExtension
* Mark constructors with `Optional<String>` for configuration file as deprecated in favor of nullable versions
* See https://rules.sonarsource.com/java/RSPEC-3553
* Better exceptions when initializing the test application fails
* Clean up tests and remove redundant test applications
Closes #1709
Closes #1830
> Improve Dropwizard test support

- dropwizard-bom/pom.xml
There is a bug in older versions of commons-lang3 that affects users running on java11
See further details in https://issues.apache.org/jira/browse/LANG-1384
Using the recent commons-lang3 version in dropwizard-bom eases java11 transitioning for dropwizard users.
Updating to the most recent release of commons-lang3 (atm 3.8.1) solves the problem
Dropwizard users relying on dropwizard-bom do not need to manually version manage commons-lang3 to a newer version themselves
> Upgrade commons-lang3 in release/1.3.x to make bom java11 compatible

- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
Travis build failed in #2682 because sleeping for any amount of time does not guarantee that Caffeine will have performed its background cleanup before performing the next call.
Made `cache` field in CachingAuthorizer package private and manually called the `cleanup` function on the Caffeine instance instead of sleeping.
Test should not fail randomly anymore.
> Fixed flaky test in CachingAuthorizer

- dropwizard-jdbi3/src/main/java/io/dropwizard/jdbi3/JdbiFactory.java
- dropwizard-jdbi3/src/test/java/io/dropwizard/jdbi3/JdbiFactoryTest.java
Metrics library was updated to use JDBI 3's `SqlLogger` instead of the deprecated `TimingCollector`, but Dropwizard is still using `TimingCollector`.
Updated Dropwizard to use the new `SqlLogger`.
> Update JdbiFactory to use metrics' InstrumentedSqlLogger

- docs/source/manual/configuration.rst
- docs/source/manual/core.rst
Document that Dropwizard defaults to asynchronous and will drop lower priority logging events if the log queue buffer starts to fill up. Closes #2681
> Document asynchronous logging

- docs/source/manual/index.rst
- docs/source/manual/upgrade-notes.rst
- docs/source/manual/upgrade-notes/upgrade-notes-0_7_x.rst
- docs/source/manual/upgrade-notes/upgrade-notes-0_8_x.rst
- docs/source/manual/upgrade-notes/upgrade-notes-0_9_x.rst
- docs/source/manual/upgrade-notes/upgrade-notes-1_0_x.rst
- docs/source/manual/upgrade-notes/upgrade-notes-1_1_x.rst
- docs/source/manual/upgrade-notes/upgrade-notes-2_0_x.rst
Instead of maintaining multiple places where users have to check for information, let's move the upgrade notes for Dropwizard into the documentation.
> Move upgrade notes from GitHub wiki into documentation

- docs/source/about/release-notes.rst
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
A DW service running behind a proxy/LB need to know the real source of the request. Attempt to solve #1176 
[Proxy-Protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) is one the solution for this. Jetty has inbuilt support for it. We just need to utilize that.
request.getRemoteAddr() and request.getRemoteHost() shall give you information about the client that is making the request to proxy not of proxy itself (which is the case as of today without this feature).
> Add ProxyConectionFactory for enabling the proxy protocol.

- dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
- dropwizard-db/src/main/java/io/dropwizard/db/PooledDataSourceFactory.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryHealthCheck.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/HibernateBundleTest.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryHealthCheckTest.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIFactory.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIHealthCheck.java
- dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/DBIHealthCheckTest.java
- dropwizard-jdbi3/src/main/java/io/dropwizard/jdbi3/JdbiFactory.java
- dropwizard-jdbi3/src/main/java/io/dropwizard/jdbi3/JdbiHealthCheck.java
- dropwizard-jdbi3/src/test/java/io/dropwizard/jdbi3/JdbiFactoryTest.java
- dropwizard-jdbi3/src/test/java/io/dropwizard/jdbi3/JdbiHealthCheckTest.java
tomcat jdbc allows validationQuery to be null, see https://tomcat.apache.org/tomcat-9.0-doc/jdbc-pool.html . In that case it will validate connections by isValid() method on Connection object.
making validation query Optional. healthchecks calling isValid when validation query is not defined.
> #2702 allowing validation query to be null

- pom.xml
Preferring [`instanceof` instead of `getClass` in `Object#equals`](https://errorprone.info/bugpattern/EqualsGetClass) may be polarizing (https://github.com/dropwizard/dropwizard/pull/2647). So instead leaving the PR stagnated and warning to pollute the console output -- suppress them
Warnings suppressed in pom.
Closes #2647
> Disable errorprone: EqualsGetClass check

- docs/source/manual/configuration.rst
- dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
- dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java
Support configuration of jetty dump properties to assist in troubleshooting and diagnostic investigations.
See also #2742 and https://www.eclipse.org/jetty/documentation/9.4.x/jetty-dump-tool.html
Add jetty dump properties to the AbstractServerFactory. Properties are defaulted to false and must be opted into.
```yaml
server:
dumpAfterStart: true
dumpBeforeStop: true
```
Jetty dump is output when requested.
dumpAfterStart
```
2019-04-22T21:49:20,585Z INFO  [main] org.eclipse.jetty.server.handler.ContextHandler Started i.d.j.MutableServletContextHandler@476efc81{/,null,AVAILABLE}
2019-04-22T21:49:20,610Z INFO  [main] org.eclipse.jetty.server.AbstractConnector Started application@4913465d{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-04-22T21:49:20,669Z INFO  [main] …
```
> Support configuration of jetty dump properties

- dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/PostBodyTask.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/Task.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
I sometimes want to return data in JSON format in the response from a Task, and it's inconvenient that the response content type is hardcoded as `text/plain;charset=UTF-8`, because some client libraries expect JSON with an `application/json` content type and it means I have to do an extra translation step.
It would be really helpful if, when implementing actions, I had the option of specifying the response type to override the default `text/plain;charset=UTF-8`.
I added an Optional<String> responseContentType field to Task. 
I kept the existing constructor the same, and added a new one where you can pass a `String contentResponseType`. If the original constructor is used, or if `null` is passed as `contentResponseType` in the new one, then the `contentResponseType` field will be empty.
I …
> Allow response content type to be specified for a Task

- pom.xml
In order to use third party services such as https://javadoc.io/ effectively, there should be an aggregated Javadoc artifact which includes the documentation for all official Dropwizard modules.
> Generate and publish aggregated Dropwizard Javadoc artifact

- dropwizard-bom/pom.xml
- dropwizard-jersey/pom.xml
- dropwizard-validation/pom.xml
Fixes duplicate classes between the 3 jars
Fixes #2739
jakarta jars are replacing javax jars, so should depend on that instead of javax.  Furthermore, the glassfish jakarta.el implementation jar includes all the classes from the jakarta.el-api jar (see https://github.com/eclipse-ee4j/el-ri/issues/32), so should only depend on the implementation jar.
depend on org.glassfish:jakarta-el, and exclude the other 2 jars
> Exclude javax.el and jakarta.el-api, using glassfish jakarta.el instead

- dropwizard-core/src/main/java/io/dropwizard/ConfiguredBundle.java
- dropwizard-db/src/main/java/io/dropwizard/db/DatabaseConfiguration.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/ScanningHibernateBundle.java
- dropwizard-views/src/main/java/io/dropwizard/views/ViewBundle.java
- dropwizard-views/src/main/java/io/dropwizard/views/ViewConfigurable.java
The restriction of `T extends Configuration` on `ConfiguredBundle<T>` was accidentally added in #2516 and can be removed again.
Refs #2516
Closes #2759
> Remove restrictions on generic type for ConfiguredBundle

- docs/source/about/release-notes.rst
- dropwizard-logging/src/main/java/ch/qos/logback/core/recovery/ResilientSocketOutputStream.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/socket/DropwizardSocketAppender.java
- dropwizard-logging/src/test/java/ch/qos/logback/core/recovery/ResilientSocketOutputStreamTest.java
As pointed out by @Sounie in https://github.com/dropwizard/dropwizard/commit/04c4563bd5dc6aeb8237ad5349cff05eb91fa5a8#r33455524, `ResilientSocketOutputStream` had a typo in the class name.
Update class name to remove typo.
Breaking change for any dropwizard user who relied on this class (I suspect the number effected to be small to nil), so it's documented in the release notes just in case.
> Fix typo for ResilientSocketOutputStream class

- dropwizard-core/src/test/java/io/dropwizard/BundleTest.java
Running the `BundleTest` tests while another service is running on the box will fail the test as this test uses the default server configuration binding to port 8080.
Force the test to use an available port.
Test passed on a machine where 8080 was not available.
> Fix test that binds to 8080

- dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ReuseDropwizardAppExtensionTestSuite.java
If a DropwizardAppExtension instance is reused in multiple classes (as described in its JavaDoc), the client returned by the client() method is closed after the first class.
Set the client to null after closing it.
Tests reusing DropwizardAppExtension as described in its JavaDoc can successfully use the client returned from client(). The example still won't be accurate as the application is not really being reused as DropwizardExtensionsSupport can't tell the difference between this and any other static field implementing DropwizardExtension and closes it after each class. Here is the related issue:
https://github.com/dropwizard/dropwizard/issues/2763
> reset the client

- dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
Junit5 does not contain the same suite level resource as junit4 ([based on stackoverflow answer][stack] and [open issue][issue]). `DropwizardAppExtension` doesn't advertises code that for suite level testing, but it is a lie and thus misleading.
Remove documentation involving suite level testing from `DropwizardAppExtension` from the javadocs to avoid any confusion.
Closes #2763
[stack]: https://stackoverflow.com/a/50678092/433785
[issue]: https://github.com/junit-team/junit5/issues/456
> Remove mention of junit5 suite level extension

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
In certain environments (eg AWS Lambda), the default/system
class loader doesn't have dropwizard classes in it.  Use the
current class's class loader to ensure that it does.
In certain environments (eg AWS Lambda), the default/system
class loader doesn't have dropwizard classes in it, and we see the following:
```
javassist.NotFoundException: io.dropwizard.jersey.DropwizardResourceConfig$SpecificBinder
at javassist.ClassPool.get(ClassPool.java:422)
at io.dropwizard.jersey.DropwizardResourceConfig.register(DropwizardResourceConfig.java:152)
```
Use the current class's class loader to ensure that it does.
Running dropwizard in aws lambda works (with some glue between an aws RequestHandler and the dropwizard application's resourceConfig).  Running as a standard shaded jar also still works. …
> Add current class loader to javassist ClassPool

- docs/source/about/release-notes.rst
- docs/source/manual/core.rst
- dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/filter/UriFilterFactory.java
- dropwizard-request-logging/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable
- dropwizard-request-logging/src/main/resources/META-INF/services/io.dropwizard.logging.filter.FilterFactory
- dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/filter/UriFilterFactoryTest.java
#2794 
Adds a `UriFilterFactory` class to the `dropwizard-request-logging` module, so that users of Dropwizard can add this in without pulling in any other dependencies if they find it useful.
If this factory is used and configured, any specified paths (only fully qualified paths, regexes don't work in this implementation) will be filtered out of request logs. 
If a user wanted to filter out their request logs for the `/health-check` path (if they were using https://github.com/dropwizard/dropwizard-health :) ), their request logs would only contain logs for requests to paths that are not equal to `/health-check`.
> Adds a request logging uri filter 

- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
Updated documentation of CachingAuthenticator to properly reflect the change from Guava to Caffeine
While reviewing usages of Guava I noticed that the Javadoc for `CachingAuthenticator` was out of date.
I fixed the documentation.
> CachingAuthenticator documentation fix

- dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableLookup.java
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableSubstitutor.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableLookupTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableSubstitutorTest.java
#2787 describes it well, but the crux is that `${DOES_NOT_EXIST:-myval}` in strict mode will throw an exception even though a default value is provided.
While apache-commons 1.7 will contain this feature natively ([TEXT-127](https://issues.apache.org/jira/browse/TEXT-127)), in the meantime I extracted the same logic used in [`StringSubstitutor` 1.6](https://github.com/apache/commons-text/blob/commons-text-1.6/src/main/java/org/apache/commons/text/StringSubstitutor.java#L1248-L1381) and surgically inserted our desired behavior (the `else if (strict) {` branch). Once 1.7 is released we can remove this copy and pasted code in favor of `enableUndefinedVariableException`
Closes #2787
> Default values allowed on strict undefined config env vars

- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientConfiguration.java
- dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
Recent versions (>=4.5.8) of HTTPClient introduced a normalizeUri
settings that prevent URL rewrites introduce in earlier versions.
Being able to disable said settings is sometimes useful when dealing
with legacy systems.
See: https://issues.apache.org/jira/browse/HTTPCLIENT-1968
This allow to enable or disable `normalizeUri` settings, the default is still true, therefore the existing behaviour is unchanged.
> Allow to setNormalizeUri on HTTP client

- dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java
- dropwizard-logging/src/test/resources/yaml/logging_level_off.yml
Fixes #2818
`DefaultLoggingFactory` doesn't allow for `OFF` to be configured as a logger level in the simple config case. Example: 
```
logging:
loggers:
"com.example.my.logger": OFF
```
results in "Unsupported format of logger".
Updated the if check to accept boolean values since `OFF` is translated to `false` in YAML and use existing `toLevel` method that properly handles boolean as `Level.OFF`.
`OFF` will be allowed as a logger level in the simple case without requiring it to be quoted.
> Allow simple logger level config to support "OFF"

- .gitignore
- docs/source/about/release-notes.rst
- docs/source/manual/configuration.rst
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
- dropwizard-jetty/src/test/resources/yaml/http-connector.yml
Starting in version 9.4.3, Jetty's default cookie compliance behavior changed to adhere to the more strict RFC6265 standard which no longer allows for special characters to be included in a cookie value if it is enclosed within double quotes (which was allowed under RFC2109 and RFC2965). In some legacy use cases, the old cookie behavior is needed for the application to behave correctly. 
More Context: https://webtide.com/jetty-cookies-and-rfc6265-compliance/
Jetty allows for the old cookie compliance behavior to be configured for requests or responses via the `HttpConfiguration` object. Dropwizard's `HttpConnectorFactory` can be updated to allow for configuring the legacy cookie compliance behavior.
Dropwizard allows for configuring the request and response cookie compliance behavior for …
> Add support for configuring Jetty cookie compliance

- dropwizard-bom/pom.xml
Due to a vulnerability in jackson-databind 2.9.9 it is being upgraded to 2.9.9.1
Closes #2783
> Upgrade jackson-databind to 2.9.9.1 (1.3 releases)

- dropwizard-bom/pom.xml
Due to a vulnerability in jackson-databind 2.9.9.1 it is being upgraded to 2.9.9.1
Closes #2783
> Upgrade jackson-databind to 2.9.9.1

- dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableSubstitutor.java
https://github.com/dropwizard/dropwizard/pull/2801 solved its problem through a surgical copy and paste from commons-text. It's verbose and we'd miss out on any bugs fixed upstream. 
Use the new `setEnableUndefinedVariableException` baked into commons-text 1.7
`UndefinedEnvironmentVariableException` is still thrown, but now with a different error message.
Before:
> The environment variable 'DOES_NOT_EXIST' is not defined; could not substitute the expression '${DOES_NOT_EXIST}'.
After
> Cannot resolve variable 'DOES_NOT_EXIST' (enableSubstitutionInVariables=false).
Should I work to reconcile the two? All tests currently pass.
> Use commons-text native undef var detection

- dropwizard-auth/src/main/java/io/dropwizard/auth/JSONUnauthorizedHandler.java
Dropwizard provides a `DefaultUnauthorizedHandler` that will returns an HTML error message. A lot of end user seems to need return JSON error message back, which they have to implement themselves, in a more or less consistent fashion with dropwizard error handling.
This provides a `JSONUnauthorizedHandler` that match dropwizard JSON error message handling, and prevent every end user to reimplement one.
- https://github.com/stardogventures/starwizard/blob/master/starwizard-core/src/main/java/io/stardog/starwizard/handlers/JsonUnauthorizedHandler.java
- https://github.com/dropwizard/dropwizard/pull/1863#issuecomment-269090433
> Add a JSONUnauthorizedHandler

- docs/source/about/release-notes.rst
- dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/Authorizer.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
I was looking for a way to authorize a request based on both the `Principal` and path parameters, without having to rewrite an `AuthFilter` or more.
This comes up if you have a `Principal` that has different permissions or roles depending on the object it's accessing, for example: 
A user can access its `Company`, can create a `Case`, but cannot read somebody else `Case`:
```java
@RolesAllowed({"read", "write"})
@GET
public Case getPlan(@Auth User user, @PathParam("company") String company, @PathParam("case") String case) {
return dao.findCase(user, company, case);
}
@RolesAllowed({"write"})
@POST
public Case getPlan(@Auth User user, @PathParam("company") String company) {
return dao.createCase(user, company);
}
```
There is currently no real way to authorize this kind of logic using the …
> Pass request UriInfo to Authorizer.authorize

- dropwizard-bom/pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9#micro-patches
> Upgrade to Jackson 2.9.9.20190807

- pom.xml
Eclipse displayed multiple errors due to unsupported Maven plugins.
Eclipse auto-generated POM changes to fix the errors.
Eclipse IDE can be used for DropWizard development.
> Added eclipse exclusion to fix IDE errors

- .github/workflows/close_stale.yml
Issues and PRs will be marked as stale after 90 days and removed if there wasn't any activity 14 days after that.
> Add GitHub workflow to close stale issues and PRs

- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventAttribute.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactory.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/EventJsonLayout.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/EventJsonLayoutTest.java
json-log-format does not include slf4j marker information in the output.
Added EventAttribute.MARKER and included it if present in EventJsonLayout.
> Add slf4j marker to dropwizard-json-logging.

- dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardExtensionsSupport.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/NestedResourceTest.java
`DropwizardExtensionsSupport` didn't initialize the extension fields of enclosing classes, so that nested tests using fields of the enclosing class wouldn't work.
Fixes #2906
> Support nested JUnit 5 tests with `DropwizardExtension`

- dropwizard-logging/src/main/java/io/dropwizard/logging/ResilientOutputStreamBase.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/ResilientSocketOutputStream.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/socket/DropwizardSocketAppender.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/ResilientSocketOutputStreamTest.java
Using a "reserved" package, such as `ch.qos.logback.core.recovery` from Logback, in an unrelated artifact will cause problems with the Java Platform Module System (JPMS).
In order to prevent a future conflict, the `ResilientSocketOutputStream` and the parent class `ResilientOutputStreamBase` from Logback have been moved into `io.dropwizard.logging`.
While copying code is usually a bad idea, I don't see how we could support Java 9+ with Dropwizard without this change or a change from the Logback project to change the modifier of the required methods in `ResilientOutputStreamBase` to `protected`.
> Move ResilientSocketOutputStream into io.dropwizard.logging

- dropwizard-bom/pom.xml
As per #2938, jackson 2.9.9.20190807 has two newly-discovered threats: CVE-2019-14540 and CVE-2019-16335
Bump jackson.version to 2.9.10
> Update jackson version to 2.9.10

- docs/source/manual/configuration.rst
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/AccessJsonLayoutBaseFactory.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/AccessJsonLayout.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/AccessJsonLayoutTest.java
Summary
=======
Support for requestAttributes similar to LogbackAccessLayout.
When specified, all non-null values will be included in logs
We were using servletFilters to populate certain application specific contextual information and pass them along as request attributes, which are in turn used for central logging of access logs. Lack of way to specify request Attributes in json log layout is hindering us to move to json logging instead of file logging. 
* Added configuration support to specify requestAttribute names to be logged. 
* Retrieving the attribute from `IAccessEvent#getAttribute()` api to add them to json log
> Support for requestAttributes in Json access log

- dropwizard-http2/pom.xml
Refs https://github.com/jetty-project/jetty-alpn/blob/99b59b42ce87c74606749eb8d6593d0ecd7ada72/docs/version_mapping.properties
> Add mapping for Jetty alpn-boot to Java versions

- dropwizard-example/pom.xml
Use same dependency versions in dropwizard-example as in the other projects.
> Use same dependency versions in dropwizard-example

- .github/workflows/maven.yml
The [joschi/setup-jdk](https://github.com/marketplace/actions/setup-java-environment-based-on-adoptopenjdk) action supports the OpenJDK distributions from AdoptOpenJDK.
https://github.com/marketplace/actions/setup-java-environment-based-on-adoptopenjdk
> Move to joschi/setup-jdk for GitHub Actions

- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
- dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
This PR is to support [CachingHttpClientBuilder](https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient-cache/src/main/java/org/apache/http/impl/client/cache/CachingHttpClientBuilder.java)
The `HttpClientBuilder` always creates an `org.apache.http.impl.client.HttpClientBuilder`, which is not possible to take in another builder.
This change together with `customizeBuiler()`, we will be able to create a `CachingHttpClient`.
Instead of hardcoded `org.apache.http.impl.client.HttpClientBuilder.create()`, move it to a method so the subclass can override it and provide other builders.
> make it possible to created subclass of apache http builder

- dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java
The Jackson Afterburner module is currently not compatible with the JPMS and will lead to illegal reflective access operation warnings:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:.m2/repository/com/fasterxml/jackson/module/jackson-module-afterburner/2.9.9/jackson-module-afterburner-2.9.9.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Fixes #2909 …
> Enable Jackson Afterburner only on Java 8

- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
- dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
Similar to https://github.com/dropwizard/dropwizard/pull/2958, this is a further improvement to allow passing in a customised RequestExecutor so that we can additional metrics regarding cache hit and cache miss.
Instead of fixed `new InstrumentedHttpRequestExecutor()`, allow the subclasses to provide their own implementation of `HttpRequestExecutor`
N.A.
> allow overriding request executor

- dropwizard-views/src/main/java/io/dropwizard/views/ViewMessageBodyWriter.java
In our application we want to have a custom application specific locale
detection procedure based on query parameters of the HTTP request.
Currently, the `ViewMessageBodyWriter.detectLocale` method is package
private which makes it quite cumbersome to override.
Make `ViewMessageBodyWriter.detectLocale` protected
We will be able to register our own ViewMessageBodyWriter implementation
which overrides the `detectLocale` method in a nice way.
> Allow overriding ViewMessageBodyWriter#detectLocale()

- dropwizard-bom/pom.xml
As per #2987, jackson 2.910 has three newly-discovered threats: CVE-2019-16942, CVE-2019-16943, CVE-2019-17531.  Each has a CVSS v3.1 score of 9.8
Bump `jackson.version` to 2.9.10.20191020.  This updates `jackson-databind` to 2.9.10.1 but does not change anything else.
> Update to Jackson 2.9.10.20191020

- .github/workflows/maven.yml
```
[ERROR] Unknown lifecycle phase ".test.skip=true". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>.
```
Refs https://stackoverflow.com/questions/6347985/cannot-run-maven-using-mvn-d-argument-within-microsoft-powershell-but-works
> Add quotes to Maven commands in GitHub actions

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/ProvidersBinderTest.java
Before 2.0.0 version, dropwizard and jeresey allowed to register org.glassfish.hk2.utilities.binding.AbstractBinder. This got broken by jersey and then fixed in 2.29. However dropwizard does not pass hk2 Abstract binder directly to jersey, resulting in a failure.
This pull request modifies DropwizardResourceConfig, so that instances of org.glassfish.hk2.utilities.binding.AbstractBinder are passed directly to jersey.
As a result of this pull request, 2.0.0 will behave exactly the same as 1.x.x for configuring hk2 dependency injection.
Fixes #2999
> Register HK2 AbstractBinder with Jersey

- docs/source/manual/client.rst
There are still old URLs in [other files](https://github.com/dropwizard/dropwizard/search?q=%22jersey.github.io%22). I don’t know whether they should point to the latest Jersey version or the one Dropwizard actually uses (which would take some effort to keep in sync).
> Fix links to Jersey Client API

- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
As I was running some tests locally I saw that `TaskServletTest` was throwing `NullPointerException` due to incomplete method stubbing.
Add proper method stubbing in `TaskServletTest` to avoid unnecessary `NullPointerException`'s
`NullpointerException` will not be thrown and caught in `TaskServlet` while running tests.
> Fix Incomplete TaskServletTest Method Stubbing To Avoid NullpointerException In Tests

- docs/source/manual/configuration.rst
- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
- dropwizard-core/src/main/java/io/dropwizard/Configuration.java
- dropwizard-core/src/main/java/io/dropwizard/cli/EnvironmentCommand.java
- dropwizard-core/src/main/java/io/dropwizard/setup/AdminEnvironment.java
- dropwizard-core/src/main/java/io/dropwizard/setup/AdminFactory.java
- dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java
- dropwizard-core/src/main/java/io/dropwizard/setup/HealthCheckConfiguration.java
- dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java
- dropwizard-core/src/test/java/io/dropwizard/server/SimpleServerFactoryTest.java
- dropwizard-core/src/test/java/io/dropwizard/setup/AdminEnvironmentTest.java
- dropwizard-core/src/test/java/io/dropwizard/setup/ExceptionMapperBinderTest.java
- dropwizard-forms/src/test/java/io/dropwizard/forms/MultiPartBundleTest.java
- dropwizard-jdbi3/src/test/java/io/dropwizard/jdbi3/JdbiTest.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskConfiguration.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
This change set adds configuration settings for the tasks resource and the health check resources in the Dropwizard admin interface.
The `printStackTraceOnError` (default: false) setting allows to control whether to expose the full exception stack trace of a failing task.
The `minThreads`, `maxThreads`, and `workQueueSize` configuration settings allow to control the thread settings for health checks.
Closes #3036
> Add config settings for tasks and health check resources

- dropwizard-bom/pom.xml
See https://issues.apache.org/jira/browse/HTTPCLIENT-1968 for detailed background.
4.5.7 introduced a change to normalize URIs by removing repeated forward slashes.  However, this broke encoded reserved characters in the URI, such as the forward slash itself (`%2F`).  I've been running into this while using the latest Dropwizard 1.3 release.
Example URI that fails: `http://localhost/math/1%2F2` (gets converted to `http://localhost/math/1/2` prior to the request being made)
4.5.8 fixed this issue, but .9 and .10 included good fixes as well, so bump up to 4.5.10.
See the release notes for the list of fixes: https://github.com/apache/httpcomponents-client/blob/4.5.10/RELEASE_NOTES.txt
> Upgrade Apache httpclient to 4.5.10 to fix URI rewriting

- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventAttribute.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactory.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/EventJsonLayout.java
- dropwizard-json-logging/src/main/java/io/dropwizard/logging/json/layout/MapBuilder.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/EventJsonLayoutTest.java
Need Slf4j marker in json logs
Backported changes from #2899 
Marker will be included when present
Fixes: #2960
> Add slf4j marker to dropwizard-json-logging (backport)

- dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java
- dropwizard-util/pom.xml
- dropwizard-util/src/main/java/io/dropwizard/util/JavaVersion.java
- dropwizard-util/src/test/java/io/dropwizard/util/JavaVersionTest.java
This MR is to backport the fixes made on b1c39570ef51e0c337f6cacea159fbd80fb598ce to release/1.3.x
The Jackson Afterburner module is currently not compatible with the JPMS and will lead to illegal reflective access operation warnings:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:.m2/repository/com/fasterxml/jackson/module/jackson-module-afterburner/2.9.9/jackson-module-afterburner-2.9.9.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access …
```
> Enable Jackson Afterburner only on Java 8 (backport)

- docs/source/manual/auth.rst
While attempting to implement Basic Authentication, I saw no example of testing for Basic Authentication, while documentation did exist for OAuth.
I have added cleaned example code that I have used in my own project to test Basic Authentication successfully.
More complete documentation.
> Adding BasicAuthentication Documentation Example

- .circleci/config.yml
- .github/workflows/maven.yml
- .travis.yml
- appveyor.yml
- dropwizard-auth/src/main/java/io/dropwizard/auth/AuthorizationContext.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
- dropwizard-dependencies/pom.xml
- dropwizard-e2e/src/test/java/com/example/app1/App1Test.java
- dropwizard-hibernate/pom.xml
- dropwizard-jersey/pom.xml
- dropwizard-jetty/pom.xml
- dropwizard-lifecycle/pom.xml
- dropwizard-migrations/pom.xml
- dropwizard-servlets/pom.xml
- dropwizard-testing/pom.xml
- pom.xml
When creating a shaded jar based on dropwizard APIs, warnings are shown
during shading about duplicate classes on the classpath.
This occurs because there is a mix of javax.* and jakarta.* modules on the
runtime classpath which ship the same (but conflicting) versions of classes.
Update to use the latest jakarta apis in all dropwizard modules instead
of a mix of jakarta and javax.* ones (which ship the same classes). This
should make the APIs on the classpath consistent when creating a shaded
application jar and also avoid warnings about duplicate classes during
shading.
To validate that jakarta apis are used, a Maven profile `jakarta-apis` has
been added to the build. To verify jakarta APIs are used, run the build 
with the argument `-P jakarta-apis`.
Should have no impact to downstream …
> Prefer jakarta apis over older javax apis.

- docs/source/getting-started.rst
- dropwizard-example/src/main/java/com/example/helloworld/api/Saying.java
- dropwizard-example/src/main/java/com/example/helloworld/core/Person.java
- dropwizard-example/src/main/java/com/example/helloworld/resources/HelloWorldResource.java
- dropwizard-example/src/main/java/com/example/helloworld/resources/PeopleResource.java
- dropwizard-example/src/main/resources/migrations.xml
- dropwizard-example/src/test/java/com/example/helloworld/IntegrationTest.java
- dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOTest.java
- dropwizard-example/src/test/java/com/example/helloworld/resources/PeopleResourceTest.java
https://github.com/dropwizard/dropwizard/issues/3053
As described in the Issue #3053, the Saying validation annotation doesn't entirely make sense. 
I have removed the ```@Max``` annotation from the ```Saying``` class and removed the ```@Valid``` annotation from the resource. To still show the annotation in use I have modified the ```Person``` class in core and the people resource to reflect that. I have also added a test to show the validation in action on the resource.
I know adding age to a person isn't a particularly sensible thing  to do normally, but it is a good way to show basic use of these annotations in action. Feedback on the test would also be appreciated, without an exception mapper I'm not sure what to test for - other than what I have implemented.
> Example validation annotations

- docs/source/manual/auth.rst
- docs/source/manual/forms.rst
Dropwizard 2.0 deprecated ResourceTestRule in favor of ResourceExtension. The documentation providing examples of testing resources was not updated to reflect this.
ResourceTestRule has been removed from the documentation in favor of ResourceExtension.
This work was completed in `auth.rst` and `forms.rst` but not `testing.rst` as that will be handled in #3062 
Documentation is now more up-to-date with reality. :)
> Replacing ResourceTestRule with ResourceExtension in documentation

- dropwizard-bom/pom.xml
Update `jackson.version` from 2.9.10.20191020 to 2.9.10.20200103
This has effect of updating `jackson-databind` from 2.9.10.1 to 2.9.10.2 and addresses [CVE-2019-20330](https://nvd.nist.gov/vuln/detail/CVE-2019-20330)
Dropwizard 1.3.17 uses `jackson-databind` 2.9.10.1.  This is vulnerable to CVE-2019-20330
Update `jackson.version` in `dropwizard-bom` from 2.9.10.20191020 to 2.9.10.20200103.
Updating `jackson.version` results in update to `jackson-bom` that is imported by Dropwizard 1.3.x., thus updating `jackson-databind` from 2.9.10.1 to 2.9.10.2. From [jackson release notes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9):
> jackson-databind 2.9.10.2 (03-Jan-2020)
> 2526: Block two more gadget types (ehcache/JNDI -CVE-2019-20330)
> 2544: java.lang.NoClassDefFoundError …
> Update jackson version to 2.9.10.20200103 in 1.3.x branch

- dropwizard-e2e/src/main/java/com/example/app1/App1Resource.java
Test `customJsonProviderRoundtrip` in [App1Test](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-e2e/src/test/java/com/example/app1/App1Test.java) calls`postMapper` in [App1Resource](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-e2e/src/main/java/com/example/app1/App1Resource.java), which returns a HashMap. The test then asserts if the HashMap contains certain entries. However, the test assumes a specific iteration order of the underlying map. But HashMap does not guarantee any specific order of entries. Therefore, the assertions will fail if the iteration order differs
This PR proposes to change the HashMap to LinkedHashMap for a deterministic iteration order (same as insertion order). This order is also same as expected by the test assertion: ` …
> Use LinkedHashMap for deterministic iterations

- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/AssetServletTest.java
Previously, a static CRC32 instance was created and shared across
requests. When assets are requested across multiple threads, the
underlying CRC32 could be calculated inconsistently.
Updated the code to create a new CRC32 instance for each request.
Alternatively, a ThreadLocal could be used if this is determined to be a
major performance issue.
Fixes #3119.
> Fix thread safety issue with eTag calculation.

- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/ResilientOutputStreamBase.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
- dropwizard-metrics/src/main/java/io/dropwizard/metrics/RegexStringMatchingStrategy.java
- dropwizard-parent/pom.xml
Newer versions of Java need to run error-prone as a compiler plugin.
Update the profile for Java 9+ builds to run with error-prone plug-in
and same arguments that are used for Java 1.8 build.
> Enable error-prone on Java 9+ builds.

- .github/workflows/maven.yml
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/DefaultValueUtils.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalDoubleParamConverterProvider.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalIntParamConverterProvider.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalLongParamConverterProvider.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalDoubleMessageBodyWriterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalDoubleParamConverterProviderTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalIntMessageBodyWriterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalIntParamConverterProviderTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalLongMessageBodyWriterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalLongParamConverterProviderTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
DropWizard 2.x changed the behavior of OptionalInt/Long/Double
parameters in two ways. First, empty values used to result in the
`@DefaultValue` of a parameter being used. In DropWizard 2.x, this changed
to return OptionalXYZ.empty() instead.
Additionally, using an invalid value for a `@DefaultValue` parameter used
to fail fast when the Jersey resource was added. This changed with more
lax parsing in DropWizard 2.x.
Update to preserve the previous behavior of empty string parameter
values and invalid `@DefaultValue` values. This should avoid issues with
adoption of DropWizard 2.x.
Fixes #3123.
> Fix regression in OptionalInt/Long/Double handling.

- docs/source/manual/core.rst
Small typo in the `Resources` section of the dropwizard-core doccumentation.
Fixed the typo
N/A
> Fix a typo in the fourth paragraph of the Resources -> Methods section of core.rst

- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ViolationCollector.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
> Escape EL expressions in ViolationCollector

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DefaultValueUtils.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalDoubleParamConverterProvider.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalIntParamConverterProvider.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalLongParamConverterProvider.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParam.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParamConverter.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParamConverterProvider.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
In Dropwizard 1.3.x and earlier, Jersey interpreted empty strings in parameters (`@CookieParam`, `@QueryParam`, etc.) identical to `null` as missing and used the default value (`@DefaultValue`) as fall-back if it existed.
This change set restores the described behavior in Dropwizard 2.x for the classes inheriting from `AbstractParam`.
Keep in mind that `AbstractParam` and its child classes are deprecated and will be removed in a later Dropwizard version in favor of using `Optional<T>` directly.
Refs #3123
Refs #3134
> Fix regression in `AbstractParam` handling

- dropwizard-bom/pom.xml
Refs https://github.com/FasterXML/jackson-databind/issues/2620
> Upgrade to Jackson 2.9.10.20200223 to address CVE-2020-8840

- dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java
Documentation and signature are outdated.
Update them!  
Change to signature should be safe as it does not make the type more restrictive.
Better documentation.
Refs #3020
Refs #3014
Refs #3015
> Fix outdated documentation and method signature

- docs/source/manual/core.rst
There was a dead link for jersey filters and interceptors. Instead of leading you to the documentation it would just redirect you to the main jersey page.
I have updated this link to be https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/filters-and-interceptors.html.
The docs will have the proper link to jersey filters.
> Update dead link to jersey documentation on filters and interceptors

- dropwizard-views-freemarker/src/main/java/io/dropwizard/views/freemarker/FreemarkerViewRenderer.java
- dropwizard-views-freemarker/src/test/java/io/dropwizard/views/freemarker/FreemarkerViewRendererTest.java
This addresses https://github.com/dropwizard/dropwizard/issues/3195
[FreemarkerViewRenderer](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-views-freemarker/src/main/java/io/dropwizard/views/freemarker/FreemarkerViewRenderer.java) uses `freemarker.template.Configuration` in a way that is not recommended by using `Configuration.getVersion()` as the "incompatible improvements" setting.
In this PR a new constructor is defined that lets the user set the version to use for the freemarker configuration and deprecates the old constructor.
The following error messages aren't logged anymore:
```
[2020-03-16T16:42:03,118Z](dw-admin-47)([]) ERROR - configuration - DefaultObjectWrapper.incompatibleImprovements was set to the object returned by Configuration.getVersion(). That defeats …
```
> Fix FreeMarker "incompatible improvements" error logs

- docs/source/about/release-notes.rst
- docs/source/manual/upgrade-notes.rst
- docs/source/manual/upgrade-notes/upgrade-notes-2_1_x.rst
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilderTest.java
Update ExecutorServiceBuilder to remove the format string from the
metric name. Currently, a thread pool named 'jersey-client-foo-%d' will
have metrics 'jersey-client-foo-%d.created',
'jersey-client-foo-%d.terminated', and 'jersey-client-foo-%d.running'
added to the metrics registry. The '-%d' format string is only meant to
ensure that threads are uniquely named and shouldn't be included in the
name of the metric.
Update ExecutorServiceBuilder to strip the format portion of the
nameFormat from the metric name.
Fixes #3139.
> Executor metrics shouldn't contain fmt string.

- dropwizard-validation/src/main/java/io/dropwizard/validation/InterpolationHelper.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidating.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidator.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ViolationCollector.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
Disable message interpolation in `ConstraintViolations` by default but allow enabling it explicitly with `SelfValidating#escapeExpressions()`.
Additionally, `ConstraintViolations` now provides a set of methods which take a map of message parameters for interpolation. These message parameters are be escaped by default.
Thanks to @pwntester and @gsmet for their invaluable input!
Refs #3153
Refs #3157
> Disable message interpolation in ConstraintViolations by default

- dropwizard-dependencies/pom.xml
The hk2-bom includes dependencies on asm but doesn't define the version
of artifacts to pull in. Instead of using hk2-bom, switch to pulling in
specific hk2 dependencies at the proper version in the
dropwizard-dependencies pom.
Fixes #3212.
> Remove dependency on hk2-bom.

- dropwizard-bom/pom.xml
- dropwizard-parent/pom.xml
- pom.xml
The dropwizard-parent POM was using `${project.version}` for specifying the version of dropwizard-dependencies.
This prevented using it in projects in which the version is not a valid (and not the desired) Dropwizard version.
Refs #2897
> Make it easier to inherit from dropwizard-parent

- docs/source/manual/configuration.rst
There is a typo in the code example.  The example as-is doesn't work with Dropwizard
Corrected the typo
Code example works with Dropwizard
> Fix typo in `flattenMdc` field name

- dropwizard-bom/pom.xml
SnakeYAML < 1.26 is vulnerable to a Billion Laughs attack (denial of service).
* https://nvd.nist.gov/vuln/detail/CVE-2017-18640
* https://bitbucket.org/asomov/snakeyaml/issues/377
Refs FasterXML/jackson-dataformats-text#187
Refs #3223
> Upgrade to SnakeYAML to address CVE-2017-18640

- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
`CachingAuthenticator` isn't caching negative results (`Optional.absent()`) because of #947.
But in other cases, not having a negative cache causes a kind of DoS.
If the underlying authenticator requires a little high cost to verify authentication request and the failure will not be cached, many invalid auth requests will cause resource shortage very easily.
In our case, client agents may send so many requests (possibly with invalid auth token by misconfiguration). If we authenticate those requests without negative caches, our underlying authentication endpoint will meet the unexpected number of requests.
The change of this pull-requests introduces optional negative caches. CachingAuthenticator will enable negative caches only when it's specified so.
> Add CachingAuthenticator option to enable negative caches

- dropwizard-jackson/src/main/java/io/dropwizard/jackson/DiscoverableSubtypeResolver.java
Add the ability to have comments in the DiscoverableSubtypeResolver class resources file
Currently if you have any other lines in the discoverable resource files you get a bunch of log lines detailing "cannot load this class".  Example:
```
org.github.Foo
```
Add the ability to allow for comments in the resource file.  Comments are lines that start with `#`.
No more log lines for lines that begin with `#` detailing that it's not a class when parsing the class resource files.
> Support comments in DiscoverableSubtypeResolver

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
Currently, `@Timed` annotations are not useful for asynchronous resource methods. For example:
`````
@Path("/v1/resource")
public class MyResource {
@Timed
@Path("/something")
@GET 
public CompletableFuture<Response> myResourceMethod() {
return someOperationThatRequiresIo().thenApply(entity -> Response.status(200).entity(entity).build());
}
private CompletableFuture<String> someOperationThatRequiresIo() {
...
}
}
`````
When deployed, the `com.mypackage.MyResource.myResourceMethod.duration.*` values will not mean much. They will only incorporate the time it took to construct the future object and return, not the time the resource actually took to run and create a response.
The `InstrumentedResourceMethodApplicationListener` actually supports a flag, `trackFilters`, that listens to the …
> Configure metrics event listener to track filters

- dropwizard-bom/pom.xml
- dropwizard-example/pom.xml
- dropwizard-parent/pom.xml
- pom.xml
Many Maven plugins and other tools needed to automate releases don't support the Dropwizard version being used from a global property in POM files.
> Replace global dropwizard.version property

- dropwizard-bom/pom.xml
Update jackson-bom from  2.9.10.20200223 to 2.9.10.20200411.  This addresses issue #3245 and updates `jackson-databind` from 2.9.10.3 to 2.9.10.4 thus fixing 12 CVE by blocking multiple gadget types (including shiro-core, for which there is no CVE):
* CVE-2020-9546
* CVE-2020-9547
* CVE-2020-9548
* CVE-2020-10969
* CVE-2020-10650
* CVE-2020-10672
* CVE-2020-10673
* CVE-2020-10968
* CVE-2020-11111
* CVE-2020-11112
* CVE-2020-11113
* CVE-2020-11619
* CVE-2020-11620
> Upgrade to Jackson 2.9.10.20200411

- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryFactoryTest.java
Allows to add [Integrators](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/integrator/spi/class-use/Integrator.html) to Hibernate
Add a protected method to SessionFactoryFactory that allow the configuration of BootstrapServiceRegistryBuilder
> Support customizing BootstrapServiceRegistryBuilder

- dropwizard-http2/pom.xml
The alpn-boot dependency is not required anymore starting with Java 8u251/8u252:
https://github.com/jetty-project/jetty-alpn#jetty-alpn
> The ALPN APIs have been backported from Java 9 to OpenJDK 8u251/8u252. Therefore, since OpenJDK 8u251/8u252 there is no more need for the Jetty ALPN boot jar provided by this project.
> Remove alpn-boot dependency in dropwizard-http2 for Java 8u252

- dropwizard-dependencies/pom.xml
https://www.liquibase.org/2020/04/liquibase-4.0.0-beta1-released.html
> Upgrade to Liquibase 4.0.0-beta1

- dropwizard-assets/src/main/java/io/dropwizard/assets/AssetsBundle.java
- dropwizard-assets/src/test/java/io/dropwizard/assets/AssetsBundleTest.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/AssetServletTest.java
Sometimes the default media type of `text/html` in the `AssetServlet` and `AssetBundle` might not be the best fit for every use case.
This PR exposes a setting to specify the default media type for `AssetBundle` and `AssetServlet` and override the default of `text/html`.
> Allow overriding default media type in AssetServlet/AssetBundle

- dropwizard-testing/pom.xml
- dropwizard-testing/src/main/java/io/dropwizard/testing/common/DropwizardTestResourceConfig.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/common/Resource.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/PersonResourceTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ResourceExtensionMocksTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ResourceExtensionRandomPortsTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ResourceExtensionWithJettyTest.java
The `JerseyTest` instance used by `Resource` didn't set `TestProperties.CONTAINER_PORT` properly so that the tests weren't run with a random port which caused problems when trying to run tests in parallel.
> Fix random port assignment in Resource

- dropwizard-example/pom.xml
- dropwizard-example/src/test/java/com/example/helloworld/DockerIntegrationTest.java
- dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOIntegrationTest.java
- dropwizard-example/src/test/resources/test-docker-example.yml
- dropwizard-testing/src/main/java/io/dropwizard/testing/common/DAOTest.java
`DAOTest` was missing a method to override the default password.
This PR adds the missing method as well as `DAOTest#setDriver(String)` which works better with external tooling such as Testcontainers.
> Add missing DAOTest#setPassword() method

- docs/source/manual/upgrade-notes/upgrade-notes-2_0_x.rst
Task.execute method parameter has slightly changed between 1.3 and 2.0.
Added upgrade note
https://github.com/dropwizard/dropwizard/issues/3277
> Added note on Task.execute method

- docs/source/manual/core.rst
Task.execute method parameter has slightly changed between 1.3 and 2.0.
Corrected the parameter type
Fix for https://github.com/dropwizard/dropwizard/issues/3277
> Changed signature of Task.execute method

- docs/source/manual/configuration.rst
Docs on filter factories could be improved. Only after studying this PR https://github.com/dropwizard/dropwizard/pull/1435 it becomes clear how to register them. The fact that logging event has different type for request logger was another conundrum.
Explicitly specify steps to register filter factory and the type to use for which logger (request logging vs generic logging)
> Add details on how to configure filterFactories

- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ScheduledExecutorServiceBuilder.java
The current default thread factory creates a new DefaultThreadFactory instance whenever a new thread is constructed
Just reusing the same threadFactory per executorService
Will reduce object creation when requesting new threads
> Reuse DefaultThreadFactory

- dropwizard-bom/pom.xml
This addresses various security fixes:
* CVE-2020-14062: https://github.com/advisories/GHSA-c265-37vj-cwcc
* CVE-2020-14195: https://github.com/advisories/GHSA-mc6h-4qgp-37qh
* CVE-2020-14060: https://github.com/advisories/GHSA-j823-4qch-3rgm
* CVE-2020-14061: https://github.com/advisories/GHSA-c2q3-4qrh-fm48
> Upgrade to Jackson 2.9.10.20200621

- dropwizard-dependencies/pom.xml
https://github.com/liquibase/liquibase/releases/tag/v3.9.0
https://github.com/liquibase/liquibase/releases/tag/v3.10.0
> Upgrade to Liquibase 3.10.0

- dropwizard-dependencies/pom.xml
`<dependencyManagement>` is commonly used for locking down the version of a dependency, not its scope. Doing that breaks the scope of transitive dependencies and is very hard to troubleshoot.
I've a dependency in my project:
```
<dependency>
<groupId>org.keycloak</groupId>
<artifactId>keycloak-core</artifactId>
<version>${keycloak.version}</version>
</dependency>
```
`keycloak-core`'s `pom.xml` has the following `compile` dependency:
```
<dependency>
<groupId>org.bouncycastle</groupId>
<artifactId>bcprov-jdk15on</artifactId>
<version>${bouncycastle.version}</version>
</dependency>
```
With `dropwizard-dependencies` BOM in my project, here is how `keycloak-core` looks like in the output of maven dependency tree:
```
[INFO] +- org.keycloak:keycloak-core:jar:8.0.2:compile
[INFO] | +- …
```
> Don't specify scope in dependencyManagement of BOM

- dropwizard-validation/src/test/java/io/dropwizard/validation/DataSizeValidatorTest.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/DurationValidatorTest.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/OneOfValidatorTest.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/SizeValidatorTest.java
Conditions within the test method will alter the behavior of the test and its expected output, and would lead to situations where the test fails to detect defects in the production method since test statements were not executed as a condition was not met.
Instead of using a conditional to control the test execution, we use the proper JUnit API with assumeTrue().
Before:
if("en".equals(Locale.getDefault().getLanguage()){...}
After:
assumeTrue("en".equals(Locale.getDefault().getLanguage()),
"This test executes when the defined language is English ('en'). If not, it is skipped.");
> Removed some conditional tests (test smell)

- dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
- dropwizard-core/src/main/java/io/dropwizard/setup/ExceptionMapperBinder.java
- dropwizard-jersey/pom.xml
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/EofExceptionWriterInterceptor.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/EofExceptionWriterInterceptorJerseyTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/EofExceptionWriterInterceptorTest.java
- dropwizard-testing/pom.xml
- dropwizard-testing/src/main/java/io/dropwizard/testing/common/DropwizardTestResourceConfig.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/common/Resource.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/common/ResourceTestJerseyConfiguration.java
If a client drops the connection before a response was completely sent, Jetty will emit an `org.eclipse.jetty.io.EofException` which is then caught by Jersey and logged.
This can quite noisy in the logs and should typically be swallowed instead of logged including the stack trace.
The introduced `EofExceptionWriterInterceptor` will catch `EofException` which are being thrown while writing and will swallow them (after logging on DEBUG level).
Refs #2482
Refs #2541
Refs eclipse/jetty.project#544
> Swallow EofException when response was incomplete

- dropwizard-dependencies/pom.xml
https://github.com/liquibase/liquibase/releases/tag/v3.10.2
https://www.liquibase.org/blog/liquibase-3-10-2-released
> Upgrade to Liquibase 3.10.2

- .github/workflows/maven.yml
reduce noise in the CI build by adding Maven's --no-transfer-progress parameter
> ci: mvn --no-transfer-progress

- dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ReuseDropwizardAppExtensionTestSuite.java
Junit5 jersey client test is broken in 1.3.x due to reset clients
Already fixed in master, backport fixes in https://github.com/dropwizard/dropwizard/pull/2764
> Reset Jersey client in tests

- dropwizard-configuration/pom.xml
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/BaseConfigurationFactory.java
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationMetadata.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/BaseConfigurationFactoryTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationMetadataTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/JsonConfigurationFactoryTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/YamlConfigurationFactoryTest.java
- dropwizard-configuration/src/test/resources/factory-test-valid-no-type.json
- dropwizard-configuration/src/test/resources/factory-test-valid-no-type.yml
This PR resolves the following limitation when overriding configurations by System Properties:
> The array override facility only handles configuration elements that are arrays of simple strings. *Also, the setting in question must already exist in your configuration file as an array; this mechanism will not work if the configuration key being overridden does not exist in your configuration file. If it does not exist or is not an array setting, it will get added as a simple string setting, including the ‘,’ characters as part of the string.*
We ship our services in Docker Containers to be run in our customer's infrastructure and want to give them the possibility to configure rarely used configurations with System Properties. This includes for example the proxy settings of HTTP Clients. We …
> Support parsing system property configuration values as arrays when the field does not exist

- docs/source/manual/hibernate.rst
When piecing together code from the docs, two issues popped up.
Added the setter to the docs so users don't end up seeing
```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "database" (class com.example.helloworld.HelloWorldConfiguration), not marked as ignorable (6 known properties: "server", "template", "defaultName", "logging", "metrics", "admin"])
``` 
when they start piecing their app together.
Added a cast to the usage of `namedQuery` so that people are aware that the function signature has changed since previous versions.
```
/Users/cwalker/Source/hibernate-source/src/main/java/com/example/helloworld/db/PersonDAO.java:24: error: no suitable method found for list(Query<CAP#1>)
return …
```
> Update docs to fix updated methods

- .codeclimate.yml
Since checkstyle was removed in #2693 , disabling it in the codeclimate config in order to fix the badge
> Disable Checkstyle for Code Climate

- docs/source/about/release-notes.rst
- docs/source/manual/configuration.rst
- docs/source/manual/core.rst
- docs/source/manual/upgrade-notes/upgrade-notes-0_7_x.rst
Several documentation files contain minor typos.
Corrected the typos.
Less typos.
> Fix typos in documentation

- docs/source/manual/configuration.rst
- dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
- dropwizard-db/src/main/java/io/dropwizard/db/PooledDataSourceFactory.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java
- dropwizard-db/src/test/resources/yaml/empty_driver_class_db_pool.yml
The `driverClass` configuration setting is only required if no JDBC drivers have been registered with the Java service loader (`META-INF/services/java.sql.Driver`).
Closes #3506
> Make `driverClass` configuration setting optional

- .github/workflows/maven.yml
Forked repositories don't have access to the `SONAR_TOKEN` secret and thus cannot run the SonarCloud analysis as part of the build.
> Run SonarCloud analysis only in dropwizard/dropwizard

- docs/source/manual/configuration.rst
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
The default list of excluded protocols used in `HttpsConnectorFactory` wasn't working as expected.
Jetty currently doesn't support using regular expressions for supported or excluded protocols.
This is only working for supported and excluded _cipher suites_ as of Jetty 9.4.33.v20201020.
The default list of excluded protocols now only contains valid and complete entries:
SSLv3, TLSv1, and TLSv1.1
Refs https://github.com/eclipse/jetty.project/issues/5531
Fixes #3532
> Replace invalid default excludedProtocols in HttpsConnectorFactory

- .github/workflows/maven.yml
- pom.xml
Avoid leaking SonarQube/SonarCloud configuration properties from `dropwizard-project`/`dropwizard-bom`/`dropwizard-dependencies` into projects using `dropwizard-dependencies` as their Parent POM.
Closes #3531
> Move SonarQube settings to GitHub workflow

- dropwizard-configuration/pom.xml
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationMetadata.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationMetadataTest.java
Processing a configuration class with self-referencing fields could lead to an `OutOfMemoryError`.
To prevent this, multiple safe guards have been added:
- Reduce recursion depth from 100 to 10 levels
- Check for loops in the parents of a property
- Take `@JsonIgnore` annotation into account
Fixes #3528
> Prevent deep recursion in ConfigurationMetadata

- dropwizard-json-logging/pom.xml
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/LayoutIntegrationTests.java
Got random build failures while working on #3530 due to two tests in `LayoutIntegrationTests` waiting for log output using a one-off call to `Thread.sleep()`. In addition to being brittle, the tests will fail with an NPE (while trying to assert on the "timestamp" field) that doesn't point to the cause of the failure directly.
Using Awaitility instead of `Thread.sleep()` which will periodically check if either the log output is present or a timeout has been reached.
> Reduce flakiness of LayoutIntegrationTests

- .github/workflows/maven.yml
Forked repositories don't have access to the `SONAR_TOKEN` secret and thus cannot run the SonarCloud analysis as part of the build.
The changes in #3535 unfortunately weren't working as expected because `github.repository` seems to always be set to the repository the GitHub workflow is running in and not the "source" repository of a branch/PR.
> Run SonarCloud analysis only when SONAR_TOKEN is available

- docs/source/manual/configuration.rst
- dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/AppenderFactoryCustomLayoutTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/AppenderFactoryCustomTimeZone.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/TestPatternLayoutFactory.java
- dropwizard-logging/src/test/resources/yaml/appender_with_custom_layout_and_format.yml
- dropwizard-logging/src/test/resources/yaml/appender_with_time_zone_placeholder.yml
As described in #3481, there are two limitations in the appender configuration:
1. When using the **layout** option to set a custom `LayoutFactory`, the **logFormat** is always ignored.
2. The time zone information in a custom **logFormat** is a fixed part of the string and may contradict the configured **timeZone** option.
1. `AbstractAppenderFactory` applies the **logFormat** to any `LayoutFactory` that derives from `PatternLayoutBase`, not just to the default factory. If a **logFormat** is set along with a non-pattern **layout**, a warning will be logged.
2. The introduction of the placeholder `%dwTimeZone` allows the time zone information in a custom log format to depend on the value of the **timeZone** option.
Closes #3481
> Fix logFormat configuration inconsistencies

- README.md
Since v2.0.10, [dropwizard-core](https://github.com/jvm-repo-rebuild/reproducible-central#io.dropwizard:dropwizard-core) is been validated as a reproducible build in [Reproducible Central project](https://github.com/jvm-repo-rebuild/reproducible-central)
But who knows?
A badge in documentation might be good to follow this information. Then users can see directly from the dropwizard repository.
A badge with the "Reproducible build" in status "OK" will be added.
Closes #3468
> #3468 - Add badge for reproducible build

- dropwizard-client/pom.xml
- dropwizard-jetty/pom.xml
- dropwizard-logging/pom.xml
- dropwizard-migrations/pom.xml
I noticed `dropwizard-logging` included a dependency on `commons-lang3` and thought to myself "I bet it doesn't really need that"
I've discovered `commons-lang3` is mostly only used in tests, so I constrained some of the dependencies to `test` scope where possible.
`dropwizard-client`, `dropwizard-jetty`, `dropwizard-logging` and `dropwizard-migrations` will no longer bundle or require `commons-lang3`
In fact commons-lang3 is only used in the following non-test code:
- dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/ConstraintViolationBenchmark.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
- …
> Tighten up commons-lang3 dependencies

- dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationMetadata.java
```
java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/LoggerContextListener
at io.dropwizard.configuration.ConfigurationMetadata$1.optionalProperty(ConfigurationMetadata.java:163)
at io.dropwizard.configuration.ConfigurationMetadata.<init>(ConfigurationMetadata.java:76)
at io.dropwizard.configuration.BaseConfigurationFactory.<init>(BaseConfigurationFactory.java:76)
at io.dropwizard.configuration.YamlConfigurationFactory.<init>(YamlConfigurationFactory.java:29)
at io.dropwizard.configuration.DefaultConfigurationFactoryFactory.create(DefaultConfigurationFactoryFactory.java:18)
at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:124)
at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
at io.dropwizard.cli.Cli.run(Cli.java:78)
at …
```
> Skip errors when visiting default implementations in ConfigurationMetadata

- docs/source/manual/configuration.rst
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
Jetty 9.4.34.v20201102 added support for regular expressions in included/excluded protocols.
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.34.v20201102
Refs #3533
Refs https://github.com/eclipse/jetty.project/issues/5535
This partially reverts commit 206e858b9171d4dff0c71a55a017909cf2b67d22.
> Revert "Replace invalid default excludedProtocols in HttpsConnectorFactory"

- docs/source/manual/views.rst
Out of date links to FreeMarker project
Changed the URL to freemarker.apache.org.
> updated documentation links from freemaker.sourceforge.io to freemaker.apache.org

- dropwizard-dependencies/pom.xml
https://tomcat.apache.org/tomcat-9.0-doc/changelog.html#Tomcat_9.0.41_(markt)
> Bump tomcat-jdbc from 9.0.40 to 9.0.41

- docs/source/manual/testing.rst
assertj.org is now a domain squatting site. Use the docs link from README.md at
https://github.com/assertj/assertj-core
> Fix the AssertJ documentation URL

- docs/source/manual/core.rst
Core page of documentation presents standard project structure incorrectly. Among packages that really exist such as `api`, `health` and `resources` it has `jdbi3` which isn't really a standard structure package judging by [example project](https://github.com/dropwizard/dropwizard/tree/master/dropwizard-example/src/main/java/com/example/helloworld) and also project structure generated from maven archetype.
Replace `jdbi3` with `db` in the docs.
More accurate docs.
> Rename `jdbi3` to `db` packages in example docs

- docs/source/manual/core.rst
One of examples in the core docs misses a parentheses. `UriBuilder.fromResource(NotificationResource.class).build(userId.get(), id)` here is an argument of `Response.created()` which in turn returns `ResponseBuilder()` that requires one more `build()` call to return actual `Response`.
Add missing parentheses.
Better docs.
> Add missing parentheses in example docs

- dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/PersonResourceTest.java
Remove calls to this deprecated method. Neither of the test classes used Mockito annotations, so it wasn't necessary.
> Remove usage of deprecated Mockito#initMocks()

- dropwizard-jackson/src/main/java/io/dropwizard/jackson/AnnotationSensitivePropertyNamingStrategy.java
This has been replaced by PropertyNamingStrategies.SnakeCaseStrategy due to a possible classloader deadlock:
https://github.com/FasterXML/jackson-databind/issues/2715
> Remove usage of deprecated jackson-databind PropertyNamingStrategy.SnakeCaseStrategy

- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
Caffeine does not allow to [register more than one StatsCounter](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Caffeine.java#L945), raising an `IllegalStateException` if you do so. Since Dropwizard attempt to add its own automatically when using Caffeine, this prevent anyone from using a custom one.
This adds a new constructor providing a way to supply a custom `StatsCounter` if needed for `CachingAuthorizer` and `CachingAuthorization`, that will replace the dropwizard one if provided.
> Support custom StatsCounter in CachingAuthenticator/CachingAuthorization

- dropwizard-configuration/src/main/java/io/dropwizard/configuration/BaseConfigurationFactory.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/ServerPushFilterFactory.java
In a couple of places we use the Streams API to join a String list with a delimiter. `String.join()` is a simpler way to do this.
Replace `Stream` usage with `String.join` where possible.
Maybe things will be quicker? Certainly there's a little less code.
> Replace Streams usage with String#join

- dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationMetadata.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/LogbackExcludedTest.java
Only swallow NoClassDefFoundError if the default implementation
generated it, and do not print message to standard output about it.
Currently an error message appears whenever Logback (specifically the
logback-access dependency) is excluded, which users should be able to do
if they configuring logging externally.
Dropwizard generates error output whenever Logback is excluded according to the instructions in the [documentation](https://www.dropwizard.io/en/latest/manual/core.html#logging). See the linked issue: https://github.com/dropwizard/dropwizard/issues/3615
Avoid printing to standard error and only the swallow NoClassDefException generated by the default implementation.
Users who configure external logging will not see spurious error messages.
> Do not print error message about class not found

- dropwizard-logging/src/test/java/io/dropwizard/logging/TcpServer.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/TcpSocketAppenderFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/UdpSocketAppenderFactoryTest.java
We were catching some exceptions and dumping the stack trace. It would be better to fail the tests with details of the exception.
This makes error-prone a little happier.
> Stop ignoring exceptions in dropwizard-logging tests

- dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java
`hasOnlyOneElementSatisfying()` has been deprecated and replaced by `singleElement()`
I adjusted the assertions to use non-deprecated methods. I wasn't too sure about the use of `hasFieldOrPropertyWithValue` though. It feels like there should be a more type-safe way to do this.
Fewer deprecation warnings.
> Replace deprecated AssertJ assertions

- dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
`String.format("%n")` is a rather heavyweight way to get the system's line separator.
Use `System.lineSeparator()` instead. They are specified as being equivalent.
An undetectable performance improvement.
> Use System.lineSeparator() instead of String.format(%n")

- dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/AbstractDropwizardAppExtensionTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionRegisterExtensionTest.java
This PR enables us to use DropwizardAppExtension with JUnit 5's "RegisterExtension" annotation.
We're adding JUnit 5 capabilities to our open source framework [sda-dropwizard-commons](https://github.com/SDA-SE/sda-dropwizard-commons/). We noticed that JUnit 4's RuleChain is no longer available and are looking for a different solution to specify the order of the execution of the extensions. This is needed to spin up a service (e.g. with Wiremock) beforehand and configure URLs and ports in our application afterwards.
JUnit 5 provides these solutions as far as I know:
- declare the order by enumerating all extensions in your `ExtendWith` annotation
- declare the order by the order of the fields that have a `RegisterExtension` annotation
- you can also add an `Order` annotation to the fields …
> DropwizardAppExtension support for RegisterExtension

- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
The `dropwizard-jetty` tests use reflection in a couple of places where it isn't necessary.
Also, we use `commons-lang3` to perform OS detection for a test. JUnit has a built-in mechanism for this.
Replace reflection with calls to the relevant accessors.
Use JUnit's built-in OS detection.
More compile-time type safety, tests will be more JUnit-y.
> Reduce use of reflection in dropwizard-jetty tests

- dropwizard-client/src/main/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactory.java
- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
`DropwizardSSLConnectionSocketFactoryTest` uses `commons-lang3`'s `FieldUtils` to access a private member field of `DropwizardSSLConnectionSocketFactory`.
Move the test to the same package as the class it's testing and make the field package-private.
Less reliance on reflection, which makes the tests less fragile.
> Move DropwizardSSLConnectionSocketFactoryTest to io.dropwizard.client

- dropwizard-auth/src/test/java/io/dropwizard/auth/AuthBaseTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/principal/PolymorphicPrincipalEntityTest.java
It is (subjectively) better to specify tests in terms of success rather than terms of failure and also for there to be less code, provided it works and isn't confusing.
With that in mind, some tests could be improved slightly.
translate
```
try {
something();
failBecauseExceptionWasNotThrown();
} catch (Exception e) {
// assert some things about e
}
```
into
```
assertThatExceptionOfType(Exception.class)
.isThrownBy(() -> something())
// assert some more things
```
There is less code and (opinions may differ) the tests become more expressive.
If you agree this is a good thing to do, there are other places where `failBecauseExceptionWasNotThrown` is used and I'm happy to give those the same treatment if they look like suitable candidates.
Also, if these little cleanup PRs are annoying and …
> Use assertThatExceptionOfType in dropwizard-auth

- dropwizard-client/pom.xml
- dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
- dropwizard-jetty/pom.xml
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
- dropwizard-logging/pom.xml
- dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java
- dropwizard-metrics-graphite/pom.xml
- dropwizard-metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterFactoryTest.java
- dropwizard-migrations/pom.xml
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbStatusCommandTest.java
No real problem, just a personal vendetta. Feel free to close the PR if you disagree.
`dropwizard-jetty` tests use reflection to determine the configuration of the created `ArrayByteBufferPool`. Switch to using (in a rather icky way) Mockito spy instead. This is taken from https://github.com/dropwizard/dropwizard/pull/3661
Remove Apache commons-lang3 from several sets of tests
commons-lang3 is only now directly depended on by
- dropwizard-jersey
- dropwizard-views
There are marginally fewer LOC.
> Remove apache commons-lang3 from tests

- dropwizard-core/src/main/java/io/dropwizard/cli/ConfiguredCommand.java
- dropwizard-core/src/main/java/io/dropwizard/cli/EnvironmentCommand.java
- dropwizard-e2e/src/main/java/com/example/badlog/BadLogApp.java
- dropwizard-e2e/src/test/java/com/example/badlog/BadLogTest.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionWithCheckCommandTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionWithConfiguredCommandTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardAppExtensionWithCustomCommandTest.java
`DropwizardTestSupport` didn't support running plain `Command` or `ConfiguredCommand<C>` classes which have been with the `commandInstantiator` parameter in the `DropwizardAppExtension` extension (JUnit 5) or `DropwizardAppRule` rule (JUnit 4).
> Add support for testing plain Command classes

- docs/source/manual/core.rst
Not calling super from `ConfiguredCommand#configure` skips the declaration of the configuration parameter. Making it mandatory would involve some non-minor API changes so emphasised the need of the super call on the docs (The wording is pretty similar to the [javadoc](https://www.javadoc.io/doc/io.dropwizard/dropwizard-core/1.0.2/io/dropwizard/cli/ConfiguredCommand.html#configure-net.sourceforge.argparse4j.inf.Subparser-))
Explicitly state the need for the `super` call. 
Hopefully less people will be confused when they configure a `ConfiguredCommand` that fails to accept the configuration file as a parameter.
Closes https://github.com/dropwizard/dropwizard/issues/3669
> Clarify the need of calling super from ConfiguredCommand

- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
Simplify and normalise the test assertions relating to exceptions, favouring `assertThatExceptionOfType` over other mechanisms.
> Refactor testing of thrown exceptions in dropwizard-client

- dropwizard-assets/src/test/java/io/dropwizard/assets/AssetsBundleTest.java
JUnit 5 no longer requires test classes and methods to be declared public and Sonar grumbles about this.
If this is alright, I'm happy to do it to the rest of the tests, but it'll either be a large MR for everything or a lot of medium sized MRs. Let me know what you think.
> Remove public modifiers from dropwizard-assets tests

- dropwizard-auth/src/main/java/io/dropwizard/auth/AuthValueFactoryProvider.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/PolymorphicAuthValueFactoryProvider.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicCredentialsTest.java
Sonar didn't like the accesses of static fields on a derived type, preferring direct access to the supertype instead.
Also, some assertions in the tests can be chained and we can use a few more specialised AssertJ assertions to make the tests more expressive.
> Address SonarCloud concerns in dropwizard-auth

- dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
Ensure these tests use the temporary directory provided by JUnit for their log files.
Stop the appender before finishing the test so that open file handles won't upset Windows.
Slip in a couple of cleanups whilst we're here.
> Ensure FileAppenderFactoryTest works within its temporary directories

- dropwizard-e2e/pom.xml
- dropwizard-e2e/src/test/java/com/example/sslreload/SslReloadAppTest.java
This was only used for the `NoopHostnameVerifier` in `SslReloadAppTest`, but since it's a functional interface we can replace it with a lambda expression.
With this removal, `dropwizard-client` is the only module which depends on `httpclient` directly.
> Remove Apache httpclient from dropwizard-e2e

- dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/DropwizardResourceConfigBenchmark.java
- dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/SelfValidatingBenchmark.java
Sonar isn't a fan of empty methods, considering them a critical issue. Add a comment to persuade it that things are OK.
I don't really like doing this, but having Sonar scream "critical" isn't great either. Is there a better way? Sonar currently complains about 64 things it deems critical and this will resolve 9 of them.
> Appease Sonar in dropwizard-benchmarks

- dropwizard-testing/src/test/java/io/dropwizard/testing/app/GzipDefaultVaryBehaviourTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceExceptionMapperTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithGrizzlyTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithoutLoggingBootstrapTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleConfigTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleWithoutLoggingBootstrapTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleConfigOverrideTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleReentrantTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleResetConfigOverrideTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleWithExplicitTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleWithoutConfigTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardClientRuleTest.java
This is a regression from f17aea0e7669b6182330151697022b1d44fde8bd - not all tests are jUnit 5. jUnit 4 test methods should be made public.
> Make jUnit 4 test methods public

- dropwizard-dependencies/pom.xml
- dropwizard-hibernate/pom.xml
- dropwizard-testing/pom.xml
Dependencies declared in a BOM shouldn't have scopes pre-defined.
Fixes #3769
> Remove explicit scope in dropwizard-dependencies

- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactoryTest.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/AccessJsonLayoutTest.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/EventJsonLayoutTest.java
verify start() and stop() behavior in dropwizard-json-logging
add new assertions to dropwizard-json-logging test suite
> add assertions for json-logging start() and stop() methods

- .github/workflows/maven.yml
- .github/workflows/release.yml
The `CACHE_VERSION` repository secret can be used to "purge" the caches created by the `actions/cache` action.
Using the current date for `CACHE_VERSION` and a random suffix should suffice, for example `2021-03-17-cache`.
Refs https://github.com/actions/cache/issues/2
Refs https://stackoverflow.com/a/64819132
> Support "purging" the GitHub workflow cache

- dropwizard-http2/pom.xml
- dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/AbstractHttp2Test.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2CIntegrationTest.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2ConnectorFactoryTest.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2IntegrationTest.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithConscrypt.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithCustomCipherTest.java
The HTTP/1.1 protocol wasn't added to the ALPNServerConnectionFactory constructor which prevented using HTTP/1.1 when ALPN was being used.
Directly using HTTP/1.1 without ALPN was still possible.
Fixes #3776
Refs https://github.com/eclipse/jetty.project/issues/6058
> Properly support HTTP/1.1 in Http2ConnectorFactory

- dropwizard-parent/pom.xml
The signature verification of our dependencies is often running into problem, so let's skip POM signature verification for now.
The actual artifacts (JARs) are still verified.
> Skip POM signature verification

- dropwizard-auth/src/main/java/io/dropwizard/auth/AuthorizationContext.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/Authorizer.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/DefaultAuthorizationContext.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
This address issue #3714, where `ContainerRequestContext ` is too unique and increases drastically the chance of cache misses.
This solve the problem by allowing an authorizer to return a custom `AuthorizationContext` used by `CachingAuthorizer`.
The existing behaviour is unchanged, but if you'd wish to be able to increase your cache hit you can return make your `Authorizer` return a custom `AuthorizationContext` that will be unique for the attributes/fields you need to authorize a request.
> Support using custom AuthorizationContext

- dropwizard-jackson/pom.xml
- dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java
Instead of going to great lengths trying to accommodate users Java 8 and 9+, let's use this opportunity to give them a nudge in the right direction and upgrade their JVM. 😉 
Since the Jackson Blackbird module is working with Java 8 and later, there shouldn't be a big performance impact for anyone according to the benchmarks mentioned in the Blackbird documentation.
https://github.com/FasterXML/jackson-modules-base/blob/jackson-modules-base-2.12.2/blackbird/README.md
https://cowtowncoder.medium.com/jackson-2-12-features-eee9456fec75#ec83
Closes #3652
Closes #3674
> Replace Jackson Afterburner with Blackbird

- dropwizard-example/src/test/java/com/example/helloworld/DockerIntegrationTest.java
- dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOIntegrationTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
The latest versions of Java 8 and 11 don't support TLSv1.1 anymore.
```
JDK-8256490: Disable TLS 1.0 and 1.1
====================================
TLS 1.0 and 1.1 are versions of the TLS protocol that are no longer
considered secure and have been superseded by more secure and modern
versions (TLS 1.2 and 1.3).
These versions have now been disabled by default. If you encounter
issues, you can, at your own risk, re-enable the versions by removing
"TLSv1" and/or "TLSv1.1" from the `jdk.tls.disabledAlgorithms`
security property in the `java.security` configuration file.
```
https://mail.openjdk.java.net/pipermail/jdk8u-dev/2021-April/013680.html
https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2021-April/005860.html
> Exclude TLSv1.1 in `HttpsConnectorFactoryTest`

- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ResourceExtensionRandomPortsTest.java
`ResourceExtensionRandomPortsTest` regularly fails because one or more ports are randomly occurring twice.
[![Dilbert: Tour of accounting](https://assets.amuniversal.com/321a39e06d6401301d80001dd8b71c47)](https://dilbert.com/strip/2001-10-25)
> Make `ResourceExtensionRandomPortsTest` less flaky

- docs/source/index.rst
- docs/source/manual/di.rst
refs #1626
This provides a sample documentation for how HK2 that comes included with Dropwizard can be used for implementing test-friendly DI mechanism in your application.
Added new section "Dropwizard Dependency Injection" to the documentation.
> Add example for using HK2 for DI in your project

- dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
When using the archetype to create a new project based on Dropwizard, it uses a version of surefire that is not yet compatible with JUnit 5. This causes problems because unexpectedly no tests are being run when the project is being built with Maven. Since testing examples in the docs use JUnit 5 I think it should be supported out of the box with the need to adjust your `pom.xml`
Added a plugin declaration for surefire 2.22.2 to the template for the `pom.xml`
New projects created using the archetype automatically run JUnit 5 tests.
> Use surefire plugin in archetype compatible with JUnit 5

- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
With this change the extension of the index file is used do determine the content type of responses of requests to directories.
Background: I have written a filter which uses a servlet extending `AssetServlet` to serve static resources at the same path level as Jersey resources (for example, it’s possible to have dynamic Jersey resources at `/someResource` while also serving static content at paths like `/`, `/robots.txt` and `/favicon.ico`). Currently the servlet replaces the `HttpServletRequest` with a [proxy](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/reflect/Proxy.html) which replaces the return value of `getRequestURI()` with the URI of the index file if the real request URI ends with `/`. This change eliminates the need for the (somewhat ugly) proxy.
If …
> AssetServlet: Use MIME type of index file for directory requests

- docs/source/manual/hibernate.rst
- dropwizard-example/src/main/java/com/example/helloworld/db/PersonDAO.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/AbstractDAO.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java
`AbstractDAO` offers a way to easily get named queries but does so in a way that requires casting the returned `Query` to the correct type.
Added a method to `AbstractDAO` which returns a named query in a type-safe way, `namedTypedQuery(String)`. This methods uses `Session#createNamedQuery(String, Class)` internally where the generic type is retrieved via `AbstractDAO#getEntityClass()`.
I hope I followed all conventions of this project. Please let me know if you would like me to change anything.
> Add method to `AbstractDAO` to get `NamedQuery` in a type-safe manner

- dropwizard-dependencies/pom.xml
Release notes:
https://github.com/dropwizard/metrics/releases/tag/v4.1.22
> Bump Dropwizard Metrics from 4.1.21 to 4.1.22

- dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java
Dropwizard allows customized object mapper. If the customization happens to disable AUTO_DETECT_SETTERS (https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/MapperFeature.html#AUTO_DETECT_SETTERS), it will only consider methods explicitly annotated as setters. Thus layout field cannot be recognized. 
Also, it is not consistent with other properties in the same file. The other setters/getters are all annotated.
Add @JsonProperty annotation for layout property getter and setter
> Add @JsonProperty for field layout getter/setter

- dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java
HTTP/2 requires that a server MUST support TLSv1.2 or higher.
See http://http2.github.io/http2-spec/index.html#rfc.section.9.2.2
Fixes #4066
> Add support for HTTP/2 over TLSv1.3

- dropwizard-core/pom.xml
- dropwizard-dependencies/pom.xml
https://github.com/dropwizard/metrics/releases/tag/v4.1.23
> Upgrade to Dropwizard Metrics 4.1.23

- dropwizard-dependencies/pom.xml
https://github.com/dropwizard/metrics/releases/tag/v4.1.24
> Upgrade to Dropwizard Metrics 4.1.24

- dropwizard-dependencies/pom.xml
https://github.com/dropwizard/metrics/releases/tag/v4.1.25
> Upgrade to Dropwizard Metrics 4.1.25

- docs/source/manual/core.rst
Provide a link directly to the section in the docs on overriding configuration via system properties.
Add an anchor to the note in the docs on overriding configs via system properties.
> Add anchor to note on config overrides to allow direct links

- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/ByteRange.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/ByteRangeTest.java
`AssetsServlet` will accept a `Range:` header which isn't RFC-compliant due to the behaviour of `Integer.parseInt` 
`Integer.parseInt()` will gladly accept non-ASCII representations of digits, but RFC7233 specifies that only ASCII 0-9 are valid digits in a `Range` header.
I initially thought this might have some security implications, but I've decided either I'm lacking in creativity or it's just a regular minor bug.
Treat the header value as ASCII when parsing.
Requests with an invalid `Range` header will be rejected.
> Be stricter when parsing 'Range' headers

- dropwizard-migrations/pom.xml
`dropwizard-migrations` only needs it for `CloseableLiquibaseTest`. Move the dependency to `test`.
We do still depend on `dropwizard-db` which pulls it in, so there isn't really a change to the overall dependency graph here.
> Tighten up tomcat-jdbc dependency in dropwizard-migrations

- dropwizard-migrations/src/test/java/io/dropwizard/migrations/AbstractMigrationTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbCalculateChecksumCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbClearChecksumsCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDropAllCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbFastForwardCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbGenerateDocsCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbLocksCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCustomSchemaTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateDifferentFileCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbPrepareRollbackCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbRollbackCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbStatusCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbTagCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbTestCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/TestMigrationConfiguration.java
There are some opportunities to improve the `dropwizard-migrations` tests.
- Some fields could be made `final`
- The UTF-8 character set was referenced via a shared string when `StandardCharsets` could be used instead.
- In some cases we were using the ability to create something (e.g. a table) as a proxy for  detecting whether the table existed or not.
- Make fields `final` which can be.
- Switch to using `StandardCharsets`.
- Test for existence of database entities directly rather than using the ability to create them as a proxy.
Tests should be a bit more precise and Sonar should complain a bit less.
> Improve dropwizard-migrations tests

- dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckSchedulerTest.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/AbstractHttp2Test.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2CIntegrationTest.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2IntegrationTest.java
Sonar is currently listing 9 'Blocker' code smells. They're mostly pretty spurious, but some are about test methods which lack assertions, which are mostly easy to fix.
Where a test is testing that no exception is thrown (`HealthCheckSchedulerTest`), use `assertThatCode().doesNotThrowAnyException()` to be explicit about what is being tested.
In `dropwizard-http2`, `AbstractHttp2Test` has a helper method `performManyAsyncRequests` which is called by both `Http2IntegrationTest` and `Http2CIntegrationTest`. It contains embedded assertions about each requests and also a final assertion that all requests completed within a reasonable time.
Move that final assertion to the caller by returning a boolean. Also make the helper `static` and call it as a class method rather than instance method.
The …
> Add more test assertions

- docs/source/manual/example.rst
Documentation [Dropwizard Example, Step by Step](https://www.dropwizard.io/en/latest/manual/example.html>) makes mention of the example project, but does not supply a link. New users, such as; myself, are left to search for the source code.
While most users will likely enter through [Getting Started](https://www.dropwizard.io/en/latest/getting-started.html), which has a link to the source code, users entering by way of the the example page mentioned above could use the link as well.
Added link to documentation
Users can link directly to the mentioned example application's source code from the [Dropwizard Example, Step by Step](https://www.dropwizard.io/en/latest/manual/example.html>) page.
> Link to example application source code from docs

- dropwizard-auth/src/test/java/io/dropwizard/auth/AuthFilterTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/OptionalAuthFilterOrderingTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicCredentialsTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/chained/ChainedAuthProviderTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthProviderTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/principal/NoAuthPolymorphicPrincipalEntityTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/principal/NoAuthPrincipalEntityTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/principal/PolymorphicPrincipalEntityTest.java
This is no longer needed since JUnit 5
> Remove public modifiers from dropwizard-auth tests

- dropwizard-core/src/test/java/io/dropwizard/validation/InjectValidatorFeatureTest.java
- dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckSchedulerTest.java
- dropwizard-health/src/test/java/io/dropwizard/health/response/ServletHealthResponderFactoryTest.java
- dropwizard-health/src/test/java/io/dropwizard/health/response/ServletHealthResponderTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/filter/AllowedMethodsFilterTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/NonblockingServletHolderTest.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/AccessJsonLayoutTest.java
- dropwizard-metrics/src/test/java/io/dropwizard/metrics/ScheduledReporterManagerTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleTest.java
This isn't needed as equality is the default matcher type. Picked up by Sonar.
> Remove unnecessary eq() Mockito references

- dropwizard-e2e/src/main/java/com/example/app1/CustomClassBodyWriter.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/ZipExceptionHandlingInputStream.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/ResilientOutputStreamBase.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/common/DAOTest.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidator.java
Sonar never stops complaining
- AssertJ assertions can be chained
- A private helper function is only used by an inner class
- The order of modifiers doesn't match the Java Language Specification
Do the things Sonar suggests
Sonar will still complain, just marginally less.
> Sonar tidy

- dropwizard-auth/src/test/java/io/dropwizard/auth/AuthBaseTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/principal/PolymorphicPrincipalEntityTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
- dropwizard-e2e/src/test/java/com/example/health/HealthIntegrationTest.java
- dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedClassResourceTest.java
- dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedResourceTest.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/ErrorEntityWriterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/LoggingExceptionMapperTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalMessageBodyWriterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalDoubleMessageBodyWriterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalDoubleParamConverterProviderTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalIntMessageBodyWriterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalIntParamConverterProviderTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalLongMessageBodyWriterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalLongParamConverterProviderTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalMessageBodyWriterTest.java
- dropwizard-views-freemarker/src/test/java/io/dropwizard/views/freemarker/FreemarkerViewRendererTest.java
- dropwizard-views-mustache/src/test/java/io/dropwizard/views/mustache/MustacheViewRendererFileSystemTest.java
Sonar warns, if methods are chained inside the lambda of `isThrownBy`.
Extract the chained methods to a local variable and only call the last method inside `isThrownBy`.
Sonar will provide less code smells.
> Sonar cleanup

- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/BaseConfigurationFactory.java
- dropwizard-jdbi3/src/test/java/io/dropwizard/jdbi3/JdbiHealthCheckTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/filter/RuntimeFilterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalLongMessageBodyWriterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalQueryParamResourceTest.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/layout/AccessJsonLayoutTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/AppenderFactoryCustomLayoutTest.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/ResourceHelpers.java
- dropwizard-util/src/test/java/io/dropwizard/util/EnumsTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/GenericsTest.java
- Some tests are still marked public (I missed a few earlier)
- `BaseConfigurationFactory` has a couple of nested `if` statements
- `CachingAuthorizer` in `dropwizard-auth` has a complex boolean comparison which can be simpler
- `AssetServlet` has nested try-catch blocks, which Sonar doesn't like
- A couple of `catch` blocks use `instanceof` to match certain types of exception
- Remove `public` from the remaining tests
- Merge nested `if` statements
- Use `Boolean.TRUE.equals()` to cope with possible null values when comparing
- Move inner try-catch to the helper function it was surrounding
- Match exception types using `catch` rather than `instanceof`
This should be a no-op and Sonar should be a little happier.
A secondary effect is that I will probably not raise any more Sonar PRs for a …
> More Sonar-induced fixups

- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java
- [dropwizard-lifecycle ExecutorServiceBuilder](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&open=AXUXdI01pBosHuY9-P9n&resolved=false&types=BUG) ignores the result of String.format, but intentionally so as it's using the call to check that the format string is valid.
Instead of calling `String.format` and throwing away the result, instantiate a `Formatter` and use that. It still throws an exception on invalid format strings, but doesn't generate a formatted string.
Sonar will stop complaining about this
> Use Formatter to validate format strings, rather than String.format()

- dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java
- dropwizard-core/src/test/java/io/dropwizard/server/SimpleServerFactoryTest.java
- dropwizard-jackson/src/test/java/io/dropwizard/jackson/JacksonTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/NonblockingServletHolderTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/SyslogAppenderFactoryTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
Rather than checking some code doesn't explode, it's better to check that it does something.
> Replace doesNotThrow assertions with more explicit checks

- docs/source/manual/client.rst
- Explicitly state to include dependency into project dropwizard-client
- The Rx Usage was out of date. Added RxJava2 example instead.
1) Problem was that the documentation doesn't explicitly states that it is necessary to add additional dependency dropwizard-client
2) Problem was in outdated Rx Usage example that didn't work. 
1) Added dependency inclusion fragment at the top
2) Fixed Rx Usage example by introducing RxJava2 example
> Update dropwizard-client docs

- .github/workflows/maven.yml
- .github/workflows/release.yml
- appveyor.yml
- dropwizard-parent/pom.xml
- pom.xml
Instead of relying on activating a build profile, always enforce using Jakarta EE APIs.
> Always enforce using Jakarta EE APIs

- dropwizard-core/pom.xml
- dropwizard-http2/pom.xml
- dropwizard-jetty/pom.xml
> Exclude `javax.servlet:javax.servlet-api` from Jetty dependencies

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/AbstractParamConverter.java
Sonar didn't like this method name. The name wasn't really meaningful, so inline it.
> Inline helper in dropwizard-jersey AbstractParamConverter

- docs/source/manual/core.rst
Currently, in the docs, Jersey filters and Servlet filters are placed in the Representations section, and it seems like they don't belong to it.
Add a separate section for filters
> Move jersey and servlet filters to their own section in the docs

- dropwizard-validation/pom.xml
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidator.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidatorTest.java
The `dropwizard-validations` tests produce output to the console:
```
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ dropwizard-validation ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.dropwizard.validation.selfvalidating.SelfValidatingValidatorTest
2021-11-02T20:35:23.035Z [main] ERROR io.dropwizard.validation.selfvalidating.SelfValidatingValidator - The method public boolean io.dropwizard.validation.selfvalidating.SelfValidatingValidatorTest$InvalidExample.validateFailReturn(io.dropwizard.validation.selfvalidating.ViolationCollector) is annotated with @SelfValidation but does not return void. It is ignored
Nov 02, 2021 8:35:23 PM …
```
> Suppress console output in `dropwizard-validations` tests

- dropwizard-validation/pom.xml
- dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
The `slf4j-test` and `lidalia-slf4j-ext` packages only get used in one test and can be replaced with `logback` functionality.
Use `logback` over the `uk.org.lidalia` packages, since `logback` is used elsewhere in the project.
The project will contain less dependencies.
> Replace slf4j-test by logback

- dropwizard-validation/src/test/resources/slf4jtest.properties
slf4jtest is no longer used, following https://github.com/dropwizard/dropwizard/pull/4399
> Remove old slf4jtest configuration

- dropwizard-client/pom.xml
- dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java
As far as I can see, only the `LocalizationMessages.ERROR_BUFFERING_ENTITY()` method from the `jersey-apache-connector` seems to be used.
Drop the localization by returning the String from a constant and remove the dependency.
The project will contain less dependencies.
> Remove jersey-apache-connector

- dropwizard-e2e/src/test/java/com/example/badlog/BadLogTest.java
- dropwizard-testing/pom.xml
- dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
`dropwizard-e2e`'s `BadLogTest` is failing on windows, because a file is not properly closed on application shutdown.
Stop all logging appenders in the `DropwizardTestSupport.after()` method to free the occupied resources.
Used resources are properly freed and therefore the `BadLogTest` can be re-enabled for Windows.
> Fix `BadLogTest`

- dropwizard-health/src/test/java/io/dropwizard/health/check/tcp/TcpHealthCheckTest.java
When executing the tests on Windows with Java 11, a `SocketTimeoutException` is thrown in a test of `dropwizard-health` instead of a `ConnectException`. However, the test completes successfully when running with Java 17 or when running the test on Linux.
Since the framework will probably support Java 11 for quite some time, the test should succeed on Windows. Therefore the test is modified to allow both exception types.
> `SocketTimeoutException` instead of `ConnectException` thrown on Windows

- dropwizard-parent/pom.xml
When building the project with Java 17 on Windows, an error is thrown because of an 'invalid flag'.
Windows doesn't seem to like new lines in argument definitions, so remove all new lines and place all options on one line.
The build will complete on Windows.
> Fix build on Windows with Java 17

- dropwizard-logging/src/test/java/io/dropwizard/logging/ResilientSocketOutputStreamTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/TcpServer.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/TcpSocketAppenderFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/TlsSocketAppenderFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/UdpServer.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/UdpSocketAppenderFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/socket/DropwizardUdpSocketAppenderTest.java
These tests relied on `TcpServer` and counting the number of log messages
received.
Replace direct `Thread` usage with `ExecutorService` and `Future` so that we
can instead retrieve the log messages actually received and perform assertions
on them.
Do the same for UDP-based tests, introducing `UdpServer`.
Note that the logs in `UdpSocketAppenderFactoryTest` have trailing newlines, unlike those in `TcpSocketAppenderFactoryTest` - is that expected?
> Improve dropwizard-logging socket-based tests

- dropwizard-views-freemarker/pom.xml
```
[INFO] --- maven-dependency-plugin:3.1.2:analyze-only (analyze) @ dropwizard-views-freemarker ---
[WARNING] Used undeclared dependencies found:
[WARNING]     io.dropwizard.logback:logback-throttling-appender:jar:1.1.4:compile
[WARNING]  Unused declared dependencies found:
[WARNING]     com.google.code.findbugs:jsr305:jar:3.0.2:compile
```
Refs #4458
> Fix dependency scopes in dropwizard-views-freemarker

- pom.xml
After the migration to the new OSSRH Sonatype instance releases will hopefully be more reliable.
https://central.sonatype.org/news/20210223_new-users-on-s01/
https://issues.sonatype.org/browse/OSSRH-76149
> Update repository URLs for new OSSRH Sonatype instance

- dropwizard-jersey/pom.xml
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
`commons-lang3` is (IMO) largely unnecessary baggage in Java 8+ and we should work hard to minimise unnecessary dependencies.
Replace lang3 usage with standard Java where possible.
The only remaining usage of `commons-lang3` in Dropwizard is now `ExceptionUtils` because finding the root cause of an exception in Java is (in the general case) annoyingly nontrivial.
The remaining usages are:
- dropwizard-jetty's `ZipExceptionHandlingGzipHandler`
- dropwizard-views's `ViewRenderExceptionMapper`
and a usage in `dropwizard-e2e`
> Remove commons-lang3 from dropwizard-jersey

- dropwizard-parent/pom.xml
The pgpverify plugin complains about the hkp:// SKS keyservers URL.
Since the plugin's default list of keyservers is the same, just using HTTPS rather than hkp/hkps, remove the explicit list and fall back to the default.
> Remove keyserver list

- .github/workflows/maven.yml
Use https://github.com/ScaCap/action-surefire-report for collecting and publishing Surefire test reports.
> Publish Maven test results

- dropwizard-validation/src/main/java/io/dropwizard/validation/MaxSize.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/MaxSizeValidator.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/MinSize.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/MinSizeValidator.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/SizeRange.java
`Size` is deprecated in favour of `DataSize` so it makes sense to also deprecate the corresponding validators.
> Deprecate the `Size` validators in favour of `DataSize` validators

- dropwizard-e2e/src/test/java/com/example/health/HealthIntegrationTest.java
- dropwizard-health/src/test/java/io/dropwizard/health/StateTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipHandlerFactoryTest.java
- dropwizard-lifecycle/pom.xml
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilderTest.java
AssertJ 3.22.0 adds `singleElement()` for `ObjectArrayAssert`. Use it in `GzipHandlerTest`.
Use parameterized tests in `ExecutorServiceBuilderTest`
AssertJ supports asserting on `AtomicInteger` and friends so there's no need to call .get() explicitly.
> Small test enhancements

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java
This is an internal class which should probably be package-private.
Mark it deprecated as a step towards doing that.
(this is as an alternative to just straight up doing that - https://github.com/dropwizard/dropwizard/pull/4569)
> Mark dropwizard-jetty's `NetUtil` deprecated

- dropwizard-auth/pom.xml
- dropwizard-core/pom.xml
- dropwizard-dependencies/pom.xml
- dropwizard-jersey/pom.xml
Jersey 2.35 uses a repackaged `javax.inject` OSGi bundle from HK2, which seems to get no further updates. So especially the package would not support the `jakarta.inject` namespace.
Update `org.glassfish.hk2.external:jakarta.inject` to `jakarta.inject:jakarta.inject-api`.
The migration of Dropwizard to the Jakarta namespace will get easier.
> Update HK2's repackaged jakarta.inject to jakarta.inject-api

- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
- dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
- dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java
- dropwizard-core/src/main/java/io/dropwizard/sslreload/SslReloadTask.java
- dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/GzipHandlerFactory.java
- dropwizard-util/src/main/java/io/dropwizard/util/Optionals.java
- dropwizard-views/src/main/java/io/dropwizard/views/ViewMessageBodyWriter.java
Sonar is upset about things which are annotated with `@Deprecated` but which lack the corresponding javadoc `@deprecated` tag.
Sonar is also upset about local variables which have the same name as fields.
The `InstrumentedHttpClientConnectionManager` constructor has been deprecated in favour of a builder.
Add missing javadoc, rename local variables, use the `InstrumentedHttpClientConnectionManager` builder.
Sonar will grumble less
> Clean up a few sonar gripes

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/LocalIpFilter.java
The interface `LocalIpFilter` is only used by `NetUtil`. Since `NetUtil` was marked as deprecated in #4584 to restrict access to package-private, I guess this should be done for `LocalIpFilter` too.
> Deprecate `LocalIpFilter`

- dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/util/SizeBenchmark.java
- dropwizard-util/src/main/java/io/dropwizard/util/DataSize.java
- dropwizard-util/src/test/java/io/dropwizard/util/DataSizeTest.java
Since `Size` is deprecated, it makes sense for these conversion methods to also be deprecated.
Annotate the corresponding tests as `@Deprecated` as an alternative to `@SuppressWarnings`.
Also deprecate `SizeBenchmark` for the same reason.
> Deprecate `DataSize#toSize()` and `DataSize#fromSize()`

- dropwizard-health/src/main/java/io/dropwizard/health/response/ServletHealthResponder.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
Raised for consideration regarding issue #4279.
This PR suppresses `IOException`s from being thrown from servlet methods since Sonar suggests not to throw them because of the possibility of denial of service attacks or information exposure.
Therefore the `IOException` from an error at `getWriter()` is logged and a status code 500 is set. Calls to `sendError(...)` are converted to
```java
if (!response.isCommitted()) {
response.reset();
response.setStatus(...);
}
```
since this code won't throw an exception. This results in not committing the response in the servlet method and deferring the processing to the underlying servlet container.
> Do not throw `IOException`s from servlet methods

- docs/source/manual/configuration.rst
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
maxRequestHeaderSize was documented in Dropwizard (and Jetty) as being a
limit for the size of a single request header, but it's actually a limit
for the combined size of all request headers and the request line.
Corresponding Jetty PR: https://github.com/eclipse/jetty.project/pull/7417
Clarify the documentation accordingly.
> Clarify that maxRequestHeaderSize is a combined limit for all headers

- dropwizard-logging/src/test/resources/yaml/logging.yml
This was added in cc53136ae8754c20df268b6ea1a0cf3528618450 but isn't used by the tests.
It causes errors to be logged during tests as the `currentLogFilename` is identical to another log configuration in the same file.
`FileAppenderFactoryTest` tests the behaviour of `FileAppenderFactory` directly without roundtripping through the YAML configuration parser.
Remove the duplicate log file definition.
> Remove duplicate logfile from dropwizard-logging tests (#4568)

- dropwizard-health/src/test/java/io/dropwizard/health/DefaultHealthFactoryTest.java
This method is fairly tricky to test, but previously had no coverage. Ideas to make this test better would be appreciated.
Part of a mini-quest to kill that Sonar error about not meeting 80% test coverage on new code.
> Add a basic test for `DefaultHealthFactory#configure()`

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
- dropwizard-util/src/main/java/io/dropwizard/util/JavaVersion.java
- dropwizard-util/src/test/java/io/dropwizard/util/JavaVersionTest.java
Is "it passes tests" enough validation?
Use `CtClass#toClass(MethodHandles.Lookup)` to register resources. Note that I'm not really familiar with this API - am I doing it right?
The javaassist docs suggest this will work under both Java 8 and 11.
Deprecate `JavaVersion` as it is now unused.
> Register resources in the same way for Java 8 and 11

- dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckManagerTest.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/LifecycleEnvironmentTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbCalculateChecksumCommandTest.java
AssertJ supports asserting on Atomic* types directly - no need to call `.get()`.
Also, make use of `FutureAssert` when asserting on `Future`s.
> Make better use of AssertJ `AtomicAssert` and `FutureAssert`

- dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckManagerTest.java
Test the behaviour of `HealthCheckManager#healthStateView()` and
`HealthCheckManager#healthStateViews()`
Question: Is it correct that when a healthcheck is removed via `HealthCheckManager#onHealthCheckRemoved()`, `HealthCheckManager#healthStateViews()` returns a collection containing `null`? Should `onHealthCheckRemoved()` remove it from the `checks` collection?
`onHealthCheckRemoved()` is never called by Dropwizard.
> Increase test coverage for `HealthCheckManager`

- dropwizard-core/src/test/java/io/dropwizard/validation/InjectValidatorFeatureTest.java
- dropwizard-db/src/main/java/io/dropwizard/db/TimeBoundHealthCheck.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java
- dropwizard-e2e/src/main/java/com/example/badlog/BadLogApp.java
- dropwizard-example/src/test/java/com/example/helloworld/DockerIntegrationTest.java
- dropwizard-example/src/test/java/com/example/helloworld/IntegrationTest.java
- dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckManager.java
- dropwizard-health/src/main/java/io/dropwizard/health/response/JsonHealthResponseProvider.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/filter/AllowedMethodsFilterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalDoubleMessageBodyWriterTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
- dropwizard-metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterFactoryTest.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/ResourceHelpers.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/GzipDefaultVaryBehaviourTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/MapsTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/SetsTest.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/DataSizeRange.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/DurationRange.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/SizeRange.java
- dropwizard-views/src/test/java/io/dropwizard/views/ViewMessageBodyWriterTest.java
This is a bit of a grab-bag of random changes, addressing linter concerns from Sonar and IntelliJ. Mostly in tests, but not all.
Remove usage of raw generic types in a few places.
Remove a couple of deprecated usages:
- Remove usage of `@OverridesAttribute.List`
- Update BadLogApp to avoid overriding deprecated methods
Some random cleanups:
- Remove unnecessary cast and unused local variable
- Remove unused imports
A few test simplifications:
- Tighten assertion in DataSourceFactoryTest
- Simplify lambdas in tests
- Use try-with-resources in AllowedMethodsFilterTest
- Use more specific AssertJ assertions
- Simplify InjectValidatorFeatureTest
> Various linter fixes

- docs/source/manual/core.rst
- dropwizard-e2e/pom.xml
- dropwizard-e2e/src/main/java/com/example/httpsessions/HttpSessionsApp.java
- dropwizard-e2e/src/main/java/com/example/httpsessions/HttpSessionsResource.java
- dropwizard-e2e/src/test/java/com/example/httpsessions/HttpSessionsTest.java
- dropwizard-e2e/src/test/resources/httpsessions/config.yml
Dropwizard generally provides the ability to use HTTP sesssions, but does not provide documentation on this.
Add a documentation section on session support and provide an e2e test explaining how to use it.
> Provide documentation for session support

- dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DAOTestExtension.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DAOTestExtensionRegisterExtensionTest.java
The DAOTestExtension currently does not implement the Junit5 `BeforeAll` and `AfterAll` callbacks, therefore its not possible to register it as a proper extension during testing.
Implement the `BeforeAllCallback` and `AfterAllCallback` interfaces.
DAOTestExtension can be registered as a proper extension during testing using the `@RegisterExtension` annotation.
> Extend DAOTestExtension with junit5 callbacks

- SECURITY.md
- dropwizard-core/src/main/java/io/dropwizard/Bundle.java
- dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/LazyLoadingTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/CustomDeserialization.java
- dropwizard-metrics/src/main/java/io/dropwizard/metrics/MetricsFactory.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/Person.java
- dropwizard-views-freemarker/src/main/java/io/dropwizard/views/freemarker/FreemarkerViewRenderer.java
Address a few linter concerns
- Add missing `@Deprecated` tag to FreemarkerViewRenderer constructor
- Simplify dropwizard-jersey CustomDerialization (test helper)
- Fix javadoc reference in dropwizard-core Bundle
- Adjust test class name in LazyLoadingTest
- Remove unused imports from DataSourceFactoryTest
- Remove unnecessary cast from DefaultServerFactory
- Fix markdown in SECURITY.md
- Remove unnecessary character escape
- Remove stray `@JsonProperty` in MetricsFactory
> Further linter appeasements

- .mvn/jvm.config
- dropwizard-parent/pom.xml
After setting the baseline for Dropwizard to Java 11, we can simplify the Error Prone configuration which had to account running on Java 8, 11, and 17 before.
> Clean up Error Prone configuration

- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/ResourceURL.java
This is a bit of a noop change - I don't think there were any gaps in the control flow.
Sonar was struggling to work out whether cases could fall-through, but they can't.
Still, moving the `return 0` to the end of each case statement makes it very clear what the behaviour will be.
> Simplify switch statement in `ResourceURL#getLastModified()`

- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
AssetServlet has `getResourceURL()` and `getResourceUrl(String)`, which is deemed potentially confusing by Sonar.
`getResourceURL()` goes back all the way to 2012 in commit 482b9f552ecb1d0a44a11fba7acdfb35843f2723 whereas `getResourceUrl(String)` is a relative newcomer, added in 2015 in cc20a03a3a297646589ea50c1cd9d8ef5a8c1cc4.
Provide `getResourceURL(String)` as a preferred replacement for `getResourceUrl(String)`, but delegate to the existing method for now, to give anyone subclassing `AssetServlet` time to migrate their usage.
> Deprecate `AssetServlet#getResourceUrl(String)`

- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/GzipDefaultVaryBehaviourTest.java
We can use `containsEntry` here and chain the assertions.
> Make better use of AssertJ in `GzipDefaultVaryBehaviourTest`

- dropwizard-core/src/main/java/io/dropwizard/cli/ServerCommand.java
- dropwizard-core/src/main/java/io/dropwizard/setup/AdminEnvironment.java
- dropwizard-core/src/main/java/io/dropwizard/sslreload/SslReloadBundle.java
- dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/LifecycleEnvironment.java
`AbstractLifeCycleListener` is deprecated since `LifeCycle.Listener` gained default methods.
Deprecate `HttpsConnectionFactory#logSslInfoOnStart(SslContextFactory) since its return type is the deprecated `AbstractLifeCycle.AbstractLifeCycleListener` but should probably have been `LifeCycle.Listener` all along.
Deprecate the existing method and replace it with a new method, `logSslParameters(SslContextFactory)` which just delegates to the old method until we remove it.
> Remove use of deprecated `AbstractLifeCycle.AbstractLifeCycleListener`

- dropwizard-configuration/src/test/java/io/dropwizard/configuration/BaseConfigurationFactoryTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/JsonConfigurationFactoryTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/YamlConfigurationFactoryTest.java
This was inspired by Sonar getting upset about the lack of assertions in `BaseConfigurationFactoryTest#printsDetailedInformationOnMalformedContent()`.
Move assertion logic to the base class, with subclasses simply supplying the string to check for.
This should remove 1 of the 6 'Blocker' issues in Sonar.
Not sure I'm completely satisfied with the result, but see what you think....
> Simplify inheritance in dropwizard-configuration test

- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardExtensionsSupportTest.java
This change was inspired by Sonar complaining about `public` members in the `DropwizardExtensionsSupportTest`.
> Remove `public` modifiers from nested test classes and test methods

- dropwizard-benchmarks/pom.xml
This module's code is already test code. Don't report on test coverage for it.
Note: I'm not sure if this is quite the way to do it - the Sonar docs aren't very clear to me.
https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/#header-3
> Ignore code coverage metrics for dropwizard-benchmarks

- docs/source/manual/core.rst
- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
- dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java
- dropwizard-health/src/main/java/io/dropwizard/health/HealthCheckConfigValidator.java
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/AutoCloseableManager.java
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/ExecutorServiceManager.java
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/Managed.java
Not everything needs both a start and stop method. Provide default no-op implementations.
> Add default methods to dropwizard-lifecycle's `Managed` interface

- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
`HttpProcessor` is marked as deprecated but is supported in httpclient-5.
Remove the `@Deprecated` tag.
Refs #4338
> Remove deprecated tag as HttpProcessor is supported in httpclient 5

- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2CIntegrationTest.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2IntegrationTest.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2TestCommon.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithConscryptTest.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithCustomCipherTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbCalculateChecksumCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbClearChecksumsCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDropAllCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbFastForwardCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbGenerateDocsCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbLocksCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCustomSchemaTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateDifferentFileCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbPrepareRollbackCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbRollbackCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbStatusCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbTagCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbTestCommandTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/LiquibaseScopingTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/MigrationTestSupport.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportTest.java
Appease some more Sonar grumbles
- Add an assertion to `DropwizardTestSupportTest#isCustomFactoryCalled()`
- Rename `AbstractHttp2Test` to `Http2TestCommon`
- Remove the static initialiser from `AbstractMigrationTest`
- Replace `AbstractMigrationTest` with some static helper methods.
The static initialiser which unregistered `AddColumnGeneratorSQLite.class` no longer seems to be necessary (added in fe842d2fcf13c3d8eb67ad50219f929b0989539b in 2018 as part of the Liquibase 3.6.0 upgrade)
> Address Sonar warnings in tests

- dropwizard-assets/pom.xml
- dropwizard-auth/pom.xml
- dropwizard-client/pom.xml
- dropwizard-configuration/pom.xml
- dropwizard-core/pom.xml
- dropwizard-db/pom.xml
- dropwizard-forms/pom.xml
- dropwizard-health/pom.xml
- dropwizard-hibernate/pom.xml
- dropwizard-http2/pom.xml
- dropwizard-jackson/pom.xml
- dropwizard-jdbi3/pom.xml
- dropwizard-jersey/pom.xml
- dropwizard-jetty/pom.xml
- dropwizard-json-logging/pom.xml
- dropwizard-lifecycle/pom.xml
- dropwizard-logging/pom.xml
- dropwizard-metrics-graphite/pom.xml
- dropwizard-metrics/pom.xml
- dropwizard-migrations/pom.xml
- dropwizard-parent/pom.xml
- dropwizard-request-logging/pom.xml
- dropwizard-servlets/pom.xml
- dropwizard-testing/pom.xml
- dropwizard-util/pom.xml
- dropwizard-validation/pom.xml
- dropwizard-views-freemarker/pom.xml
- dropwizard-views-mustache/pom.xml
- dropwizard-views/pom.xml
This PR adds automatic module names for all Dropwizard modules.
We'll need more tests to see, if everything works with Java 9+ when using the module path.
See also: https://blog.joda.org/2018/03/jpms-negative-benefits.html
Refs https://github.com/dropwizard/dropwizard/pull/3233
> Add automatic module names for all Dropwizard modules

- docs/source/manual/testing.rst
- dropwizard-example/src/test/java/com/example/helloworld/core/PersonTest.java
- dropwizard-example/src/test/java/com/example/helloworld/resources/PeopleResourceTest.java
- dropwizard-example/src/test/java/com/example/helloworld/resources/PersonResourceTest.java
- dropwizard-example/src/test/resources/person.json
- dropwizard-testing/src/main/java/io/dropwizard/testing/FixtureHelpers.java
_Question_ This is a bit speculative - I don't _think_ these helpers seem to offer much value, but maybe you know differently?
Jackson can read directly from `URL`s and `InputStream`s so these helpers don't especially useful.
In addition, Java 9+ has `InputStream#readAllBytes()` which can be combined with `String(byte[])` to parse resources to strings.
> Deprecate `FixtureHelpers`

- dropwizard-util/src/main/java/io/dropwizard/util/ByteStreams.java
- dropwizard-util/src/main/java/io/dropwizard/util/Maps.java
Deprecate `ByteStreams` and `Maps` as an indicator that they are to be removed in Dropwizard 3.x.
Raised in relation to https://github.com/dropwizard/dropwizard/pull/4914 and https://github.com/dropwizard/dropwizard/pull/4916
> Deprecate Bytestreams and Maps

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/LocalIpFilter.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java
These were unintentionally public in previous versions and had a deprecation warning saying they would be made package-private.
Make them package-private.
> Make `LocalIpFilter` and `NetUtil` package-private

- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2TestCommon.java
Instead of using our own `ResourceHelpers` class, since `SslContextFactory` is a jetty util class, use the Jetty util class `Resource` to load our test truststore from the classpath.
This reduces our usage of `ResourceHelpers` to be obtaining absolute paths to files in order to supply config overrides or to pass to `Application#run()`
> Use Jetty's `Resource` to locate truststore in `Http2TestCommon`

- dropwizard-util/src/main/java/io/dropwizard/util/Sets.java
Dropwizard 3.0 will drop support for Java 8 and this class will no longer be necessary.
Mark it as deprecated now, to give users some notice.
> Deprecate Sets, ready for Dropwizard 3.0

- docs/source/manual/testing.rst
- dropwizard-example/src/test/java/com/example/helloworld/core/PersonTest.java
This should've been part of 2df06548a8821c92446c1b8e4055bdd81afbe79b but it got missed.
Also that commit got the path to `person.json` incorrect. The earlier parts of the docs say to put it in `src/test/resources/fixtures` so make the code consistent with that.
Refs https://github.com/dropwizard/dropwizard/pull/4890
> Remove deprecated `FixtureHelpers` from the docs

- dropwizard-auth/src/main/java/io/dropwizard/auth/Authorizer.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/PermitAllAuthorizer.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/util/AuthUtil.java
- dropwizard-example/src/main/java/com/example/helloworld/auth/ExampleAuthorizer.java
- dropwizard-health/src/main/java/io/dropwizard/health/DefaultHealthFactory.java
- dropwizard-health/src/test/java/io/dropwizard/health/DefaultHealthFactoryTest.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
Remove the following deprecated methods:
- `Authorizer#authorize(P, String)`
- `HttpsConnectorFactory#logSslInfoOnStart(SslContextFactory)`
- `DefaultHealthFactory#getHealthChecks()`
- `DefaultHealthFactory#setHealthChecks(List<HealthCheckConfiguration>)`
> Remove deprecated methods from `HttpsConnectorFactory` and `DefaultHealthFactory`

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalDoubleMessageBodyWriter.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalIntMessageBodyWriter.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalLongMessageBodyWriter.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalMessageBodyWriter.java
We can use `Optional#orElseThrow(Supplier<? extends Throwable>)` instead of explicitly checking for `Optional#isPresent()` here.
> Simplify `Optional` handling in dropwizard-jersey

- docs/source/manual/hibernate.rst
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWork.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitsOfWork.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/MultipleUnitOfWorkTest.java
- dropwizard-hibernate/src/test/resources/hibernate-multiple-unitofwork.yaml
In some situations, there is the need to access multiple databases in a Jersey resource method.
At the moment, only one `@UnitOfWork` annotation can be provided to a Jersey method and therefore only one database can be managed automatically.
Starting from Java 8, annotations can be repeatable. So make `@UnitOfWork` a repeatable annotation.
If multiple annotations with the same value are provided, the last one gets used.
When a Jersey resource method is annotated with multiple `@UnitOfWork` annotations, for each of these a `UnitOfWorkAspect` gets instantiated and the hibernate `Session`s all get managed automatically.
> Repeatable `@UnitOfWork` annotation
