dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
This PR adds the ability for tests using **DropwizardAppRule** to hook the **Application** lifecycle.  It additionally includes a convenience method to add **Managed** objects to the lifecycle.
```java
@ClassRule
public static final DropwizardAppRule<TestConfiguration> RULE =
new DropwizardAppRule<TestConfiguration>(MyApp.class, resourceFilePath("my-app-config.yaml"))
.manage(new MyTestManagedObject());
```
There are many cases where tests need to add **Managed** objects to the application lifecycle and execute code in the application **onRun** method.  For example, many of our services use an ActiveMQ bundle which handles connections to a remote ActiveMQ server.  When testing these services we want to standup a local broker and override the config to use this local broker.  The changes …
=> Testing: Add listeners to DropwizardAppRule

dropwizard-client/src/main/java/io/dropwizard/client/ApacheClientBuilderBase.java, dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
This PR improves the JerseyClientBuilder with:
* Add back metrics provided by  **InstrumentedHttpClientConnectionManager**
* Respect the timeout, cookie, and credential provider configuration parameters
Additionally it:
* Adds a few tests for the configuration parameters
* Moves common code shared between **HttpClientBuilder** and **JerseyClientBuilder** into an **ApacheClientBuilderBase** class
I recommend including this in 0.8, as the existing JerseyClientBuilder is a bit broken without these enhancements.
**Note**: 
This PR does **not** include the request timing that InstrumentedHttpRequestExecutor provided.  I have submitted a metrics PR (https://github.com/dropwizard/metrics/pull/705) to add this, and will submit a dropwizard PR when that is merged.
=> JerseyClientBuilder: Add back metrics and use provided configuration values

dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ConfigOverride.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardServiceRuleResetConfigOverrideTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/TestConfiguration.java, dropwizard-testing/src/test/resources/test-config.yaml
Prior to this change, `DropwizardAppRule` would clear *ALL* system properties that start with `dw.`, regardless of whether they were defined as `ConfigOverride` values in the test. This caused problems with tests that relied on a combination of command-line overrides (that should not be reset) and test-specific overrides (that should be reset).
An example of where this might be useful is dynamic port allocation, where the build system (Maven, Jenkins, etc.) dynamically allocates port numbers to the app and provides these via command-line overrides (e.g. `-Ddw.cassandra.port=${SOME_DYNAMIC_PORT}`). These values should be retained (otherwise subsequent tests fail), but the configuration that was explicitly overridden using `ConfigOverride` in the test should be reset.
Note that this does …
=> `DropwizardAppRule` more strict in resetting config overrides

dropwizard-testing/src/main/java/io/dropwizard/testing/ConfigOverride.java, dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardClientRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/DropwizardTestSupportTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleConfigOverrideTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleResetConfigOverrideTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleWithoutConfigTest.java
Hi,
I was looking at starting/stopping a Dropwizard app in Cucumber tests and DropwizardAppRule has all the functionality I need but obviously it doesn't expose startIfRequired and stop methods.
I'd happy to extract a DropWizardAppTestSupport class from DropwizardAppRule and make the DropwizardAppRule depend on that and contribute the code if there's any interest.
What do you think?
Thanks,
Csaba
=> Generalize DropwizardAppRule for other test frameworks

dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/setup/JerseyEnvironment.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
List of endpoints is useful not only for logging but also as API for users.
This change was originally introduced in commit c0eb424, 
but has been lost after upgrading to Jersey. 
See PR #643 for reference
=> Make endpoints information public

dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/GzipDefaultVaryBehaviourTest.java, dropwizard-testing/src/test/resources/gzip-vary-test-config.yaml
Resolve #774, fix #821
Jersey GZipEncoder conflicts with Jetty BiDiGzipFilter and breaks
breaks backwards compatibility of Dropwizard configuration.
It always compresses responses if a client accepts gzip encoding,
which is not the same behaviour as in BiDiGzipFilter. The latter
is configured through a YML file, has more configuration options
and could be disabled externally. As a result users can't disable
response compressing even if they want to.
Also it conflicts with Jersey LoggingFilter, which is useful
for debug purposes.
=> Remove Jersey GZip Encoder

docs/source/manual/configuration.rst, dropwizard-client/src/main/java/io/dropwizard/client/ApacheClientBuilderBase.java, dropwizard-client/src/main/java/io/dropwizard/client/HttpClientConfiguration.java, dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
When number of connections per route reaches the limit (dropwizard default is 1024) a call to fetch the next connection will block. The default timeout is not set so the wait might potentially exceed the expectations. A special case is that the thread could stuck if connections are leaked somewhere instead of generating timeout exception.
This PR adds a way to set this timeout by adding an attribute to HttpClientConfiguration and support for it for both JerseyClient and HttpClient.
=> Connection request timeout

docs/source/manual/core.rst, dropwizard-core/src/main/java/io/dropwizard/setup/AdminEnvironment.java, dropwizard-logging/pom.xml, dropwizard-logging/src/main/java/io/dropwizard/logging/tasks/LogConfigurationTask.java, dropwizard-logging/src/test/java/io/dropwizard/logging/tasks/LogConfigurationTaskTest.java
Logback provides a `JmxConfigurator` for changing logging levels at runtime, but this does not currently appear to be exposed in a Dropwizard-friendly manner. I didn't want to simply use the JMX approach, as that would introduce an inconsistency in managing my DW apps (everything else is managed via config or HTTP access).
I created a `Task` implementation that essentially does the same as Logback's `JmxConfigurator` and provided this via an external library (see https://github.com/stuartgunter/dropwizard-logging-config), but feel it would be appropriate to include in the main DW library. (If there's no appetite for including this in DW, I'd be happy maintaining the library separately.)
I'm not comfortable with the way it has been included, but haven't yet come up with a nice way of doing …
=> Added `LogConfigurationTask` to allow runtime changes to log levels

dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java, dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilderTest.java
Fix #575
JDK ThreadPoolExecutor behaves a rather different than users can expect.
A user expects that parameter 'maximumPoolSize' controls maximum amount
of worker threads for processing tasks. When there is more tasks than
amount of worker threads then the pool grows incrementally to that size.
But actually ThreadPoolExecutor will grow the pool only if a queue is
reached it's bound. If the queue is unbounded then it won't increase
pool size beyond 'corePoolSize' limit. This seems rather awkward because
queue type shouldn't be related with speed of it's processing.
Anyway we should give a warning to users to improve their awareness
of the situation.
=> Warning about maximum pool size and unbounded queues

dropwizard-forms/pom.xml
Packaging needs to be changed to jar to be able to use the new bundle.
=> change dropwizard-forms packaging

docs/source/manual/configuration.rst
Currently there is no database (connection pool) configuration reference in the official documentation. There are only YML examples in JDBI and Hibernate sections.
It would be great to have this configuration in the single place along with others modules.
=> Add the database (connection pool) configuration reference

dropwizard-example/src/test/java/io/dropwizard/migrations/CloseableLiquibaseTest.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/CloseableLiquibase.java
When creating an instance of `CloseableLiquibase`, a jdbc connection is fetched from the supplied datasource. This connection is never closed in `CloseableLiquibase#close`, which results in a connection leak. 
I'm not sure if catching `LiquibaseException` is the "right" thing to do, let me know if I should just propagate the exception.
=> Fixed connection leak in CloseableLiquibase

dropwizard-jdbi/pom.xml
The version bump is straightforward.
Classmate *is* used by jdbi, but it is shaded and renamespaced. There is no declared dependency on classmate.
=> Update JDBI Version and Remove Unnecessary Classmate Exclusion

dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationFactory.java, dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryTest.java
Fix #636, Fix #865
If a YAML configuration file is not provided, Dropwizard by default uses an empty object tree as a config representation.
This approach has a flaw in case of configuration overriding. For this to work, a full object tree analogous by structure with the configuration should be present.
A better approach is to instantiate a configuration object with defaults, ask Jackson to build an object tree and pass this tree to the overriding routine. After that Jackson will create a desired configuration
from a changed tree.
In case if there is no overriding Jackson will just build the same configuration object as the default.
=> Add facility to override the default configuration

docs/source/manual/testing.rst
When writing tests, I noticed Integration Tests docs are slightly out of date: not using JerseyClientBuilder nor client.target(). So I've updated them accordingly.
This is a cleaned up version of PR #859
=> Updated Integration Test instructions in documentation

docs/source/manual/configuration.rst, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientConfiguration.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientConfigurationTest.java, dropwizard-client/src/test/resources/yaml/jersey-client.yml
In relation to #834 
Jersey's async thread pool is configured with 2 parameters: *minThreads* and *maxThreads*. 
The problem is that the pool will not grow up than *minThread* because its work queue is 
unbounded. It's a property of JDK *ThreadPoolExecutor*.
A solution to this problem is to set a bounded queue as the work queue and provide facility 
to users to set the queue size.
By default queue size is set to 8. It's a middle ground between creating too many threads 
and waiting too much time in the queue without spawning new threads.
=> Configure Jersey client thread pool with a bounded queue

dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryManager.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/HibernateBundleTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryFactoryTest.java
Resolve #855
By default the name of a Hibernate bundle (actually "hibernate)" is hardcoded. This name is used for the database pool metrics and the health check associated with the bundle. This causes conflicts when
several bundles used alongside in a project.
This change adds to the HibernateBundle class a protected method which returns a bundle name. This method can be overridden by users who want to set a custom name. The new name will be used for the bundle's database pool metrics and health check.
=> Support for a custom name of a Hibernate bundle

dropwizard-logging/src/main/java/io/dropwizard/logging/LoggingFactory.java, dropwizard-logging/src/test/java/io/dropwizard/logging/LoggingFactoryPrintErrorMessagesTest.java
A couple of days ago, I spent a ridiculous amount of time tracking down a relatively stupid issue. 
Turned out that I had messed up write permission in my log directly. So the file appender
couldn't write to my configured log directory.
My own fault, I know. But I got no warning when I started up the application. 
So, I'm proposing a change :)
In `LoggingFactory#configure`, after the appenders are set up, logback's `StatusPrinter#printIfErrorsOccured` is called. If any errors has occurred, those are printed to `System.out`. 
I'm not sure if printing to `System.out` is smart, perhaps we should print to `System.err` instead? Printing to `System.out` could interfere with output from other commands.
Example of an error message:
```
10:51:26,122 |-ERROR in …
```
=> Print error messages (if any) when initializing loggers

docs/source/manual/configuration.rst, dropwizard-metrics/src/main/java/io/dropwizard/metrics/BaseReporterFactory.java, dropwizard-metrics/src/test/java/io/dropwizard/metrics/BaseReporterFactoryTest.java
Updating the BaseReporterFactory to optionally support regex in its includes/excludes fields. This implementation makes a few assumptions:
- By default any existing implementations or configurations that use the BaseReporterFactory should not have their behavior changed
- The user should be able to toggle on regular expressions by changing data, without modifications to the code
- The code should be easily extended to support still-more complicated matching functionality (potentially by making the StringMatchingStrategy public and adding it as a parameter to the getFilter() call)
These assumptions influenced my design decisions.
Please let me know what you think!
=> Updating the BaseReporterFactory to optionally support regex

docs/source/about/release-notes.rst
Fix a few small typos in the 0.8 release notes.
=> Fix typos in release notes.

docs/source/manual/core.rst, dropwizard-configuration/pom.xml, dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableLookup.java, dropwizard-configuration/src/main/java/io/dropwizard/configuration/EnvironmentVariableSubstitutor.java, dropwizard-configuration/src/main/java/io/dropwizard/configuration/SubstitutingSourceProvider.java, dropwizard-configuration/src/main/java/io/dropwizard/configuration/UndefinedEnvironmentVariableException.java, dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableLookupTest.java, dropwizard-configuration/src/test/java/io/dropwizard/configuration/EnvironmentVariableSubstitutorTest.java, dropwizard-configuration/src/test/java/io/dropwizard/configuration/SubstitutingSourceProviderTest.java, dropwizard-example/example.yml, dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java, pom.xml
This pull request adds the capability to lookup environment variables from within configuration files.
Some PaaS offerings make it hard to modify the Java runtime environment for applications (e. g. set custom system properties) but make it rather easy to use environment variables (also see [The Twelve Factor App](http://12factor.net/)). The `SubstitutingSourceProvider` and `EnvironmentVariableSubstitutor` classes from this PR simplify using environment variables as source for individual configuration settings.
=> Lookup environment variables in configuration files

dropwizard-core/src/main/java/io/dropwizard/setup/Bootstrap.java, dropwizard-core/src/test/java/io/dropwizard/setup/BootstrapTest.java
Swapping out the ValidatorFactory is required in order to add custom value handlers to Hibernate Validator, e. g. for Java's `Optional<T>`.
=> Allow using a custom ValidatorFactory in Bootstrap

dropwizard-client/pom.xml
Not sure why this wasn't picked up by the enforcer.
metrics-httpclient relies on slf4j-api 1.7.7, not 1.7.10
=> Exclude slf4j-api from metrics-httpclient

dropwizard-example/example.yml, dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
The example doesn't have a file appender which does archiving, so it wasn't triggering the issue. I've added that.
http://logback.qos.ch/codes.html
The File property, if present, must be placed before any rolling policy or triggering policy. Thus, in a configuration file, the File property, if present, must be declared declared before any rolling policy or triggering policy declarations.
=> Fix logback error, which ultimately quiets the noise on startup

docs/source/manual/views.rst, dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java, dropwizard-example/src/main/java/com/example/helloworld/HelloWorldConfiguration.java, dropwizard-views-freemarker/src/main/java/io/dropwizard/views/freemarker/FreemarkerViewRenderer.java, dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/MustacheViewRenderer.java, dropwizard-views/src/main/java/io/dropwizard/views/ViewBundle.java, dropwizard-views/src/main/java/io/dropwizard/views/ViewConfigurable.java, dropwizard-views/src/main/java/io/dropwizard/views/ViewRenderer.java, dropwizard-views/src/test/java/io/dropwizard/views/ViewBundleTest.java
The original change was using the concrete `ImmutableMap<K, V>` implementation from Google Guava instead of the generic `Map<K, V>` interface which allows the use of other map implementations.
=> Replace ImmutableMap with Map interface in ViewRenderer interface

dropwizard-servlets/src/main/java/io/dropwizard/servlets/Servlets.java
Added fast-path for the case where a query string is not present in the request.
Previously a potentially unused StringBuilder instance was allocated for every request.
=> Improve extraction of full URL from HttpServletRequest.

dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResource.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceTest.java
In `ResourceTestRule` configure the client in `JerseyTest` to use the same provided `ObjectMapper` as the server to prevent serialization/deserialization issues.
See https://github.com/dropwizard/dropwizard-java8/issues/8 for details.
=> Use same ObjectMapper for client and server in ResourceTestRule

dropwizard-client/pom.xml, dropwizard-client/src/main/java/io/dropwizard/client/ConfiguredCloseableHttpClient.java, dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java, dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/ConfiguredCloseableHttpClientTest.java, dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java, dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java, dropwizard-client/src/test/resources/yaml/dropwizardApacheConnectorTest.yml
**Motivation**
JerseyClient and the ApacheHttpClient are statically configured at creation time. Dropwizard configuration builders ensure those configs are in sync. However, `WebTarget` objects can have the configuration overridden per generated request. This information will be added to the `JerseyRequest`. Unfortunately, the current implementation of the `DropwizardApacheConnector` does not propagate this onto the `RequestConfig` in the created `HttpUriRequest`.
In DW 0.7.1 this was working thanks to this code: http://grepcode.com/file/repo1.maven.org/maven2/com.sun.jersey.contribs/jersey-apache-client4/1.18.1/com/sun/jersey/client/apache4/ApacheHttpClient4Handler.java#241
This is currently blocking the migration of https://github.com/yammer/tenacity project to DW 0.8.0, as we need this …
=> Ensuring that JerseyRequest scoped ClientConfig gets propagated to HttpUriRequest

docs/source/getting-started.rst
Changed 1.6 in 2.3 which provides amongst others better error messages.
=> User manual mentions outdated Maven Shade Plugin

dropwizard-example/src/main/java/com/example/helloworld/core/Person.java, dropwizard-example/src/test/java/com/example/helloworld/IntegrationTest.java, dropwizard-example/src/test/resources/test-example.yml
* The test can be executed from an IDE
* Use a test, not a real configuration
* Dynamically assign application and admin ports
* Close an HTTP client in the test
* Replace tabs to spaces
* Add an integration test for work with a database  
* Create a temporary folder
* Override the DW database config
* Migrate the DB schema
* Test that database-related resource is working
=> Improvements of IntegrationTest in the example application

dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java
* patched `UnitOfWorkApplicationListener` to detect `UnitOfWork` annotation on methods that implement a resource method defined on an interface
* caused by difference between `definitionMethod` (interface) and `handlingMethod` (implementation) for a jersey resouce
* behavior:
* listener checks `definitionMethod` for `UnitOfWork`
* if found, this annotation wins (as before)
* if not found, listener now checks `handlingMethod` for `UnitOfWork`
* extended tests to cover the new behavior
Minimal example to share jersey definitions among clients and the server:
* an interface defines the jersey resources (without `UnitOfWork`)
```java
@Path("user")
public interface UserResource {
@GET
@Path("list")
@Produces(MediaType.APPLICATION_JSON)
List<User> getAllUsers();//definitionMethod
}
```
* the …
=> Enabling UnitOfWork on implementations of interfaces

dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/DataExceptionMapper.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/ErrorMessage.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java
If a database commit fails, it's better not to rethrow an Hibernate exception in the original form, but
wrap it as a MappableException.
This way users can map sql exceptions to web responses and derive a business value from the
database validation checks.
Resolve #949
=> Rethrow Hibernate exceptions as Jersey exceptions

docs/source/manual/testing.rst
Issue 815 points out a discrepancy in the documentation where JSON string representations are used to assert equality. This pull request replaces the example to fullfil the promise of the text.
=> Updated documentation to address issue #815.

dropwizard-auth/pom.xml, dropwizard-core/pom.xml, dropwizard-hibernate/pom.xml, dropwizard-jersey/pom.xml, dropwizard-testing/pom.xml, pom.xml
It reduces burden of upgrading dependencies to the correct version and excluding unwanted dependencies in every place.
It also excludes a duplicate dependency on javax.servlet-api 3.0.1
=> Move Jersey test dependencies to the dependency management section

dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIFactory.java, dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/JodaDateTimeArgument.java, dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/JodaDateTimeArgumentFactory.java, dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/JodaDateTimeMapper.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/DBIClient.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/DatabaseInTimeZone.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/DateTimeSqlTimestampTest.java, dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/LifecycleEnvironment.java
Provide facility to specify the database time zone during converting Joda-Time `DateTime`
values from/to `SQL TIMESTAMP`.
It's crucial for cases when the database operates in a different timezone then the client and it doesn't handle timestamps as SQL `TIMESTAMP WITH TIME ZONE`
Resolve #968
=> Facility to specify a database timezone

dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/JodaDateTimeMapper.java
`JodaTimeMapper` is a public class and should provide the default constructor because of:
* backwards compatibility
* users, who don't care about timezones
* consistency with `JodaTimeArgumentFactory`
=> Return back the default constructor for JodaDateTimeMapper

docs/source/manual/core.rst
I like to use commands and I thought the documentation surrounding them were a little light.
Let me know if everything looks alright, or if there is someway to improve it.
=> Expand documentation around commands

dropwizard-core/src/main/java/io/dropwizard/ConfiguredBundle.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java, dropwizard-views/src/main/java/io/dropwizard/views/ViewBundle.java
Use Type parameter for configuration in both, run and initialize so that one can for example add another ConfigurationBundle in initialize method.
See also https://github.com/dropwizard/dropwizard/pull/795
----
Example: There is a team-wide default set of bundles that is used for all webservices. They all use the same (superset) of configuration. Instead of adding all the bundles in every Application I'd like to add a single default bundle that adds all bundles I need.
```java
class DeploymentConfiguration extends Configuration {
boolean production = true;
}
class App extends Application<DeploymentConfiguration> {
@Override
public void initialize(Bootstrap<DeploymentConfiguration> bootstrap) {
bootstrap.addBundle(new DefaultBundle());
}
@Override
public void run(DeploymentConfiguration …
```
=> Use Type parameter for configuration in initialize

docs/source/manual/core.rst
* Use the default configuration as more common
* Add a note about the path of API for the simple server configuration
Close #959
=> Fix an example of dropwizard-assets configuration

dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
Prior to this fix, DropwizardTestSupport.after() assumed that a previous execution of before() had completed successfully. But if before() failed, then after() would fail, too -- typically, with an NPE accessing an undefined jettyServer. In which case the, JUnit report for tests using DropwizardTestSupport become muddled, showing an extra failure for each test class.
=> DropwizardTestSupport: after() completes even if before() failed

dropwizard-logging/src/test/java/io/dropwizard/logging/PrefixedRootCauseFirstThrowableProxyConverterTest.java
The current test is not reliable, because it fails when it's run from an IDE. The reason for this is that the amount of omitted frames is different for the IDE test runner and, hence,
is not reliable.
Solution is not to match whole stack trace, but split the test to two independent tests:
* First checks, that every line starts with an exclamation mark
* Second checks, that the exceptions ordering is correct and the root cause is placed first in the stack trace.
=> Make tests on an exception converter reliable

dropwizard-benchmarks/pom.xml, dropwizard-benchmarks/src/io/dropwizard/benchmarks/util/DurationBenchmark.java, dropwizard-benchmarks/src/io/dropwizard/benchmarks/util/SizeBenchmark.java
Add benchmarks for [Duration](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-util/src/main/java/io/dropwizard/util/Duration.java) and [Size](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-util/src/main/java/io/dropwizard/util/Size.java)
The benchmarks measure an average time to parse a string to Duration and Size representations.
=> First stab on dropwizard-benchmarks

docs/source/getting-started.rst, docs/source/manual/client.rst, docs/source/manual/core.rst, dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/NonEmptyStringParam.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalCookieParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalFormParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalHeaderParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalQueryParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/NonEmptyStringParamTest.java
Following the discussions in #986 and #983, this pull requests adds documentation and tests around empty string params, such as cases like `/hello-world?name=` where the param will evaluate to `Optional.of("")`
I decided to add in a sample implementation for those following along in the getting started, so `/hello-world?name=` will return "Hello, Stranger". The implementation derives from `AbstractParam`. Alternatively, a custom `ParamConverterProvider` could be registered but that would affect all String params for all endpoints (so I decided against that).
Also this pull request fixes a link that was missing (originally my fault :blush:)
=> Add documentation and tests surrounding empty string optionals

dropwizard-jersey/pom.xml, dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
See https://jersey.java.net/documentation/latest/bean-validation.html for details
about the Bean Validation support in Jersey. It enables the use of Java validation annotations like `@NotNull`, `@Min`, or `@Email` in the context of JAX-RS and Jersey.
Merging this could probably fix #625 and #633 (as both, the issue and the PR, are now outdated anyway).
=> Add Jersey Bean Validation Support

dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProvider.java
As discussed on https://groups.google.com/forum/#!topic/dropwizard-user/FQd_Y4ihb7I, I have prepared a little patch that will print the failed validation alongside the object that was validated, on TRACE only.
=> Add logging (on TRACE) for failed validation of Jackson data.

dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
=> Sanitize URL pattern from rootPath

dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardClientRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardClientRuleTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/TestResource.java
This can be helpful in cases where non-Resources are passed in that
depend on `@Context` annotations or it's preferable for other
reasons to have Jersey manage the object lifetime.
=> Add support for X.class to DropwizardClientRule

docs/source/manual/testing.rst
`GrizzlyWebTestContainerFactory` is what is recommended to allow `Context` injections but the docs use `GrizzlyTestContainerFactory`.
=> Reference correct Grizzly server in testing docs

dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
The list of endpoints logged when starting Dropwizard becomes hard to read when it grows larger. This will sort all endpoints before logging them.
=> Gather all endpoints and sort before logging them

dropwizard-configuration/pom.xml, dropwizard-metrics-graphite/pom.xml, dropwizard-metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteReporterFactory.java, dropwizard-metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterFactoryTest.java, pom.xml
`InetSockedAddres` performs DNS resolution during construction time, which is not great if the Graphite server moves to a different IP-address.
The solution is to initialize `Graphite` gateway with a hostname and port. In such configuration it will resolve an address just before connecting to the server.
Resolve #1003
=> Defer DNS resolution in GraphiteReporter

dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
We create this executor, so our responsibility to close it.
=> Close Jersey ExecutorService in tests

dropwizard-example/example.yml, dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java, dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java, dropwizard-logging/src/test/resources/yaml/logging.yml
This is a pull request to add support for logback's maxFileSize attribute.  Earlier discussed here: https://github.com/dropwizard/dropwizard/issues/997
=> add support for logback's maxFileSize attribute

dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryTest.java, dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationValidationExceptionTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProviderTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java, dropwizard-validation/src/main/java/io/dropwizard/validation/ConstraintViolations.java, dropwizard-validation/src/test/java/io/dropwizard/validation/DurationValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/OneOfValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/PortRangeValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/SizeValidatorTest.java
* ConstraintViolations should not print the invalid value as it may cause reflective-cross-site scripting issue
* Fixed all unit tests that expect the (was {invalidValue}) in the violation message.
=> fix #953 Possible reflective cross site scripting in ConstraintViolations

dropwizard-jersey/pom.xml
*Dropwizard-jersey* module has a dependency via *dropwizard-validation* on *org.glassfish.javax.el-3.0.0*, which includes API as well as an implementation of the expression language.
This also removes warnings from the *maven-shade plugin* about duplicated classes in the classpath.
=> Remove javax.el 2.x dependencies

dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/BeanParameter.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
Due to #842, validation opens up new opportunities and by happenstance, a new bug. Now validations can be done on resource query parameters, return values, etc, and this, in my opinion is a good thing.
The pitfall I ran into is that the current `ConstraintViolationExceptionMapper` with the new bean validation in place, does not follow the [jersey documentation], which states that:
> 500 (Internal Server Error): If the exception was thrown while validating a method return type.
>
> 400 (Bad Request): Otherwise.
This pull request attempts to fix the current behavior, which will return 422 on return values and `*Params`. The violations in `*Params` now return a 400 and a return value violation is a 500.
There is an issue with this implementation: I'm uncomfortable that the only sane …
=> ConstraintViolations context determines HTTP status

dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java
HSQLDB correctly retrieves a timestamp from the DB in the JVM timezone, Jadira converts it to DateTime and then Jackson serializes it to JSON in UTC.
So all assertions in UTC will pass regardless of the JVM timezone.
=> Don't override the JVM timezone in a Hibernate integration test

dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java, dropwizard-validation/pom.xml, dropwizard-validation/src/main/java/io/dropwizard/validation/ConstraintViolations.java, dropwizard-validation/src/test/java/io/dropwizard/validation/ConstraintPerson.java, dropwizard-validation/src/test/java/io/dropwizard/validation/ConstraintViolationsTest.java
Useful for those who want to derive their own `ExceptionMapper<ConstraintViolationException>` (for instance, an exception mapper that returns JSON containing constraint violations)
=> Extract constraint status for public use

dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
On windows there is a carriage return line feed instead of just a line
feed so the regex failed. The fix is more cross platform friendly.
=> Fix test for sorting endpoints in log

docs/source/about/release-notes.rst
Some quick fixes to the release notes.
=> Fix underline to be the same length as header text and various spelling mistakes

docs/source/manual/core.rst
Two quick fixes to the Dropwizard Core manual page
=> Use double quotes for string literal and fix underline to be the same length as header text

docs/source/manual/jdbi.rst
ExampleConfiguration class in JDBI example lacks setter for database json property, and it doesn't work until it's added.
=> added setter to ExampleConfiguration class

dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java
If an error occurs processing JSON by default we just receive a message in the response indicating the dropwizard was "Unable to process JSON". This should be logged at least as a warning so a developer/sysadmin can see the cause.
=> Do not swallow exception cause when parsing JSON.

dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/MustacheViewRenderer.java, dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/PerClassMustacheResolver.java
A more canonical way to provide a custom resource loader is through delegation, rather then inheritance.
There is the `MustacheResolver` interface, that gives ability to provide own strategy of loading resources and pass it to the `DefaultMustacheFactory` class in the constructor.
Also this removes throwing `MustacheException`, because internally Mustache already handles the case when a returned reader is null and throws a `MustacheNotFoundException` with the same semantic.
=> Use a custom mustache resolver then a custom factory

dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
* Use the default cookie policy as a replacement for deprecated "best-match"
* Set 'setValidateAfterInactivity' instead of deprecated 'staleConnectionCheckEnabled'
* Use 'NoopHostnameVerifier' as a replacement for 'AllowAllHostnameVerifier'
=> Remove deprecated Apache HTTP client API

dropwizard-core/src/main/java/io/dropwizard/Application.java, dropwizard-core/src/main/java/io/dropwizard/setup/Bootstrap.java, dropwizard-core/src/test/java/io/dropwizard/setup/BootstrapTest.java
* Add a setter for the metric registry in `Bootstrap`, so users can provide own customized instance during initialization.
* Move system metrics registration into a separate method from the constructor.
* Invoke the method after `Application#initialize`, where users can customize `Bootstrap`.
Resolve #956
=> Add facility to specify a custom MetricRegistry in Bootstrap

dropwizard-jersey/pom.xml, pom.xml
When running Dropwizard unit tests on a pt-BR [locale] machine (by example), the validation tests fails.
```
Failed tests:  
getInvalidReturnIs500(io.dropwizard.jersey.validation.ConstraintViolationExceptionMapperTest): expected:<...laze.<return value> [length must be between 0 and] 3"]}"> but was:<...laze.<return value> [Tamanho deve estar entre 0 e] 3"]}">
getInvalidBeanParamsIs400(io.dropwizard.jersey.validation.ConstraintViolationExceptionMapperTest): expected:<...:["blazer.arg0.name [may not be empty]"]}"> but was:<...:["blazer.arg0.name [Não pode estar vazio]"]}">
getInvalidQueryParamsIs400(io.dropwizard.jersey.validation.ConstraintViolationExceptionMapperTest): expected:<...rrors":["blaze.arg0 [length must be between 3 and] 2147483647"]}"> but was:<...rrors":["blaze.arg0 [Tamanho …
```
=> Ensures that unit tests always run in 'en_US' locale

dropwizard-migrations/src/main/java/io/dropwizard/migrations/MigrationsBundle.java
In some case, configuration class retrieved by MigrationsBundle is invalid (in my case, when MigrationsBundle is constructed from an abstract Application class where configuration is still a Generic Type).
This fix the issue by retrieving the configuration class from Application object.
=> Use configuration class from Application object

dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
Referring this https://github.com/dropwizard/dropwizard/issues/1066 and consequently this: https://github.com/federecio/dropwizard-swagger/issues/52
This pull request fixes this referred NPE. Basically, what I've found is that resources without @Path annotation on class level the method `org.glassfish.jersey.server.model.Resource#getPath` returns null, so, causing the issue in `EndpointLogger#normalizePath`. I've just wrote a defensive code to avoid this NPE.
=> Fix NPE when resources have the @Path annotation just on method level

docs/source/manual/core.rst
In order for the app startup not to fail if an env var defined in the yaml config file cannot be found I had to add a boolean false parameter to the EnvironmentVariableSubstitutor constructor
=> [Documentation] Specify boolean false parameter in EnvironmentVariableSubstitutor constructor

docs/source/manual/configuration.rst
Polymorphic configuration is an advanced technique and should pe placed in the end of section.
Doing so, we don't confuse users, who open the section just to consult the reference.
=> Move polymorphic configuration to the end of configuration section

dropwizard-core/src/main/java/io/dropwizard/server/SimpleServerFactory.java
Add logging of application and admin context paths during server startup. `DefaultServerFactory` already does [that](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java#L160).
It should help to avoid confusion for users who use this configuration for the first time and expect that application resources are served from the root path.
Resolve #1058
=> Log context paths in `SimpleServerFactory` during startup

dropwizard-example/src/main/java/com/example/helloworld/resources/HelloWorldResource.java
~~* Use a POST, rather then GET, because GET requests should return some values, no 204 return code~~
~~* Change name of the parameter to from `date` to `value`~~
* Use `Optional` to handle an omitted parameter
* Return a passed date, so Jersey doesn't warn us about 204 error
=> Update an example of using query parameters

dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
We should acquire the lock when we stop the context, because other threads could change it in the `configure` in the same time, which leads to `ConcurrentModificationException`.
I've seen this exception in Travis several times and had to restart builds.
````
io.dropwizard.testing.app.GzipDefaultVaryBehaviourTest  Time elapsed: 0.001 sec  <<< ERROR!
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
at java.util.ArrayList$Itr.next(ArrayList.java:851)
at ch.qos.logback.classic.LoggerContext.fireOnStop(LoggerContext.java:323)
at ch.qos.logback.classic.LoggerContext.stop(LoggerContext.java:337)
at io.dropwizard.logging.DefaultLoggingFactory.stop(DefaultLoggingFactory.java:145)
at …
```
=> Prevent ConcurrentModificationException during stopping logger context

dropwizard-migrations/pom.xml, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbMigrateCommand.java, dropwizard-migrations/src/test/java/io/dropwizard/migrations/CloseableLiquibaseTest.java, dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCommandTest.java, dropwizard-migrations/src/test/java/io/dropwizard/migrations/TestMigrateConfiguration.java, dropwizard-migrations/src/test/resources/migrations.xml
It's a first attempt to write tests for the `dropwizard-migrations` module.
* First of all, this change moves [CloseableLiquibaseTest](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/src/test/java/io/dropwizard/migrations/CloseableLiquibaseTest.java) from `dropwizard-example` to `dropwizard-migrations`. It seems to me that it was placed there for mistake. 
* It sets the test directory, Logback testing configuration and test dependencies for the module.
* It adds a test for the [DbMigrate](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbMigrateCommand.java) command. The following use cases are tested:
* Migration of pending migrations to the DB.
* Dry-run mode (printing the pending change set to the …
=> Migration tests

.travis.yml, pom.xml
Coveralls-plugin 3.x changed the plugin goal.  Now it's just `coveralls:report`.
See [this](https://github.com/trautonen/coveralls-maven-plugin/commit/355b2e73715bdde4375bb151aeeddaf446b0779c).
=> Fix Coveralls integration

dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/ConstraintViolationBenchmark.java, dropwizard-jersey/pom.xml, dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapper.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ValidationErrorMessage.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/FailingExample.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/WrappedFailingExample.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/WrappedValidRepresentation.java, dropwizard-validation/src/main/java/io/dropwizard/validation/ConstraintViolations.java
This pull requests attempts to return user friendly error messages when constraints are violated either in the response or the request.
So instead of error messages of
```json
{"errors":["blazer.arg0.name may not be empty"]}
```
and
```json
{"errors":["blaze.<return value> length must be between 0 and 3"]}
```
more user friendly error messages are returned
```json
{"errors":["query param name may not be empty"]}
```
```json
{"errors":["server response length must be between 0 and 3"]}
```
This pull request isn't done, so don't merge (hardly any documentation and I didn't completely mull over edge cases). As it happens, I'll be off the grid for the next couple weeks, but I wanted to get some eyes on the code (hence the pull request), but if someone is extremely enthusiastic they can carry …
=> Descriptive constraint violation messages

dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java, dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
In the [documentation](http://www.dropwizard.io/manual/client.html#apache-httpclient) we say that we create managed instances of Apache HTTP client. But in the fact, it's not true. 
To follow this contract, we should tie the lifecyle of the client to the lifecycle of the server, if the user specified the environment in the builder. The rationale is the same for Jersey HTTP client.
If the user has already created own managed object for the client  - it's not an issue, because the close method of the HTTP client is idempotent.
=> Manage Apache HTTP and Jersey HTTP clients

dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java, dropwizard-db/src/main/java/io/dropwizard/db/DatabaseConfiguration.java, dropwizard-db/src/main/java/io/dropwizard/db/PooledDataSourceFactory.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java, dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIFactory.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/AbstractLiquibaseCommand.java
Dropwizard by default is shipped with the Tomcat JDBC Connection pool. It's mostly fine, but has some disadvantages (performance, limited metrics, handling network failures). It would be great if we had facility to plug-in other DB pools into Dropwizard. For example, Brett Wooldridge's
wonderful [HikariCP](https://github.com/brettwooldridge/HikariCP) or [BoneCP](http://jolbox.com/).
Of cource, nothing stops us from implementing a factory, that creates a `ManagedDataSource`. The problem is that `dropwizard-jdb`i, `dropwizard-hibernate` and` dropwizard-migrations` modules require `DataSourceFactory` for the configuration. `DataSourceFactory` is closely tied with the Tomcat pool. So if we use an another pool, we are forced to write own factories for JDBI, Hibernate, etc...
A solution is to …
=> Add facility to plug-in custom DB connection pools

dropwizard-migrations/src/test/java/io/dropwizard/migrations/AbstractMigrationTest.java, dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCommandTest.java
The test for the db migrate command help is dependent upon terminal width, so it fails on my mac laptop. This change fixes the test to instruct argparse4j to not detect terminal width during the test. Unfortunately the library keeps this setting as a static class variable, rather than a setting on the parser, so the try/catch block is needed to ensure it gets reset after the test is done.
=> Width independent test

docs/source/manual/core.rst
Added @JsonIgnore to example validation method. Whilst the application will work without this flag, it will fail during testing as additional paramters will be added to the created JSON StackOverflow: http://stackoverflow.com/questions/26551726/dropwizard-validationmethod-adding-a-json-property
To be safe, and promote unit testing, this should be included in the example documentation.
=> Update validationmethod documentation to use JsonIgnore

dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/ConstraintViolationBenchmark.java, dropwizard-core/src/main/java/io/dropwizard/cli/EnvironmentCommand.java, dropwizard-core/src/main/java/io/dropwizard/setup/Bootstrap.java, dropwizard-core/src/test/java/io/dropwizard/setup/BootstrapTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/NonEmptyStringParam.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/NonEmptyStringParamFeature.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/HibernateValidationFeature.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/NonEmptyStringParamUnwrapper.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ParamValidatorUnwrapper.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/Validators.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/NonEmptyStringParamProviderTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ParamValidatorUnwrapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java
This commit enables `Optional` and `AbstractParam` parameters to be
validated in resource endpoints. This required additional code needed in
setting up the validator, so I extracted the common functionality out to a
new class `Hibernate` that should be analogous to the present `Jackson`
class.
Also this commit makes the `NonEmptyStringParam` constructor public like other
`AbstractParam`s. The second commit registers the default
`ConstraintViolationExceptionMapper` in test cases (and this can always be
overridden by the user if they have a custom exception mapper for constraint
violations)
The one area where this commit falls short is that it currently doesn't
allow a user custom hibernate configuration in the jersey validation. Thus,
request entities will be validated by the user's …
=> Use dropwizard hibernate validator in jersey validations

docs/source/manual/auth.rst, dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java, dropwizard-auth/src/main/java/io/dropwizard/auth/Authorizer.java, dropwizard-auth/src/main/java/io/dropwizard/auth/basic/BasicCredentialAuthFilter.java, dropwizard-auth/src/main/java/io/dropwizard/auth/oauth/OAuthCredentialAuthFilter.java, dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicCustomAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/chained/ChainedAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthCustomProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/util/AuthUtil.java, dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java, dropwizard-example/src/main/java/com/example/helloworld/auth/ExampleAuthorizer.java, dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedResourceTest.java
The current implementation of authorization is too cumbersome and requires implementing a big amount of boilerplate code.
This changes introduce `Authorizer` interface, which is responsible for authorizing users. It's a replacement for specifying a function for creating a new secure context.
Advantage stem from the fact that users only implement business logic for authorization and nothing more. Also this type of API is similar to `Authenticator`, which makes API more consistent.
=> Simplify authorization

docs/source/manual/core.rst, docs/source/manual/index.rst, docs/source/manual/validation.rst, dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ValidationErrorMessage.java
A hefty chunk of documentation on validation that covers previously undocumented features and updates others. I made it into it's own page due to its length. If this is not desired (due to potentially broken links to the documentation), I can merge it back
**The documentation is currently not accurate (so it may not be a good idea to merge just yet)**: as
```java
@PUT
@Valid
public Person replace(@Valid Person person) {
// Oops, we got a bug, a person can't have a null name
return new Person(null);
}
```
will return a `200 OK` and not `500 Internal Server Error`. 
Let me know if there are any corrections/suggestions.
=> Update Validation Documentation

dropwizard-core/src/main/java/io/dropwizard/setup/Bootstrap.java, dropwizard-core/src/test/java/io/dropwizard/setup/BootstrapTest.java, dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java
Some users reported, that the default Dropwizard's `ObjectMapper` is too aggresive for them. 
See #1111, #1095, #1098. So we should provide a way to set a more *ligthweight* mapper. To achieve this this change:
* Adds a factory method, that creates a minimal `ObjectMapper`, which still works with Dropwizard.
* Adds a setter in Boostrap, allowing users to provide a custom `ObjectMapper`.
=> Add facility to set a custom ObjectMapper in Bootstrap

docs/source/manual/configuration.rst, dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java, dropwizard-db/src/test/java/io/dropwizard/db/CustomConnectionValidator.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java, dropwizard-db/src/test/resources/yaml/full_db_pool.yml
Some users want to specify a custom validation logic for database connections. 
Tomcat JDBC Pool provides this facility and we can support it in the YAML configuration.
Close #1089
=> Add support for setting a custom DB pool connection validator

dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbDumpCommand.java, dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java
This pull requests consists from 2 changes:
* Fix descriptions of some parameters in `DbDumpCommand`
* Add tests for `DbDumpCommand`
This suite checks 4 cases:
* Dump the existed database schema to an XML change set
* Dump the schema and data to an XML change set
* Dump only data
* Print a correct help page
For checking correctness of a change set, it uses a DOM XML parser, rather than regular expressions or string manipulations. The reason for this is that the resulted XML text is not a constant and depends on environment and time of a run. To overcome this, we use the XML parser, because it provides ability to make an intelligent  assertions. In the end, it makes tests more stable and easy to maintain.
=> Tests for DbDumpCommand

dropwizard-jackson/src/main/java/io/dropwizard/jackson/FuzzyEnumModule.java, dropwizard-jackson/src/test/java/io/dropwizard/jackson/FuzzyEnumModuleTest.java
If Jackson if configured with *READ_ENUMS_USING_TO_STRING* feature, `PermissiveEnumDeserializer` should respect it and let Jackson to correctly deserialize an enum using its `toString` method.
Fix #1098
=> Respect deserialization of enums using toString()

dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
The previous behavior was returning an empty error list.
=> Null entities return error messages

dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/Person.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResource.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceTest.java
The default exception mappers are not registered in `ResourceTestRule`, which may be an annoyance to users, as they would have know what the defaults are and know to re-register them if their tests relied on functionality the exception mappers provided. This pull requests fixes this situation by registering them out of the box.
The only users who would be negatively affected by this pull request are those that turn off `registerDefaultExceptionMappers` in the configuration and choose not to define new mappers to replace them. Those that override default exception mappers in the application will still override them in `ResourceTestRule` as usual.
Closes #808
=> Register default mappers in ResourceTestRule

dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/ContextInjectionResource.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestWithGrizzly.java
When using Grizzly with `ResourceTestRule`, it didn't know how to map exceptions (it would just return the generic Grizzly error page, which is not useful for testing). This pull request fixes this by turning on `RESPONSE_SET_STATUS_OVER_SEND_ERROR`
Closes #1057 (though it only mentioned protected routes)
=> Tests with Grizzly now map exceptions properly

docs/source/about/release-notes.rst
"startAsRoot" should be "startsAsRoot" per AbstractServerFactory.java
=> Fixed typo in v0.7.0 release notes

docs/source/about/release-notes.rst, dropwizard-util/pom.xml
It seems to be safe to upgrade from 2.7 to 2.8.1
See:
http://www.joda.org/joda-time/upgradeto281.html
http://www.joda.org/joda-time/upgradeto280.html
=> use joda-time 2.8.1

dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/Person.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResource.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceTest.java
Reverts dropwizard/dropwizard#1125
This pull request needs to be reverted so that users that define their own exception mappers that conflict with ones that Dropwizard defines don't have their test cases fail undeterministically. I tried to make it so that overriding exception mappers can be graceful (#1144), but it is halted due to a Jersey issue. The reverted pull request didn't make it into the release notes, so those don't have to change.
=> Revert "Register default mappers in ResourceTestRule"

docs/source/about/release-notes.rst
This affords to users more easily browse details of the new features and bug fixes.
=> Add links to Github issues in the 0.9.0 release notes

dropwizard-logging/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable, dropwizard-logging/src/main/resources/META-INF/services/io.dropwizard.logging.LoggingFactory
It looks like [#996](https://github.com/dropwizard/dropwizard/pull/996) omitted these changes - I'm not sure if that was deliberate. I just pulled down 0.9.0-rc1 to play around with adding a custom LoggingFactory and it wouldn't work without these changes.
=> Make LoggingFactory discoverable.

dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java, dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java, dropwizard-metrics/src/main/java/io/dropwizard/metrics/MetricsFactory.java
Objects which hold configuration are serialized from json/yaml files.
Without proper ```toString()``` methods, it is impossible to log what
is the configuration of the application after it was deserialized into
the configuration class. It is especially important in regards to the
```DefaultServerFactory``` class, which holds the configuration for the
```server``` command. By adding the ```toString()``` methods, it is
possible to log during application startup what is the actual configuration
used by the app.
=> Add toString for configuration objects

docs/source/manual/auth.rst, dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java, dropwizard-auth/src/main/java/io/dropwizard/auth/basic/BasicCredentialAuthFilter.java, dropwizard-auth/src/main/java/io/dropwizard/auth/oauth/OAuthCredentialAuthFilter.java, dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicCustomAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthCustomProviderTest.java, dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java, dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedResourceTest.java
Generic parameter that controls a type of a passed authenticator to the `AuthFilterBuilder` is not actually needed. Type-safety is already forced by the generic parameters C(credentials) and P(principal). The user has to provide a class that implements interface `Authenticator<C,P>`, and we don't care about concrete type of this implementation, because it doesn't affect the auth filter.
This commit also moves the common logic of building auth filters to the `AuthFilterBuilder` and adds some comments for the public API.
=> Remove Authenticator generic parameter from AuthFilterBuilder

docs/source/manual/auth.rst, dropwizard-auth/src/main/java/io/dropwizard/auth/AuthDynamicFeature.java, dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java, dropwizard-auth/src/main/java/io/dropwizard/auth/PermitAllAuthorizer.java, dropwizard-auth/src/main/java/io/dropwizard/auth/basic/BasicCredentialAuthFilter.java, dropwizard-auth/src/main/java/io/dropwizard/auth/oauth/OAuthCredentialAuthFilter.java, dropwizard-auth/src/test/java/io/dropwizard/auth/AuthResource.java, dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicCustomAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/chained/ChainedAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthCustomProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/util/AuthUtil.java, dropwizard-example/src/main/java/com/example/helloworld/auth/ExampleAuthorizer.java, dropwizard-example/src/main/java/com/example/helloworld/resources/ProtectedResource.java, dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedResourceTest.java
This change consists from two parts: fixing behavior of the`@PermitAll` annotation and making
providing an authorizer in `AuthFilterBuilder` optional.
The `@PermitAll` annotation is actually intended  for marking that a resource doesn't require authorization. Currently we treat it like the resource doesn't require authentication. 
The solution is to register an auth filter for the methods marked with the `@PermitAll` annotation. The methods will require authentication, but anyone, who was given access, can use it. This simplifies the work of users who don't care about roles and authorization. They don't need create a fiction role and register `RolesAllowedDynamicFeature`.
Because users have an option to not authorize their resource methods, it makes sense to not require a custom …
=> Make authorization optional

docs/source/manual/auth.rst, dropwizard-auth/src/main/java/io/dropwizard/auth/AuthValueFactoryProvider.java, dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java, dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedResourceTest.java
* Make sure users pass the type inherited from `Principal`.
* Remove unchecked cast warnings.
* Remove unnecessary static class `AuthValueFactory`, which could be replaced by an anonymous class.
* Make `PrincipalClassProvider` a holder class, rather then an interface. Doing so, we don't create a new anonymous class in `Binder`.
* Documentation and style improvements.
=> Improve AuthFactoryProvider

docs/source/manual/auth.rst, dropwizard-auth/src/main/java/io/dropwizard/auth/AuthDynamicFeature.java, dropwizard-auth/src/test/java/io/dropwizard/auth/AuthBaseResourceConfig.java, dropwizard-auth/src/test/java/io/dropwizard/auth/AuthBaseTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/AuthResource.java, dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicCustomAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/chained/ChainedAuthProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthCustomProviderTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthProviderTest.java
* Auth alone should be enough to trigger the authentication servlet filter (https://github.com/dropwizard/dropwizard/pull/1162)
* There was a lot of duplication in auth tests, this should be more maintainable
=> Register auth filter when @Auth is present

docs/source/manual/configuration.rst, dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java, dropwizard-client/src/main/java/io/dropwizard/client/HttpClientConfiguration.java, dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
This adds an option to `HttpClientConfiguration` named `validateAfterInactivityPeriod` which enables a 'stale' connection check with the frequency of the given period.
This check helps detect connections that have become stale (half-closed) while kept inactive in a client's connection pool.
This check is disabled by default, but is configurable as a duration.
The HTTP/1.1 specification indicates the responsibility is with the client to handle closed keep-alive connections gracefully, and that the server can be expected to close that session at any time with or without intention.
In the HTTP/1.1 RFC#7230 it is stated in section 6.3.1 that:
>Connections can be closed at any time, with or without intention.
>Implementations ought to anticipate the need to recover from asynchronous close …
=> Add a config option to validate inactive connections

docs/source/manual/configuration.rst
The documentation has default value of rootPath as `/` while it should be `/*`. Setting it to `/` causes 404 on resources
=> Correct default value of rootPath

docs/source/about/release-notes.rst, dropwizard-jackson/pom.xml, pom.xml
2.6.0 is a cross-module update for Jackson, so we can remove the mess with the dependencies exclusion.
It's a release candidate, but pretty stable. This upgrade is backward-compatible, so it should not affect Dropwizard users.
=> Upgrade to Jackson 2.6.0-rc1

dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java, dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java, dropwizard-logging/src/test/resources/yaml/logging_advanced.yml
Also it is unnecessary to delete the log files after the test is done
because the log files are zeroed out when the test runs.
=> Fix DefaultLoggingFactoryTest on Windows

dropwizard-views-freemarker/pom.xml, dropwizard-views-mustache/pom.xml
The view tests were the only ones that used the `jdk-http` provider. Once I swapped it out for `inmemory`, the tests ran 25 seconds faster.
=> Use inmemory jersey server for view tests

dropwizard-auth/src/main/java/io/dropwizard/auth/ChainedAuthFactory.java, dropwizard-auth/src/test/java/io/dropwizard/auth/AuthResource.java, dropwizard-auth/src/test/java/io/dropwizard/auth/ChainedAuthProviderTest.java
Fixing issue #1201.
`ChainedAuthFactory` currently defaults `required` parameter to true, instead of using the annotation `required` value.
=> Fixing issue with ChainedAuthFactory to allow not required authentication

docs/source/manual/auth.rst
Minor fix on the auth documentation
=> Documentation : Missing generic type for basic auth

docs/source/manual/configuration.rst, docs/source/manual/core.rst, dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java, dropwizard-logging/src/main/java/io/dropwizard/logging/LoggerConfiguration.java, dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java, dropwizard-logging/src/test/resources/yaml/logging_advanced.yml
This is related to dropwizard#868 and dropwizard@7ab73cd
With additive=true (the default), a logger writes to its appender -and- any appenders hierarchically above it, including the root logger. For true redirection as described in issue 868, we need to be able to set additive=false so a logger writes to its appender only.
=> Add additivity setting to LoggerConfiguration

dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/main/java/io/dropwizard/client/JerseyIgnoreRequestUserAgentHeaderFilter.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyIgnoreRequestUserAgentHeaderFilterTest.java, dropwizard-client/src/test/resources/yaml/jerseyIgnoreRequestUserAgentHeaderFilterTest.yml
The details are here:
https://github.com/dropwizard/dropwizard/issues/1157
https://groups.google.com/forum/#!topic/dropwizard-user/XmSTpzz8Xx8
This commit is a part of UpWork.com initiative to maintain the 0.8.x
branch. The details about it are here:
https://groups.google.com/forum/#!topic/dropwizard-dev/hlK_Wi_2jis
=> #1157 Fixed user modifications of 'User-Agent' http header on requests

docs/source/manual/testing.rst
It doesn't make sense in the docs to setup mock _and_ then reset immediately. It was very confusing for me when I was setting up test
=> Should reset mock DAO in tear down

dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java, dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
Jersey expects that we create a new instance of the Apache HTTP client every time, when we create a new instance of the connector.
So, when `ClientRuntime` is garbage collected, the client is closed and new requests, that work with a new connector, use already closed client.
The fix is to not close the client in the connector. We can rely on the fact, that the client is managed by Dropwizard environment and it will be closed, when the application will be shut down.
Also users of Apache HTTP Client keep the ability to close the client manually, if they want to.
Fix #1160
=> Don't close the client instance in DropwizardApacheConnector

docs/source/about/release-notes.rst, dropwizard-core/src/test/java/io/dropwizard/setup/BootstrapTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java, dropwizard-validation/pom.xml, dropwizard-validation/src/test/java/io/dropwizard/validation/valuehandling/OptionalValidatedValueUnwrapperTest.java
Picked out a few interesting bits:
In some cases, when validating `Optional`, the `UnwrapValidatedValue` is not needed. Only one line of code in the entire code base was changed as the result of this. Since it's not entirely intuitive when `UnwrapValidatedValue` is needed, I've omitted changing the documentation because it still works with the annotation applied.
This doesn't affect dropwizard immediately, since we're not targeting jdk 8 right now, but with [new type annotations](https://blogs.oracle.com/java-platform-group/entry/java_8_s_new_type), it is possible to write code like:
```java
List<@NotEmpty String> strs; 
```
=> Update hibernate validator to 5.2.1.Final

docs/source/manual/views.rst, dropwizard-views-freemarker/src/main/java/io/dropwizard/views/freemarker/FreemarkerViewRenderer.java, dropwizard-views-freemarker/src/test/java/io/dropwizard/views/freemarker/ErrorView.java, dropwizard-views-freemarker/src/test/java/io/dropwizard/views/freemarker/FreemarkerViewRendererTest.java, dropwizard-views-freemarker/src/test/resources/example-error.ftl, dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/MustacheViewRenderer.java, dropwizard-views-mustache/src/test/java/io/dropwizard/views/mustache/ErrorView.java, dropwizard-views-mustache/src/test/java/io/dropwizard/views/mustache/MustacheViewRendererTest.java, dropwizard-views-mustache/src/test/resources/example-error.mustache, dropwizard-views/src/main/java/io/dropwizard/views/ViewMessageBodyWriter.java
Instead of hiding behind a sometimes deceptive error message saying that the
template file was not found, ~~propagate the error message in an HTML safe
way~~ return a generic error message with the actual error going to the log
file. This makes the behavior more in line with validation errors (though this
doesn't deal with validation errors, itself)
Closes #1077
=> Improve View Template Error Message

dropwizard-auth/src/main/java/io/dropwizard/auth/AuthValueFactoryProvider.java, dropwizard-auth/src/test/java/io/dropwizard/auth/AbstractAuthResourceConfig.java, dropwizard-auth/src/test/java/io/dropwizard/auth/AuthBaseResourceConfig.java, dropwizard-auth/src/test/java/io/dropwizard/auth/principal/JsonPrincipal.java, dropwizard-auth/src/test/java/io/dropwizard/auth/principal/NoAuthPrincipalEntityResource.java, dropwizard-auth/src/test/java/io/dropwizard/auth/principal/NoAuthPrincipalEntityTest.java
Principal parameter which is not annotated with Auth annotation shouldn't be authenticated. This worked before but only when such parameter is not annotated with any annotation. Otherwise parameter injection failed. The prove that this didn't work is NoAuthPrincipalEntityTest.annotatedPrincipalEntityWithoutAuth test which fails without the fix.
Btw., still wondering why Auth annotation is allowed on method and type level..
=> Fix for #1197 - Principal instance not injected when annotated

dropwizard-logging/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable
Changed LoggerFactory to LoggingFactory in META-INF/services/io.dropwizard.jackson.Discoverable
Solves issue #1248 : "Unable to load io.dropwizard.logging.LoggerFactory"
=> LoggingFactory in io.dropwizard.jackson.Discoverable

docs/source/manual/configuration.rst, dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java, dropwizard-db/src/test/resources/yaml/inline_user_pass_db_pool.yml
Some platforms provide credentials to connect to a database inlined in the connection URL. Examples:
* `postgres://postgres:SOME_PASSWORD@172.17.0.1:5432/lolipop`
* ` jdbc:h2:file:~/sample;USER=sa;PASSWORD=123`
* `jdbc:postgresql://localhost/test?user=fred&password=secret`
JDBC drivers support such a type of configuration. We should respect it and provide users ability to use it.
It means we should not require the username field to be set in the data source configuration.
Fixes #1259
=> Don't require username in the data source configuration

docs/source/manual/configuration.rst, dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java, dropwizard-db/src/test/resources/yaml/full_db_pool.yml
=> Add settings for removeAbandonedTimeout and removeAbandoned

docs/source/manual/auth.rst
The previous PR #1234 was for dropwizard 0.8.*, I updated it to work with dw 0.9 :)
I think that an empty line was missing after ```.. code-block:: java``` so the block was not displayed well.
Do we have to keep this part of the documentation in this file or should I move it to the **Testing** section?
=> Fix auth testing documentation

dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientIntegrationTest.java
By default Apache HTTP client builder enables decompression of responses. If we want to disable this feature in Jersey HTTP client, we should explicitly disable it in the underlying Apache HTTP client
during building.
=> Support for disabling decompression of HTTP responses

dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWork.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/HibernateBundleTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java
In some cases one need to simultaneously connect to several relational databases. Users want to use Hibernate to access each database. The problem that the current implementation of
`UnitOfWorkApplicationListener` supports only one session factory, which ultimately restricts ability to support several session factories.
Another problem is that users should have the ability to specify the name of datasource, against which a transaction should be opened in a resource method.
This change:
* Adds the method `value` to the `@UnitOfWork` annotation. It allows to specify the name of Hibernate bundle (session factory). By default it specifies the default bundle.
* Replaces the single session factory in `UnitOfWorkApplicationListener` to a map of session factories by names of bundles.
* The …
=> Add support for several Hibernate bundles

dropwizard-client/src/main/java/io/dropwizard/client/ConfiguredCloseableHttpClient.java, dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
This PR is to allow clients to override HttpClientBuilder's createClient method. Since not all configuration values can be set directly using the class or the YML configuration, this would allow clients fine grain control over the underlaying Apache's HttpClientBuilder in case they need to.
See https://github.com/dropwizard/dropwizard/issues/1186#issuecomment-148188882
=> Allow clients to override HttpClientBuilder#createClient method

docs/source/manual/client.rst
In order to create a new configuration class you need to provide also a setter for HttpClientConfiguration
=> doc fix - set method is also required

dropwizard-client/src/main/java/io/dropwizard/client/HttpClientConfiguration.java
With Hibernate Validator 5.2.x, when an annotation such as `@NotNull` can be applied to either the inner or wrapper type (in this case, `String` or `Optional`), the code must explicitly define `@UnwrapValidatedValue`
Fixes #1292
=> Fix HTTP Client Config User Agent Validation

dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientConfigurationTest.java, dropwizard-client/src/test/java/io/dropwizard/client/proxy/HttpClientConfigurationTest.java, dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/DBIClient.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/DefaultJacksonMessageBodyProvider.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/DefaultJacksonMessageBodyProvider.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProviderTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/DefaultJacksonMessageBodyProvider.java
The validator used in tests
(`Validation.buildDefaultValidatorFactory().getValidator()`) is not dropwizard
configured, thus bugs like #1292 slipped through. This pull request moves the
tests to the dropwizard configured validator. Note that this doesn't cover all
cases as some classes are not able to import dropwizard-jersey (where the
dropwizard configured validator lies) into the tests, so more work will need
to be done to cover all the bases.
~~This pull request also fixes #1292~~
=> Replace default validator in tests

dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
Another tests which was failing on non-English system because the whole (L10ned) validation message is verified.
=> Fixing failing tests on non-English OS by changing default locale

dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIFactory.java, dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/OptionalJodaTimeArgumentFactory.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/JDBIOptionalDateTimeTest.java
An alternative implementation of an argument factory that handles JodaTime arguments wrapped by Guava's Optional.
It uses the fact that JDBI processes argument factories in the specific order, so we can process optional JodaTime arguments before other optional arguments.
=> Add support for optional JodaTime arguments in JDBI

dropwizard-metrics/src/main/java/io/dropwizard/metrics/BaseReporterFactory.java
Proposed fix for #1308. I'm not familiar with how validations are tested in the Dropwizard codebase, so please advise on how I can write a test for this change.
=> Add UnwrapValidatedValue annotation to `BaseReporterFactory.frequency`

dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryFactoryTest.java, dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryTest.java, dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationValidationExceptionTest.java, dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java, dropwizard-core/src/test/java/io/dropwizard/server/SimpleServerFactoryTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/Validators.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipFilterFactoryTest.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/RequestLogFactoryTest.java, dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java, dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java, dropwizard-metrics/src/test/java/io/dropwizard/metrics/CsvReporterFactoryTest.java, dropwizard-metrics/src/test/java/io/dropwizard/metrics/MetricsFactoryTest.java, dropwizard-validation/src/main/java/io/dropwizard/validation/BaseValidator.java, dropwizard-validation/src/test/java/io/dropwizard/validation/ConstraintViolationsTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/DurationValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/MethodValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/OneOfValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/PortRangeValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/SizeValidatorTest.java
Use a minimally configured Hibernate Validator everywhere, instead of the
default unconfigured Hibernate Validator that doesn't have Optional support
enabled.
Good news, no other part of the code was affected by the behavior seen in #1309. So this pull request is more preventive than anything.
I do wonder if there is a better implementation out there (I'd rather not expose `BaseValidator` to the world, but it's the best I came up with). Let me know if a better implementation exists :wink:
=> Use a minimally configured Hibernate Validator everywhere

dropwizard-jersey/src/main/java/io/dropwizard/jersey/guava/OptionalParamConverterProvider.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalQueryParamResourceTest.java
Some converters return a null value (e.g. in case of empty input).
=> Guava Optional<T>: Treat null values after conversion as absent value.

dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java, dropwizard-db/src/main/java/io/dropwizard/db/PooledDataSourceFactory.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java, dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIFactory.java
The `PooledDataSourceFactory#getHealthCheckValidation{Query,Timeout}` methods were introduced while refactoring `DataSourceFactory` to allow custom DB connection pools (PR #1030) but broke the serialization of the default configuration for `DataSourceFactory`.
By deprecating these methods and pulling the original `DataSourceFactory#getValidation{Query,Timeout}` methods into `PooledDataSourceFactory`, the
original behaviour was restored.
Fixes #1321, refs #1030
=> Deprecate PooledDataSourceFactory#getHealthCheckValidation{Query,Timeout}

dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java, dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java, dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java, dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java, dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
The beginning of going to a 1.0 Version is maybe a good timing to get rid of ancient list of TODOs. Important stuff pops up every day, no need to keep TODOs from two years ago.
=> Removed ancient TODOs from the code

docs/source/manual/example.rst
The current rendered docs aren't displaying the nested lists as intended, but rather lumping each block into a single line: http://www.dropwizard.io/0.9.1/docs/manual/example.html
=> Fix nested lists and other styling in example.rst

dropwizard-logging/src/main/java/io/dropwizard/logging/LoggingUtil.java
Missing a single letter in the document comments
SL4J -> SLF4J
=> fix typo in document comments

docs/source/getting-started.rst
There's a typo in the "And Friends" section of the "Getting Started" docs. `JSR-349` should be `JSR-303`, as specified in the links below that section.
=> Fix typo in Getting Started section of docs

dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonResource.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/NonBeanImplementation.java
Jackson is good about serializing types that conform to the Bean spec, but
needs help serializing and deserializing types that don't (normally with
the use of annotations). Previous behavior would return a 400 (Bad
Request) when the server would attempt to return an entity that couldn't
be serialized. This is misleading because it gives the illusion that the
fault lies with the client instead of the server.
=> Entities that can't be serialized now return a 500

dropwizard-client/src/main/java/io/dropwizard/client/HttpClientConfiguration.java, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientConfiguration.java
Would be nice if the docs for the latest version were available at `/latest/docs` or something like that we one could point to the docs without specifying a particular version, but lacking that, pointing to `/0.9.1/docs` is the best I can think of.
=> Fix broken links to manual in javadoc

docs/source/manual/core.rst
Dropwizard contains the task `LogConfigurationTask` and adds it by
default to the [admin environment](https://github.com/dropwizard/dropwizard/blob/49ff92712a936554d2cf9bd7a2b09a0fc07eaf25/dropwizard-core/src/main/java/io/dropwizard/setup/AdminEnvironment.java#L42). Unfortunately this task is not
yet documented.
=> docs: Explain HTTP based log level configuration

dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
Add the ability to set predefined HTTP headers for each HTTP request of an HTTP client.
Apache `HttpClientBuilder` already supports such functionality and we should just delegate building from Dropwizard `HttpClientBuilder`.
In the result users can provide own headers without subclassing Dropwizard `HttpClientBuilder`.
Resolves #1353
=> Add support for setting default headers in Apache HTTP client

dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
The `reportPlugins` section has been deprecated since version 3.3 of `maven-site-plugin` in favour of the classic reporting configuration. Currently my IDE marks the former as not valid according to an XSD schema. 
Explanation is [here](http://maven.apache.org/plugins/maven-site-plugin/maven-3.html#New_Configuration_Maven_3_only_no_reports_configuration_inheritance).
Diff is kind of weird, better to view with `?w=1`
=> Move the reportPlugins section in the archetype

dropwizard-archetypes/pom.xml, dropwizard-example/pom.xml, pom.xml
Add a development profile that allow to skip following things during project installation:
* Running Findbugs checks;
* Generating Javadoc;
* Creating a verifying a sample project from the archetype;
* Generating a shadowed artifact for the example project.
This allows to decrease the time to clean and install project from 4-5 minutes to 20-30 seconds during development.
=> Add a development profile to Maven

.editorconfig
Java properties files are assumed to be ISO-8859-1 (latin-1) encoded.
=> Encoding of properties files is ISO-8859-1

docs/source/manual/client.rst
Since dropwizard has upgraded to jersey 2, the dropwizard-client docs should link to jersey 2 docs.
=> link to jersey 2.22.1 docs, not 1.18

dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java, dropwizard-core/src/test/java/io/dropwizard/cli/CommandTest.java
Currently, if `-h` is provided on the commandline and invalid arguments are specified as well, the help message will be printed twice. This is not desired (the help message should only be printed once)
This change is not backwards compatible for those who need to see that `is-help` is set in the `run` command (this would only be when the case when all arguments are optional)
Closes #1357
=> Print help once on invalid command line arguments

dropwizard-util/src/main/java/io/dropwizard/util/Size.java, dropwizard-util/src/test/java/io/dropwizard/util/SizeTest.java
Support case insensitive SizeUnit suffixes.
Support all single letter SizeUnit suffixes.
=> Make SizeUnit more flexible

dropwizard-configuration/src/main/java/io/dropwizard/configuration/SubstitutingSourceProvider.java, dropwizard-configuration/src/test/java/io/dropwizard/configuration/SubstitutingSourceProviderTest.java
This probably doesn't ever cause problems, but closing streams is important
if it gets called repeatedly (e.g if it is actually a zlib InputStream, it
holds on to native memory until closed). Fixing this will help prevent future
copy and paste bugs.
I found this because I was doing some quick code searching to determine if Dropwizard might have any obvious places where a zlib InputStream might not get closed right away, that might have caused the following native memory leak. I suspect this is *not* the actual cause of the bug, but it might as well be fixed also.
=> configuration: SubstitutingSourceProvider: close the delegate's stream

docs/source/manual/testing.rst, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResource.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceExceptionMapperTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceTest.java
This commit makes the default behavior of `ResourceTestRule` to register
all the default exception mappers, much like how the default yaml
configuration will register the default exception mappers.
If a user wants to override the default exception mappers, then they can
call `setRegisterDefaultExceptionMappers(false)` and subsequently register
their custom exception mappers.
Note that this is breaking behavior as those who registered their
exception mappers will now have to call setRegisterDefaultExceptionMappers
and those who wanted the default exception mappers should now remove their
registrations of the default exception mappers.
The  reason behind this pull request is that, in my opinion, it is unreasonable
for someone new to Dropwizard to know all the default exception mappers that …
=> Add RegisterDefaultExceptionMappers to TestRule

dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2583 - Conditions should not unconditionally evaluate to "TRUE" or to "FALSE"
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2583
Kirill Vlasov
=> Conditions should not unconditionally evaluate to "TRUE" or to "FALSE"

dropwizard-client/src/test/java/io/dropwizard/client/ssl/DropwizardSSLConnectionSocketFactoryTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1481 - Unused local variables should be removed
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1481
Kirill Vlasov
=> Unused local variables should be removed

dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2259 - Null pointers should not be dereferenced
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2259
Kirill Vlasov
=> Null pointers should not be dereferenced

dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/jersey/LoggingDBIExceptionMapper.java, dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/jersey/LoggingSQLExceptionMapper.java, dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2444 - Lazy initialization of "static" fields should be "synchronized"
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2444
Kirill Vlasov
=> Lazy initialization of "static" fields should be "synchronized"

pom.xml
Run them in parallel only in the dev mode. Looks like that Travis CI is really flaky with a parallel test execution. The build often fails without a reason and this really confuses new contributors. Better
to have a slow and stable build then fast and unreliable.
=> Disable parallel tests by default

dropwizard-client/src/main/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactory.java, dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java, dropwizard-logging/src/test/java/io/dropwizard/logging/PrefixedRootCauseFirstThrowableProxyConverterTest.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2325 - "private" methods that don't access instance data should be "static"
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2325
Kirill Vlasov
=> "private" methods that don't access instance data should be "static"

dropwizard-core/src/main/java/io/dropwizard/Application.java
I've started using Dropwizard for CLI apps and other types of things. This way, I can create an entire system that consumes config in the same way, etc. However, DW always adds server and check commands. I don't always want this. Add a method to not add these.
=> Dropwizard always adds "server" and "check" commands. This is restrictive

docs/source/about/release-notes.rst
A number of improvements have already been [contributed](https://github.com/dropwizard/dropwizard/pulls?q=is%3Apr+milestone%3A1.0.0+is%3Aclosed) in 1.0.0, and it would be great to write them down to the changelog. 
This PR synchronizes the release notes in the docs with the current mainline state, which should allows users to more easily track progress in 1.0.0.
=> Synchronize 1.0.0 release notes

docs/source/manual/configuration.rst, dropwizard-example/example.yml, dropwizard-http2/src/main/java/io/dropwizard/http2/Http2CConnectorFactory.java, dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java, dropwizard-http2/src/test/resources/test-http2.yml, dropwizard-http2/src/test/resources/test-http2c.yml
`h2` and `h2c` are official identificators for the HTTP/2 over TLS and HTTP/2 clear text protocols. It would be more consistent with the spec and less confusing for users, if we used these them instead `http2` and `http2c`.
See [HTTP/2 implementation list](https://github.com/http2/http2-spec/wiki/Implementations) for the reference.
=> Use h2 and h2c as the HTTP/2 connector names

dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ParamValidatorUnwrapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
Before if you had a resource that was like:
```java
@GET
@Path("nullable-int-param")
public String nullableIntParam(@QueryParam("num") @Max(3) IntParam secretSauce) {
return secretSauce == null ? "I was null" : secretSauce.get().toString();
}
```
And you passed in `null`, the validator will fail due to an null
dereference in the unwrapper class.
This fixes the behavior by checking if the param is null before attempting
to unwrap
=> Fix: allow validation of Param nullable instances

dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWork.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java
This PR provides the ability to use the `@UnitOfWork` annotation outside of Jersey resources.
It consists from two changes: 
* In first we move operations over `@UnitOfWork` methods from `UnitOfWorkApplicationListener` into  an aspect. It allows to perform these operations outside of the listener (for example, in proxies or AOP providers).
* In second we provide a factory for creating `@UnitOfWork` aware proxies. A created proxy will
detect the annotation on component methods and will open/close a Hibernate session around them.
It uses aforementioned aspect for this. Javassist is used for creating proxies, because it has a
simple API for that and it's shipped with Hibernate.
Now to use `@UnitOfWork` in authenticators, one need just to create proxy like this:
```java
SessionDao dao = new …
```
=> Support  `@UnitOfWork` outside of Jersey resources

dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleReentrantTest.java
We've found on our projects that builds go significantly faster if we use DropwizardAppRule at the suite level.
This however makes it difficult to run individual tests in isolation.
This pull request makes DropwizardAppRule usable in a recursive way, but only starts and stops the application once for the outer call. With this change we are able to run the entire test suite, or a single test in a single class, and the application will be started/stopped once and only once.
There are usage examples in the javadoc changes.
=> Make DropwizardAppRule start and stop app only once, even when called recursively

dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java, dropwizard-db/src/main/java/io/dropwizard/db/PooledDataSourceFactory.java
Some downstream Dropwizard modules need access to the JDBC
connection URL, which exists on DataSourceFactory but not the
PooledDataSourceFactory interface.  Since this interface is
JDBC-specific (i.e. all connection-pool implementations will
have a connection URL), it won't restrict any implementations.
Fixes #1413.
=> Add #getUrl() to PooledDataSourceFactory

dropwizard-jetty/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable
Last missing piece for #1290 (as verified by external implementation, sorry for the scattered dot connection). Also included in #1415 by this is a much smaller change.
=> Register RequestLogFactory as Discoverable

dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardTestResourceConfig.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestJerseyConfiguration.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java
Currently the `ResourceTestResourceConfig` class is kind of a mess. It uses several inner classes, a static map of test rules, and doesn't have any comments. It's hard to see what's going on there.
This change:
* moves the inner class `ResourceTestResourceConfig` to a separate class named `DropwizardTestResourceConfig`. This name is more meaningful and suitable in my opinion;
* introduces the class `ResourceTestJerseyConfiguration` which contains a configuration passed by a user via `ResourceTest.Builder`. It allows to decouple `DropwizardTestResourceConfig` from `ResourceTestRule`.
* this class is also used for passing the current `ResourceConfig` configuration via a servlet context instead of the `ResourceTestRule` class in a Grizzly web test container. This removes additinal …
=> Refactor ResourceTestRule

dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java, dropwizard-jetty/src/test/resources/yaml/https-connector.yml
We currently don't have any tests for this. This change add a check, that the configuration, that we provide in the reference at http://dropwizard.io, is actually correctly parsed.
=> Add a test for parsing HTTPS connector configuration

dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryTest.java, dropwizard-configuration/src/test/resources/factory-test-malformed-advanced.yml, dropwizard-configuration/src/test/resources/factory-test-typo.yml, dropwizard-configuration/src/test/resources/factory-test-wrong-type.yml
I found out that we currently don't have tests for handling errors during parsing and binding YAML configuration files. This changes fixes this by adding several tests:
* A test that we print the `Did you mean?` suggestions on an unrecognized field in the configuration class. The suggestions are sorted based on an edit distance from the input. The limit is 5 suggestions.
* A test that we print a detailed error message, when there are type data type errors during binding a YAML tree to the configuration class.
* A test that we print a line number, a position of an error, and a parser error message, if a YAML file is malformed.
As a result, this provides the ability to catch regressions during Jackson and SnakeYAML updates.
=> Add ConfigurationParsingException tests

dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryTest.java
Looks like the exception message contains newlines, so this test failed on Windows. Not sure if this is the desired behavior, because as of now there is a mix of line endings -- I just got the test to pass.
=> Fix configuration factory test on windows

docs/source/manual/configuration.rst
https://github.com/dropwizard/dropwizard/issues/1375
It's a little difficult for me to explain the situation in the documentation, but I did my best :). I can update it as you see fit.
I could also move it to above like this note:
=> Add a note to jersey maxThread configuration documentation

dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java, dropwizard-auth/src/test/java/io/dropwizard/auth/AuthFilterTest.java
The current implementation of `AuthFilter.authenticate` does this:
```java
requestContext.setSecurityContext(new SecurityContext() {
@Override
public boolean isSecure() {
return requestContext.getSecurityContext().isSecure();
}
});
```
Calling `isSecure()` on the filtered requestContext will recurse infinitely causing a StackOverflowError.
This PR fixes this bug and adds a test. The test is quite complex for such a small fix, but I can't think of a simpler way, due to the JAX-RS class design. Because of this, I'm fine with this being merged with or without the test.
=> Fixed infinite recursion bug in AuthFilter::authenticate

dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java, dropwizard-validation/src/main/java/io/dropwizard/validation/ConstraintViolations.java, dropwizard-validation/src/test/java/io/dropwizard/validation/MethodValidatorTest.java
Previously, when a ValidationMethod caused a constraint violation and the
violation was caused by a nested object using the `@Valid` annotation, the
message would contain the path of the nested object. This may be
misleading to the client who sees the message because the nested code path
may not have a related field in the JSON they sent (for example, the field
could be a misnomer).
The fix is return the message exactly as it is transcribed in the
`@ValidationMethod` annotation. Thus, it is now the user's responsibility
to create descriptive enough messages, such that the client can discern
the error through any amount of nesting.
This change does break APIs that relied on the message containing the code path
to the object that contained the ValidationMethod violation. ValidationMethods …
=> ValidationMethod violation message is itself

dropwizard-bom/pom.xml, dropwizard-hibernate/pom.xml, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryHealthCheck.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/HibernateBundleTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryFactoryTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryHealthCheckTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java
Hibernate 5 has been out for a while; there are a few patch releases and it seems fairly stable, so I updated the dropwizard-hibernate module to use Hibernate 5.
This is a big advantage to people who want to use Java 8 time classes such as Instant, because they won't have to include extra Jadira jars to make hibernate persist the new types.  I'm not aware of any downside since those not using Java 8 can still use the Jadira support for Joda time etc. as before.
=> Updated to Hibernate 5.0.7

docs/source/about/release-notes.rst, docs/source/manual/migrations.rst, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/MigrationsBundle.java
In similar lines to HibernateBundles, having the possibility of unique names. This PR attempts to do the same for MigrationBundles, so that multiple migration bundles can be provided for.
=> Added naming to migration bundles

dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestJerseyConfiguration.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceTest.java
Addresses #1416.
Adds a `setClientConfigurator` method to the `ResourceTestRule.Builder` class which allows configuration of the Jersey Clients used in test rules. Adds a test to `PersonResourceTest` which ensures that custom providers installed by this new builder method are reflected in the produced clients.
=> dropwizard-testing: Add Jersey Client configurability to ResourceTestRule

docs/source/manual/configuration.rst, dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java, dropwizard-logging/src/main/java/io/dropwizard/logging/ConsoleAppenderFactory.java, dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java, dropwizard-logging/src/main/java/io/dropwizard/logging/SyslogAppenderFactory.java, dropwizard-logging/src/main/java/io/dropwizard/logging/filter/FilterFactory.java, dropwizard-logging/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable, dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java, dropwizard-logging/src/test/java/io/dropwizard/logging/SecondTestFilterFactory.java, dropwizard-logging/src/test/java/io/dropwizard/logging/TestFilterFactory.java, dropwizard-logging/src/test/resources/META-INF/services/io.dropwizard.logging.filter.FilterFactory, dropwizard-logging/src/test/resources/yaml/logging_advanced.yml
This change adds a seam to allow consumers to supply Logback Filters to apply to logging Appenders. These filters will be applied, in order, after the threshold filter. This allows for further refinement of what will be logged. For example, I have an endpoint that is called on a schedule to check availability that I would like to exclude from the access logs by supplying a filter for this URI.
You could also add appenders with the following:
* A filter that will only log failures based on status code.
* A filter that will log requests with slow responses.
* A filter that will log large requests/responses.
=> Allow for supplying Filters to Logging Appenders

dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java, dropwizard-core/src/test/java/io/dropwizard/server/AbstractServerFactoryTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/setup/JerseyEnvironment.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/setup/JerseyEnvironmentTest.java
Before this commit, the only way to set the Jersey URL pattern was to
add it in the YAML configuration, under `rootpath`. This commit now
allows the following priority order for the Jersey URL pattern:
1. the YAML config
2. the value set in the applications `run()` block
3. the default value from `DropwizardResourceConfig`, which is `/*`
with this priority order, there should be no breaking changes for users
who have set the value in the YAML. it will now allow applications
to have this value hardcoded, making the YAML file simpler
fixes #1408
=> Added ability to set the Jersey URL pattern in Application.run()

dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIFactory.java, dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/OptionalOffsetDateTimeArgumentFactory.java, dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/OptionalZonedDateTimeArgumentFactory.java
* Renamed `OptionalOffsetTimeArgumentFactory` to `OptionalOffsetDateTimeArgumentFactory`
* Renamed `OptionalZonedTimeArgumentFactory` to `OptionalZonedDateTimeArgumentFactory`
Fixes https://github.com/dropwizard/dropwizard/issues/1382
=> Rename JDBI argument factories to match class names

dropwizard-core/src/test/java/io/dropwizard/setup/BootstrapTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalDoubleMessageBodyWriter.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalDoubleParamConverterProvider.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalIntMessageBodyWriter.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalIntParamConverterProvider.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalLongMessageBodyWriter.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalLongParamConverterProvider.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalParamBinder.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalCookieParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalDoubleMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalFormParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalHeaderParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalIntMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalLongMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalQueryParamResourceTest.java, dropwizard-validation/src/main/java/io/dropwizard/validation/BaseValidator.java, dropwizard-validation/src/main/java/io/dropwizard/validation/valuehandling/OptionalDoubleValidatedValueUnwrapper.java, dropwizard-validation/src/main/java/io/dropwizard/validation/valuehandling/OptionalIntValidatedValueUnwrapper.java, dropwizard-validation/src/main/java/io/dropwizard/validation/valuehandling/OptionalLongValidatedValueUnwrapper.java, dropwizard-validation/src/test/java/io/dropwizard/validation/valuehandling/OptionalDoubleValidatedValueUnwrapperTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/valuehandling/OptionalIntValidatedValueUnwrapperTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/valuehandling/OptionalLongValidatedValueUnwrapperTest.java
This PR adds `ValidatedValueUnwrapper`, `ParamConverter`, and `MessageBodyWriter` implementations for `OptionalDouble`, `OptionalInt`, and `OptionalLong` to be consistent with the already existing `GuavaOptionalValidatedValueUnwrapper` and `OptionalValidatedValueUnwrapper` classes.
Fixes #1447
=> Improve Support for Optional{Double,Int,Long} in Jersey

dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/LoggingExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/ExceptionResource.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/LoggingExceptionMapperTest.java
The change to "[Format WebApplicationException](https://github.com/dropwizard/dropwizard/commit/930443a5bc5760c3319bedf7b36e13810bf0dd8e#diff-235351c1b64afb2dba6188b2bd0c5386)" introduced a regression: namely, if the response contained within the WebApplicationException is a redirect, the redirect no longer works. Instead, a JSON entity is returned instead.
This change restores the previous behaviour for redirects in the WebApplicationException response.
=> Handle redirect in WebApplicationException response

dropwizard-metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteReporterFactory.java, dropwizard-metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterFactoryTest.java
- allows usage of TCP or UDP graphite reporter from metrics lib
Welcome to feedback. I only tackled the UDP/TCP variant to start. Likely, other graphite reports (pickle, rabbitmq) would be separate reporter factory/config options
=> Allow selection of `TCP` or `UDP` for Graphite Reporter

docs/source/manual/core.rst
I'd like to add an example to the docs to show the structure of a simple configured bundle. I recently did some work creating a configured bundle and I think this would have helped.
=> add example for Configured Bundles docs

dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/ResourceURL.java
I have a project JAR (call it lib) containing a Bundle that exposes resources via the AssetsServlet. The resources live inside that JAR also. I am including this JAR as a dependency in another project (call it app) that uses the maven-spring-boot-plugin to create a self-contained, runnable JAR. When the asset servlet is hit, the code in lib attempts to load the resource. It fails in io.dropwizard.servlets.assets.ResourceUrl#isDirectory at this point:
```
String filename = resourceURL.getFile();
filename = filename.substring(filename.indexOf('!') + 2);
JarFile jarFile = e.getJarFile();
ZipEntry zipEntry = jarFile.getEntry(filename);
InputStream inputStream = jarFile.getInputStream(zipEntry);
```
filename starts out as: ```jar:file:app.jar!/lib/lib.jar!/resource/file.txt```
The code …
=> Deal correctly with nested JAR resources

dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/DropwizardConfiguredValidator.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/SubBeanParameter.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResource.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceTest.java
This is a fix for #1433.
Previously, the `Validated` annotation would only be allowed on entity parameters of a resource, even though a `BeanParam` could be validated. This created a problem where one would want to specify a validation group on an endpoint that only accepted a `BeanParam`, as they would be forced to annotate a dummy request entity with `Validated`.
This pull request also handles the situation when the user supplies two or more entities with `Validated`. These annotations must be equivalent (and thus redundant), else an exception will be thrown as the underlying validator cannot validate parameters under different validation groups.
I would like critiques of the implementation because as of right now, a `WebApplicationException` is thrown, as a `RuntimeException` will …
=> Allow Validated to annotate non-entity objects

dropwizard-bom/pom.xml, dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryTest.java, dropwizard-jackson/pom.xml, dropwizard-jackson/src/main/java/io/dropwizard/jackson/AnnotationSensitivePropertyNamingStrategy.java, dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java, dropwizard-jackson/src/test/java/io/dropwizard/jackson/JacksonTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/ExceptionResource.java
* Upgrade to the latest Jackson version that correctly handle subtyping
* Remove JDK7 module, because it has been merged to jackson-databind
* Upgrade deprecated API
* Fix the test for printing a detailed YAML parsing error
See the discussion of the previous update attempt in issue #1449.
=> Upgrade to Jackson 2.7.3

docs/source/manual/testing.rst
Hi,
after reading the docs of 0.9.2, I've tried the given example for non-junit tests.
In my case I'm using TestNG.
Unfortunately the give code doesn't compile and there where 'BindException'
because port 8080 was already in use.
So I've added an overriding config to get a random port and I fixed the wrong var-name.
Additionally I removed the parameter from JerseyClientBuilder,
because 'environment' and 'test-name' aren't supported.
My tests are running fine without them, but I have to admit,
that I'm not using any "special" Jackson mappings.
Feedback is always welcome.
Kind regards
Martin
=> Revise code example in docs for testing non-junit

docs/source/getting-started.rst
- link to JSR 349 did not render correctly, removed hyphen (which seems
to be the official variant anyway)
- fixed broken link to Gant (codehaus shut down)
- use updated link to Guava (Google Code shut down)
=> Fixed broken or outdated links

dropwizard-archetypes/README.md
Given that $name is used to generate Configuration and Application classes, it is vital for new users not to inappropriately name it during maven interactive mode. 
Also the hard-coded 0.9.1 archetype version is replaced with a place holder (there might be a better solution to have a token put in that is value-replaced by release version?).
=> Update on README.md in dropwizard-archetypes

docs/source/getting-started.rst
[Metrics for metrics](http://www.dropwizard.io/0.9.2/docs/getting-started.html#metrics-for-metrics)
Metrics project url `http://metrics.codahale.com/` does not point to valid url, how about pointing to `http://metrics.dropwizard.io/`?
=> fix for metrics library url at getting started section

dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java, dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
~~As a simple fix, an immutable, single-element list (`Collections.singletonList`) has been wrapped in a mutable one, so it can be extended (if there will be anymore headers with the same name).~~
In this case `Lists.newArrayList` was used to create a mutable `List`, so it can be extended in case of multiple headers with the same name, i.e. `Set-Cookie`.
Fixes #1494
=> Fix handling multiple headers with the same name

dropwizard-core/src/main/java/io/dropwizard/cli/EnvironmentCommand.java, dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java, dropwizard-core/src/main/java/io/dropwizard/server/ServerFactory.java, dropwizard-core/src/main/java/io/dropwizard/server/SimpleServerFactory.java, dropwizard-core/src/test/java/io/dropwizard/server/AbstractServerFactoryTest.java, dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java, dropwizard-core/src/test/java/io/dropwizard/server/SimpleServerFactoryTest.java
This commit configures the context paths for the application before the
application `run()` instead of setting it prior to starting the server.
This allows applications to obtain the context paths during the run
method.
This shouldn't break any changes to the users, but note that
ServerFactory now needs to call `configure` explicitly to set the
context paths in the environment
=> configures the environment with the context paths before the application.run()

dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/args/OffsetDateTimeArgumentTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/args/OffsetDateTimeMapperTest.java
The problems with these three tests were caused by the fact, that the date used in them has been forcing
non-DST timezone (i.e. `+01:00` in most of the Europe), but then it was compared to the same date, but in current (that is DST) timezone (i.e. `+02:00`).
=> Fix tests affected by the DST change

docs/source/manual/views.rst, dropwizard-views/src/main/java/io/dropwizard/views/ViewMessageBodyWriter.java
=> Log missing template at ERROR instead of DEBUG

dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java
I end up doing this a lot in my code so I can reference the `MetricRegistry` throughout my app.
=> Register the default MetricRegistry as the "default"

dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryTest.java
May have been a change in the recent Jackson version, but this fixes the test on windows.
=> Fix newline comparison for windows test

docs/source/about/release-notes.rst
Just a small formatting fix I found while looking at the release notes for v1.0.0. 
Here's the before and after:
=> fix link to issue in release notes

dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/Dog.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/LazyLoadingTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java
Currently any hibernate loaded objects must be fully loaded before the resource method ends, otherwise the Jackson serialiser fails.  This forces developers to annotate associations for eager loading, or walk the object graph to force hibernate to load associations - neither is very nice.
However, the Hibernate5Module can handle lazy loading proxies, but doesn't do this by default (not sure why not) - and developers could enable it.  The problem is that UnitOfWorkApplicationListener closes the hibernate session before the results have been seriazised, so even if developers turn on the lazy-loading support it won't work.
The changes I have made cause the session to be closed later and switch on lazy-loading support by default, as well as adding a test for this functionality.
Possible …
=> Support serialisation of lazy loaded POJOs

.travis.yml, dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java, dropwizard-db/src/test/resources/yaml/empty_initial_pool.yml
#1037 Simple fix to make it possible to instantiate an empty connection pool. For cases where you still want the webapp to load, e.g. you want a service to be able to start and show an error page when a DB isn't available.
Includes tests. Please ignore the changes to `travis.yml`
=> Issue 1037

dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonResource.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/OkRepresentation.java
Previously if a client would supply a string value where an Integer should
be, for example, a 500 error would be generated. This fix will now return
a 400 for all invalid conversions from JSON to Java Object.
As discovered by @mikewatt in #1347
CC'ing others from #1347: @jplock, @brentryan
=> Jackson Invalid Format Exception is 400 response

dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProvider.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonResource.java
As a follow up to #1527
This PR does a couple things:
- Entities that throw an `IOException` on deserialization will now map to a client error on invalid input instead of being handled by the logging exception handler
- New implementation determining whether a Jackson exception is due to the server (programmer's) or client's fault. New implementation was needed because the new tests that were written exposed flaws. After scratching my head for far too long, the best solution was peeking at the exception message. Not cleanest, but the tests will show if the error messages change in a future version.
- Clean up the tests a tad
Closes #1539, #1540
=> Fix invalid JSON reporting server errors

docs/source/manual/configuration.rst, dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java, dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
Closes #1491
I think there is no reason not to allow dropwizard users the ability to keep infinite files as long as it is warned and the default remains something sensible.
This also fixes the erroneous description that the number of archived files have a maximum (they don't)
=> Allow file appender infinite log files

dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryTest.java, dropwizard-jackson/src/main/java/io/dropwizard/jackson/GuavaExtrasModule.java, dropwizard-jackson/src/test/java/io/dropwizard/jackson/GuavaExtrasModuleTest.java
If a configuration has a default value for a CacheBuilderSpec (e.g. `CacheBuilderSpec cacheBuilderSpec = CacheBuilderSpec.disableCaching();`) and the value is not overridden in the configuration file, we need to serialize the object before parsing the configuration so that it can be properly instantiated in the `Configuration` class.
=> Add CacheBuilderSpecSerializer

docs/source/about/release-notes.rst, dropwizard-benchmarks/pom.xml, dropwizard-bom/pom.xml, pom.xml
* Upgrade to Hibernate 5.1.0
* Upgrade to Mockito 2.0.53-beta
* Upgrade to tomcat-jdbc 8.5.2
* Upgrade to JMH 1.12
* Upgrade to HSQLDB 2.3.4
* Upgrade to Objenesis 2.3
* Upgrade to Liquibase 3.5.1
* Upgrade to Jetty 9.3.9.v20160517
* Upgrade to Jersey 2.23
=> Dependency updates

dropwizard-core/src/main/java/io/dropwizard/Application.java, dropwizard-core/src/test/java/io/dropwizard/ApplicationTest.java, findbugs-exclude.xml
The current behavior of configuration errors etc. in `Application.run(String...)` is to call `System.exit(1)`. This can play havoc with things like integration tests, such that a hard exit will terminate the testing process.
This change allows folks to override the default behavior to do something other than the `System.exit(1)` call.
=> Permit override of default failed command behavior

dropwizard-bom/pom.xml, dropwizard-http2/pom.xml
The version of `alpn-boot` is dependent on the version of the JVM being used, otherwise the build will fail.
Since not everyone is using the same version of the JVM, this PR adds profiles to `dropwizard-http2` for selecting the correct version of `alpn-boot`.
This is only required for running tests locally and on Travis CI.
=> Add Maven profiles for selecting alpn-boot version

docs/source/manual/migrations.rst, dropwizard-migrations/src/main/java/io/dropwizard/migrations/AbstractLiquibaseCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/CloseableLiquibase.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/CloseableLiquibaseWithClassPathMigrationsFile.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/CloseableLiquibaseWithFileSystemMigrationsFile.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbCalculateChecksumCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbClearChecksumsCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbDropAllCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbDumpCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbFastForwardCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbGenerateDocsCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbLocksCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbMigrateCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbPrepareRollbackCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbRollbackCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbStatusCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbTagCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbTestCommand.java, dropwizard-migrations/src/main/java/io/dropwizard/migrations/MigrationsBundle.java, dropwizard-migrations/src/test/java/io/dropwizard/migrations/CloseableLiquibaseTest.java, dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbDumpCommandTest.java, dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCommandTest.java, dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateDifferentFileCommandTest.java, dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbStatusCommandTest.java, dropwizard-migrations/src/test/resources/migrations-test.xml
I have a use case where I'd like to run multiple `DropwizardAppRule` instances in an integration test and each DropwizardAppRule is from a different fat jar dependency. Each DropwizardAppRule will need to migrate its own database, however the `migration.xml` files collide because they have the same name. This PR allows the migrations filename to be set in the `MigrationsBundle` by overriding `getMigrationsFileName()`, which defaults to `migrations.xml`.
=> add support for customizing the name of the migrations file

dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java, dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
Hi,
this pull request is with regards to: 
FileAppenderFactory not valid for null currentLogFilename #1278
First time pull request, let me know if there is something I forgot. 
This fix adds: 
* New validation based on the archived configuration to allow for null currentFileNames in case one wants to use the rolling policies file policy instead 
* Tests to assure that validation works and the rolling policy's filename is used instead.
=> #1278 pull request for FileAppenderFactory

dropwizard-http2/src/main/java/io/dropwizard/http2/Http2CConnectorFactory.java, dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java
The latest bump in jetty [deprecated some functions](https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java#L109-L117)
=> Fix deprecation notices in http2 servers

dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/DropwizardConfiguredValidator.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
Update ConstraintMessage.isRequestEntity to be resilient against
exceptions by using the `Iterables.get` method which accepts a default
value. This is required in case the property path contains fewer than 2
items.
=> Add Resource Bean Validation

docs/source/manual/configuration.rst
FireBird will throw SQLException("Validation Query Failed, enable logValidationErrors ...").. To fix that its necessary to set  validationQuery to  "select 1 from rdb$database"
=> Add note to Doc : migrate about Migrating with DB firebird

dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java, dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java
Hi there.  
I've noticed that the acceptQueueSize of the http connector, does not take the OS setting as detailed in the documentation:
http://www.dropwizard.io/0.9.2/docs/manual/configuration.html
````
acceptQueueSize	(OS default)	The size of the TCP/IP accept queue for the listening socket.
````
Meaning that the tcp backlog on the socket isn't that of the OS setting (somaxcon).
When you do not specify the `acceptQueueSize` on the `ServerConnector`, Jetty is reverting to the default JDK setting as set in the `java.net.ServerSocket`, example (jdk8 - I check jdk6 has the same default of 50):
````
public ServerSocket(int port, int backlog, InetAddress bindAddr) throws IOException {
setImpl();
if (port < 0 || port > 0xFFFF)
throw new IllegalArgumentException(
"Port value out of range: " + …
```
=> + take the tcp backlog from OS

dropwizard-http2/src/test/java/io/dropwizard/http2/Http2CIntegrationTest.java, dropwizard-http2/src/test/java/io/dropwizard/http2/Http2IntegrationTest.java
It looks like that the latest versions of Jetty fixed the bug which the inability to perform the first call asynchronously. Let's remove the workaround for this bug and keep tests more simple.
=> Remove a first sync call workaround in HTTP2 integration tests

dropwizard-auth/src/main/java/io/dropwizard/auth/oauth/OAuthCredentialAuthFilter.java, dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthProviderTest.java
The OAuth Bearer token spec allows to pass the access token not only in the Authorization header with the Bearer prefix, but also as an access_token query parameter.
See https://tools.ietf.org/html/rfc6750#section-2.3
While it's preferred to use the header for increased security, the
token can be helpful at times.
- biggest advantage is you can avoid CORS pre-flight requests with the query parameter since they are not triggered when no non-simple header is present
- it can be useful when testing/developing where you can simulate requests in a browser tab without a REST client
=> Support access_token query parameter for OAuth

docs/source/manual/hibernate.rst
Add a section in the docs about how to use declarative transactions in authenticators.
It's not really obvious and many users expect they will work out of box.
See #1334, #1361.
=> Document using @UnitOfWork outside Jersey resources

dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java, dropwizard-jetty/src/test/resources/logback-test.xml
I noticed that we don't have a test for building the HTTPS connector in `HttpsConnectionFactory`.
There is a lot of things are going on during this process (building a SSL context factory, logging
supported ciphers, setting metric names, using correct instrumented connectors and so on),
so it makes sense to test it independently from other components. I think it would be great to
have a test which verifies that we correctly configure Jetty on the SSL side.
As a result, this should allow to spot possible bugs earlier during future Jetty updates.
=> Add a test for building the HTTPS connector

dropwizard-hibernate/pom.xml, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/LazyLoadingTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java, dropwizard-hibernate/src/test/resources/hibernate-integration-test.yaml
But close the session during the `FINISHED` stage. This allows to the user to catch errors during commiting transactions (constraint violations, e.g) and map them to HTTP error with
an exception mapper.
This approach also is compatible with lazy loading, because the session remain open during serializing Hibernate entities.
Fix #1604
=> Commit a database transaction in the `RESP_FILTERS_START` stage

dropwizard-core/src/test/java/io/dropwizard/server/SimpleServerFactoryTest.java
(for background, see https://github.com/FasterXML/jackson-databind/issues/1311 on Jackson side)
So: there is a small problem with couple of tests cases, leading to test failures with Jackson 2.8, but not earlier versions, as earlier versions did not check type assignments wrt `defaultImpl` of `@JsonTypeInfo` annotation.
Problem here is that some tests explicitly ask for binding to `SimpleServerFactory` (instead of base type `ServerFactory`); but as per annotations in `ServerFactory`, default implementation is `DefaultServerFactory`. Since `DefaultServerFactory` is NOT a subtype of `SimpleServerFactory` (but only `ServerFactory`), such a request could return an instance of `DefaultServerFactory` and result in a class cast exception. Because of this, Jackson's type handling code throws …
=> Fix a test(-only) problem to work with both Jackson 2.7 and 2.8

dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java, dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
Addresses #1638
The boolean authorization state of principal+role pairs are cached individually using [`ImmutablePair`s](https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/tuple/ImmutablePair.html) internally as cache keys. This unfortunately leads to more allocation-prone `invalidate` methods than those of `CachingAuthenticator`.
I assumed that `CachingAuthorizer` wouldn't be subject to [the negative-result-caching issue](https://github.com/dropwizard/dropwizard/issues/947) that was dealt with in `CachingAuthenticator`. If this is incorrect, then we could instead cache an `ImmutableSet<String>` of role associations for each principal and always pass negative cache results through to the underlying authorizer.
=> dropwizard-auth: Introduce CachingAuthorizer

dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java, dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
Update CachingAuthenticator to use a LoadingCache instead of a Cache,
which will allow multiple concurrent requests to the cache for an
uncached value to only result in one call to the authenticator. The
current behavior to not cache invalid credentials is preserved.
=> Use LoadingCache in CachingAuthenticator.

dropwizard-validation/src/main/java/io/dropwizard/validation/DurationRange.java, dropwizard-validation/src/main/java/io/dropwizard/validation/MaxDuration.java, dropwizard-validation/src/main/java/io/dropwizard/validation/MaxSize.java, dropwizard-validation/src/main/java/io/dropwizard/validation/MinDuration.java, dropwizard-validation/src/main/java/io/dropwizard/validation/MinSize.java, dropwizard-validation/src/main/java/io/dropwizard/validation/OneOf.java, dropwizard-validation/src/main/java/io/dropwizard/validation/PortRange.java, dropwizard-validation/src/main/java/io/dropwizard/validation/SizeRange.java, dropwizard-validation/src/test/java/io/dropwizard/validation/DurationValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/OneOfValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/PortRangeValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/SizeValidatorTest.java
Java 8 allows the following code to be valid:
```java
@Valid
List<@OneOf({"one", "two", "three"}) String> bar;
```
But as the annotations are defined know, they will fail to compile. The
fix is simple, add `TYPE_USE` to the constraint annotation.
=> Allow Dropwizard constraints to be applied to type

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml, dropwizard-client/src/test/java/io/dropwizard/client/ssl/DropwizardSSLConnectionSocketFactoryTest.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/BiDiGzipHandlerTest.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
This PR supersedes #1608:
- By updating to a newer version of Jetty
- Fixing test case on windows due to window paths
- Fixing test failure found in #1608 with new exception comparison. Admittedly, it seems like a worse exception message to test against (`SSLException` vs `SSLHandshakeException`)
=> Update Jetty to 9.3.11.v20160721

dropwizard-bom/pom.xml
Some Dropwizard users may want to use this library with the compile scope as an HTTP/2 client. But currently the BOM forces the test scope, so users are forced to declare the dependency with the compile scope in their projects. This especially not very convenient when the library is pulled as a transitive dependency. An example is https://github.com/arteam/dropwizard-http2-client. See this [discussion](https://github.com/arteam/dropwizard-http2-client/issues/1).
=> Remove the test scope from `jetty-client` in the BOM

dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java
The current proxy implementation makes it hard for DI frameworks to play nice with the `@UnitOfWork` annotation. It is required to have an object, its proxy and wire the two in difficult way. For instance, using Guice, there are several solutions, but none are natural.
This simple change makes `UnitOfWorkAspect` public, but only accessible from a `UnitOfWorkAwareProxyFactory` instance.
This way, DI framework users can implement their own `@UnitOfWork` behavior. This moves the responsibility to the user. Therefore a guide has been written under the form of Javadoc for the `UnitOfWorkAspect` class. It basically says how to properly use the aspect, as intended by the original developer of `UnitOfWorkAwareProxyFactory`.
For instance, my original Guice solution took 300 lines of code, made …
=> Make the aspect easily available to other DI frameworks

dropwizard-core/src/main/java/io/dropwizard/Application.java
Addresses #1658 
This change adds a non-final `Level` getter method within `io.dropwizard.Application` that is used to set the log level during the logging configuration bootstrap process.
Not sure how to add a test for this. Because `BootstrapLogging` doesn't set the root logger's level, AFAICT it's not possible to inspect the log level from within an `Application` subclass.
=> Overridable log level during application bootstrap process

dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java, dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
When the `%i` log format pattern is used with the `maxFileSize` and `archivedFileCount ` properties, the logs are not rotated properly. It appear that the issue was that the triggering policy was not started.
```
-rw-r--r-- 1 dw dw  1368 Aug  1 18:02 dw_server-1.log.gz
-rw-r--r-- 1 dw dw  1807 Aug  1 18:01 dw_server-2.log.gz
-rw-r--r-- 1 dw dw  2151 Aug  1 18:00 dw_server-3.log.gz
-rw-r--r-- 1 dw dw  2170 Aug  1 18:00 dw_server-4.log.gz
-rw-r--r-- 1 dw dw  2149 Aug  1 18:00 dw_server-5.log.gz
-rw-r--r-- 1 dw dw  1384 Aug  1 18:00 dw_server_access-1.log.gz
-rw-r--r-- 1 dw dw  1378 Aug  1 18:00 dw_server_access-2.log.gz
-rw-r--r-- 1 dw dw  1419 Aug  1 18:00 dw_server_access-3.log.gz
-rw-r--r-- 1 dw dw  1403 Aug  1 18:00 dw_server_access-4.log.gz
-rw-r--r-- 1 dw dw  1410 Aug  1 18:00 …
```
=> Support maxFileSize and archivedFileCount

dropwizard-client/src/main/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactory.java, dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java, dropwizard-client/src/test/java/io/dropwizard/client/ssl/DropwizardSSLConnectionSocketFactoryTest.java
While the improvements to TLS configuration of HTTP clients in 1.0.0
(maybe prior) are awesome, as part of that process the ability to set a
custom HostnameVerifier easily on the HTTP client has been lost.
You used to be able to do e.g. as:
JerseyClientConfiguration myJerseyClientConfiguration = <some
configuration>;
HostnameVerifier verifier = new MyCustomHostnameVerifier();
JerseyClientBuilder clientBuilder = new JerseyClientBuilder(env);
clientBuilder.using(myJerseyClientConfiguration).using(verifier);
Client httpClient = clientBuilder.build();
Same is true for HttpClientBuilder too.
You can still do it by creating a custom Apache
Registry<ConnectionSocketFactory> but you need to set up socket
factories for every scheme.
This change restores the ability to set a custom HostnameVerifier …
=> Allow use of custom HostnameVerifier on clients.

dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
This change adds an overridable method which will allow `io.dropwizard.client.HttpClientBuilder` subclasses to customize the underlying `org.apache.http.impl.client.HttpClientBuilder` that is used. For example, this should allow the injection of [HTTP client caching](https://hc.apache.org/httpcomponents-client-ga/tutorial/html/caching.html), as proposed in #1633.
=> Allow HttpClientBuilder subclasses to customize the underlying builder

dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
These two nested if statements within `io.dropwizard.servlets.tasks.TaskServlet` were [flagged by Code Climate](https://codeclimate.com/github/dropwizard/dropwizard/dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java) and can be flattened.
=> dropwizard-servlets: Combine unnecessarily nested if blocks in TaskServlet

dropwizard-jetty/src/main/java/io/dropwizard/jetty/LocalIpFilter.java, dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java, dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/ServerLifecycleListener.java
I've had to do this a few times now in [dropwizard-consul](https://github.com/smoketurner/dropwizard-consul/blob/master/consul-core/src/main/java/com/smoketurner/dropwizard/consul/core/ConsulServiceListener.java#L46) and [dropwizard-discovery](https://github.com/dropwizard/dropwizard-discovery/blob/master/src/main/java/io/dropwizard/discovery/core/CuratorAdvertisementListener.java#L41) and we provide this in [DropwizardTestSupport](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java#L204), so I figured we could add these helper methods to the `ServerLifecycleListener` directly.
=> Add helper functions for getting listening ports and IP addresses

dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java
I'm working on writing a [gRPC](http://www.grpc.io/) `EnvironmentCommand` for running gRPC in Dropwizard and needed the ability to be able to use a `DropwizardAppRule` for testing. 
This pull request adds constructor parameters to `DropwizardAppRule` and `DropwizardTestSupport` so you can specify a `Function` that will instantiate the `EnvironmentCommand` that's run from `DropwizardTestSupport`. `ServerCommand` was used everywhere as a default to maintain backwards compatibility.
=> Refactored DropwizardAppRule support running different EnvironmentCommands

dropwizard-configuration/src/main/java/io/dropwizard/configuration/DefaultConfigurationFactoryFactory.java, dropwizard-configuration/src/main/java/io/dropwizard/configuration/YamlConfigurationFactory.java, dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryFactoryTest.java, dropwizard-configuration/src/test/resources/factory-test-unknown-property.yml
The logic is moved to DefaultConfigurationFactoryFactory from
YamlConfigurationFactory, making it easier to modify with a
custom ConfigurationFactoryFactory implementation.
There are some (uncommon) use cases where it's benefitial to
update an application without modifying the configuration, which
may fail if the application configuration has removed a configuration
property.
=> Set FAIL_ON_UNKNOWN_PROPERTIES in DefaultConfigurationFactoryFactory

dropwizard-client/src/main/java/io/dropwizard/client/DropwizardExecutorProvider.java, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/DropwizardExecutorProviderTest.java, dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
Addresses #1671 & #1679
This change introduces a package-private `ExecutorService` decorator which is used to signal to `DropwizardExecutorProvider` that the executor should be shut down upon its disposal by the Jersey runtime. This enables graceful shutdown of the default `ExecutorService`s created within `JerseyClientBuilder` if the builder isn't configured with one.
Included tests for this graceful shutdown behavior, as well as its absence in the case where a "non-disposable" `ExecutorService` is used.
=> Gracefully shut down default ExecutorService used by JerseyClientBuilder

dropwizard-logging/src/main/java/io/dropwizard/logging/async/AsyncLoggingEventAppenderFactory.java, dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/async/AsyncAccessEventAppenderFactory.java
Addresses #1672 
`i.d.request.logging.async.AsyncAccessEventAppenderFactory` invokes `AccessEvent. prepareForDeferredProcessing`, which triggers a race with an identical invocation [within Logback itself](https://github.com/qos-ch/logback/blob/658963544cc08059fc3cec48f5d35f650de5f6df/logback-core/src/main/java/ch/qos/logback/core/OutputStreamAppender.java#L205). The reported issue indicates that the race manifests in inconsistent logging behavior when request attributes are set within a resource class.
This change removes the `prepareForDeferredProcessing` call from dropwizard-request-logging. As far as I know, all `IAccessEvent`s encountered by this class will be of concrete type `AccessEvent` and all non-async appenders extend `OutputStreamAppender`, so the …
=> Fix request attribute-related race condition in Logback request logging

docs/source/manual/configuration.rst, dropwizard-jetty/src/main/java/io/dropwizard/jetty/GzipHandlerFactory.java
This would resolve #1673 by making sync-flush behaviour of GZipHandler configurable
=> Make GZipHandler sync-flush configurable #1673

dropwizard-jetty/src/main/java/io/dropwizard/jetty/setup/ServletEnvironment.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/setup/ServletEnvironmentTest.java
PR to support adding a collection of static resource folders in `ServletEnvironment`. 
Basically this was done to negate the need for consumers to have a dependency on `jetty-util` library, as they would need to create a `ResourceCollection` if they have multiple resources for serving static content.
=> Add ResourceCollection support ServletEnvironment

docs/source/manual/scala.rst
The `dropwizard-scala` docs currently point at my outdated repo, this PR points them to a modern one and I verified this was OK with the owner here: https://github.com/datasift/dropwizard-scala/issues/9
Alternatively this could be dropped from the docs entirely, up to y'all. :)
=> Update location of dropwizard-scala repository.

dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java
Dropwizard should exit gracefully with a non-zero (`1`) status code in the event that a command throws an `Exception` instead of just exiting the `Application`/JVM. This PR is the result of https://github.com/dropwizard/dropwizard/issues/1680#issuecomment-240132023
=> Catch Throwable and return false if any command errors out

dropwizard-core/src/main/java/io/dropwizard/Application.java
I'm opening this PR to get your thoughts on removing the final modifier from `Application#getConfigurationClass`. My use-case is creating a reusable subclass of `Application` so that we have less boilerplate and duplication in each of our REST APIs (of which we have ~400). I put our subclass in a gist [here](https://gist.github.com/jhaber/136d46c6c795117d5a5c56d035cac434#file-restapplication-java), a usage would look like:
```java
public class Main {
public static void main(String... args) throws Exception {
RestApplication.newBuilder().modules(new MyGuiceModule()).build().run(args);
}
}
```
This works, but only as long as everyone is using the same configuration class. We would like to allow users to subclass our default configuration, which we could do by modifying our subclass to look …
=> Allow overriding of configuration class

dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java, dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
Instead of listing supported cipher suites, protocols, etc of the default
SSLContext algorithm, log what Jetty's will actually use, which as of this
commit is a "TLS" SSLContext. This will also future proof the logging if
this property ever becomes configurable in Dropwizard.
=> Log Jetty initialized SSLContext not the Default

docs/source/manual/core.rst
Based on my edits in https://github.com/eclipse/jetty.project/issues/860, Jetty 9.3.7+ only supports TLS 1.2, which needs to be documented as there are poor souls (myself included) that must cater to Java 6/7 clients, which don't support the default Jetty cipher suites.
Closes #1700
=> Document that only TLSv1.2 is enabled by default

dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java, dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java
From a discussion in https://github.com/dropwizard/dropwizard/issues/1597 there is some want to have the ability to override the showDetails flag when registering the `JsonProcessingExceptionMapper` with jersey. If I just override the existing registered component in my application I receive the following warning log event at application startup which is less than ideal, though also not anything to be concerned about as I am intentionally re-registering this component.
```
{
"@timestamp":"2016-08-23T03:07:17.054+00:00",
"@version": 1,
"message":"The following warnings have been detected: WARNING: Cannot create new registration for component type class io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: Existing previous registration found for the type.\n", …
```
=> Config override for showDetails in JsonProcessingExceptionMapper

dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
Closes #1716
Supersedes #1717
Whether it is a good idea to have a method return `Object` can be left up to discussion, but the code should not throw a NPE.
=> Fix NPE of non-resource sub-resource methods

docs/source/manual/client.rst, dropwizard-client/pom.xml, dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
Jersey allows for clients to have a reactive api if created appropriately:
https://jersey.java.net/documentation/latest/rx-client.html
This functionality for creating an rx-capable client is not currently in
dropwizard, which may lead users down the wrong path. They'll try wrapping
the dropwizard configured client like so (Java8 example):
```java
RxCompletionStage.from(client);
```
This is very bad because this will not use the executor carefully crafted
by dropwizard, but instead use `ForkJoinPool#commonPool`, which is, by
default, created to only have as many threads as there are numbers of CPUs - 1.
The end result is that many requests will end up blocking, the exact
opposite of what a user may think by using this API.
This commit introduces an rx-capable client that wraps the …
=> JerseyClientBuilder can create rx-capable client

appveyor.yml, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/GuavaOptionalDateTimeTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/GuavaOptionalInstantTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/GuavaOptionalLocalDateTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/GuavaOptionalLocalDateTimeTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/GuavaOptionalOffsetDateTimeTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/GuavaOptionalZonedDateTimeTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/OptionalDateTimeTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/OptionalInstantTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/OptionalLocalDateTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/OptionalLocalDateTimeTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/OptionalOffsetDateTimeTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/OptionalZonedDateTimeTest.java
We need a windows ci runner, as many of my commits deal with fixing broken windows builds. These, ideally, should be fixed before a PR is merged. Since I'm most familiar with AppVeyor, I decided to go with them -- it was pretty simple, add `appveyor.yml` file to invoke maven.
Some notes:
- Something was going on with H2 where the same table existed when on setup, so I modified the tests to create the table if not already existing.
- I enabled the CI on my fork, and [this CI run](https://ci.appveyor.com/project/nickbabcock/dropwizard/build/1.0.5) would have caught the #1699 issue before #1678 was merged.
- To test, I reverted mentioned pull request and the [CI does pass](https://ci.appveyor.com/project/nickbabcock/dropwizard/build/1.0.4)
We'll have to add AppVeyor as a trusted integration, …
=> Add Windows CI via AppVeyor

dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/SizeParam.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/SizeParamTest.java
Duration param was created in #1734, so it's brother (`Size`) should have a param class too
=> Add SizeParam as a request parameter

dropwizard-client/src/test/java/io/dropwizard/client/ssl/DropwizardSSLConnectionSocketFactoryTest.java, dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java, dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/ResourceURLTest.java
The current usage of `fail()` in tests can't beat the messages produced by assertj's built in exception assertions. It also can't beat the conciseness 😄 
The next step may be to examine if we want to replace `failBecauseExceptionWasNotThrown` with exception assertions
=> Prefer use of assertj's java8 exception assertions

dropwizard-bom/pom.xml, dropwizard-configuration/src/test/java/io/dropwizard/configuration/ConfigurationFactoryTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProviderTest.java
Based on joschi's work in #1647
- Rebased on current master
- Bump to latest 2.8 (2.8.3)
- Maintain compatibility with how we treat errors resulting from JSON input being the wrong type. They should be treated as client errors, not server errors. The current heuristics were not sufficient enough for Jackson 2.8, so another heuristic was added via a straightforward regex.
Can squash/rebase on request.
Can update release notes on merge.
=> Jackson 2.8 Redux

docs/source/manual/configuration.rst
The old description was misleading. One could think `false` meant no self-signed certs could be trusted.
=> Edit trustSelfSignedCertificates description

dropwizard-client/src/test/resources/yaml/jerseyIgnoreRequestUserAgentHeaderFilterTest.yml, dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleWithoutConfigTest.java
This way I can have a default dropwizard app I'm testing and still run all of dropwizard's tests.
=> Avoid needlessly binding 8080 and 8081 in tests

dropwizard-bom/pom.xml
[Based on the forums](https://groups.google.com/forum/#!msg/mustachejava/84_oxOao8hM/0d4PW1L7AgAJ) closes #1696
I think this PR should be considered for 1.0.3 (0.9.2 -> 0.9.4), if that's available.
=> Update to mustache.java 0.9.4

dropwizard-jetty/src/test/java/io/dropwizard/jetty/BiDiGzipHandlerTest.java
The four tests in `BiDiGzipHandlerTest` took at least 10 seconds each. By closing the connection after use, the tests are much much faster. Each test is about ~50ms now.
See related [stackoverflow](http://stackoverflow.com/questions/20428371/why-is-servlettester-in-jetty-9-x-so-slow)
=> Speed up servlet tester tests by closing connection

docs/source/manual/client.rst
This contract with [HttpClientBuilder$build](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java#L220-L226) is the following:
```
public CloseableHttpClient build(String name);
```
=> correct sample code on building apache http client

docs/source/manual/core.rst, docs/source/manual/validation.rst, dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java, dropwizard-core/src/main/java/io/dropwizard/setup/ExceptionMapperBinder.java, dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java, dropwizard-core/src/test/java/io/dropwizard/server/SimpleServerFactoryTest.java, dropwizard-core/src/test/java/io/dropwizard/setup/ExceptionMapperBinderTest.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardTestResourceConfig.java
Currently when a user wants to override one of the default exception mappers they must specify `registerDefaultExceptionMappers: false` in their configuration, register their exception mapper, and then re-register all the other default exception mappers they want. This is not user friendly. A user should be able to register their own exception mapper, override the default exception mapper while preserving other default exception mappers.
It should be possible to achieve this behavior as alluded to in [JERSEY-2722](https://java.net/jira/browse/JERSEY-2722)
> your own ExceptionMapper<ValidationException> should always have a higher priority than anything provided by Jersey
and alluded in [Jersey's Bean Validation code](https://github.com/jersey/jersey/blob/1a7919181d8a1f550c7fc20898db67fe9da …
=> Bind default exception mappers

dropwizard-configuration/src/main/java/io/dropwizard/configuration/YamlConfigurationFactory.java, dropwizard-jackson/src/main/java/io/dropwizard/jackson/FuzzyEnumModule.java
There remains a couple more deprecations in the yaml package where Jackson's `MarkedYAMLException` and `Mark` have been deprecated in favor of the underlying snakeyaml implementation (see https://github.com/FasterXML/jackson-dataformat-yaml/issues/63), but Jackson still throws the deprecated exceptions. Hence not all deprecations have been removed as they are still needed.
cc @cowtowncoder
=> Fixup Jackson 2.8 deprecations

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml
This PR also includes the (unofficial) Jackson BOM so that users can include Jackson dependencies in the correct version into their projects.
=> Upgrade to Jackson 2.8.4

docs/source/manual/auth.rst, docs/source/manual/testing.rst, docs/source/manual/validation.rst, dropwizard-example/src/test/java/com/example/helloworld/resources/PeopleResourceTest.java, dropwizard-example/src/test/java/com/example/helloworld/resources/PersonResourceTest.java, dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedClassResourceTest.java, dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedResourceTest.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceExceptionMapperTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResourceTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestWithGrizzly.java
Depending on the web test container passed to
`ResourceTestRule#setTestContainerFactory`, one would either invoke
`client()` or `getJerseyTest()`, which is inconvenient. The fix is to
standardize on a new method that can be used regardless of web test
container that also doesn't infringe on the law of Demeter (as the other
solution would be to rewrite all usage as using `getJerseyTest()`)
=> Add web test container agnostic client target

docs/source/manual/forms.rst
Takes @psamsotha [comment](https://github.com/dropwizard/dropwizard/issues/1496#issuecomment-202352516) and adds it to the documentation as it failed my litmus test of a dropwizard feature that has testing documented 😋 
Docs will slightly change once #1778 is merged (use `target` instead of `client`), so feel free to merge in any order and I can make the appropriate change.
=> Add example of multipart forms test

dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProvider.java
The previous workaround rendered useless by the changes in Jackson 2.8.3. 🎉
=> Remove dead code in the jackson provider

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml, dropwizard-validation/src/test/java/io/dropwizard/validation/DurationValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/OneOfValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/PortRangeValidatorTest.java, dropwizard-validation/src/test/java/io/dropwizard/validation/SizeValidatorTest.java
Only changes were related to validation annotations on types (#1586). Seems like the validation message was updated. Looks to be a step backwards, but it is as [documented](https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#type-arguments-constraints) 😋
=> Hibernate validator 5.3.0

dropwizard-core/src/main/java/io/dropwizard/setup/ExceptionMapperBinder.java, dropwizard-e2e/pom.xml, dropwizard-e2e/src/main/java/com/example/app1/App1.java, dropwizard-e2e/src/main/java/com/example/app1/App1Resource.java, dropwizard-e2e/src/test/java/com/example/app1/App1Test.java, dropwizard-e2e/src/test/resources/app1/config.yml, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/guava/OptionalMessageBodyWriter.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/EmptyOptionalException.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/EmptyOptionalExceptionMapper.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalDoubleMessageBodyWriter.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalIntMessageBodyWriter.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalLongMessageBodyWriter.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalMessageBodyWriter.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalDoubleMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalIntMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalLongMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalMessageBodyWriterTest.java, pom.xml
Another implementation of #1732, but using exceptionmappers, which now have a lower code tax due to #1768. By default, backwards compatibility is preserved with the ability to easily remap it to a 204.
The shape of the custom exception (`EmptyOptionalException`) inspired by netty's [ReadTimeoutException](https://github.com/netty/netty/blob/cfa5b85075f9f3a74e7eb46e344f44775dbcea57/handler/src/main/java/io/netty/handler/timeout/ReadTimeoutException.java) to be a lightweight exception, as 204's may be a normal state and shouldn't be treated exceptionally.
Maybe controversial, but I've decided to add another submodule, dropwizard-e2e (end-to-end). It's like dropwizard-example except that it is meant to hold multiple `Applications`, as it's possible that a single example application can't …
=> Empty optional exception mapper

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml
The [release notes are pretty small](https://github.com/eclipse/jetty.project/blob/206122756f8988cf9e5abf4a4b4da83a3a562e07/VERSION.txt#L3-L22), but contain an important snippet:
> Support certificates hot reload
Which'll set the ground for better integration with Let's Encrypt (for instance), for those eschewing tls termination proxies.
Just wanted to point it out, as, in the future, I may be tinkering with it a bit 😄
=> Bump jetty

dropwizard-http2/pom.xml
Taken from [jetty's pom](https://github.com/eclipse/jetty.project/blob/338e924a5d8f0ce8589a788a85cdc53b20f92030/pom.xml#L1185)
=> Use correct alpn-boot for jdk8_u112

docs/source/manual/configuration.rst, dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java, dropwizard-jetty/src/test/resources/yaml/http-connector.yml
The issue reported in #1794.
Jetty 9.3.2.v20150730 introduced a new option for the configuration of HTTP connection factories. The option is called `blockingTimeout` and allows to configure the timeout which applies to all blocking operations in addition to `idleTimeout`. The rationale behind it is to allow to set a timeout
for blocking operations which perform I/O activity, but with a slow rate (for example serving a big static file). Such tasks won't exhaust the pool of worker threads which should improve the QoS for a Jetty server.
See:
https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00085.html
https://bugs.eclipse.org/bugs/show_bug.cgi?id=472621
=> Add support for configuring the blocking timeout for Jetty connectors

dropwizard-http2/pom.xml
When intellij jdk version does not match the sdk version used for a project, causes an alpn boot version mismatch (only when running tests manually in intellij). Instead, use the `java.version` property to determine alpn version like how [jetty does it](https://github.com/eclipse/jetty.project/blob/f3f31d163c4f04d5c8f1bc2e4ae38f8c88583e77/pom.xml#L912-L1189) 😋 
I've verified this works by running the http2 tests in intellij and seeing them complete without exception.
=> Use the java version to determine alpn boot version

dropwizard-bom/pom.xml
Update DropWizard 1.0.x to the latest patch release of Jersey 2.23 in
order to pick up HK2 fixes from HK2 2.5.
Fixes #1807.
=> Update DropWizard 1.0.x to Jersey 2.23.2.

dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/MustacheViewRenderer.java, dropwizard-views-mustache/src/test/java/io/dropwizard/views/mustache/MustacheViewRendererTest.java
A follow-up for #1814.
* Add a couple of unit tests to preserve coverage;
* Fix checkstyle warnings
=> Polish disabling caching for Mustache view renderer

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml
Release notes: https://github.com/google/guava/wiki/Release20
=> Upgrade Guava to 20.0

docs/source/about/release-notes.rst, docs/source/manual/configuration.rst, dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/old/DropwizardSlf4jRequestLog.java, dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/old/LogbackClassicRequestLogFactory.java, dropwizard-request-logging/src/main/resources/META-INF.services/io.dropwizard.request.logging.RequestLogFactory, dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/old/DropwizardSlf4jRequestLogTest.java, dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/old/LogbackClassicRequestLogFactoryTest.java, dropwizard-request-logging/src/test/resources/yaml/logbackClassicRequestLog.yml
Several users reported that they have issues with the logback-access implementation.
See #1801, #1812, #1737. It would be great to allow these users to continue to use `logback-classic`,
while they can't move their appenders to `logback-access`.
=> Bring back request logging with logback-classic

dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java, dropwizard-jetty/src/test/resources/yaml/http-connector.yml
Here's my shot at implementing the change discussed in issue 1824:
https://github.com/dropwizard/dropwizard/issues/1824
=> Added httpCompliance to the HttpConnectorFactory

docs/source/about/release-notes.rst, dropwizard-util/src/main/java/io/dropwizard/util/Duration.java, dropwizard-util/src/test/java/io/dropwizard/util/DurationTest.java
Fancy title for adding `min` and `mins` abbreviations for minute to `Duration`
[The IEEE table of abbreviations](http://www.ewh.ieee.org/soc/ias/pub-dept/abbreviation.pdf) for you viewing pleasure 📚
=> Add IEEE Minute Abbreviation to Duration

dropwizard-e2e/pom.xml, dropwizard-e2e/src/main/java/com/example/app1/App1.java, dropwizard-e2e/src/main/java/com/example/app1/App1Resource.java, dropwizard-e2e/src/test/java/com/example/app1/App1Test.java, dropwizard-views-freemarker/src/main/java/io/dropwizard/views/freemarker/FreemarkerViewRenderer.java, dropwizard-views-freemarker/src/test/java/io/dropwizard/views/freemarker/FreemarkerViewRendererTest.java, dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/MustacheViewRenderer.java, dropwizard-views-mustache/src/test/java/io/dropwizard/views/mustache/MustacheViewRendererTest.java, dropwizard-views/src/main/java/io/dropwizard/views/ViewMessageBodyWriter.java, dropwizard-views/src/main/java/io/dropwizard/views/ViewRenderException.java, dropwizard-views/src/main/java/io/dropwizard/views/ViewRenderExceptionMapper.java
This PR is one possible implementation of issue #1811. In short, I am standardizing the exception thrown by each `ViewRenderer` implementation as `ViewRenderException`, which is then caught and rethrown as `WebApplicationException` by `ViewMessageBodyWriter`.
To preserve previous behavior of returning an HTML error response on render exceptions, I have added a new `ViewRenderExceptionMapper` class which should be registered. Consequently I am still changing the original behavior by adding this registration requirement. Let me know if this is OK from backward-compatibility standpoint - if needed we can register the mapper in `ViewBundle`, although I don't know how I can register another exception mapper afterwards if I want custom behaviour. This also requires change to the documentation. …
=> Finer-grain control of exception behaviour in view renderers

dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/layout/LogbackAccessRequestLayout.java, dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/layout/SafeRequestParameterConverter.java, dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/layout/SafeRequestParameterConverterTest.java
Add a safe version of `RequestParameterConverter` which works with async appenders.
It loads request parameters from a cached map rather than trying to load request data
from the original request, which may be closed during the time of a call.  The map is
cached by the  `prepareForDefferedProcessing` method, which invokes before invoking
appenders, so in theory the call to the map should be safe.
As a result, Dropwizard users can use `%reqParameter{something}` in their request
logging patterns.
References #1827, #1672, #1686.
=> Fix request logs with request parameter in layout pattern

dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilderTest.java, dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DAOTestRule.java, dropwizard-util/src/main/java/io/dropwizard/util/Enums.java
Fixes the deprecations introduced in the Guava 20.0 update.
Most of the `propagate` can be converted to a `throw new RuntimeException`. The one instance where `throwIfUnchecked` functionality is kept is in `DAOTestRule` due mainly to a test that is written an older junit style that only looks at the shallowest exception and not the root cause.
=> Fix guava deprecations with 20.0 update

dropwizard-e2e/src/test/java/com/example/request_log/AbstractRequestLogPatternIntegrationTest.java, dropwizard-e2e/src/test/java/com/example/request_log/CustomRequestLogPatternIntegrationTest.java, dropwizard-e2e/src/test/java/com/example/request_log/RequestLogPatternIntegrationTest.java, dropwizard-e2e/src/test/resources/request_log/test-custom-request-log.yml
We recently had several reports about issues with request logging. It would be great to have some integration tests which verify that Dropwizard produces correct request logs. This should allow to us
to catch errors with it more early and not let our users down.
=> Add  integration tests for request logs

dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java, dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java, dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java, dropwizard-e2e/src/main/java/com/example/app1/App1.java, dropwizard-e2e/src/main/java/com/example/app1/App1Resource.java, dropwizard-e2e/src/main/java/com/example/app1/CustomClass.java, dropwizard-e2e/src/main/java/com/example/app1/CustomClassBodyWriter.java, dropwizard-e2e/src/main/java/com/example/app1/CustomJsonProvider.java, dropwizard-e2e/src/test/java/com/example/app1/App1Test.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JacksonBinder.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardTestResourceConfig.java
I wondered if I could create a custom JsonProvider where I could read and write a special payload at the top the body (don't ask why, it's just a thought experiment):
``` json
/* I'm a special header */
{
"check": "mate"
}
```
This PR allows a user configured `JacksonJaxbJsonProvider` or another appropriate class to take priority over the dropwizard configured class (`JacksonMessageBodyProvider`).
I believe this PR closes #1005
@jplock I used App1 in dropwizard-e2e, not sure if it is too early to call it a theme, but so far it is about overriding defaults 😋
=> Allow user to override configured JsonProvider

dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/MustacheViewRenderer.java, dropwizard-views-mustache/src/test/java/io/dropwizard/views/mustache/MustacheViewRendererFileSystemTest.java, dropwizard-views-mustache/src/test/java/io/dropwizard/views/mustache/MustacheViewRendererTest.java
This PR is for adding the ability to load Mustache templates from the file system instead of from the classpath.
To use this feature, add the new, Mustache-specific config option called `fileRoot` pointing to the directory in the file system where Mustache templates should be loaded. When specified, a `FileSystemResolver` will be used instead of `PerClassSystemResolver`. When combined with the new cache options from #1289 , you can update Mustache templates in the file system and Dropwizard will pick up the changes w/o restarting the application.
From implementation point of view, please see whether there is a better way to handle the tests. AFAIK each `JerseyTest` class can only configure the server once normally, so I cheated and added an instance variable to store the …
=> Enable option to load Mustache templates from file system

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml, dropwizard-example/pom.xml, pom.xml
This also simplifies the `dropwizard-bom` by just relying on the `jackson-bom` and `jersey-bom`.  All of the tests still pass and the example application is properly packaged without having to maintain all of the individual dependencies in the bom pom.xml.
(the preferred `jackson-bom` version to use is `2.8.5.1` per https://twitter.com/fasterxml/status/801240492000231424)
=> Update to Jackson 2.8.5

dropwizard-e2e/pom.xml, dropwizard-e2e/src/main/java/com/example/forms/FormsApp.java, dropwizard-e2e/src/main/java/com/example/forms/FormsResource.java, dropwizard-e2e/src/test/java/com/example/forms/FormsAppTest.java
There were no examples of using dropwizard-forms, so I decided to add it as a module to `e2e` as an example so that it is easier to point people to (maybe even a link from the documentation !?)
=> Add Dropwizard forms e2e

dropwizard-example/pom.xml, dropwizard-testing/pom.xml
Mockito is being exposed as a compile dependency to dependents of dropwizard, which may force them to upgrade to Mockito 2 before they are ready.
=> Mockito should be a test dependency

docs/source/manual/configuration.rst, dropwizard-client/src/test/resources/yaml/ssl_connection_socket_factory_test.yml, dropwizard-e2e/src/test/resources/sslreload/config.yml, dropwizard-example/example.yml, dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
If any either of these two options are enabled, a HTTPs enabled Dropwizard
app will most likely fail to start with cryptic error messages. Since
Jetty has these options disabled by default, we should follow their lead
and disable these options as well.
Future work includes adding in additional certificate features as
Certificate Revocation List (CRL),  CRL Distribution Points Protocol
(CRLDP), On-Line Certificate Status Protocol (OCSP)
This may be considered a bugfix and is a candidate for either 1.0.x or 1.1
=> Switch cert and peer validation to false by default

docs/source/manual/configuration.rst, docs/source/manual/core.rst, dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
Addresses #1853
This change updates the user manual and the Javadoc of `io.dropwizard.jetty.HttpsConnectorFactory` to call out the fact that the lists of supported and excluded protocols and cipher suites are inherited from the JVM and Jetty. Specifically, the supported lists fall back to JVM defaults and the excluded lists to defaults [hardcoded in Jetty](https://github.com/eclipse/jetty.project/blob/14611d2f76be9ebd955bff6cdd38fde4a008a4c3/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L202-L203).
Note that this change replaces the values of `supportedProtocols` and `supportedCipherSuites` documented in the user manual. Based on my reading of the Jetty code linked above (at the version currently used in Dropwizard, 9.3.14.v20161028), SSLv3 is explicitly …
=> Document SSL protocol/cipher suite defaults inherited from the JVM and Jetty

docs/source/manual/configuration.rst
Adding the queueSize and discardingThreshold logging configuration options to the documentation. This is related to https://github.com/dropwizard/dropwizard/issues/1856
=> Add logging configuration options to documentation

docs/source/manual/configuration.rst
Adding the queueSize and discardingThreshold logging configuration options to the documentation.  This is related to https://github.com/dropwizard/dropwizard/issues/1856.
A formatting issue in https://github.com/dropwizard/dropwizard/pull/1858 caused the table to disappear and I realized I had forgotten to include the config options in the example. This is fixed with this PR.
=> Include logging options in config

dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java
Currently, most 500s from Dropwizard internal exceptions return as application/json, with a nice logging ID, courtesy of `LoggingExceptionMapper`. This is a pleasant default.
However, `JsonProcessingException`s that have been determined to be server-side issues are still returning as the default Jersey HTML format, which is less pleasant.
This PR causes server-side JsonProcessingException 500s to return as application/json. It re-uses the `LoggingExceptionMapper` code and returns in the exact same format as other internal exceptions.
Feedback welcomed.
=> ensuring that server-side JsonProcessingExceptions return JSON, consistent with other 500 errors

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml
Unfortunately, the tomcat-jdbc project doesn't provide own release notes, but
you can find the changelog for the Tomcat project here: (you can see the `tomcat-jdbc` section):
https://tomcat.apache.org/tomcat-8.0-doc/changelog.html. The list of commits here:
https://github.com/apache/tomcat/commits/trunk/modules/jdbc-pool
The biggest feature which  is an additional statistic for the connection pool plus
some bugfixes for handling various timeouts.
=> Upgrade tomcat-jdbc to 8.5.9

dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/CustomDeserialization.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/CustomRepresentation.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonResource.java
If someone defines a custom jackson deserializer, throws a custom `JacksonMappingException`, and overrides `getMessage()` to return `null`, `JsonProcessingExceptionMapper` will have a NPE as reported in #1869. If someone creates such a devious deserializer, it should be treated as a server error, hence a 500 status code is returned.
Closes #1869
thanks @kjetilv
cc @cowtowncoder so that he is aware of this edge case. Not 100% what the behavior of 2.9 will/should be in this situation, but I figured I'd give you a heads up in case this changes anything.
=> Protect against NPE from rogue deserializers

dropwizard-benchmarks/pom.xml, dropwizard-e2e/pom.xml
This change set properly integrates the `dropwizard-e2e` into the Maven build and gets rid of the Maven warning:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.dropwizard:dropwizard-e2e:jar:1.1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ line 64, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```
=> Properly integrate dropwizard-e2e into Maven build

circle.yml, dropwizard-e2e/src/test/java/com/example/forms/FormsAppTest.java, dropwizard-e2e/src/test/java/com/example/request_log/AbstractRequestLogPatternIntegrationTest.java
Add support for running tests on CircleCI. The idea is too have an additional CI sever for running tests on the Linux environment, because in recent times we have had some issues with Travis CI.
The reason for that is PR #1875. Currently we have a CircleCI integration set up for the Dropwizard repository, but without a `circle.yml` config file all other pull requests fail. So I would like to merge it to master, so #1875 doesn't block other pull requests, but still allows to run tests in TravisCI and CircleCI.
=> Evaluate CircleCI

dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java
Ran into a situation where I want to be able to do some configuration sessions that are set up by the `UnitOfWorkAwareProxyFactory`. Specifically, in our app I wanted to set up a bunch of default hibernate filters that should be turned on for every session. 
In our resource methods that use `UnitOfWork`, we do that by implementing Jersey event listeners with lower priority than the UnitOfWork listener. I wanted to do something similar and poke some configuration in between the session being set up, and my code actually running.
With the current state of things (using 1.0.5) that required us to rewrite our own version of `UnitOfWorkAwareProxyFactory`. Additionally, because `UnitOfWorkAspect` is still package private in the latest release, we also had to copy and create our own version of …
=> Add configuration hooks to UnitOfWorkAwareProxyFactory

.travis.yml, dropwizard-http2/pom.xml, dropwizard-jersey/src/test/java/io/dropwizard/jersey/AbstractJerseyTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/AsyncServletTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/JerseyContentTypeTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/caching/CacheControlledResponseFeatureTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/LoggingExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/filter/AllowedMethodsFilterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalCookieParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalFormParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalHeaderParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/guava/OptionalQueryParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalCookieParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalDoubleMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalFormParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalHeaderParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalIntMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalLongMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalMessageBodyWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalQueryParamResourceTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/NonEmptyStringParamProviderTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/sessions/FlashFactoryTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/sessions/HttpSessionFactoryTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
Recently, the tests for Jersey resources were rather flaky and failed on Travis CI. Unfortunately, we can't get any debug information about it, because they the test suite is killed by the CI environment because it becomes unresponsive. It would be great to have timeouts for each tests, so even in case we have errors, the whole test suite won't fail.
This is achieved by introducing a new class `AbstractJerseyTest` which contains common features of the all tests for Jersey resources. Now the tests are inherited from it and perform HTTP requests with timeouts.
=> Add timeouts for the all tests in the `dropwizard-jersey`module

docs/source/manual/testing.rst, dropwizard-example/src/test/java/com/example/helloworld/IntegrationTest.java, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/app/GzipDefaultVaryBehaviourTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleConfigOverrideTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleWithExplicitTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleWithoutConfigTest.java
A common use case for the users of `DropwizardAppRule` is creating an HTTP client which performs requests against the tested server. I think we could make it little bit easier by providing a method for `DropwizardAppRule`which creates a new Jersey HTTP client client managed by the rule. The user
doesn't need to care about creating own client and shutting it down. The created is also have default sane timeouts in contrary to the default Jersey client. In the end, this allows to write tests like that:
```java
RULE.client().target("http://localhost:" + RULE.getLocalPort() + "/hello-world")
.queryParam("name", name.get())
.request()
.get(Saying.class);
```
It makes testing easy for users who don't use the `dropwizard-client` module or find it excessive for testing.
=> Add support for HTTP client managed by DropwizardAppRule

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml
See changelog here: https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.1.v20170120
=> Upgrade Jetty to 9.4.1.v20170120

docs/source/manual/testing.rst, dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOTest.java, dropwizard-testing/pom.xml, dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DAOTestRule.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleConfigTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleTest.java, dropwizard-testing/src/test/java/io/dropwizard/testing/junit/TestEntity.java
Backport of `DAOTestRule` (#1669).
Closes #1904
=> DAOTestRule backport

dropwizard-jackson/pom.xml, dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java, dropwizard-jackson/src/test/java/io/dropwizard/jackson/ParanamerModuleTest.java, dropwizard-jackson/src/test/java/io/dropwizard/jackson/Person.java
Closes #1852
Addresses @arteam's concern about users who don't compile with `-parameters`, as only the `dropwizard-jackson` test module is compiled with `-parameters` and the other modules don't fail.
=> Register Jackson parameter names module

dropwizard-jackson/src/main/java/io/dropwizard/jackson/FuzzyEnumModule.java, dropwizard-jackson/src/test/java/io/dropwizard/jackson/FuzzyEnumModuleTest.java
Closes #1888
Returning a `null` JsonDeserializer will make Jackson look elsewhere, which is preferable in all cases when we shouldn't or can't handle the deserialization.
=> Enable deeper jackson deserialization of enums

dropwizard-example/README.md
This small addition should reduce the confusion that caused the following issues: https://github.com/dropwizard/dropwizard/issues/1760, https://github.com/dropwizard/dropwizard/issues/1510
=> added run from root directory for maven command in example readme

docs/source/about/release-notes.rst, dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/LoggingExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/LoggingExceptionMapperTest.java
Closes #1866
Technically, the code doesn't need to try and detect for redirection (introduced in #1452) as the `Location` header gets through now (and all tests would pass), but I didn't remove it because redirect responses would contain a JSON payload, which some people may or may not like.
=> Default WebExceptionMapper preserves exception HTTP headers

docs/source/manual/testing.rst
The factories were removed when we moved to filter based auth.
=> Remove references to old auth code in docs

dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
I keep running into compiler bugs using the given archetype compiler version, and
I have to keep remembering to update to a new version.
=> Bump archetype maven compiler plugin

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/AbstractDAO.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryHealthCheck.java, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/DataExceptionMapper.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/JerseyIntegrationTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/LazyLoadingTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/PersistenceExceptionMapper.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryFactoryTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryHealthCheckTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java
- fix deprecation notices where type isn't exposed on DW public API (AbstractDAO API doesn't change)
- upgrade Jadira usertypes to compatible version
- Hibernate removes hibernate-entitymanager with 5.2 and merges JPA support into core
- one side effect of this is wrapping previous SQL exceptions in a PersistenceException, tests needed an additional ExceptionMapper to pass
=> Upgrade to Hibernate 5.2

dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/AbstractDAO.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java
I've been migrating our codebase to 1.1 and this popped up to be one missing thing from my previous PR:
Since the old Query object is now deprecated, this helper eases migration to the new structure.
Quick follow up to #1871 
Code before:
```java
Query<E> query = currentSession().createQuery(hql, getEntityClass());
```
Code after:
```java
Query<E> query = query(hibernateQuery);
```
btw for our pretty large app the migration has been fairly smooth, `HashLoginService` changed in Jetty, the Hibernate upgrade needs a few things here and there, and Liquibase now forces a default schema, otherwise it seems much much easier than 0.9 -> 1.0
=> Convencience AbstractDAO method for Query<T>

docs/source/getting-started.rst
When reading the getting started guidance on my first ever exposure to DropWizard, I was confused about where the YML file was supposed to go. At first I put it in the src/main/resources directory expecting the far jar execution to pick it up when I named it on the command line execution arguments. This tiny pull request seeks to clarify that the YML file can be saved anywhere and referenced later.
=> improves getting started doc by explaining where to save yml file

docs/source/manual/auth.rst, dropwizard-auth/src/main/java/io/dropwizard/auth/AuthDynamicFeature.java, dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java, dropwizard-auth/src/main/java/io/dropwizard/auth/AuthValueFactoryProvider.java, dropwizard-auth/src/main/java/io/dropwizard/auth/OptionalPrincipalContainerRequestValueFactory.java, dropwizard-auth/src/main/java/io/dropwizard/auth/PolymorphicAuthDynamicFeature.java, dropwizard-auth/src/main/java/io/dropwizard/auth/PolymorphicAuthValueFactoryProvider.java, dropwizard-auth/src/main/java/io/dropwizard/auth/WebApplicationExceptionCatchingFilter.java, dropwizard-auth/src/test/java/io/dropwizard/auth/AuthBaseTest.java, dropwizard-auth/src/test/java/io/dropwizard/auth/AuthResource.java, dropwizard-auth/src/test/java/io/dropwizard/auth/principal/PolymorphicPrincipalEntityResource.java, dropwizard-auth/src/test/java/io/dropwizard/auth/principal/PolymorphicPrincipalEntityTest.java
The current support for optionally-protected resources isn't great. We require users to implement a custom auth filter to inject a dummy `SecurityContext` for unauth'd requests.
I had occasion to write such an endpoint at work and decided to take a stab at supporting `Optional` principals with the `@Auth` annotation. With this patch, I'm able to do things like this:
```
@GET
public String getGreeting(@Auth Optional<User> userOpt) {
if (userOpt.isPresent()) {
return "Hello, " + userOpt.get().getName() + "!";
} else {
return "Greetings, anonymous visitor!"
}
}
```
This change breaks down into two steps:
1. A new `ContainerRequestFilter` decorator is used to silence exceptions thrown by failed `AuthFilter` invocations. This results in every request succeeding and principals being injected …
=> dropwizard-auth: Add support for optional resource protection

dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java, dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
Tasks are logged on startup but aren't easily accessible otherwise. Implement `TaskServlet::doGet` to print tasks lexically by name.
Example:
```
$ curl http://localhost:8081/tasks
echo
gc
log-level
```
TaskServlet is mapped on "/tasks/*" and any GET request not matching root 
will yield 404 or 405.
404: Task name is unknown.  
405: Task name is registered but must be invoked with POST.
=> Implement TaskServlet::doGet to list tasks lexically.

dropwizard-e2e/src/main/java/com/example/badlog/BadLogApp.java, dropwizard-e2e/src/test/java/com/example/badlog/BadLogTest.java, dropwizard-e2e/src/test/resources/badlog/config.yaml, dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java, dropwizard-logging/src/main/java/io/dropwizard/logging/LoggingFactory.java, dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
This PR fixes the issue where dropwizard would close all logging appenders in tests and in code when it's reasonable for there to be more log statements (eg. in case of an exception)! The fix is instead of closing all appenders, wait for them to flush all their log messages (which, as far as I can tell, was the original impetus for closing the `LoggerContext` on application shutdown, anyways)
In tests, the logging is reset to a sane default (I've chosen the default console appender as a default), so that users may still see the output of logging statements in their tests code (outside application code).
1. It's probably prudent to not merge this for 1.1.0 as logging is finicky, even though I've included a decently thorough test case (there's an API change to `LoggingFactory` 😞 to …
=> Flush loggers on cleanup, don't destroy

dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource2.java, dropwizard-jersey/src/test/java/io/dropwizard/other/RestInterface.java
A test to ensure that we don't regress on our validation messages for resources which have all their annotations on their implemented interface. Reference: #1932
=> Add test for javax.ws.rs annotations in interfaces

docs/source/manual/configuration.rst, dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java, dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java, dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java, dropwizard-logging/src/test/resources/yaml/logging_advanced.yml
Update FileAppenderFactory to support configuration of the
FileAppender#bufferSize setting. Introduced in logback 1.1.10, this
setting is reported to reduce thread contention in logging performance
tests.
=> Support configuring FileAppender#bufferSize.

dropwizard-jersey/src/main/java/io/dropwizard/jersey/filter/CharsetFilter.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/filter/CharsetUtf8Filter.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/filter/RequestIdFilter.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/filter/RuntimeFilter.java
* `X-Request-Id` filter is based upon https://devcenter.heroku.com/articles/http-request-id
* `X-Runtime` filter is based upon https://github.com/rack/rack/blob/master/lib/rack/runtime.rb
These are not registered by default.  They are merely provide for convenience if people want to opt-in to using them.
=> Add some commonly used and useful jersey request/response filters

dropwizard-e2e/src/main/java/com/example/badlog/BadLogApp.java, dropwizard-e2e/src/test/java/com/example/badlog/BadLogTest.java, dropwizard-e2e/src/test/resources/badlog/config.yaml, dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java, dropwizard-logging/src/main/java/io/dropwizard/logging/LoggingFactory.java, dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
(cherry picked from commit 6c76c27c0cf637073dc7a72ae63a97dc5ff9b78f)
Refs #1947
=> Flush loggers on cleanup, don't destroy (back-port for Dropwizard 1.1.0)

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml
Release notes:
http://metrics.dropwizard.io/3.2.1/about/release-notes.html#v3-2-1-mar-10-2017
=> Upgrade Dropwizard Metrics to 3.2.1

docs/source/about/release-notes.rst, docs/source/manual/configuration.rst, dropwizard-metrics-ganglia/src/main/java/io/dropwizard/metrics/ganglia/GangliaReporterFactory.java, dropwizard-metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteReporterFactory.java, dropwizard-metrics/src/main/java/io/dropwizard/metrics/BaseReporterFactory.java, dropwizard-metrics/src/test/java/io/dropwizard/metrics/MetricAttributesTest.java, dropwizard-metrics/src/test/java/io/dropwizard/metrics/MetricsFactoryTest.java, dropwizard-metrics/src/test/resources/yaml/metrics.yml
Metrics 3.2.* allows to configure the set of attributes which can be disabled for a reporter. It would be nice to provide the ability to set them via the YAML config the same way we provide that for
metric names.
=> Support disabled and enabled attributes for metrics

docs/source/about/release-notes.rst, dropwizard-hibernate/pom.xml, dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SubResourcesTest.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java, dropwizard-hibernate/src/test/resources/hibernate-sub-resource-test.yaml
Currently Dropwizard doesn't open transactions in sub-resources as reported in #1806. The problem is that Dropwizard scans resource methods for `@UnitOfWork` during resource initialization and sub-resource methods are not resolved at that time and can't be registered by Dropwizard. The fix is
to defer the lookup of the `@UnitOfWork` annotation on a method until it's invoked and than cache it. One downside of this approache is that `ConcurrentMap` doesn't support null values, so we have to use `Optional` from `UnitOfWork` which can add an additional overhead, but it should be negligible.
=> Support `@UnitOfWork` in sub-resources

pom.xml
Since Dropwizard is using Java 8 as a baseline, it's not necessary to "hide" disabling the Javadoc linter in a profile (`java8-disable-strict-javadoc`).
Additionally, this change enables users of Gradle to use the Dropwizard BOM with the [Nebula Dependency Recommender plugin](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin).
**build.gradle**
```
plugins {
id 'java'
id "nebula.dependency-recommender" version "4.1.0"
}
sourceCompatibility = '1.8'
targetCompatibility = '1.8'
// UTF-8 should be standard by now. So use it!
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
repositories {
mavenCentral()
}
dependencyRecommendations {
mavenBom module: "io.dropwizard:dropwizard-bom:1.1.0-rc3"
}
dependencies {
compile "io.dropwizard:dropwizard-core"
}
```
**Error …
=> Move disabling Javadoc linter from profile to main build

dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/args/OptionalDoubleTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/args/OptionalIntTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/args/OptionalLongTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/filter/AllowedMethodsFilter.java
It looks like that the set of allowed methods in `AllowedMethodsFilter` is not modified after it was created. We could embrace it and make immutable during the creation time. This also should provide some performance benefits, because immutable hash tables could be optimized during construction times (e.g. they can use linear probing instead chaining)
=> Make AllowedMethodsFilter immutable

docs/source/about/release-notes.rst, dropwizard-bom/pom.xml
Release notes: https://github.com/dropwizard/metrics/releases/tag/v3.2.2
This release fixes a nasty bug during creating a snapshot which was introduced in the 3.2.*  branch: https://github.com/dropwizard/metrics/pull/1111. The bug affects only `SlidingTimeWindowReservoir`, so its impact not so big, but anyway it would be great to ship the fix in the Dropwizard release.
=> Upgrade to metrics 3.2.2

docs/source/manual/core.rst
Just noticed this misspelling in the user manual.
=> docs: Fix `IllegalArgumentException` misspelling

dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
When resetting logging, we should set a context for the console appender. Otherwise, we get an annoying message: `LOGBACK: No context given for ch.qos.logback.core.ConsoleAppender[null]` in the tests which use `DropwizardAppRule`.
This is related to #1947.
=> Set the console logging context after a reset

dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
Setting buffer size results in writing an internal log message: `Setting bufferSize to ...`.
If the context is not set, then Logback writes a log message: `LOGBACK: No context given for ch.qos.logback.core.FileAppender[null]` to the console log. It's a little bit annoying and we can avoid by setting the context right after instantiating the appenders.
This is related to #1951.
=> Set logging context for file appenders before setting the buffer size

dropwizard-core/src/main/java/io/dropwizard/setup/ExceptionMapperBinder.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/IllegalStateExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/IllegalStateExceptionMapperTest.java
If sending a POST request with a `Content-Type` header that is not `application/x-www-form-urlencoded` and using `@FormParam` in resource method, an `IllegalStateException` will be thrown by Jersey and logged at ERROR level by `LoggingExceptionMapper`. Also, this is the same behavior as https://java.net/jira/browse/JERSEY-2636.
This indicates that **users can easily output ERROR level logs in server side**. Therefore, I would like to prevent this.
1. Create a new resource class and method that given the `@POST` and `@FormParam`.
Note: `@Consumes` is optional because ignoring.
```java
@Path("/")
public class EchoResource {
@POST
@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
public String echo(@FormParam("msg") String msg) {
return msg;
}
}
```
2. Send the POST request without a …
=> Improve error handling for Jersey's Exception that caused by client

dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/args/OptionalDoubleTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/args/OptionalIntTest.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/args/OptionalLongTest.java
The OS could return the same value for `System.currentTimeMillis()` for a long
time span, that means several tests may share the same database during a test run.
This could lead to sporadic test failures which we would like to avoid.
=> Use random UUID for database names in tests

docs/source/manual/configuration.rst, dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java, dropwizard-logging/src/test/java/io/dropwizard/logging/AppenderFactoryCustomTimeZone.java, dropwizard-logging/src/test/resources/yaml/appender_with_custom_time_zone_format.yml, dropwizard-logging/src/test/resources/yaml/appender_with_no_time_zone.yml, dropwizard-logging/src/test/resources/yaml/appender_with_system_time_zone.yml, dropwizard-logging/src/test/resources/yaml/appender_with_time_zone_in_full_format.yml, dropwizard-logging/src/test/resources/yaml/appender_with_utc_time_zone.yml, dropwizard-logging/src/test/resources/yaml/appender_with_wrong_time_zone.yml
Users should have the ability to use the system timezone in the logging configuration. It allows administrators to take advantage of the operation system/JVM time zone management tools and use the same configuration for Dropwizard applications in different time zones.
Resolves #1980.
=> Add setting system/default timezone in logging configuration

dropwizard-bom/pom.xml, dropwizard-hibernate/pom.xml
`jackson-datatype-hibernate5` pulls a `javax.transaction.jta` artifact and Jadira pulls `geronimo-jta_1.1_spec`. They are outdated, because Hibernate already pulls JTA1.2.
This exclude affords to avoid warnings about duplicated classes from the `maven-shade-plugin` during assembling a fat jar.
=> Exclude duplicated JTA 1.1 from dropwizard-hibernate dependencies

dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/old/LogbackClassicRequestLogFactory.java, dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/old/LogbackClassicRequestLogFactoryTest.java
After the last update Logback issues the following warning when an application uses the classic request logging:
`LOGBACK: No context given for io.dropwizard.request.logging.old.LogbackClassicRequestLogFactory$RequestLogLayout("null")`
A fix is assign the context to the layout after its construction.
=> Remove a logback warning for the classic request logging

docs/source/about/release-notes.rst, docs/source/manual/core.rst, dropwizard-core/src/main/java/io/dropwizard/Application.java, dropwizard-core/src/main/java/io/dropwizard/Configuration.java, dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java, dropwizard-logging/src/main/java/io/dropwizard/logging/ExternalLoggingFactory.java, dropwizard-logging/src/main/resources/META-INF/services/io.dropwizard.logging.LoggingFactory, dropwizard-logging/src/test/java/io/dropwizard/logging/ExternalLoggingFactoryTest.java, dropwizard-logging/src/test/resources/yaml/logging_external.yml, dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/ExternalRequestLogFactory.java, dropwizard-request-logging/src/main/resources/META-INF/services/io.dropwizard.request.logging.RequestLogFactory, dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/ExternalRequestLogFactoryTest.java, dropwizard-request-logging/src/test/resources/yaml/externalRequestLog.yml, dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/LogConfigurationTask.java
This is a prototype for splitting the tight integration between Dropwizard and Logback. This feature was requested several times (See #1367). The idea is too provide users the ability to exclude Logback from Dropwizard and replace it with an external logging solution, if they really want to. The main work of this PR is too initialize the Logback infrastructure lazily, so the user can swap it to an external logging mechanism in the config file.
With this change users can swap logback to other logging implementation like that:
```xml
<dependencies>
<dependency>
<groupId>io.dropwizard</groupId>
<artifactId>dropwizard-core</artifactId>
<version>1.1.0-SNAPSHOT</version>
<exclusions>
<exclusion>
<groupId>ch.qos.logback</groupId>
<artifactId>logback-classic</artifactId>
</exclusion>
<exclusion> …
```
=> Support Dropwizard applications without logback

dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java, dropwizard-validation/src/test/java/io/dropwizard/validation/valuehandling/GuavaOptionalValidatedValueUnwrapperTest.java
Some classes/fields were missing the `@UnwrapValidatedValue` annotations in combination with javax.validation annotations.
=> Add missing @UnwrapValidatedValue annotations

dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java, dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java
As mentioned in #1546, setting the context path programmatically in an application's `run` method is being ignored.
`environment.getApplicationContext().setContextPath(somePath);`
This is due to DefaultServerFactory's `build` method (which executes after the application's `run`) reapplying the default (`/`). However, since #1504, the context path information has been getting set prior to the application's run method being invoked, so the configuration being performed in `build` is redundant. Here's the execution flow:
[EnvironmentCommand.run](https://github.com/dropwizard/dropwizard/blob/v1.0.6/dropwizard-core/src/main/java/io/dropwizard/cli/EnvironmentCommand.java#L40-L44)
1. calls `configure` which sets the context paths
2. calls the application's `run` method (where I'm attempting to …
=> Enable setting context path programmatically 

dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java, dropwizard-core/src/test/java/io/dropwizard/cli/CliTest.java
Only log the exception message if there is one and
always print the exceptiopn stack trace when Cli.run
receives an unhandled exception when invoking Command.run.
Fixes #2003
=> Improve unhandled exception logging in Cli.run

docs/source/manual/validation.rst
If endpoints are written in a way that comply with bean-spec property and have validation annotations on them, they will be additionally executed as part of the validation logic.
I dug into the code and there is very little we can do in this regard. I tried coding a way to exclude certain properties that are annotated with `javax.ws.rs` annotations, but I had no luck -- we'd have to write our own `Validator`, so I thought the best solution would be to just document this small downside.
Only 1.0.0 and 1.1.0 users should be affected.
CC @scottaj 
Closes #2008
=> Document caveat of bean-spec compliant endpoints

docs/source/manual/configuration.rst, dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
Include a flag enableThreadNameFilter in AbstractServerFactory to allow
disabling of the ThreadNameFilter's installation. Existing default behavior
is preserved.
Fixes #2013.
=> Add flag to make ThreadNameFilter optional

dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilder.java
[allowCoreThreadTimeOut](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#allowCoreThreadTimeOut(boolean))
Today it's only possible to do this by casting:
```
ThreadPoolExecutor executor = (ThreadPoolExecutor) environment.lifecycle().executorService("test").....build();
executor .allowCoreThreadTimeOut(true);
```
=> Add allowCoreThreadTimeOut option to ExecutorServiceBuilder.

docs/source/manual/configuration.rst, dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java, dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java, dropwizard-db/src/test/resources/yaml/full_db_pool.yml
Had a conversation with the author or hikaricp where tomcat jdbc should have various interceptors on by default like `ConnectionState`, and I realized that one can't specify interceptors through the db yaml. This is a good first step.
Closes #1960
CC @ololoken of #1960
=> Add JDBC interceptor configuration

dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/AbstractDAO.java, dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java
Hibernate deprecated `session.createCriteria(<E>)`.
I added a `criteriaQuery()` method as a migration path away from `criteria()`. I considered `createCriteriaUpdate` and `createCriteriaDelete` methods as well, but wasn't sure if they would be wanted. Please let me know your thoughts.
=> Add new criteriaQuery method to avoid hibernate criteria deprecations.

docs/source/manual/configuration.rst, dropwizard-metrics/src/main/java/io/dropwizard/metrics/BaseReporterFactory.java, dropwizard-metrics/src/main/java/io/dropwizard/metrics/DefaultStringMatchingStrategy.java, dropwizard-metrics/src/main/java/io/dropwizard/metrics/RegexStringMatchingStrategy.java, dropwizard-metrics/src/main/java/io/dropwizard/metrics/StringMatchingStrategy.java, dropwizard-metrics/src/main/java/io/dropwizard/metrics/SubstringMatchingStrategy.java, dropwizard-metrics/src/test/java/io/dropwizard/metrics/BaseReporterFactoryTest.java
The reason I came across this `problem` (maybe it is meant to be used like the way it is now) is because I use datadog and use a thin library on top of dropwizard (https://raw.githubusercontent.com/coursera/metrics-datadog). Which gave the following description how includes work;
---
If you want to filter only a few metrics, you can use the `includes` or 
`excludes` key to create a set of metrics to include or exclude respectively.
~~~yaml
metrics:
frequency: 1 minute                       # Default is 1 second.
reporters:
- type: datadog
host: <host>
includes:
- jvm.
- ch.
~~~
The check is very simplistic so be as specific as possible. For example, if 
you have "jvm.", the filter will check if the includes has that value in any 
part of the metric name (not just the beginning).
---
After …
=> [ENHANCEMENT] SubstringMatchingStrategy for metrics

dropwizard-jetty/src/main/java/io/dropwizard/jetty/RoutingHandler.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/RoutingHandlerTest.java
Solves: #2031
Also, in order to make it possible to detect degradation caused by Jetty's version upgrade, I added several tests.
=> Fix HttpSessionListener.sessionDestroyed is not being called #2031

dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/InstantParam.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/params/InstantParamTest.java
Some java 8 users might want to avoid Joda-Time in favor of Instant
=> Added Java 8 InstantParam with test.

dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
The minimum should be lowered because it's sensible to allow for
validation intervals of less than a second. For instance, the default
validation interval for HikariCP is 500ms. The lower bound of 50ms
was chosen as a compromise between a nonsensically low number
and 500ms
=> Decrease allowable tomcat jdbc validation interval to 50ms

docs/source/manual/validation.rst, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProviderTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
The current docs did not make it clear that annotations that were a part
of the Default group had no affect if the Validation annotation did not
contain the Default group (explicitly or implicitly through
inheritance). See PR #2052 for more information.
This commit also adds test cases to make the current behavior explicit
so any regressions can be caught in the future.
Closes #2049
Closes #2052
=> Update Validation annotation documentation

dropwizard-example/src/test/java/com/example/helloworld/IntegrationTest.java, dropwizard-example/src/test/resources/test-example.yml, dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java, dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
Without this fix, file logging configurations that use time and size based rotations will not work (ie, no log file or logging statements). Added test case to guard against regressions.
cc @charbonnier666 who reported the issue and also reported this PR fixed the issue
Closes #2068
=> Fix size and time rolling appender

dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIFactory.java, dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/DBIFactoryTest.java
Refactor of DBIFactory (Issue #2056)
- Split DBI construction and configuration into dedicated protected methods.
- Added unit tests to verify default configuration.
Please also merge this into master.
Thank you!
=> Refactor of DBIFactory (Issue #2056)

dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/DBIFactory.java
Unless I'm missing something this seems like a bug. I ran into it today while playing with JDBI.
Is there a good reason to keep around the default constructor? It looks like it is only used in tests right now. Those could easily pass an empty optional and get the same result, and that would have made this impossible to miss.
=> Add time zone to Java 8 datetime mappers

docs/source/manual/views.rst, dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/ErrorEntityWriter.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/ErrorEntityWriterTest.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/ExceptionResource.java
Fixes #2038 .
This adds `ErrorEntityWriter`, a generic class that works for HTML error responses but also for other content types. Unit test + docs included.
=> Add support for HTML error responses and other non-JSON content types

dropwizard-configuration/src/main/java/io/dropwizard/configuration/JsonConfigurationFactory.java
This was an oversight on my part in the JsonConfigurationFactory. I created a new JsonParser like the YamlConfigurationFactory does. But it is better to use the one given in the ObjectMapper because the user might have changed the settings of this one in the bootstrapping phase.
=> fixed error of not using given factory in JsonConfigurationFactory

dropwizard-bom/pom.xml
Update jackson version from 2.8.8 to 2.8.9 to address Deserializer security vulnerability, per #2085
vulnerability is also fixed in jackson 2.9.0.pr3.    (see #2057)
=> Update jackson to 2.8.9

dropwizard-bom/pom.xml
Update jackson version from 2.8.7 to 2.8.9 to address Deserializer security vulnerability, per #2085
=> Update 1.1.x branch jackson to 2.8.9

dropwizard-bom/pom.xml
Update jackson version from 2.7.8 to 2.7.9.1 to address Deserializer security vulnerability, per #2085
=> Update 1.0.x branch jackson to 2.7.9.1

pom.xml
Eclipse does not support the errorprone compiler; moved errorprone setup
from build-plugins to profiles. There are now two profiles, one for
Eclipse and one for everything else.
I have verified this change with a command line build (error prone warnings are still generated) and by loading the project into Eclipse without any errors.
=> Make DropWizard Development Eclipse Friendly

dropwizard-configuration/src/test/java/io/dropwizard/configuration/JsonConfigurationFactoryTest.java, dropwizard-configuration/src/test/resources/factory-test-comment.json
Sorry for the late response. I had a lot to do the last few weeks. Here is a test for the problem in #2046 . I added an example json config that contains a comment and can only be parsed if the object mapper is configured accordingly.
=> Test for #2046

dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java, dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
As done in #1615 for CachingAuthenticator. Since `Authorizer::authorize` doesn't have a `throws` clause, I've only handled `UncheckedExecutionException`s.
Result when `null` is returned by the authorizer will differ from previously, where a `NullPointerException` would have been thrown by the cache's `put` method, whereas now a `InvalidCacheLoadException` will be thrown by the cache itself when the loader returns null. There might be a way to have the same result as previously, let me know if you want me to look into it (but personally I don't think it really matters as most users won't be catching those exceptions anyway, and it might even be clearer as to what happened).
EDIT: Looking at this again, `Authorizer::authorize` returns a `boolean` and not a `Boolean` so null returns …
=> Use LoadingCache in CachingAuthorizer

dropwizard-jackson/src/main/java/io/dropwizard/jackson/Jackson.java
Use `mapper#registerModule(Module)` instead of `mapper#registerModules(Modules...)` in `Jackson#configure(ObjectMapper)`.
=> Remove unnecessary use of varargs methods

dropwizard-views/src/main/java/io/dropwizard/views/ViewMessageBodyWriter.java, dropwizard-views/src/test/java/io/dropwizard/views/ViewMessageBodyWriterTest.java
ViewMessageBodyWriter::detectLocale will now catch
`HeaderValueException`s thrown when retrieving the languages from the
headers and return a `400 - Bad Request` to clients instead of a server
error.
The issue (#2097) talked about using the default locale in that case, but I don't agree. Not my decision in the end though, I can change this to use the default locale if you guys prefer this.
=> Handle badly formed 'Accept-Language' headers (#2097)

dropwizard-bom/pom.xml
Update Jetty version from 9.4.5.v20170502 to jetty-9.4.6.v20170531 to address CVE-2017-9735 per #2113
=> Update Jetty to 9.4.6.v20170531

dropwizard-bom/pom.xml
Update Jetty version from 9.3.9.v20160517 to 9.3.20.v20170531 to address CVE-2017-9735 per #2113
=> Update 1.0.x branch jetty to 9.3.20.v20170531

dropwizard-bom/pom.xml
Update Jetty version from 9.4.5.v20170502 to 9.4.6.v20170531 to address CVE-2017-9735 per #2113
=> Update 1.1.x branch Jetty  to 9.4.5.v20170502

dropwizard-bom/pom.xml, dropwizard-configuration/src/test/java/io/dropwizard/configuration/YamlConfigurationFactoryTest.java, dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/CustomDeserialization.java, dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapperTest.java
Jackson 2.9 greatly simplifies exception handling with the new exception,
`InvalidDefinitionException`.
This PR technically breaks behavior for custom deserializers, but I
believe it is now the correct behavior. If a deserializer fails to to deserialize
input then a 400 should be returned as it denotes unexpected input. A 500
should only be returned if a deserializer encountered an error unrelated
to the input (if it read from a non-existant file or db...(not saying it's
a good design)). Added a test case to assert this.
Do not merge this PR as Jackson 2.9 is not actually released. I'm not sure when it will
be released, but I figured it would be a good idea to know what to expect.
=> Update to Jackson 2.9

docs/source/manual/configuration.rst, dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java, dropwizard-http2/src/test/java/io/dropwizard/http2/Http2ConnectorFactoryTest.java, dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithCustomCipherTest.java, dropwizard-http2/src/test/resources/test-http2-with-custom-cipher.yml
There are many SSL ciphers which are supported by HTTP/2 clients (see https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) and the user should have the ability to use them in Dropwizard
applications. Currently it's not possible because Dropwizard forces the default cipher `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` defined in the HTTP2 spec.
This change allows users to provide a custom list of supported ciphers, so clients who support more strong ciphers, can use them. The provided list of ciphers MUST contain the `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` cipher as defined in the HTTP2 spec.
Redux of #1978.
=> Add support for setting several cipher suites for HTTP/2

dropwizard-core/src/main/java/io/dropwizard/cli/CheckCommand.java, dropwizard-core/src/main/java/io/dropwizard/cli/Cli.java, dropwizard-core/src/main/java/io/dropwizard/cli/Command.java, dropwizard-core/src/test/java/io/dropwizard/cli/CliTest.java
Fix for #2122
Allows for commands to catch configuration, environment, and command exceptions in one place (eg. forcing all commands to print the stack trace is less than desirable)
Below is an example of a custom command that will print the stack trace to stderr if someone passed in `--debug`, else print the error message to stdout.
```java
public static final class CustomCommand extends Command {
@Override
public void configure(Subparser subparser) {
subparser.addArgument("--debug").action(Arguments.storeTrue());
}
@Override
public void run(Bootstrap<?> bootstrap, Namespace namespace) throws Exception {
throw new RuntimeException("I did not expect this!");
}
@Override
public void onError(Cli cli, Namespace namespace, Throwable e) {
if (namespace.getBoolean("debug")) {
super.onError(cli, …
```
=> Allow commands to customize exception handling

dropwizard-auth/src/main/java/io/dropwizard/auth/WebApplicationExceptionCatchingFilter.java, dropwizard-auth/src/test/java/io/dropwizard/auth/OptionalAuthFilterOrderingTest.java
When `@Auth Optional<UserOrWhatever>` is used. Registered `WebApplicationExceptionCatchingFilter` has no Priority set up and in the result, filter is executed at the end of the filter chain.
=> added @Priority(Priorities.AUTHENTICATION) to WebApplicationExceptionCatchingFilter

dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java, dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java
When resetting logging, configure a layout and start the appender. Otherwise, using the appender logs a warning to the Logback StatusManager:
> WARN in ch.qos.logback.core.ConsoleAppender[null] - Attempted to append to non started appender [null].
Uses the same layout as bootstrap.
This is related to #1973.
=> Start the console appender after a logging reset

dropwizard-util/src/main/java/io/dropwizard/util/Size.java, dropwizard-util/src/test/java/io/dropwizard/util/SizeTest.java
Added unit test to verify comparable contract.
This addresses the bug alluded to in #2153. It turns out that the reporter of the issue uncovered a violation of a rule set forth when implementing the Comparable interface.
=> Fixed violation of Comparable contract in Size

dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
This should bring the documentation in line with the actual default value, as on line [389](https://github.com/dropwizard/dropwizard/pull/2160/files#diff-e5126a75b90a2bf1ce64a60b923c8eadL389).
=> Update documentation for checkConnectionOnConnect

docs/source/getting-started.rst
The old link seems to not work any longer...
=> Fix link to Jackson Annotation in Getting Started

dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java, dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
Jetty's `ServerConnector` accepts `soLingerTime` in milliseconds, rather
than in seconds as `Socket.setSoLinger` does [1]. Dropwizard on the other
hand after parsing the YML configuration and extracting the `soLingerTime` parameter
passes it to Jetty in seconds. As a result, the configuration gets really
confusing for users, because the configuration value is more than the actual
SO_LINGER timeout by 1000 times.
The fix is to pass the configuration value to Jetty's `ServerConnector`
in milliseconds.
[1]: http://www.eclipse.org/jetty/documentation/9.4.x/configuring-connectors.html
Fixes #2175
=> Correctly set up SO_LINGER for the HTTP connector
