dropwizard/dropwizard

- docs/source/manual/testing.rst
- dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java
Fixes https://github.com/dropwizard/dropwizard/issues/835
> Add option to change test container factory, and explicitly default to InMemoryTestContainer

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/gzip/ConfiguredGZipEncoder.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/gzip/ConfiguredGZipEncoderTest.java
> Added test cases

- dropwizard-core/src/main/java/io/dropwizard/setup/Bootstrap.java
- dropwizard-core/src/test/java/io/dropwizard/setup/BootstrapTest.java
Include all the metrics sets from metrics-jvm-3.1.0
> Include all metric sets from metric-jvm

- dropwizard-example/example.yml
- dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java
- dropwizard-example/src/main/java/com/example/helloworld/HelloWorldConfiguration.java
- dropwizard-views-freemarker/src/main/java/io/dropwizard/views/freemarker/FreemarkerViewRenderer.java
- dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/MustacheViewRenderer.java
- dropwizard-views/src/main/java/io/dropwizard/views/ViewBundle.java
- dropwizard-views/src/main/java/io/dropwizard/views/ViewConfigurable.java
- dropwizard-views/src/main/java/io/dropwizard/views/ViewRenderer.java
- dropwizard-views/src/test/java/io/dropwizard/views/ViewBundleTest.java
https://github.com/dropwizard/dropwizard/issues/913
> allow view renderer configuration

- dropwizard-logging/src/test/java/io/dropwizard/logging/LoggingFactoryPrintErrorMessagesTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/LogConfigurationTaskTest.java
This change fixes some failing unit tests on Windows.
> Fix tests on windows

- docs/source/manual/views.rst
- dropwizard-views/src/main/java/io/dropwizard/views/ViewBundle.java
- dropwizard-views/src/test/java/io/dropwizard/views/ViewBundleTest.java
It's awkward to demand configuration from apps, even when they don't have any need to override the defaults.
> Provide a default view configuration.

- dropwizard-example/pom.xml
- dropwizard-example/src/test/java/com/example/helloworld/resources/PersonResourceTest.java
- dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedResourceTest.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/junit/ResourceTestRule.java
All of the relevant discussion is in the issue
https://github.com/dropwizard/dropwizard/issues/922
this also would close https://github.com/dropwizard/dropwizard/issues/513
> test rule supports auth

- dropwizard-jdbi/pom.xml
[Release notes](https://github.com/jdbi/jdbi/blob/master/RELEASE_NOTES)
JDBI 2.62 has several useful features such as:
* Positional bindings in SqlObject API (incidentally contributed by me)
* Ability to bind arguments in SqlObject API as Map
* Better Java 8 support
> Upgrade to JDBI 2.62

- dropwizard-core/src/main/java/io/dropwizard/ConfiguredBundle.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java
Use Type parameter for configuration in both, run and initialize so that one can for example add another ConfigurationBundle in initialize method.
> Use Type parameter for configuration in initialize

- dropwizard-core/src/main/java/io/dropwizard/ConfiguredBundle.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java
Reverts dropwizard/dropwizard#795 the build broke
> Revert "Use Type parameter for configuration in initialize"

- dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/timestamps/DateTimeSqlTimestampTest.java
so build fails periodically, https://travis-ci.org/dropwizard/dropwizard/jobs/57990585
> DateTimeZone only accepts a subset of the IDs from TimeZone

- dropwizard-benchmarks/pom.xml
- dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/DropwizardResourceConfigBenchmark.java
The benchmark measures how long it takes to gather information about application endpoints for representing it to the user during the application startup.
The goal is to see is there were any perfomance problems in #1002.
> Add a benchmark for DropwizardResourceConfig

- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
* Expect `NoRouteException` as well as `ConnectionTimeoutException`.
If a local network is configured to reject request to non-routable addresses, then this exception is returned by JVM. We should handle such situations.
* Add a health check, so the application doesn't yell on us in logs.
* Add code style and documentation improvements.
> Improve DropwizardApacheConnectorTest

- docs/source/manual/auth.rst
- dropwizard-auth/src/main/java/io/dropwizard/auth/Auth.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/AuthValueFactoryProvider.java
- dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java
- dropwizard-example/src/main/java/com/example/helloworld/resources/ProtectedResource.java
- dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedResourceTest.java
Hopefully this eases the burden on the transition
> @Auth principal injection

- docs/source/manual/auth.rst
Added `<User, Authenticator>` when calling `AuthFilter.Builder`
> Doc update: Generic checks when creating AuthFilter

- dropwizard-client/pom.xml
There were 3 releases of Apache Http Client with many bug fixes since the last update.
Release notes: 
* [4.3.6](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310360&version=12327489)
* [4.4](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310360&version=12324872)
* [4.4.1](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310360&version=12329394)
Interesting fixes for us:
* [Stale connections in pool cause NoHttpResponseException](https://issues.apache.org/jira/browse/HTTPCLIENT-1610) 
* [Add option to create a connection eviction thread for a non-shared connection manager](https://issues.apache.org/jira/browse/HTTPCLIENT-1583)
* [SSLContextBuilder does not preserve natural order of Trust / Key managers …
> Upgrade to Apache HTTP Client 4.4.1

- docs/source/manual/auth.rst
- dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/basic/BasicCredentialAuthFilter.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/chained/ChainedAuthFilter.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/oauth/OAuthCredentialAuthFilter.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/ChainedAuthProviderTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicAuthProviderTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicCustomAuthProviderTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/chained/ChainedAuthProviderTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthCustomProviderTest.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthProviderTest.java
- dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java
- dropwizard-example/src/test/java/com/example/helloworld/resources/ProtectedResourceTest.java
* Use Filter instead of Handler
* java docs for ChainedAuthFilter 
* limit type warning suppression in ChainedAuthFilterTest
> Auth documentation & minor refactors

- docs/source/manual/core.rst
Documents some of the changes implemented in #993
> Add docs on constraint violations

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JsonProcessingExceptionMapper.java
Reverts dropwizard/dropwizard#1052
> Revert "Do not swallow exception cause when parsing JSON."

- docs/source/manual/core.rst
The current documentation gives no indication of what the metrics annotations do, added some rudimentary documentation to explain the basics
> Include information about the metrics annotations

- docs/source/getting-started.rst
- dropwizard-example/src/main/java/com/example/helloworld/api/Saying.java
- dropwizard-example/src/main/java/com/example/helloworld/resources/HelloWorldResource.java
- dropwizard-example/src/test/java/com/example/helloworld/IntegrationTest.java
Addresses https://github.com/dropwizard/dropwizard/issues/1074
> Moving the Saying representation to the api package

- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
> Update caching implementation to not cache absent values.

- docs/source/getting-started.rst
Fix for #1101 Minor "Getting started" Hibernate-validator documentation error (https://github.com/dropwizard/dropwizard/issues/1101)
> 1101 - JSR reference for Hibernate-validator

- docs/source/manual/auth.rst
https://github.com/dropwizard/dropwizard/issues/1120
> Use Bearer realm for OAuth

- pom.xml
> Add Justin Plock to the developers list

- docs/source/about/release-notes.rst
https://github.com/dropwizard/dropwizard/issues/1120
> massage commit messages into release notes

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
Thank you @michaelhixson, whose analysis made this a simple fix.
Closes #1127
> Fix endpoint log not finding nested resources

- docs/source/manual/configuration.rst
- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientConfiguration.java
https://github.com/dropwizard/dropwizard/issues/1160
> make connection pool shared by default

- docs/source/manual/configuration.rst
- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientConfiguration.java
Reverts dropwizard/dropwizard#1179
> Revert "make connection pool shared by default"

- docs/source/manual/core.rst
Add missing closing parenthesis in MessageQueueFactory build method
> Add missing closing parenthesis in configuration example

- docs/source/about/release-notes.rst
- dropwizard-db/pom.xml
- dropwizard-jdbi/pom.xml
versions:
tomcat-jdbc 8.0.24
jdbi 2.63
> tomcat-jdbc and jdbi lib upgrades

- docs/source/about/release-notes.rst
- dropwizard-core/pom.xml
- dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbTagCommand.java
Mailing list references:
* https://groups.google.com/d/msg/dropwizard-user/WwlAslJikE0/33KM6Ettd1UJ
* https://groups.google.com/d/msg/dropwizard-dev/CC2jfWLmVM4/7lF0VNJrzWUJ
> Upgrade to argparse4j 0.6.0

- docs/source/about/release-notes.rst
- docs/source/manual/client.rst
- dropwizard-example/pom.xml
- pom.xml
Hot on the heels of 2.20 is [2.21](https://github.com/jersey/jersey/releases/tag/2.21)
> Upgrade to jersey 2.21

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/SubBeanParameter.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
> Validate sub classed BeanParameters

- dropwizard-client/src/test/java/io/dropwizard/client/JerseyIgnoreRequestUserAgentHeaderFilterTest.java
similar to DropwizardApacheConnectorTest
> fix timeouts by setting client configs

- docs/source/manual/auth.rst
Add some docs to test resources with `@Auth`
> Add docs for dropwizard auth

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/LoggingExceptionMapper.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/ExceptionResource.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/LoggingExceptionMapperTest.java
This would fix issue https://github.com/dropwizard/dropwizard/issues/1192.
> #1192: Format WebApplicationException

- docs/source/about/release-notes.rst
Noticed I forgot to update the release notes in #1178, so here it is.
> Add template behavior on error in release notes

- dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
I have added validations and corresponding tests to FileAppenderFactory so that the error messages are understandable.
> Add FileAppenderFactory validations and tests

- docs/source/manual/testing.rst
We use DropWizard from Scala and I couldn't find any documentation about how to write integration tests, apart from the discussion in #488.
> Add non-JUnit integration test section

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
This should close #1257.
@espenhoh let me know if I missed anything.
EDIT: Closes #1222 too
> Log sub resource locators correctly

- dropwizard-assets/src/main/java/io/dropwizard/assets/AssetsBundle.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
minor changes so that these classes can be subclassed for customization/reuse
> Dropwizard #1265 - Allow AssetBundle/AssetServlet to be customized.

- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
Need to be able to override getResourceUrl() in case resource is in an external JAR
> Sorry! I forgot to include this. This is the most important part. Please accept.

- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
- dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
PR resulting from https://github.com/dropwizard/dropwizard/issues/1186#issuecomment-148188882
> Allow custom redirect strategy to be set

- docs/source/about/release-notes.rst
Add the major contributed fixes and improvements since the last update.
> Synchronize 0.9.0 release notes

- docs/source/manual/example.rst
The documentation of the example application was not up-to-date.
I improved the steps by grouping and removing optional steps.
> Improved Documentation of Example Application

- docs/source/getting-started.rst
- docs/source/manual/auth.rst
- docs/source/manual/client.rst
- docs/source/manual/core.rst
- docs/source/manual/internals.rst
- docs/source/manual/migrations.rst
- docs/source/manual/testing.rst
- docs/source/manual/views.rst
Checked the documentation with grammarly. Fixed some issues.
> Added an introduction to internal + Minor Typos on other pages

- .gitattributes
Closes #1305.
@nickbabcock I've assigned this PR to you because you seem to have a Windows build machine to actually test it. :wink:
> Enforce LF line endings on Mustache and Freemarker template files

- dropwizard-example/example.yml
- dropwizard-example/pom.xml
- dropwizard-example/src/main/java/com/example/helloworld/HelloWorldConfiguration.java
- dropwizard-metrics-ganglia/pom.xml
- dropwizard-metrics-ganglia/src/test/java/io/dropwizard/metrics/ganglia/GangliaReporterFactoryTest.java
- dropwizard-metrics-graphite/pom.xml
- dropwizard-metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterFactoryTest.java
- dropwizard-metrics/src/main/java/io/dropwizard/metrics/BaseReporterFactory.java
This PR adds tests for the `GangliaReporterFactory` and `GraphiteReporterFactory` classes to check whether they can be instantiated (and validated) using a `ConfigurationFactory`.
> Test {Ganglia,Graphite}ReporterFactory classes

- docs/source/manual/example.rst
PR #1298 broke the layout: double space before asterisk is not working in sphinx
> Fixed layout of the example.rst

- dropwizard-auth/src/main/java/io/dropwizard/auth/basic/BasicCredentialAuthFilter.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/oauth/OAuthCredentialAuthFilter.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/AuthResource.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicCustomAuthProviderTest.java
- dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java
- dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientBuilderTest.java
- dropwizard-core/src/main/java/io/dropwizard/cli/ConfiguredCommand.java
- dropwizard-core/src/test/java/io/dropwizard/cli/ServerCommandTest.java
- dropwizard-core/src/test/java/io/dropwizard/server/SimpleServerFactoryTest.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryFactoryTest.java
- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/JodaDateTimeArgumentFactory.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/guava/OptionalMessageBodyWriter.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/gzip/ConfiguredGZipEncoder.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/gzip/GZipDecoder.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/setup/JerseyEnvironment.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/gzip/ConfiguredGZipEncoderTest.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/GzipFilterFactoryTest.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilderTest.java
- dropwizard-metrics/src/test/java/io/dropwizard/metrics/MetricsFactoryTest.java
- dropwizard-migrations/src/main/java/io/dropwizard/migrations/MigrationsBundle.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbStatusCommandTest.java
- dropwizard-spdy/src/main/java/io/dropwizard/spdy/Spdy3ConnectorFactory.java
- dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/MustacheViewRenderer.java
The beginning of going to a 1.0 Version is maybe a good timing to get rid of a lot of the IDE warnings.
> Removed unused imports

- dropwizard-jackson/pom.xml
- dropwizard-logging/pom.xml
Fixed two Version Override Warnings
> Feature fix maven version warning

- docs/source/about/release-notes.rst
- dropwizard-bom/pom.xml
A pretty big JDBI upgrade. See the release announcement [here](https://groups.google.com/forum/#!topic/jdbi/onYQtaBeEng).
> Upgrade to JDBI 2.70

- docs/source/manual/client.rst
A couple of fixes to the documentation of integration with Apache HTTP Client.
> Apache HTTP Client doc fixes

- dropwizard-auth/src/main/java/io/dropwizard/auth/AuthFilter.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/basic/BasicCredentialAuthFilter.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/oauth/OAuthCredentialAuthFilter.java
The current implementation of filters is rather cumbersome and doesn't really reuses the code.
This change:
* separates parsing credentials and authentication of a request;
* reuses the code of setting the security context;
* improves readability of the credentials parsing methods;
* adds additional documentation about the credentials format and authentication process.
The diff is better viewed with `?w=1`.
> Simplify auth filters

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/RequestLogFactory.java
Extend Discoverable for standard ServiceLoader based extensibility.
> Allow RequestLogFactory implementation discovery

- dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardClientRule.java
Fixes https://github.com/dropwizard/dropwizard/issues/1393
> Expose the ObjectMapper and Environment from the FakeApplication

- docs/source/about/release-notes.rst
- dropwizard-bom/pom.xml
- dropwizard-core/src/test/java/io/dropwizard/server/AbstractServerFactoryTest.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/NonblockingServletHolder.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/NonblockingServletHolderTest.java
This is a bugfix release. The release notes are [here](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/VERSION.txt)
> Upgraded to Jetty 9.3.8.v20160314

- docs/source/manual/configuration.rst
- dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceConfigurationTest.java
- dropwizard-db/src/test/resources/yaml/full_db_pool.yml
> Add DataSourceFactory.rollbackOnReturn flag

- dropwizard-bom/pom.xml
- dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java
- dropwizard-logging/src/test/resources/yaml/logging_advanced.yml
Fix https://github.com/dropwizard/dropwizard/issues/1478
> Fix issue when upgrading logback to 1.1.5 beyond

- docs/source/manual/core.rst
> Update link to Riak

- dropwizard-core/src/main/java/io/dropwizard/cli/EnvironmentCommand.java
- dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java
- dropwizard-core/src/main/java/io/dropwizard/server/ServerFactory.java
- dropwizard-core/src/main/java/io/dropwizard/server/SimpleServerFactory.java
- dropwizard-core/src/test/java/io/dropwizard/server/AbstractServerFactoryTest.java
- dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java
- dropwizard-core/src/test/java/io/dropwizard/server/SimpleServerFactoryTest.java
https://github.com/dropwizard/dropwizard/pull/1503 including a build fix
> configures the context paths before the application.run()

- docs/source/getting-started.rst
> Update Maven reference link

- docs/source/manual/configuration.rst
- dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
See https://github.com/dropwizard/dropwizard/issues/1465
> Documentation for maxFileSize option of file-based logger

- dropwizard-example/example.yml
- dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java
- dropwizard-example/src/main/java/com/example/helloworld/HelloWorldConfiguration.java
- dropwizard-metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteReporterFactory.java
- dropwizard-metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterFactoryTest.java
@postwait mentioned this on twitter, but the example application didn't attempt to send any metrics to Graphite.
> Add an example of using the GraphiteReporter to the example application

- docs/source/manual/hibernate.rst
Add Path annotation, as method expects PathParam
(will get NullPointerException otherwise)
> Update documentation on hibernate resource method example

- dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/args/JodaDateTimeMapper.java
> Add customizable constructors to JodaDateTimeMapper

- dropwizard-core/src/main/java/io/dropwizard/cli/ServerCommand.java
- dropwizard-core/src/test/java/io/dropwizard/cli/ServerCommandTest.java
small fix for Issue#1557, feel free to adapt/modify this bugfix
> Surrounded server.stop() and cleanup with a try/catch block, see #1557

- docs/source/manual/configuration.rst
- dropwizard-http2/src/main/java/io/dropwizard/http2/Http2CConnectorFactory.java
- dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java
> Rename initialStreamSendWindow setting to initialStreamRecvWindow

- dropwizard-http2/pom.xml
Had this unfortunate pleasure today, and this change fixed it :stuck_out_tongue:
> Fix build for users with spaces in home directory

- dropwizard-testing/src/main/java/io/dropwizard/testing/ConfigOverride.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardAppRuleConfigOverrideTest.java
> Enable lazy-loading of ConfigOverride values via Supplier

- docs/source/manual/core.rst
The error handling docs were a bit out of date, so I updated them :smile:
Rendered right on my machine :+1:
> Update error handling guide in docs

- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
I rebased this branch on the master and re-ran it on Travis twice and it passed (twice!).
So here's to being optimistic :tada:
> Remove @Ignore from DropwizardApacheConnectorTest

- dropwizard-logging/src/main/java/io/dropwizard/logging/BootstrapLogging.java
Should be `bootstrappingLock` instead `bootsrappingLock`.
> Correct the name of the lock in @GuardedBy

- docs/source/about/contributors.rst
I noticed you only have my GitHub handle in the contributors file. So I've updated my own entry in the contributors file to include my name :smiley_cat:
> Replaced my GitHub handle with my real name in contributors file

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java
- pom.xml
Adds Google Error Prone (http://errorprone.info) compiler checks
Also updates the plugin dependencies to their latest versions.
> Add Google Error Prone checks

- docs/source/about/release-notes.rst
- dropwizard-bom/pom.xml
- dropwizard-jackson/src/test/java/io/dropwizard/jackson/Issue1627.java
- dropwizard-jackson/src/test/java/io/dropwizard/jackson/JacksonTest.java
> Upgrade to Jackson 2.7.6

- RELEASES.md
- prepare_docs.sh
This change proposes a simple draft of a document, which describes the technical aspects of making a release of Dropwizard. This information is mostly exist in the form emails between Dropwizard maintainers and personal experience, so it's quite easy for a maintainer to forget some steps during a release and make a mistake. It would be great, if we wrote it down in the repository and make accessible to the community. This should make Dropwizard a more transparent project and allow to improve our release process.
@dropwizard/committers, please give your feedback on this document. This is a rough draft which contains only the basic information. What other aspects we should address? Maybe something should be stripped out?
> Document the Dropwizard release process

- docs/source/manual/configuration.rst
timeZone is now a member of appenders.
> Update request log docs

- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
- dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientIntegrationTest.java
- dropwizard-jackson/src/main/java/io/dropwizard/jackson/AnnotationSensitivePropertyNamingStrategy.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
- Fix or comment deprecation usage in tests/docs
- Remove redundant try-catch in TaskServlet
- Prefer java8 mechanisms in CachingAuthorizer (cc @evnm)
> Minor Code Fixes

- docs/source/about/release-notes.rst
- dropwizard-auth/src/main/java/io/dropwizard/auth/PrincipalContainerRequestValueFactory.java
- dropwizard-bom/pom.xml
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/YamlConfigurationFactory.java
- dropwizard-core/src/test/java/io/dropwizard/server/DefaultServerFactoryTest.java
- dropwizard-core/src/test/java/io/dropwizard/server/SimpleServerFactoryTest.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/sessions/FlashFactory.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/sessions/HttpSessionFactory.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProviderTest.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/NonblockingServletHolder.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
- dropwizard-metrics/src/main/java/io/dropwizard/metrics/BaseReporterFactory.java
- dropwizard-metrics/src/main/java/io/dropwizard/metrics/ConsoleReporterFactory.java
- dropwizard-metrics/src/main/java/io/dropwizard/metrics/Slf4jReporterFactory.java
- dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/LogbackAccessRequestLogFactory.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardClientRuleTest.java
- dropwizard-views-freemarker/src/main/java/io/dropwizard/views/freemarker/FreemarkerViewRenderer.java
- dropwizard-views/src/main/java/io/dropwizard/views/ViewBundle.java
- pom.xml
Here's the link to the error prone information on the class `newInstance()` changes - http://errorprone.info/bugpattern/ClassNewInstance
> Update dependencies and fix some error prone warnings

- dropwizard-configuration/src/main/java/io/dropwizard/configuration/YamlConfigurationFactory.java
A minor improvement to the escaping code in `YamlConfigurationFactory`.
A good practice is to avoid manipulating arrays in favour of Java collections, because arrays are relatively dangerous to operate and provide a less convenient API.
See "Effective Java Item 25: Prefer lists to arrays".
> Use a List instead an array in YamlConfigurationFactory

- dropwizard-auth/src/main/java/io/dropwizard/auth/AuthDynamicFeature.java
Jersey does not behave exactly the same when registering
object and class during a DynamicFeature configuration.
This commit allows for both behaviour to be exploited in
AuthDynamicFeature.
This fixes #1630.
@evnm @psamsotha please review and tell me if we need more doc that what I added :)
> Allow for passing a filter as a class

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
> Fix occasional null comparison introduced in #1718

- dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java
Following #1513, this PR adds the default `HealthCheckRegistry` to `SharedHealthCheckRegistries`.
> Register the default HealthCheckRegistry as "default"

- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
Since it looks like we'll be making another 1.0.x, the branch should be build-able on windows
Partial cherry-pick of #1649
> Fix path issue to build on windows

- docs/source/manual/validation.rst
> Update extending validation error messages docs

- dropwizard-bom/pom.xml
Fixes: FasterXML/jackson-databind#1383
> Update jackson version from 2.7.6 -> 2.7.8

- docs/source/manual/validation.rst
> Add enum constraints to validation docs

- docs/source/manual/hibernate.rst
Corrected the documentation. Replaced the UserDAO class reference with PersonDAO.
> Issue#1757 Possible documentation bug or confusing documentation

- dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/MustacheViewRenderer.java
Solves [1289](https://github.com/dropwizard/dropwizard/issues/1289).
> #1289: Enabling configuration option for caching of Mustache Views

- dropwizard-views/src/main/java/io/dropwizard/views/ViewRenderExceptionMapper.java
> Move ViewExceptionMapper to an ExtendedExceptionMapper

- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthorizerTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/ssl/DropwizardSSLConnectionSocketFactoryTest.java
- dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationParsingException.java
- dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
- dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
- dropwizard-e2e/src/main/java/com/example/app1/App1.java
- dropwizard-example/src/test/java/com/example/helloworld/resources/PeopleResourceTest.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/AbstractDAOTest.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryHealthCheckTest.java
- dropwizard-jackson/src/main/java/io/dropwizard/jackson/GuavaExtrasModule.java
- dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/GuavaJDBITest.java
- dropwizard-jdbi/src/test/java/io/dropwizard/jdbi/JDBITest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/filter/AllowedMethodsFilterTest.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/ServerPushFilterFactoryTest.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/ConsoleAppenderFactory.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/SyslogAppenderFactory.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/AssetServlet.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/assets/ByteRange.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/tasks/TaskServlet.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/GzipDefaultVaryBehaviourTest.java
- dropwizard-views/src/test/java/io/dropwizard/views/ViewBundleTest.java
These should be pretty uncontroversial code improvements, but let me know if otherwise. Most of these improvements were automatically done through intellij with me reviewing the changes.
- Fixup mockito deprecations
- Rest of Guava's propagate replaced
- Remove unneeded throws declaration
- Simplify stream calls to collection foreach
- Remove caught and rethrown exception
- Replace anonymous types with lambdas
- Replace isPresent check with ifPresent function
- Replace asList with singleton list with one element
- Use diamond operator
- Prefer contains to indexOf() != -1
- Directly sort list instead of Collections.sort
Feel free to squash this into a single commit
> General Code Improvements

- docs/source/manual/views.rst
> Document template exception mapper customization

- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
- dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
Solves: https://github.com/dropwizard/dropwizard/issues/1441
> Ability to set HttpProcessor to Instrumented Apache's Http Client

- docs/source/about/release-notes.rst
- dropwizard-bom/pom.xml
- dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
- pom.xml
> Dependency updates

- .travis.yml
> Use same JAVA_OPTS in Travis and Circle CI

- dropwizard-auth/src/test/java/io/dropwizard/auth/basic/BasicCredentialsTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientIntegrationTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/JerseyIgnoreRequestUserAgentHeaderFilterTest.java
- dropwizard-db/src/test/java/io/dropwizard/db/DataSourceFactoryTest.java
- pom.xml
Upgrade to Errorprone 2.0.15 split out from #1865.
> Upgrade to Errorprone 2.0.15

- docs/source/manual/configuration.rst
- dropwizard-bom/pom.xml
- dropwizard-http2/src/test/java/io/dropwizard/http2/AbstractHttp2Test.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
Hopefully, it's just a version bump.
Resolves #1874.
> Upgrade Jetty to 9.4.0.v20161208

- docs/source/manual/configuration.rst
- docs/source/manual/core.rst
- dropwizard-logging/src/main/java/io/dropwizard/logging/AbstractAppenderFactory.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/ConsoleAppenderFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
> Add support for neverBlock on AsyncAppenders

- dropwizard-bom/pom.xml
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/SessionFactoryHealthCheckTest.java
http://metrics.dropwizard.io/3.2.0/about/release-notes.html
> Upgrade to Dropwizard Metrics 3.2.0

- dropwizard-core/src/main/java/io/dropwizard/setup/Environment.java
Related to https://github.com/dropwizard/metrics/pull/801
> Use the new setDefault() option to set the default metric registry

- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/AutoCloseableManager.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/AutoCloseableManagerTest.java
I used ExecutorServiceManager as a guide.
> Add a lifecycle.Managed for AutoClosable's instances

- dropwizard-bom/pom.xml
Metrics 3.1.3 and 3.1.4 contains some bug fixes, with are quite useful.
> metrics version 3.1.4

- dropwizard-jersey/pom.xml
> Remove javax.el from jersey-bean-validation

- dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/old/DropwizardSlf4jRequestLog.java
fixes https://github.com/dropwizard/dropwizard/issues/1988
> making DropwizardSl4jRequestLogger public instead of package private

- docs/source/manual/configuration.rst
> Update documentation about minimum and maximum number of threads

- dropwizard-http2/pom.xml
> Use latest version of alpn-boot by default

- dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
Should have been part of #2030
Also moved the property from the top of the class to where the other properties are to be more consistent.
> Add JsonProperty to jdbcInterceptors property

- dropwizard-client/src/test/java/io/dropwizard/client/ConfiguredCloseableHttpClientTest.java
- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardExecutorProviderTest.java
- dropwizard-e2e/src/test/java/com/example/forms/FormsAppTest.java
- dropwizard-example/src/test/java/com/example/helloworld/resources/PeopleResourceTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/setup/ServletEnvironmentTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/DbMigrateCustomSchemaTest.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DAOTestRule.java
- Fix some deprecations
- Bind to a random port instead of 8080 for a test case
- Simplify a line using Map::forEach
> Minor code cleanup

- docs/source/manual/core.rst
The organizing your code section has been confusing, as reported in #1979. This PR attempts to fix this 👼 
CC @fabriziocucci
Closes #1979
> More docs for project structure

- README.md
- docs/source/about/release-notes.rst
- docs/source/getting-started.rst
- docs/source/manual/client.rst
- docs/source/manual/core.rst
- docs/source/manual/forms.rst
- docs/source/manual/testing.rst
java.net site has closed. Updating all jersey URL's to new Jersey home.
> Updating all jersey URL's to new Jersey home

- dropwizard-util/src/test/java/io/dropwizard/util/GenericsTest.java
I create a test class for the Generics class in dropwizard-util.
> Test for Generics class

- docs/source/manual/core.rst
Closes #2064 by documenting that the feature
> Document log filters

- dropwizard-util/src/test/java/io/dropwizard/util/GenericsTest.java
Class now compiles in both IntelliJ and Eclipse (as well as with Maven
directly).
> Fix 'GenericsTest' to compile in IntelliJ (#2089)

- docs/source/manual/internals.rst
- dropwizard-core/src/main/java/io/dropwizard/Application.java
Hi,
I created the original document for internal use - but thought of contributing it back to the community.
This pull request is just to check you are interestested in this contribution, before I invest extra effort.
A concept being used is "simplified code" -> showing code, but in a simpler form that is easier to follow.
Work still needed:
* Translate two code snippets from kotlin --> java (we use kotlin)
* Style and grammar
* Some formatting
* Add links
I'll need you to:
* review the content is correct and accurate / suggest fixes.
* grammar review will be appreciated as well, as I'm not a native english speaker.
Just answer on the commit which way you want to go.
> enhanced bootstrapping flow documentation

- docs/source/about/release-notes.rst
- dropwizard-bom/pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.1
> Upgrade to Jackson 2.9.1

- docs/source/getting-started.rst
> Update getting started archetype version reference

- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/ScanningHibernateBundle.java
... in order to close the referenced resource.
Resolves #2188.
> Close PackageNamesScanner in ScanningHibernateBundle

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/FuzzyEnumParamConverterProvider.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/FuzzyEnumParamConverterProviderTest.java
This is a continuation of Stefan Zhelyazkov 's work in PR #1987
> Support fromString in FuzzyEnumParamConverter

- docs/source/manual/configuration.rst
- dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
replacement for https://github.com/dropwizard/dropwizard/pull/2100
> add immediateFlush option for file logging #2098

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/filter/RequestIdFilter.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/filter/RuntimeFilter.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/filter/CharsetUtf8FilterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/filter/RequestIdFilterTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/filter/RuntimeFilterTest.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/SlowRequestFilter.java
- dropwizard-servlets/src/main/java/io/dropwizard/servlets/ThreadNameFilter.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/SlowRequestFilterTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/ThreadNameFilterTest.java
This change adds unit test for useful Dropwizard filters:
* ThreadNameFilter
* SlowRequestFilter
* CharsetUtf8Filter
* RequestIdFilter
* RuntimeFilter
> Add tests for Dropwizard filters

- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
Verify that instrumentation of tasks works and the measurements are added to the Dropwizard's 'MetricRegistry'.
> Add tests for instrumenting admin tasks

- dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/SelfValidatingBenchmark.java
- dropwizard-validation/pom.xml
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidating.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidator.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidation.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ValidationCaller.java
- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ViolationCollector.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidatorTest.java
* Use Stream API
* Add curly brackets to if blocks
* Avoid nested if blocks and keep the main line of execution
* Reorder imports
References #2150
> Polish SelfValidatingValidator

- pom.xml
https://github.com/uber/NullAway
> Enable NullAway errorprone checks

- docs/source/about/release-notes.rst
- dropwizard-bom/pom.xml
Refs https://hibernate.atlassian.net/browse/HHH-11996
Fixes #2206
> Upgrade to Hibernate 5.2.12.Final

- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java
Slight typo in private method name
Fixed the typo
Not much. I just stumbled upon that and thought I'd fix it ;)
> Fixed typo. Lister -> Listener

- dropwizard-bom/pom.xml
Hi everyone, I opened this little PR because a patch version of 2.9 was recently released. 
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.2
Best Regards
Juan Pablo
> Upgrade to Jackson 2.9.2

- pom.xml
> Force Java 8 as compile target

- dropwizard-archetypes/README.md
> Split archetype example command to multiple lines

- docs/source/about/release-notes.rst
> Update release notes

- dropwizard-bom/pom.xml
Better switch to the latest version before 1.3.0 release.
> Update Jdbi3 to 3.1.0

- docs/source/manual/testing.rst
The current example does not work. The DropwizardAppRule allows creating the client using the method.
> Fix Integration Testing Example

- dropwizard-bom/pom.xml
> Upgrade Jdbi3 to 3.2.1

- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidator.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/selfvalidating/SelfValidatingValidatorTest.java
Remove use of Javassist from SelfValidatingValidator in favor of plain old Java.
> Simplify SelfValidatingValidator

- docs/source/manual/views.rst
Fixes #2454. There was a typo.
Fixed the typo.
Typo-free docs!
> Fix typo in Views doc

- docs/source/manual/client.rst
- docs/source/manual/configuration.rst
- docs/source/manual/core.rst
Mostly some accidental duplication of words that slowed down the flow and readability.
> Minor documentation typo fixes.

- dropwizard-bom/pom.xml
http://in.relation.to/2018/10/17/hibernate-orm-537-final-out/
Refs https://hibernate.atlassian.net/browse/HHH-12964
Closes #2542
> Upgrade to Hibernate ORM 5.3.7.Final

- dropwizard-http2/pom.xml
see https://github.com/jetty-project/jetty-alpn/commit/0d70cb95c21cf7bca35308e2ab261b6cc1c0884f
> Upgrade to alpn-boot v8.1.13.v20181017

- .mvn/wrapper/maven-wrapper.properties
- dropwizard-bom/pom.xml
- dropwizard-example/pom.xml
- pom.xml
> Dependencies updates

- dropwizard-auth/src/test/java/io/dropwizard/auth/CachingAuthenticatorTest.java
This particular test case has proven to be rather flaky.
Removed the test case as it is effectively testing Caffeine's internal implementation; something that is tested by Caffeine itself.
Removing this test eliminates its flakiness once and for all.
Please see #2575
Thanks.
> Removed respectsTheCacheConfiguration test case

- dropwizard-bom/pom.xml
> Upgrade JDBI3 to 3.5.1

- dropwizard-bom/pom.xml
- pom.xml
- suppressed-cves.xml
* Upgrade to OWASP Dependency Check 4.0.2
* Upgrade to JUnit 5.3.2
* Upgrade to NullAway 0.6.4
* Upgrade to ByteBuddy 1.9.7
* Upgrade to Mockito 2.23.4
* Upgrade to Dropwizard Metrics 4.1.0-rc3
* Upgrade to Apache Tomcat JDBC Pool 9.0.14
* Upgrade to Hibernate ORM 5.4.1.Final
* Upgrade to jdbi 3.6.0
> Update dependencies (master branch)

- docs/source/about/release-notes.rst
- docs/source/manual/core.rst
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/BooleanParam.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/DateTimeParam.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/DurationParam.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/InstantParam.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/IntParam.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/LocalDateParam.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/LongParam.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/SizeParam.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/params/UUIDParam.java
Replaces https://github.com/dropwizard/dropwizard/pull/2625
> Deprecate *Param classes, will be removed in 3.0.0

- .circleci/config.yml
* Use OpenJDK 11
* Use Maven wrapper
* Use build cache to speed up builds even more
> Upgrade to CircleCI 2.0

- docs/source/manual/core.rst
Added documentation and code examples (borrowed and modified from metrics documentation) for metrics annotations used in jersey resources.
> Add documentation for metrics annotations

- dropwizard-util/src/test/java/io/dropwizard/util/StringsTest.java
I've analysed your code base and noticed that `dropwizard.util.StringsTest` is not fully tested.
I've written some tests for the functions in this class with the help of [Diffblue](https://www.diffblue.com/) [Cover](https://www.diffblue.com/products). Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.
> Add unit tests for dropwizard.util.StringsTest

- docs/source/manual/upgrade-notes/upgrade-notes-2_0_x.rst
> Add documentation about import changes for HK2

- pom.xml
➡️ https://www.simplify4u.org/pgpverify-maven-plugin/
Refs #2664
> Verify dependency signatures during build

- docs/source/about/release-notes.rst
> Add some additional information in the 2.0.0 release notes

- dropwizard-testing/src/main/java/io/dropwizard/testing/common/DAOTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestRuleWithoutLoggingBootstrapTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DAOTestRuleWithoutLoggingBootstrapTest.java
> Allow to disable logging bootstrap in DAOTest

- docs/source/about/release-notes.rst
- docs/source/manual/configuration.rst
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpConnectorFactoryTest.java
- dropwizard-jetty/src/test/resources/yaml/http-connector.yml
> Don't use X-Forwarded-* headers by default

- docs/source/getting-started.rst
> Fixed broken link.

- docs/source/manual/core.rst
Fixes #2736 
@mattnelson Does this cover what you were looking for?
> Updates Conscrypt docs to follow recommended usage patterns (#2736)

- dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
- dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java
Fixes #2853 
validated minimum value doesn't actually work
Increased the minimum value to the lowest value that starts up
> Increases the values in the hibernate validator annotations 

- dropwizard-configuration/src/main/java/io/dropwizard/configuration/BaseConfigurationFactory.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/BaseConfigurationFactoryTest.java
Missing word
Added word
Message contains previously missing word
> Slight message change

- dropwizard-util/src/test/java/io/dropwizard/util/MapsTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/SetsTest.java
I've analysed your code base and noticed that `io.dropwizard.util.Maps` and `io.dropwizard.util.Sets` are not fully tested.
I've written some tests for the methods in these classes with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.
> Add unit tests for io.dropwizard.util.Maps and Sets

- docs/source/manual/testing.rst
Added documentation covering testing of config files with environment variables and substitution
> Updating configuration testing documentation

- docs/source/manual/internals.rst
There is a typo in the doc
I fixed the typo
s/Bootsrap/Bootstrap/g
> fixed typo

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
> Correctly log resource paths with relative path segments

- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java
When a method annotated with @UnitOfWork calls into another method that
is annotated like that, the transaction is prematurely committed when
the inner method returns.
This leads to difficult to debug situations and should be prevented.
Either an exception has to be raised as soon as possible or nesting
needs to do the sane thing.
The implementation checks if a session is already associated with this
thread. If that is not the case (non-nested), the original code paths
are invoked. If there exists already a session, its state is validated,
if the session is compatible with the requested state, the unit of work
is joined, if not an IllegalStateException is raised.
> Nested calls to @UnitOfWork methods cause inconsistent behaviour

- dropwizard-dependencies/pom.xml
https://github.com/uber/NullAway/blob/8990141ce7bc63cb84c2f3b90dee78688da85c4b/CHANGELOG.md
> Upgrade to NullAway 0.7.8

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-util/src/main/java/io/dropwizard/util/JavaVersion.java
- dropwizard-util/src/test/java/io/dropwizard/util/JavaVersionTest.java
> Fix illegal reflection warning in DropwizardResourceConfig

- dropwizard-util/src/main/java/io/dropwizard/util/DataSize.java
- dropwizard-util/src/main/java/io/dropwizard/util/Duration.java
- dropwizard-util/src/main/java/io/dropwizard/util/Size.java
- dropwizard-util/src/test/java/io/dropwizard/util/DataSizeTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/DurationTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/SizeTest.java
> Make Duration, DataSize, and Size serializable

- .github/workflows/maven.yml
* https://help.github.com/en/github/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows
* https://github.com/actions/cache/blob/e1ed41a9c913f73dd08e261583c25e9d5eca5007/examples.md#java---maven
> Add cache action to Maven workflow

- docs/source/manual/internals.rst
This commit makes a very minor change fixing the grammar in a sentence.
There's a grammar error in a sentence "A ``ConfiguredBundle`` is a bundle that require a configuration "
"require" -> "requires"
> Minor gramatical fix.

- dropwizard-views-freemarker/src/test/java/io/dropwizard/views/freemarker/MultipleContentTypeTest.java
> Replace JSON string asserts in MultipleContentTypeTest

- docs/source/about/release-notes.rst
> Dropwizard 2.0.0 release notes

- .github/workflows/maven.yml
GitHub Actions checkout v1 -> v2
https://github.com/actions/checkout/blob/master/README.md
GitHub Actions checkout v1 -> v2
> GitHub Actions checkout v2

- dropwizard-logging/src/test/java/io/dropwizard/logging/FileAppenderFactoryTest.java
> FileAppenderFactoryTest: verify that the appender has started

- .dependabot/config.yml
See also: https://dependabot.com/docs/config-file/
> Add configuration for Dependabot

- dropwizard-jersey/src/test/java/io/dropwizard/jersey/errors/LoggingExceptionMapperTest.java
> Don't depend on iteration order in LoggingExceptionMapperTest

- dropwizard-validation/src/main/java/io/dropwizard/validation/selfvalidating/ViolationCollector.java
- dropwizard-validation/src/test/java/io/dropwizard/validation/SelfValidationTest.java
Fixes #3153
Refs #3157
(cherry picked from commit d87d1e4f8e20f6494c0232bf8560c961b46db634)
> Escape EL expressions in ViolationCollector

- dropwizard-core/src/main/java/io/dropwizard/setup/Bootstrap.java
- dropwizard-core/src/test/java/io/dropwizard/setup/BootstrapTest.java
> Expose JmxReporter in Bootstrap

- dropwizard-example/pom.xml
- dropwizard-testing/pom.xml
> Fix dependency scopes in dropwizard-testing

- dropwizard-dependencies/pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.11
> Upgrade to Jackson 2.11.0.rc1

- dropwizard-archetypes/pom.xml
- pom.xml
Use correct coordinates of maven-archetype-plugin:
https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-archetype-plugin/3.1.2
> Fix coordinates of maven-archetype-plugin

- dropwizard-dependencies/pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10.4
> Upgrade to Jackson 2.10.4

- dropwizard-dependencies/pom.xml
> Remove unused dependency on Objenesis

- dropwizard-parent/pom.xml
- pom.xml
> Reproducible builds are a set of software development practices that create an independently-verifiable path from source to binary code. A build is reproducible if given the same source code, build environment and build instructions, any party can recreate bit-by-bit identical copies of all specified artifacts.
* https://maven.apache.org/guides/mini/guide-reproducible-builds.html
* https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318
* https://github.com/jvm-repo-rebuild/reproducible-central
* https://reproducible-builds.org/
> Enable reproducible builds

- docs/source/manual/configuration.rst
- dropwizard-logging/src/main/java/io/dropwizard/logging/SyslogAppenderFactory.java
> Add docs for `includeStackTrace` setting of syslog appender

- dropwizard-dependencies/pom.xml
- dropwizard-parent/pom.xml
https://github.com/google/error-prone/releases/tag/v2.4.0
Closes #3315
Closes #3317
> Upgrade to Error Prone 2.4.0

- dropwizard-auth/pom.xml
- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthenticator.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/CachingAuthorizer.java
> Export cache stats in CachingAuthorizer and CachingAuthenticator

- .github/workflows/codeql.yml
- .github/workflows/maven.yml
https://github.com/github/codeql-action
> Add CodeQL analysis for security scans

- dropwizard-dependencies/pom.xml
- dropwizard-e2e/pom.xml
- dropwizard-e2e/src/test/java/com/example/app1/App1Test.java
> Try making App1Test#earlyEofTest() less flaky

- dropwizard-dependencies/pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10.5
> Upgrade to Jackson 2.10.5

- dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
Fix build errors of java-simple archetype on Windows due to an old version of `maven-javadoc-plugin`:
```
2020-07-28T08:14:59.5885875Z [INFO] [INFO] --- maven-source-plugin:3.0.1:jar (attach-sources) @ test-project ---
2020-07-28T08:14:59.6834130Z [INFO] [INFO] Building jar: D:\a\dropwizard\dropwizard\dropwizard-archetypes\java-simple\target\it\projects\shaded\test-project\target\test-project-1.0.0-SNAPSHOT-sources.jar
2020-07-28T08:14:59.6837655Z [INFO] [INFO] 
2020-07-28T08:14:59.6838455Z [INFO] [INFO] --- maven-javadoc-plugin:3.0.1:jar (attach-javadocs) @ test-project ---
2020-07-28T08:14:59.9093330Z [INFO] [WARNING] Error injecting: org.apache.maven.plugins.javadoc.JavadocJar
2020-07-28T08:14:59.9301119Z [INFO] java.lang.NoClassDefFoundError: org/apache/commons/lang3/ClassUtils …
```
> Bump Maven plugins in java-simple Maven archetype template

- .circleci/config.yml
- .travis.yml
- appveyor.yml
* AppVeyor
* CircleCI
* Travis CI
Refs #3400
> Add `--no-transfer-progress` to other Maven invocations

- dropwizard-bom/pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9
> Upgrade to Jackson 2.9.10.20200824 

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalDoubleParamConverterProvider.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalIntParamConverterProvider.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional/OptionalLongParamConverterProvider.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/optional/OptionalBeanParamResourceTest.java
> Handle null values in Optional* ParamConverters

- docs/source/manual/core.rst
The link to mockito is outdated.
Fixed the link.
> Update outdated mockito link

- .github/workflows/maven.yml
> ci: add JDK 15

- dropwizard-parent/pom.xml
> Remove deprecated "optimize" compiler flag

- dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbMigrateCommand.java
- dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbRollbackCommand.java
- dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbStatusCommand.java
Hard to read and understand if expression.
Simpfiable conditional expressions. More readable code.
> Hacktoberfest: Simplify conditional experession

- .github/workflows/maven.yml
- pom.xml
https://sonarcloud.io/dashboard?id=dropwizard_dropwizard
> Add analysis with SonarCloud

- dropwizard-dependencies/pom.xml
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ValidatingResource.java
https://github.com/uber/NullAway/blob/v0.8.0/CHANGELOG.md
> Upgrade to NullAway 0.8.0

- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/TransactionHandlingTest.java
- dropwizard-hibernate/src/test/resources/transaction-handling-test.yaml
> UnitOfWork: Support serialized and mixed transactional app

- dropwizard-jackson/src/main/java/io/dropwizard/jackson/AnnotationSensitivePropertyNamingStrategy.java
- dropwizard-jackson/src/test/java/io/dropwizard/jackson/AnnotationSensitivePropertyNamingStrategyTest.java
Refs FasterXML/jackson-datatypes-collections#79
Fixes #3514
> Add null-checks to AnnotationSensitivePropertyNamingStrategy

- dropwizard-bom/pom.xml
> Bump httpclient from 4.5.12 to 4.5.13

- dropwizard-dependencies/pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10#micro-patches
> Upgrade to Jackson 2.10.5.20201202

- docs/source/manual/testing.rst
Syntax in example was incorrect.
Fixed syntax.
Example will be closer to a working test.
> Fixed syntax in Testing Database Interactions example

- dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java
- dropwizard-core/src/main/java/io/dropwizard/setup/AdminEnvironment.java
- dropwizard-jdbi3/src/main/java/io/dropwizard/jdbi3/jersey/LoggingJdbiExceptionMapper.java
- dropwizard-jdbi3/src/main/java/io/dropwizard/jdbi3/jersey/LoggingSQLExceptionMapper.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/LoggingExceptionMapper.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/FuzzyEnumParamConverter.java
- dropwizard-lifecycle/src/main/java/io/dropwizard/lifecycle/ExecutorServiceManager.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/ExecutorServiceBuilderTest.java
- dropwizard-parent/pom.xml
https://github.com/KengoTODA/errorprone-slf4j
> Add checks for logging statements via errorprone-slf4j (#3607)Add checks for logging statements via errorprone-slf4j

- dropwizard-core/src/test/java/io/dropwizard/cli/CheckCommandTest.java
- dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkApplicationListenerTest.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/ExecutorServiceManagerTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/CacheBustingFilterTest.java
verifyZeroInteractions is deprecated, update to the latest API.
> Replace Mockito#verifyZeroInteractions with verifyNoInteractions

- dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java
> Fix typo in HttpClientBuilder Javadoc

- dropwizard-benchmarks/pom.xml
- dropwizard-benchmarks/src/main/java/io/dropwizard/benchmarks/jersey/ConstraintViolationBenchmark.java
We can do this with standard reflection...
... I think (I couldn't get JMH annotation processing to work, so haven't been able to test)
> Remove commons-lang3 from dropwizard-benchmarks

- dropwizard-jackson/src/main/java/io/dropwizard/jackson/CaffeineModule.java
- dropwizard-jackson/src/main/java/io/dropwizard/jackson/GuavaExtrasModule.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/ServerPushFilterFactory.java
- dropwizard-testing/src/main/java/io/dropwizard/testing/DropwizardTestSupport.java
I was trawling through the codebase and found some things I thought could be made a little bit nicer.
It's all very subjective though, so feel free to just close this PR if you disagree.
> Small cleanups

- dropwizard-dependencies/pom.xml
https://github.com/eclipse-ee4j/jersey/releases/tag/2.33
> Upgrade to Jersey 2.33

- dropwizard-dependencies/pom.xml
https://tomcat.apache.org/tomcat-9.0-doc/changelog.html
> Bump tomcat-jdbc from 9.0.41 to 9.0.43

- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardApacheConnectorTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/JsonConfigurationFactoryTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/LevenshteinComparatorTest.java
- dropwizard-configuration/src/test/resources/factory-test-comment.json
Add some basic assertions to tests which Sonar was upset had none.
> Add assertions to some tests which lacked them

- .github/workflows/maven.yml
- dropwizard-example/src/test/java/com/example/helloworld/DockerIntegrationTest.java
- dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOIntegrationTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
- dropwizard-parent/pom.xml
https://mail.openjdk.java.net/pipermail/announce/2021-March/000295.html
> Build Dropwizard with Java 16

- dropwizard-assets/src/main/java/io/dropwizard/assets/AssetsBundle.java
- dropwizard-auth/src/main/java/io/dropwizard/auth/AuthDynamicFeature.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/sessions/SessionFactoryProvider.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/SyslogAppenderFactory.java
Sonar is very picky and as a consequence is kinda noisy. I picked a few of its grumbles which seemed vaguely legitimate:
- [AuthDynamicFeature code complexity](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&issues=AXUXdIbApBosHuY9-P1u&open=AXUXdIbApBosHuY9-P1u)
- static access via a subclass in `dropwizard-jersey` [SessionFactoryProvider](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&issues=AXUXdIC5pBosHuY9-Pso&open=AXUXdIC5pBosHuY9-Pso) and `ConstraintMessage` [1](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&issues=AXUXdICZpBosHuY9-Psk&open=AXUXdICZpBosHuY9-Psk) [2](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&issues=AXUXdICZpBosHuY9-Psl&open=AXUXdICZpBosHuY9-Psl) [3](https://sonarcloud.io/project/issues?id=dropwizard_dropwi …
> Address some Sonar issues

- dropwizard-dependencies/pom.xml
https://www.whitesourcesoftware.com/vulnerability-database/WS-2019-0379
Fixes #3851
> Force commons-codec 1.15 to address WS-2019-0379

- dropwizard-jetty/src/main/java/io/dropwizard/jetty/ContextRoutingHandler.java
> Implement `expandChildren()` in `ContextRoutingHandler`

- docs/source/manual/di.rst
Docs reference Guice Bundle for DI, but there are multiple, and unclear which is the one that should be used. 
Add a link to the docs
> [Docs] Add link to xvik/dropwizard-guicey

- docs/source/manual/di.rst
Added clarifying note on Singleton annotation that it's not picked up for custom classes, only for Resources.
> Added clarifying note on Singleton annotation

- dropwizard-dependencies/pom.xml
https://github.com/dropwizard/metrics/releases/tag/v4.2.2
> Upgrade to Dropwizard Metrics 4.2.2

- .mvn/wrapper/maven-wrapper.properties
https://mail-archives.apache.org/mod_mbox/maven-announce/202108.mbox/%3C85a7a3d4-c4ae-8e1e-f5c4-832017b79ca3@apache.org%3E
> Bump Maven version to 3.8.2

- dropwizard-configuration/src/test/java/io/dropwizard/configuration/BaseConfigurationFactoryTest.java
- dropwizard-json-logging/src/test/java/io/dropwizard/logging/json/EventJsonLayoutBaseFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/ExternalLoggingFactoryTest.java
- dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/ExternalRequestLogFactoryTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/ResourceURLTest.java
- dropwizard-views/src/test/java/io/dropwizard/views/ViewBundleTest.java
> Chain AssertJ calls where possible

- dropwizard-e2e/src/test/java/com/example/health/HealthIntegrationTest.java
- dropwizard-example/src/test/java/com/example/helloworld/db/PersonDAOTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/HttpsConnectorFactoryTest.java
- dropwizard-jetty/src/test/java/io/dropwizard/jetty/NetUtilTest.java
- dropwizard-metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterFactoryTest.java
- dropwizard-metrics/src/test/java/io/dropwizard/metrics/CsvReporterFactoryTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/ByteRangeTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/assets/ResourceURLTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/LogConfigurationTaskTest.java
- dropwizard-servlets/src/test/java/io/dropwizard/servlets/tasks/TaskServletTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/DataSizeTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/DurationTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/JarLocationTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/SizeTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/StringsTest.java
As suggested by Sonar
Should reduce the code smells by 149
> Use more specific AssertJ assertions in tests

- dropwizard-e2e/src/main/java/com/example/validation/ValidatedResource.java
- dropwizard-example/src/main/java/com/example/helloworld/cli/RenderCommand.java
- dropwizard-example/src/main/java/com/example/helloworld/core/User.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/HibernateBundle.java
- dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryHealthCheck.java
- dropwizard-http2/src/test/java/io/dropwizard/http2/Http2WithConscryptTest.java
- dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/NetUtil.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/AppenderFactoryCustomTimeZoneTest.java
- dropwizard-metrics/src/main/java/io/dropwizard/metrics/BaseReporterFactory.java
- dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbCalculateChecksumCommand.java
- dropwizard-migrations/src/main/java/io/dropwizard/migrations/DbFastForwardCommand.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit/DropwizardClientRuleTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/DropwizardClientExtensionTest.java
- dropwizard-testing/src/test/java/io/dropwizard/testing/junit5/ReuseDropwizardAppExtensionTestSuite.java
Sonar is very picky and likes to complain about things which don't really matter
Do some of the things Sonar suggests
Sonar will complain less.
Possibly the code will be tidier?
These changes seem reasonable to me - see what you think. Each class of change is a separate commit, so if something doesn't look desirable it's easy to cut out.
> Appease various minor Sonar gripes

- dropwizard-health/src/test/java/io/dropwizard/health/response/JsonHealthResponseProviderTest.java
- dropwizard-metrics/src/test/java/io/dropwizard/metrics/CsvReporterFactoryTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/DataSizeTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/DurationTest.java
- dropwizard-util/src/test/java/io/dropwizard/util/SizeTest.java
A previous PR simplified the AssertJ assertions in some tests in a vain attempt to make Sonar happy.
Sadly, Sonar wasn't as happy as it could have been - it found some more specific AssertJ assertions we can use.
Use more specific assertions
Sonar might quit moaning
> Further improvements to test assertions

- dropwizard-core/src/test/java/io/dropwizard/cli/ConfiguredCommandTest.java
- dropwizard-example/src/test/java/com/example/helloworld/core/UserTest.java
- dropwizard-health/src/test/java/io/dropwizard/health/DefaultHealthFactoryTest.java
- dropwizard-health/src/test/java/io/dropwizard/health/DelayedShutdownHandlerTest.java
- dropwizard-health/src/test/java/io/dropwizard/health/HealthStatusCheckerTest.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/ExecutorServiceManagerTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/MigrationsBundleTest.java
The tests cover roughly 71% of the code since the last release.
Add more tests and assertions to improve coverage.
The Sonar report will show higher coverage percentage.
> Improve coverage on new code

- .github/workflows/maven.yml
- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
- dropwizard-parent/pom.xml
Run builds in GitHub Actions workflow with Java 17.
> Build with Java 17 and migrate to actions/setup-java

- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
> Enable `DropwizardSSLConnectionSocketFactoryTest`

- .github/workflows/docs.yml
- docs/source/about/release-notes.rst
- docs/source/manual/configuration.rst
- docs/source/manual/core.rst
Build documentation on pull requests to be notified about warnings in the documentation markup.
> Add workflow to build Sphinx documentation on PRs

- dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
This hasn't been used since v2.0.0 (usage removed in commit
88f8e081d108e1d075b6b9fb1330b8ebe7a35dfb)
> Remove `DefaultLoggingFactory#clear()`

- dropwizard-dependencies/pom.xml
https://github.com/dropwizard/metrics/releases/tag/v4.1.26
> Update dependency io.dropwizard.metrics:metrics-bom to v4.1.26

- dropwizard-client/src/test/java/io/dropwizard/client/DropwizardSSLConnectionSocketFactoryTest.java
> Disable SSL tests failing on Windows

- dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java
- dropwizard-configuration/src/test/java/io/dropwizard/configuration/BaseConfigurationFactoryTest.java
- dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckManagerTest.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/validation/ConstraintViolationExceptionMapperTest.java
- dropwizard-lifecycle/src/test/java/io/dropwizard/lifecycle/setup/LifecycleEnvironmentTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/DefaultLoggingFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/TcpSocketAppenderFactoryTest.java
- dropwizard-logging/src/test/java/io/dropwizard/logging/TlsSocketAppenderFactoryTest.java
- dropwizard-metrics/src/test/java/io/dropwizard/metrics/MetricsFactoryTest.java
- dropwizard-migrations/src/test/java/io/dropwizard/migrations/MigrationsBundleTest.java
- dropwizard-request-logging/src/test/java/io/dropwizard/request/logging/RequestLogFactoryTest.java
Use more features of `ListAssert` to reduce the volume of test code.
> Make better use of AssertJ list assertions

- dropwizard-dependencies/pom.xml
https://github.com/dropwizard/metrics/releases/tag/v4.1.27
> Update dependency io.dropwizard.metrics:metrics-bom to v4.1.27

- docs/source/manual/configuration.rst
documentation change. see #4512
> added useProxyProtocol to the Dropwizard Configuration Reference

- .github/workflows/maven.yml
- dropwizard-assets/pom.xml
- dropwizard-health/pom.xml
- dropwizard-http2/pom.xml
- dropwizard-jetty/pom.xml
- dropwizard-views-freemarker/pom.xml
As reported by `mvn dependency:analyze`
> Remove unused test dependencies

- SECURITY.md
> Clarify support for Dropwizard 1.3.x in security policy

- dropwizard-health/src/test/java/io/dropwizard/health/HealthCheckManagerTest.java
Raised for consideration regarding issue #4613.
> Disable `HealthCheckManagerTest` on Windows

- dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationParsingException.java
- dropwizard-core/src/main/java/io/dropwizard/validation/InjectValidatorFeature.java
- dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java
- dropwizard-health/src/main/java/io/dropwizard/health/DefaultHealthFactory.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/ContextRoutingHandler.java
- dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java
- dropwizard-logging/src/main/java/io/dropwizard/logging/DefaultLoggingFactory.java
Sonar isn't a fan of this. Coming up with pleasing alternate names for these variables isn't easy, however.
> Avoid shadowing class fields with local variables

- dropwizard-example/src/test/java/com/example/helloworld/DockerIntegrationTest.java
DockerIntegrationTest checks the content of application.log
The assertions are not adequate.
Improved assertion DockerIntegrationTest
Unit test passes.
> improve assertion in DockerIntegrationTest testLogFileWritten

- dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java
- dropwizard-jersey/src/test/java/io/dropwizard/jersey/DropwizardResourceConfigTest.java
- dropwizard-util/src/main/java/io/dropwizard/util/JavaVersion.java
- dropwizard-util/src/test/java/io/dropwizard/util/JavaVersionTest.java
Reverts dropwizard/dropwizard#4587
> Revert "Register resources in the same way for Java 8 and 11"

- .github/workflows/maven.yml
- .github/workflows/release.yml
- dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
- dropwizard-example/pom.xml
- dropwizard-parent/pom.xml
The change should've been against `release/3.0.x` and not against `master`
Reverts dropwizard/dropwizard#4726
> Revert "Set baseline to Java 11 and update CI workflows accordingly"

- .github/workflows/maven.yml
- .github/workflows/release.yml
- dropwizard-archetypes/java-simple/src/main/resources/archetype-resources/pom.xml
- dropwizard-example/pom.xml
- dropwizard-parent/pom.xml
Refs https://github.com/dropwizard/dropwizard/pull/4726
> Set baseline to Java 11 and update CI workflows accordingly
